/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedThinkingModelsRouteImport } from './routes/_authenticated/thinking-models'
import { Route as AuthenticatedTestDemoRouteImport } from './routes/_authenticated/test-demo'
import { Route as AuthenticatedRetrievalTestRouteImport } from './routes/_authenticated/retrieval-test'
import { Route as AuthenticatedModelSettingsRouteImport } from './routes/_authenticated/model-settings'
import { Route as AuthenticatedIntelligenceAnalysisRouteImport } from './routes/_authenticated/intelligence-analysis'
import { Route as AuthenticatedFlowRouteImport } from './routes/_authenticated/flow'
import { Route as AuthenticatedCookieSettingsRouteImport } from './routes/_authenticated/cookie-settings'
import { Route as AuthenticatedComfyuiRouteImport } from './routes/_authenticated/comfyui'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSystemWorkflowsRouteRouteImport } from './routes/_authenticated/system-workflows/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedProjectsRouteRouteImport } from './routes/_authenticated/projects/route'
import { Route as AuthenticatedNovelsRouteRouteImport } from './routes/_authenticated/novels/route'
import { Route as AuthenticatedKnowledgeBaseRouteRouteImport } from './routes/_authenticated/knowledge-base/route'
import { Route as AuthenticatedDiariesRouteRouteImport } from './routes/_authenticated/diaries/route'
import { Route as AuthenticatedCanvasRouteRouteImport } from './routes/_authenticated/canvas/route'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags/index'
import { Route as AuthenticatedSystemWorkflowsIndexRouteImport } from './routes/_authenticated/system-workflows/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedNovelsIndexRouteImport } from './routes/_authenticated/novels/index'
import { Route as AuthenticatedKnowledgeBaseIndexRouteImport } from './routes/_authenticated/knowledge-base/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedDiariesIndexRouteImport } from './routes/_authenticated/diaries/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAiMusicIndexRouteImport } from './routes/_authenticated/ai-music/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSystemWorkflowsWebParseRouteImport } from './routes/_authenticated/system-workflows/web-parse'
import { Route as AuthenticatedSystemWorkflowsVideoParseRouteImport } from './routes/_authenticated/system-workflows/video-parse'
import { Route as AuthenticatedSystemWorkflowsTieredRagRouteImport } from './routes/_authenticated/system-workflows/tiered-rag'
import { Route as AuthenticatedSystemWorkflowsThinkingModelRouteImport } from './routes/_authenticated/system-workflows/thinking-model'
import { Route as AuthenticatedSystemWorkflowsStructuredExtractionRouteImport } from './routes/_authenticated/system-workflows/structured-extraction'
import { Route as AuthenticatedSystemWorkflowsStandardRagRouteImport } from './routes/_authenticated/system-workflows/standard-rag'
import { Route as AuthenticatedSystemWorkflowsOpinionIngestionRouteImport } from './routes/_authenticated/system-workflows/opinion-ingestion'
import { Route as AuthenticatedSystemWorkflowsFileParseRouteImport } from './routes/_authenticated/system-workflows/file-parse'
import { Route as AuthenticatedSystemWorkflowsEventIngestionRouteImport } from './routes/_authenticated/system-workflows/event-ingestion'
import { Route as AuthenticatedSystemWorkflowsDouyinParseRouteImport } from './routes/_authenticated/system-workflows/douyin-parse'
import { Route as AuthenticatedSystemWorkflowsDiaryAnalysisRouteImport } from './routes/_authenticated/system-workflows/diary-analysis'
import { Route as AuthenticatedSystemWorkflowsCaseIngestionRouteImport } from './routes/_authenticated/system-workflows/case-ingestion'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedNovelsNovelIdRouteImport } from './routes/_authenticated/novels/$novelId'
import { Route as AuthenticatedKnowledgeBaseKbIdRouteImport } from './routes/_authenticated/knowledge-base/$kbId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDocumentsDocIdRouteImport } from './routes/_authenticated/documents/$docId'
import { Route as AuthenticatedDiariesTimelineRouteImport } from './routes/_authenticated/diaries/timeline'
import { Route as AuthenticatedDiariesDiaryIdRouteImport } from './routes/_authenticated/diaries/$diaryId'
import { Route as AuthenticatedCanvasWorkflowTestRouteImport } from './routes/_authenticated/canvas/workflow-test'
import { Route as AuthenticatedCanvasComicRouteImport } from './routes/_authenticated/canvas/comic'
import { Route as AuthenticatedCanvasComfyuiRouteImport } from './routes/_authenticated/canvas/comfyui'
import { Route as AuthenticatedTemplatesLayoutIndexRouteImport } from './routes/_authenticated/templates/layout/index'
import { Route as AuthenticatedTemplatesComponentsIndexRouteImport } from './routes/_authenticated/templates/components/index'
import { Route as AuthenticatedTemplatesLayoutTopNavLayoutRouteImport } from './routes/_authenticated/templates/layout/top-nav-layout'
import { Route as AuthenticatedTemplatesLayoutTabLayoutRouteImport } from './routes/_authenticated/templates/layout/tab-layout'
import { Route as AuthenticatedTemplatesLayoutStandardListLayoutRouteImport } from './routes/_authenticated/templates/layout/standard-list-layout'
import { Route as AuthenticatedTemplatesLayoutStandardLayoutRouteImport } from './routes/_authenticated/templates/layout/standard-layout'
import { Route as AuthenticatedTemplatesComponentsUserSearchRouteImport } from './routes/_authenticated/templates/components/user-search'
import { Route as AuthenticatedTemplatesComponentsBasicComponentsRouteImport } from './routes/_authenticated/templates/components/basic-components'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThinkingModelsRoute =
  AuthenticatedThinkingModelsRouteImport.update({
    id: '/thinking-models',
    path: '/thinking-models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestDemoRoute = AuthenticatedTestDemoRouteImport.update({
  id: '/test-demo',
  path: '/test-demo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetrievalTestRoute =
  AuthenticatedRetrievalTestRouteImport.update({
    id: '/retrieval-test',
    path: '/retrieval-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelSettingsRoute =
  AuthenticatedModelSettingsRouteImport.update({
    id: '/model-settings',
    path: '/model-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelligenceAnalysisRoute =
  AuthenticatedIntelligenceAnalysisRouteImport.update({
    id: '/intelligence-analysis',
    path: '/intelligence-analysis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlowRoute = AuthenticatedFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCookieSettingsRoute =
  AuthenticatedCookieSettingsRouteImport.update({
    id: '/cookie-settings',
    path: '/cookie-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComfyuiRoute = AuthenticatedComfyuiRouteImport.update({
  id: '/comfyui',
  path: '/comfyui',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSystemWorkflowsRouteRoute =
  AuthenticatedSystemWorkflowsRouteRouteImport.update({
    id: '/system-workflows',
    path: '/system-workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRouteRoute =
  AuthenticatedProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovelsRouteRoute =
  AuthenticatedNovelsRouteRouteImport.update({
    id: '/novels',
    path: '/novels',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeBaseRouteRoute =
  AuthenticatedKnowledgeBaseRouteRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiariesRouteRoute =
  AuthenticatedDiariesRouteRouteImport.update({
    id: '/diaries',
    path: '/diaries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCanvasRouteRoute =
  AuthenticatedCanvasRouteRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemWorkflowsIndexRoute =
  AuthenticatedSystemWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRouteRoute,
  } as any)
const AuthenticatedNovelsIndexRoute =
  AuthenticatedNovelsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNovelsRouteRoute,
  } as any)
const AuthenticatedKnowledgeBaseIndexRoute =
  AuthenticatedKnowledgeBaseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKnowledgeBaseRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiariesIndexRoute =
  AuthenticatedDiariesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDiariesRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiMusicIndexRoute =
  AuthenticatedAiMusicIndexRouteImport.update({
    id: '/ai-music/',
    path: '/ai-music/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSystemWorkflowsWebParseRoute =
  AuthenticatedSystemWorkflowsWebParseRouteImport.update({
    id: '/web-parse',
    path: '/web-parse',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsVideoParseRoute =
  AuthenticatedSystemWorkflowsVideoParseRouteImport.update({
    id: '/video-parse',
    path: '/video-parse',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsTieredRagRoute =
  AuthenticatedSystemWorkflowsTieredRagRouteImport.update({
    id: '/tiered-rag',
    path: '/tiered-rag',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsThinkingModelRoute =
  AuthenticatedSystemWorkflowsThinkingModelRouteImport.update({
    id: '/thinking-model',
    path: '/thinking-model',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsStructuredExtractionRoute =
  AuthenticatedSystemWorkflowsStructuredExtractionRouteImport.update({
    id: '/structured-extraction',
    path: '/structured-extraction',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsStandardRagRoute =
  AuthenticatedSystemWorkflowsStandardRagRouteImport.update({
    id: '/standard-rag',
    path: '/standard-rag',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsOpinionIngestionRoute =
  AuthenticatedSystemWorkflowsOpinionIngestionRouteImport.update({
    id: '/opinion-ingestion',
    path: '/opinion-ingestion',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsFileParseRoute =
  AuthenticatedSystemWorkflowsFileParseRouteImport.update({
    id: '/file-parse',
    path: '/file-parse',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsEventIngestionRoute =
  AuthenticatedSystemWorkflowsEventIngestionRouteImport.update({
    id: '/event-ingestion',
    path: '/event-ingestion',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsDouyinParseRoute =
  AuthenticatedSystemWorkflowsDouyinParseRouteImport.update({
    id: '/douyin-parse',
    path: '/douyin-parse',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsDiaryAnalysisRoute =
  AuthenticatedSystemWorkflowsDiaryAnalysisRouteImport.update({
    id: '/diary-analysis',
    path: '/diary-analysis',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSystemWorkflowsCaseIngestionRoute =
  AuthenticatedSystemWorkflowsCaseIngestionRouteImport.update({
    id: '/case-ingestion',
    path: '/case-ingestion',
    getParentRoute: () => AuthenticatedSystemWorkflowsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AuthenticatedProjectsRouteRoute,
  } as any)
const AuthenticatedNovelsNovelIdRoute =
  AuthenticatedNovelsNovelIdRouteImport.update({
    id: '/$novelId',
    path: '/$novelId',
    getParentRoute: () => AuthenticatedNovelsRouteRoute,
  } as any)
const AuthenticatedKnowledgeBaseKbIdRoute =
  AuthenticatedKnowledgeBaseKbIdRouteImport.update({
    id: '/$kbId',
    path: '/$kbId',
    getParentRoute: () => AuthenticatedKnowledgeBaseRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocIdRoute =
  AuthenticatedDocumentsDocIdRouteImport.update({
    id: '/documents/$docId',
    path: '/documents/$docId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiariesTimelineRoute =
  AuthenticatedDiariesTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => AuthenticatedDiariesRouteRoute,
  } as any)
const AuthenticatedDiariesDiaryIdRoute =
  AuthenticatedDiariesDiaryIdRouteImport.update({
    id: '/$diaryId',
    path: '/$diaryId',
    getParentRoute: () => AuthenticatedDiariesRouteRoute,
  } as any)
const AuthenticatedCanvasWorkflowTestRoute =
  AuthenticatedCanvasWorkflowTestRouteImport.update({
    id: '/workflow-test',
    path: '/workflow-test',
    getParentRoute: () => AuthenticatedCanvasRouteRoute,
  } as any)
const AuthenticatedCanvasComicRoute =
  AuthenticatedCanvasComicRouteImport.update({
    id: '/comic',
    path: '/comic',
    getParentRoute: () => AuthenticatedCanvasRouteRoute,
  } as any)
const AuthenticatedCanvasComfyuiRoute =
  AuthenticatedCanvasComfyuiRouteImport.update({
    id: '/comfyui',
    path: '/comfyui',
    getParentRoute: () => AuthenticatedCanvasRouteRoute,
  } as any)
const AuthenticatedTemplatesLayoutIndexRoute =
  AuthenticatedTemplatesLayoutIndexRouteImport.update({
    id: '/templates/layout/',
    path: '/templates/layout/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesComponentsIndexRoute =
  AuthenticatedTemplatesComponentsIndexRouteImport.update({
    id: '/templates/components/',
    path: '/templates/components/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesLayoutTopNavLayoutRoute =
  AuthenticatedTemplatesLayoutTopNavLayoutRouteImport.update({
    id: '/templates/layout/top-nav-layout',
    path: '/templates/layout/top-nav-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesLayoutTabLayoutRoute =
  AuthenticatedTemplatesLayoutTabLayoutRouteImport.update({
    id: '/templates/layout/tab-layout',
    path: '/templates/layout/tab-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesLayoutStandardListLayoutRoute =
  AuthenticatedTemplatesLayoutStandardListLayoutRouteImport.update({
    id: '/templates/layout/standard-list-layout',
    path: '/templates/layout/standard-list-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesLayoutStandardLayoutRoute =
  AuthenticatedTemplatesLayoutStandardLayoutRouteImport.update({
    id: '/templates/layout/standard-layout',
    path: '/templates/layout/standard-layout',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesComponentsUserSearchRoute =
  AuthenticatedTemplatesComponentsUserSearchRouteImport.update({
    id: '/templates/components/user-search',
    path: '/templates/components/user-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesComponentsBasicComponentsRoute =
  AuthenticatedTemplatesComponentsBasicComponentsRouteImport.update({
    id: '/templates/components/basic-components',
    path: '/templates/components/basic-components',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/canvas': typeof AuthenticatedCanvasRouteRouteWithChildren
  '/diaries': typeof AuthenticatedDiariesRouteRouteWithChildren
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRouteRouteWithChildren
  '/novels': typeof AuthenticatedNovelsRouteRouteWithChildren
  '/projects': typeof AuthenticatedProjectsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/system-workflows': typeof AuthenticatedSystemWorkflowsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/comfyui': typeof AuthenticatedComfyuiRoute
  '/cookie-settings': typeof AuthenticatedCookieSettingsRoute
  '/flow': typeof AuthenticatedFlowRoute
  '/intelligence-analysis': typeof AuthenticatedIntelligenceAnalysisRoute
  '/model-settings': typeof AuthenticatedModelSettingsRoute
  '/retrieval-test': typeof AuthenticatedRetrievalTestRoute
  '/test-demo': typeof AuthenticatedTestDemoRoute
  '/thinking-models': typeof AuthenticatedThinkingModelsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/canvas/comfyui': typeof AuthenticatedCanvasComfyuiRoute
  '/canvas/comic': typeof AuthenticatedCanvasComicRoute
  '/canvas/workflow-test': typeof AuthenticatedCanvasWorkflowTestRoute
  '/diaries/$diaryId': typeof AuthenticatedDiariesDiaryIdRoute
  '/diaries/timeline': typeof AuthenticatedDiariesTimelineRoute
  '/documents/$docId': typeof AuthenticatedDocumentsDocIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/knowledge-base/$kbId': typeof AuthenticatedKnowledgeBaseKbIdRoute
  '/novels/$novelId': typeof AuthenticatedNovelsNovelIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/system-workflows/case-ingestion': typeof AuthenticatedSystemWorkflowsCaseIngestionRoute
  '/system-workflows/diary-analysis': typeof AuthenticatedSystemWorkflowsDiaryAnalysisRoute
  '/system-workflows/douyin-parse': typeof AuthenticatedSystemWorkflowsDouyinParseRoute
  '/system-workflows/event-ingestion': typeof AuthenticatedSystemWorkflowsEventIngestionRoute
  '/system-workflows/file-parse': typeof AuthenticatedSystemWorkflowsFileParseRoute
  '/system-workflows/opinion-ingestion': typeof AuthenticatedSystemWorkflowsOpinionIngestionRoute
  '/system-workflows/standard-rag': typeof AuthenticatedSystemWorkflowsStandardRagRoute
  '/system-workflows/structured-extraction': typeof AuthenticatedSystemWorkflowsStructuredExtractionRoute
  '/system-workflows/thinking-model': typeof AuthenticatedSystemWorkflowsThinkingModelRoute
  '/system-workflows/tiered-rag': typeof AuthenticatedSystemWorkflowsTieredRagRoute
  '/system-workflows/video-parse': typeof AuthenticatedSystemWorkflowsVideoParseRoute
  '/system-workflows/web-parse': typeof AuthenticatedSystemWorkflowsWebParseRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/ai-music/': typeof AuthenticatedAiMusicIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/diaries/': typeof AuthenticatedDiariesIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/knowledge-base/': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/novels/': typeof AuthenticatedNovelsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/system-workflows/': typeof AuthenticatedSystemWorkflowsIndexRoute
  '/tags/': typeof AuthenticatedTagsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/templates/components/basic-components': typeof AuthenticatedTemplatesComponentsBasicComponentsRoute
  '/templates/components/user-search': typeof AuthenticatedTemplatesComponentsUserSearchRoute
  '/templates/layout/standard-layout': typeof AuthenticatedTemplatesLayoutStandardLayoutRoute
  '/templates/layout/standard-list-layout': typeof AuthenticatedTemplatesLayoutStandardListLayoutRoute
  '/templates/layout/tab-layout': typeof AuthenticatedTemplatesLayoutTabLayoutRoute
  '/templates/layout/top-nav-layout': typeof AuthenticatedTemplatesLayoutTopNavLayoutRoute
  '/templates/components/': typeof AuthenticatedTemplatesComponentsIndexRoute
  '/templates/layout/': typeof AuthenticatedTemplatesLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/canvas': typeof AuthenticatedCanvasRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/comfyui': typeof AuthenticatedComfyuiRoute
  '/cookie-settings': typeof AuthenticatedCookieSettingsRoute
  '/flow': typeof AuthenticatedFlowRoute
  '/intelligence-analysis': typeof AuthenticatedIntelligenceAnalysisRoute
  '/model-settings': typeof AuthenticatedModelSettingsRoute
  '/retrieval-test': typeof AuthenticatedRetrievalTestRoute
  '/test-demo': typeof AuthenticatedTestDemoRoute
  '/thinking-models': typeof AuthenticatedThinkingModelsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/': typeof AuthenticatedIndexRoute
  '/canvas/comfyui': typeof AuthenticatedCanvasComfyuiRoute
  '/canvas/comic': typeof AuthenticatedCanvasComicRoute
  '/canvas/workflow-test': typeof AuthenticatedCanvasWorkflowTestRoute
  '/diaries/$diaryId': typeof AuthenticatedDiariesDiaryIdRoute
  '/diaries/timeline': typeof AuthenticatedDiariesTimelineRoute
  '/documents/$docId': typeof AuthenticatedDocumentsDocIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/knowledge-base/$kbId': typeof AuthenticatedKnowledgeBaseKbIdRoute
  '/novels/$novelId': typeof AuthenticatedNovelsNovelIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/system-workflows/case-ingestion': typeof AuthenticatedSystemWorkflowsCaseIngestionRoute
  '/system-workflows/diary-analysis': typeof AuthenticatedSystemWorkflowsDiaryAnalysisRoute
  '/system-workflows/douyin-parse': typeof AuthenticatedSystemWorkflowsDouyinParseRoute
  '/system-workflows/event-ingestion': typeof AuthenticatedSystemWorkflowsEventIngestionRoute
  '/system-workflows/file-parse': typeof AuthenticatedSystemWorkflowsFileParseRoute
  '/system-workflows/opinion-ingestion': typeof AuthenticatedSystemWorkflowsOpinionIngestionRoute
  '/system-workflows/standard-rag': typeof AuthenticatedSystemWorkflowsStandardRagRoute
  '/system-workflows/structured-extraction': typeof AuthenticatedSystemWorkflowsStructuredExtractionRoute
  '/system-workflows/thinking-model': typeof AuthenticatedSystemWorkflowsThinkingModelRoute
  '/system-workflows/tiered-rag': typeof AuthenticatedSystemWorkflowsTieredRagRoute
  '/system-workflows/video-parse': typeof AuthenticatedSystemWorkflowsVideoParseRoute
  '/system-workflows/web-parse': typeof AuthenticatedSystemWorkflowsWebParseRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/ai-music': typeof AuthenticatedAiMusicIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/diaries': typeof AuthenticatedDiariesIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/novels': typeof AuthenticatedNovelsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/system-workflows': typeof AuthenticatedSystemWorkflowsIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/templates/components/basic-components': typeof AuthenticatedTemplatesComponentsBasicComponentsRoute
  '/templates/components/user-search': typeof AuthenticatedTemplatesComponentsUserSearchRoute
  '/templates/layout/standard-layout': typeof AuthenticatedTemplatesLayoutStandardLayoutRoute
  '/templates/layout/standard-list-layout': typeof AuthenticatedTemplatesLayoutStandardListLayoutRoute
  '/templates/layout/tab-layout': typeof AuthenticatedTemplatesLayoutTabLayoutRoute
  '/templates/layout/top-nav-layout': typeof AuthenticatedTemplatesLayoutTopNavLayoutRoute
  '/templates/components': typeof AuthenticatedTemplatesComponentsIndexRoute
  '/templates/layout': typeof AuthenticatedTemplatesLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/canvas': typeof AuthenticatedCanvasRouteRouteWithChildren
  '/_authenticated/diaries': typeof AuthenticatedDiariesRouteRouteWithChildren
  '/_authenticated/knowledge-base': typeof AuthenticatedKnowledgeBaseRouteRouteWithChildren
  '/_authenticated/novels': typeof AuthenticatedNovelsRouteRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/system-workflows': typeof AuthenticatedSystemWorkflowsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/comfyui': typeof AuthenticatedComfyuiRoute
  '/_authenticated/cookie-settings': typeof AuthenticatedCookieSettingsRoute
  '/_authenticated/flow': typeof AuthenticatedFlowRoute
  '/_authenticated/intelligence-analysis': typeof AuthenticatedIntelligenceAnalysisRoute
  '/_authenticated/model-settings': typeof AuthenticatedModelSettingsRoute
  '/_authenticated/retrieval-test': typeof AuthenticatedRetrievalTestRoute
  '/_authenticated/test-demo': typeof AuthenticatedTestDemoRoute
  '/_authenticated/thinking-models': typeof AuthenticatedThinkingModelsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/canvas/comfyui': typeof AuthenticatedCanvasComfyuiRoute
  '/_authenticated/canvas/comic': typeof AuthenticatedCanvasComicRoute
  '/_authenticated/canvas/workflow-test': typeof AuthenticatedCanvasWorkflowTestRoute
  '/_authenticated/diaries/$diaryId': typeof AuthenticatedDiariesDiaryIdRoute
  '/_authenticated/diaries/timeline': typeof AuthenticatedDiariesTimelineRoute
  '/_authenticated/documents/$docId': typeof AuthenticatedDocumentsDocIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/knowledge-base/$kbId': typeof AuthenticatedKnowledgeBaseKbIdRoute
  '/_authenticated/novels/$novelId': typeof AuthenticatedNovelsNovelIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/system-workflows/case-ingestion': typeof AuthenticatedSystemWorkflowsCaseIngestionRoute
  '/_authenticated/system-workflows/diary-analysis': typeof AuthenticatedSystemWorkflowsDiaryAnalysisRoute
  '/_authenticated/system-workflows/douyin-parse': typeof AuthenticatedSystemWorkflowsDouyinParseRoute
  '/_authenticated/system-workflows/event-ingestion': typeof AuthenticatedSystemWorkflowsEventIngestionRoute
  '/_authenticated/system-workflows/file-parse': typeof AuthenticatedSystemWorkflowsFileParseRoute
  '/_authenticated/system-workflows/opinion-ingestion': typeof AuthenticatedSystemWorkflowsOpinionIngestionRoute
  '/_authenticated/system-workflows/standard-rag': typeof AuthenticatedSystemWorkflowsStandardRagRoute
  '/_authenticated/system-workflows/structured-extraction': typeof AuthenticatedSystemWorkflowsStructuredExtractionRoute
  '/_authenticated/system-workflows/thinking-model': typeof AuthenticatedSystemWorkflowsThinkingModelRoute
  '/_authenticated/system-workflows/tiered-rag': typeof AuthenticatedSystemWorkflowsTieredRagRoute
  '/_authenticated/system-workflows/video-parse': typeof AuthenticatedSystemWorkflowsVideoParseRoute
  '/_authenticated/system-workflows/web-parse': typeof AuthenticatedSystemWorkflowsWebParseRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/ai-music/': typeof AuthenticatedAiMusicIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/diaries/': typeof AuthenticatedDiariesIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/knowledge-base/': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/_authenticated/novels/': typeof AuthenticatedNovelsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/system-workflows/': typeof AuthenticatedSystemWorkflowsIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/templates/components/basic-components': typeof AuthenticatedTemplatesComponentsBasicComponentsRoute
  '/_authenticated/templates/components/user-search': typeof AuthenticatedTemplatesComponentsUserSearchRoute
  '/_authenticated/templates/layout/standard-layout': typeof AuthenticatedTemplatesLayoutStandardLayoutRoute
  '/_authenticated/templates/layout/standard-list-layout': typeof AuthenticatedTemplatesLayoutStandardListLayoutRoute
  '/_authenticated/templates/layout/tab-layout': typeof AuthenticatedTemplatesLayoutTabLayoutRoute
  '/_authenticated/templates/layout/top-nav-layout': typeof AuthenticatedTemplatesLayoutTopNavLayoutRoute
  '/_authenticated/templates/components/': typeof AuthenticatedTemplatesComponentsIndexRoute
  '/_authenticated/templates/layout/': typeof AuthenticatedTemplatesLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/canvas'
    | '/diaries'
    | '/knowledge-base'
    | '/novels'
    | '/projects'
    | '/settings'
    | '/system-workflows'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/comfyui'
    | '/cookie-settings'
    | '/flow'
    | '/intelligence-analysis'
    | '/model-settings'
    | '/retrieval-test'
    | '/test-demo'
    | '/thinking-models'
    | '/tools'
    | '/canvas/comfyui'
    | '/canvas/comic'
    | '/canvas/workflow-test'
    | '/diaries/$diaryId'
    | '/diaries/timeline'
    | '/documents/$docId'
    | '/errors/$error'
    | '/knowledge-base/$kbId'
    | '/novels/$novelId'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/general'
    | '/settings/notifications'
    | '/system-workflows/case-ingestion'
    | '/system-workflows/diary-analysis'
    | '/system-workflows/douyin-parse'
    | '/system-workflows/event-ingestion'
    | '/system-workflows/file-parse'
    | '/system-workflows/opinion-ingestion'
    | '/system-workflows/standard-rag'
    | '/system-workflows/structured-extraction'
    | '/system-workflows/thinking-model'
    | '/system-workflows/tiered-rag'
    | '/system-workflows/video-parse'
    | '/system-workflows/web-parse'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/agents/'
    | '/ai-music/'
    | '/chats/'
    | '/dashboard/'
    | '/diaries/'
    | '/documents/'
    | '/help-center/'
    | '/knowledge-base/'
    | '/novels/'
    | '/projects/'
    | '/settings/'
    | '/system-workflows/'
    | '/tags/'
    | '/tasks/'
    | '/templates/'
    | '/templates/components/basic-components'
    | '/templates/components/user-search'
    | '/templates/layout/standard-layout'
    | '/templates/layout/standard-list-layout'
    | '/templates/layout/tab-layout'
    | '/templates/layout/top-nav-layout'
    | '/templates/components/'
    | '/templates/layout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/canvas'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/comfyui'
    | '/cookie-settings'
    | '/flow'
    | '/intelligence-analysis'
    | '/model-settings'
    | '/retrieval-test'
    | '/test-demo'
    | '/thinking-models'
    | '/tools'
    | '/'
    | '/canvas/comfyui'
    | '/canvas/comic'
    | '/canvas/workflow-test'
    | '/diaries/$diaryId'
    | '/diaries/timeline'
    | '/documents/$docId'
    | '/errors/$error'
    | '/knowledge-base/$kbId'
    | '/novels/$novelId'
    | '/projects/$projectId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/general'
    | '/settings/notifications'
    | '/system-workflows/case-ingestion'
    | '/system-workflows/diary-analysis'
    | '/system-workflows/douyin-parse'
    | '/system-workflows/event-ingestion'
    | '/system-workflows/file-parse'
    | '/system-workflows/opinion-ingestion'
    | '/system-workflows/standard-rag'
    | '/system-workflows/structured-extraction'
    | '/system-workflows/thinking-model'
    | '/system-workflows/tiered-rag'
    | '/system-workflows/video-parse'
    | '/system-workflows/web-parse'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/agents'
    | '/ai-music'
    | '/chats'
    | '/dashboard'
    | '/diaries'
    | '/documents'
    | '/help-center'
    | '/knowledge-base'
    | '/novels'
    | '/projects'
    | '/settings'
    | '/system-workflows'
    | '/tags'
    | '/tasks'
    | '/templates'
    | '/templates/components/basic-components'
    | '/templates/components/user-search'
    | '/templates/layout/standard-layout'
    | '/templates/layout/standard-list-layout'
    | '/templates/layout/tab-layout'
    | '/templates/layout/top-nav-layout'
    | '/templates/components'
    | '/templates/layout'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/canvas'
    | '/_authenticated/diaries'
    | '/_authenticated/knowledge-base'
    | '/_authenticated/novels'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/system-workflows'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/comfyui'
    | '/_authenticated/cookie-settings'
    | '/_authenticated/flow'
    | '/_authenticated/intelligence-analysis'
    | '/_authenticated/model-settings'
    | '/_authenticated/retrieval-test'
    | '/_authenticated/test-demo'
    | '/_authenticated/thinking-models'
    | '/_authenticated/tools'
    | '/_authenticated/'
    | '/_authenticated/canvas/comfyui'
    | '/_authenticated/canvas/comic'
    | '/_authenticated/canvas/workflow-test'
    | '/_authenticated/diaries/$diaryId'
    | '/_authenticated/diaries/timeline'
    | '/_authenticated/documents/$docId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/knowledge-base/$kbId'
    | '/_authenticated/novels/$novelId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/system-workflows/case-ingestion'
    | '/_authenticated/system-workflows/diary-analysis'
    | '/_authenticated/system-workflows/douyin-parse'
    | '/_authenticated/system-workflows/event-ingestion'
    | '/_authenticated/system-workflows/file-parse'
    | '/_authenticated/system-workflows/opinion-ingestion'
    | '/_authenticated/system-workflows/standard-rag'
    | '/_authenticated/system-workflows/structured-extraction'
    | '/_authenticated/system-workflows/thinking-model'
    | '/_authenticated/system-workflows/tiered-rag'
    | '/_authenticated/system-workflows/video-parse'
    | '/_authenticated/system-workflows/web-parse'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/agents/'
    | '/_authenticated/ai-music/'
    | '/_authenticated/chats/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/diaries/'
    | '/_authenticated/documents/'
    | '/_authenticated/help-center/'
    | '/_authenticated/knowledge-base/'
    | '/_authenticated/novels/'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/system-workflows/'
    | '/_authenticated/tags/'
    | '/_authenticated/tasks/'
    | '/_authenticated/templates/'
    | '/_authenticated/templates/components/basic-components'
    | '/_authenticated/templates/components/user-search'
    | '/_authenticated/templates/layout/standard-layout'
    | '/_authenticated/templates/layout/standard-list-layout'
    | '/_authenticated/templates/layout/tab-layout'
    | '/_authenticated/templates/layout/top-nav-layout'
    | '/_authenticated/templates/components/'
    | '/_authenticated/templates/layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/thinking-models': {
      id: '/_authenticated/thinking-models'
      path: '/thinking-models'
      fullPath: '/thinking-models'
      preLoaderRoute: typeof AuthenticatedThinkingModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/test-demo': {
      id: '/_authenticated/test-demo'
      path: '/test-demo'
      fullPath: '/test-demo'
      preLoaderRoute: typeof AuthenticatedTestDemoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retrieval-test': {
      id: '/_authenticated/retrieval-test'
      path: '/retrieval-test'
      fullPath: '/retrieval-test'
      preLoaderRoute: typeof AuthenticatedRetrievalTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model-settings': {
      id: '/_authenticated/model-settings'
      path: '/model-settings'
      fullPath: '/model-settings'
      preLoaderRoute: typeof AuthenticatedModelSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence-analysis': {
      id: '/_authenticated/intelligence-analysis'
      path: '/intelligence-analysis'
      fullPath: '/intelligence-analysis'
      preLoaderRoute: typeof AuthenticatedIntelligenceAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flow': {
      id: '/_authenticated/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof AuthenticatedFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cookie-settings': {
      id: '/_authenticated/cookie-settings'
      path: '/cookie-settings'
      fullPath: '/cookie-settings'
      preLoaderRoute: typeof AuthenticatedCookieSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comfyui': {
      id: '/_authenticated/comfyui'
      path: '/comfyui'
      fullPath: '/comfyui'
      preLoaderRoute: typeof AuthenticatedComfyuiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/system-workflows': {
      id: '/_authenticated/system-workflows'
      path: '/system-workflows'
      fullPath: '/system-workflows'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/novels': {
      id: '/_authenticated/novels'
      path: '/novels'
      fullPath: '/novels'
      preLoaderRoute: typeof AuthenticatedNovelsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-base': {
      id: '/_authenticated/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diaries': {
      id: '/_authenticated/diaries'
      path: '/diaries'
      fullPath: '/diaries'
      preLoaderRoute: typeof AuthenticatedDiariesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/canvas': {
      id: '/_authenticated/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof AuthenticatedCanvasRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-workflows/': {
      id: '/_authenticated/system-workflows/'
      path: '/'
      fullPath: '/system-workflows/'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRouteRoute
    }
    '/_authenticated/novels/': {
      id: '/_authenticated/novels/'
      path: '/'
      fullPath: '/novels/'
      preLoaderRoute: typeof AuthenticatedNovelsIndexRouteImport
      parentRoute: typeof AuthenticatedNovelsRouteRoute
    }
    '/_authenticated/knowledge-base/': {
      id: '/_authenticated/knowledge-base/'
      path: '/'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseIndexRouteImport
      parentRoute: typeof AuthenticatedKnowledgeBaseRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diaries/': {
      id: '/_authenticated/diaries/'
      path: '/'
      fullPath: '/diaries/'
      preLoaderRoute: typeof AuthenticatedDiariesIndexRouteImport
      parentRoute: typeof AuthenticatedDiariesRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-music/': {
      id: '/_authenticated/ai-music/'
      path: '/ai-music'
      fullPath: '/ai-music/'
      preLoaderRoute: typeof AuthenticatedAiMusicIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/system-workflows/web-parse': {
      id: '/_authenticated/system-workflows/web-parse'
      path: '/web-parse'
      fullPath: '/system-workflows/web-parse'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsWebParseRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/video-parse': {
      id: '/_authenticated/system-workflows/video-parse'
      path: '/video-parse'
      fullPath: '/system-workflows/video-parse'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsVideoParseRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/tiered-rag': {
      id: '/_authenticated/system-workflows/tiered-rag'
      path: '/tiered-rag'
      fullPath: '/system-workflows/tiered-rag'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsTieredRagRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/thinking-model': {
      id: '/_authenticated/system-workflows/thinking-model'
      path: '/thinking-model'
      fullPath: '/system-workflows/thinking-model'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsThinkingModelRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/structured-extraction': {
      id: '/_authenticated/system-workflows/structured-extraction'
      path: '/structured-extraction'
      fullPath: '/system-workflows/structured-extraction'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsStructuredExtractionRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/standard-rag': {
      id: '/_authenticated/system-workflows/standard-rag'
      path: '/standard-rag'
      fullPath: '/system-workflows/standard-rag'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsStandardRagRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/opinion-ingestion': {
      id: '/_authenticated/system-workflows/opinion-ingestion'
      path: '/opinion-ingestion'
      fullPath: '/system-workflows/opinion-ingestion'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsOpinionIngestionRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/file-parse': {
      id: '/_authenticated/system-workflows/file-parse'
      path: '/file-parse'
      fullPath: '/system-workflows/file-parse'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsFileParseRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/event-ingestion': {
      id: '/_authenticated/system-workflows/event-ingestion'
      path: '/event-ingestion'
      fullPath: '/system-workflows/event-ingestion'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsEventIngestionRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/douyin-parse': {
      id: '/_authenticated/system-workflows/douyin-parse'
      path: '/douyin-parse'
      fullPath: '/system-workflows/douyin-parse'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsDouyinParseRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/diary-analysis': {
      id: '/_authenticated/system-workflows/diary-analysis'
      path: '/diary-analysis'
      fullPath: '/system-workflows/diary-analysis'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsDiaryAnalysisRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/system-workflows/case-ingestion': {
      id: '/_authenticated/system-workflows/case-ingestion'
      path: '/case-ingestion'
      fullPath: '/system-workflows/case-ingestion'
      preLoaderRoute: typeof AuthenticatedSystemWorkflowsCaseIngestionRouteImport
      parentRoute: typeof AuthenticatedSystemWorkflowsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRouteRoute
    }
    '/_authenticated/novels/$novelId': {
      id: '/_authenticated/novels/$novelId'
      path: '/$novelId'
      fullPath: '/novels/$novelId'
      preLoaderRoute: typeof AuthenticatedNovelsNovelIdRouteImport
      parentRoute: typeof AuthenticatedNovelsRouteRoute
    }
    '/_authenticated/knowledge-base/$kbId': {
      id: '/_authenticated/knowledge-base/$kbId'
      path: '/$kbId'
      fullPath: '/knowledge-base/$kbId'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseKbIdRouteImport
      parentRoute: typeof AuthenticatedKnowledgeBaseRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$docId': {
      id: '/_authenticated/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diaries/timeline': {
      id: '/_authenticated/diaries/timeline'
      path: '/timeline'
      fullPath: '/diaries/timeline'
      preLoaderRoute: typeof AuthenticatedDiariesTimelineRouteImport
      parentRoute: typeof AuthenticatedDiariesRouteRoute
    }
    '/_authenticated/diaries/$diaryId': {
      id: '/_authenticated/diaries/$diaryId'
      path: '/$diaryId'
      fullPath: '/diaries/$diaryId'
      preLoaderRoute: typeof AuthenticatedDiariesDiaryIdRouteImport
      parentRoute: typeof AuthenticatedDiariesRouteRoute
    }
    '/_authenticated/canvas/workflow-test': {
      id: '/_authenticated/canvas/workflow-test'
      path: '/workflow-test'
      fullPath: '/canvas/workflow-test'
      preLoaderRoute: typeof AuthenticatedCanvasWorkflowTestRouteImport
      parentRoute: typeof AuthenticatedCanvasRouteRoute
    }
    '/_authenticated/canvas/comic': {
      id: '/_authenticated/canvas/comic'
      path: '/comic'
      fullPath: '/canvas/comic'
      preLoaderRoute: typeof AuthenticatedCanvasComicRouteImport
      parentRoute: typeof AuthenticatedCanvasRouteRoute
    }
    '/_authenticated/canvas/comfyui': {
      id: '/_authenticated/canvas/comfyui'
      path: '/comfyui'
      fullPath: '/canvas/comfyui'
      preLoaderRoute: typeof AuthenticatedCanvasComfyuiRouteImport
      parentRoute: typeof AuthenticatedCanvasRouteRoute
    }
    '/_authenticated/templates/layout/': {
      id: '/_authenticated/templates/layout/'
      path: '/templates/layout'
      fullPath: '/templates/layout/'
      preLoaderRoute: typeof AuthenticatedTemplatesLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/components/': {
      id: '/_authenticated/templates/components/'
      path: '/templates/components'
      fullPath: '/templates/components/'
      preLoaderRoute: typeof AuthenticatedTemplatesComponentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/layout/top-nav-layout': {
      id: '/_authenticated/templates/layout/top-nav-layout'
      path: '/templates/layout/top-nav-layout'
      fullPath: '/templates/layout/top-nav-layout'
      preLoaderRoute: typeof AuthenticatedTemplatesLayoutTopNavLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/layout/tab-layout': {
      id: '/_authenticated/templates/layout/tab-layout'
      path: '/templates/layout/tab-layout'
      fullPath: '/templates/layout/tab-layout'
      preLoaderRoute: typeof AuthenticatedTemplatesLayoutTabLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/layout/standard-list-layout': {
      id: '/_authenticated/templates/layout/standard-list-layout'
      path: '/templates/layout/standard-list-layout'
      fullPath: '/templates/layout/standard-list-layout'
      preLoaderRoute: typeof AuthenticatedTemplatesLayoutStandardListLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/layout/standard-layout': {
      id: '/_authenticated/templates/layout/standard-layout'
      path: '/templates/layout/standard-layout'
      fullPath: '/templates/layout/standard-layout'
      preLoaderRoute: typeof AuthenticatedTemplatesLayoutStandardLayoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/components/user-search': {
      id: '/_authenticated/templates/components/user-search'
      path: '/templates/components/user-search'
      fullPath: '/templates/components/user-search'
      preLoaderRoute: typeof AuthenticatedTemplatesComponentsUserSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/components/basic-components': {
      id: '/_authenticated/templates/components/basic-components'
      path: '/templates/components/basic-components'
      fullPath: '/templates/components/basic-components'
      preLoaderRoute: typeof AuthenticatedTemplatesComponentsBasicComponentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCanvasRouteRouteChildren {
  AuthenticatedCanvasComfyuiRoute: typeof AuthenticatedCanvasComfyuiRoute
  AuthenticatedCanvasComicRoute: typeof AuthenticatedCanvasComicRoute
  AuthenticatedCanvasWorkflowTestRoute: typeof AuthenticatedCanvasWorkflowTestRoute
}

const AuthenticatedCanvasRouteRouteChildren: AuthenticatedCanvasRouteRouteChildren =
  {
    AuthenticatedCanvasComfyuiRoute: AuthenticatedCanvasComfyuiRoute,
    AuthenticatedCanvasComicRoute: AuthenticatedCanvasComicRoute,
    AuthenticatedCanvasWorkflowTestRoute: AuthenticatedCanvasWorkflowTestRoute,
  }

const AuthenticatedCanvasRouteRouteWithChildren =
  AuthenticatedCanvasRouteRoute._addFileChildren(
    AuthenticatedCanvasRouteRouteChildren,
  )

interface AuthenticatedDiariesRouteRouteChildren {
  AuthenticatedDiariesDiaryIdRoute: typeof AuthenticatedDiariesDiaryIdRoute
  AuthenticatedDiariesTimelineRoute: typeof AuthenticatedDiariesTimelineRoute
  AuthenticatedDiariesIndexRoute: typeof AuthenticatedDiariesIndexRoute
}

const AuthenticatedDiariesRouteRouteChildren: AuthenticatedDiariesRouteRouteChildren =
  {
    AuthenticatedDiariesDiaryIdRoute: AuthenticatedDiariesDiaryIdRoute,
    AuthenticatedDiariesTimelineRoute: AuthenticatedDiariesTimelineRoute,
    AuthenticatedDiariesIndexRoute: AuthenticatedDiariesIndexRoute,
  }

const AuthenticatedDiariesRouteRouteWithChildren =
  AuthenticatedDiariesRouteRoute._addFileChildren(
    AuthenticatedDiariesRouteRouteChildren,
  )

interface AuthenticatedKnowledgeBaseRouteRouteChildren {
  AuthenticatedKnowledgeBaseKbIdRoute: typeof AuthenticatedKnowledgeBaseKbIdRoute
  AuthenticatedKnowledgeBaseIndexRoute: typeof AuthenticatedKnowledgeBaseIndexRoute
}

const AuthenticatedKnowledgeBaseRouteRouteChildren: AuthenticatedKnowledgeBaseRouteRouteChildren =
  {
    AuthenticatedKnowledgeBaseKbIdRoute: AuthenticatedKnowledgeBaseKbIdRoute,
    AuthenticatedKnowledgeBaseIndexRoute: AuthenticatedKnowledgeBaseIndexRoute,
  }

const AuthenticatedKnowledgeBaseRouteRouteWithChildren =
  AuthenticatedKnowledgeBaseRouteRoute._addFileChildren(
    AuthenticatedKnowledgeBaseRouteRouteChildren,
  )

interface AuthenticatedNovelsRouteRouteChildren {
  AuthenticatedNovelsNovelIdRoute: typeof AuthenticatedNovelsNovelIdRoute
  AuthenticatedNovelsIndexRoute: typeof AuthenticatedNovelsIndexRoute
}

const AuthenticatedNovelsRouteRouteChildren: AuthenticatedNovelsRouteRouteChildren =
  {
    AuthenticatedNovelsNovelIdRoute: AuthenticatedNovelsNovelIdRoute,
    AuthenticatedNovelsIndexRoute: AuthenticatedNovelsIndexRoute,
  }

const AuthenticatedNovelsRouteRouteWithChildren =
  AuthenticatedNovelsRouteRoute._addFileChildren(
    AuthenticatedNovelsRouteRouteChildren,
  )

interface AuthenticatedProjectsRouteRouteChildren {
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedProjectsRouteRouteChildren: AuthenticatedProjectsRouteRouteChildren =
  {
    AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
    AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  }

const AuthenticatedProjectsRouteRouteWithChildren =
  AuthenticatedProjectsRouteRoute._addFileChildren(
    AuthenticatedProjectsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSystemWorkflowsRouteRouteChildren {
  AuthenticatedSystemWorkflowsCaseIngestionRoute: typeof AuthenticatedSystemWorkflowsCaseIngestionRoute
  AuthenticatedSystemWorkflowsDiaryAnalysisRoute: typeof AuthenticatedSystemWorkflowsDiaryAnalysisRoute
  AuthenticatedSystemWorkflowsDouyinParseRoute: typeof AuthenticatedSystemWorkflowsDouyinParseRoute
  AuthenticatedSystemWorkflowsEventIngestionRoute: typeof AuthenticatedSystemWorkflowsEventIngestionRoute
  AuthenticatedSystemWorkflowsFileParseRoute: typeof AuthenticatedSystemWorkflowsFileParseRoute
  AuthenticatedSystemWorkflowsOpinionIngestionRoute: typeof AuthenticatedSystemWorkflowsOpinionIngestionRoute
  AuthenticatedSystemWorkflowsStandardRagRoute: typeof AuthenticatedSystemWorkflowsStandardRagRoute
  AuthenticatedSystemWorkflowsStructuredExtractionRoute: typeof AuthenticatedSystemWorkflowsStructuredExtractionRoute
  AuthenticatedSystemWorkflowsThinkingModelRoute: typeof AuthenticatedSystemWorkflowsThinkingModelRoute
  AuthenticatedSystemWorkflowsTieredRagRoute: typeof AuthenticatedSystemWorkflowsTieredRagRoute
  AuthenticatedSystemWorkflowsVideoParseRoute: typeof AuthenticatedSystemWorkflowsVideoParseRoute
  AuthenticatedSystemWorkflowsWebParseRoute: typeof AuthenticatedSystemWorkflowsWebParseRoute
  AuthenticatedSystemWorkflowsIndexRoute: typeof AuthenticatedSystemWorkflowsIndexRoute
}

const AuthenticatedSystemWorkflowsRouteRouteChildren: AuthenticatedSystemWorkflowsRouteRouteChildren =
  {
    AuthenticatedSystemWorkflowsCaseIngestionRoute:
      AuthenticatedSystemWorkflowsCaseIngestionRoute,
    AuthenticatedSystemWorkflowsDiaryAnalysisRoute:
      AuthenticatedSystemWorkflowsDiaryAnalysisRoute,
    AuthenticatedSystemWorkflowsDouyinParseRoute:
      AuthenticatedSystemWorkflowsDouyinParseRoute,
    AuthenticatedSystemWorkflowsEventIngestionRoute:
      AuthenticatedSystemWorkflowsEventIngestionRoute,
    AuthenticatedSystemWorkflowsFileParseRoute:
      AuthenticatedSystemWorkflowsFileParseRoute,
    AuthenticatedSystemWorkflowsOpinionIngestionRoute:
      AuthenticatedSystemWorkflowsOpinionIngestionRoute,
    AuthenticatedSystemWorkflowsStandardRagRoute:
      AuthenticatedSystemWorkflowsStandardRagRoute,
    AuthenticatedSystemWorkflowsStructuredExtractionRoute:
      AuthenticatedSystemWorkflowsStructuredExtractionRoute,
    AuthenticatedSystemWorkflowsThinkingModelRoute:
      AuthenticatedSystemWorkflowsThinkingModelRoute,
    AuthenticatedSystemWorkflowsTieredRagRoute:
      AuthenticatedSystemWorkflowsTieredRagRoute,
    AuthenticatedSystemWorkflowsVideoParseRoute:
      AuthenticatedSystemWorkflowsVideoParseRoute,
    AuthenticatedSystemWorkflowsWebParseRoute:
      AuthenticatedSystemWorkflowsWebParseRoute,
    AuthenticatedSystemWorkflowsIndexRoute:
      AuthenticatedSystemWorkflowsIndexRoute,
  }

const AuthenticatedSystemWorkflowsRouteRouteWithChildren =
  AuthenticatedSystemWorkflowsRouteRoute._addFileChildren(
    AuthenticatedSystemWorkflowsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCanvasRouteRoute: typeof AuthenticatedCanvasRouteRouteWithChildren
  AuthenticatedDiariesRouteRoute: typeof AuthenticatedDiariesRouteRouteWithChildren
  AuthenticatedKnowledgeBaseRouteRoute: typeof AuthenticatedKnowledgeBaseRouteRouteWithChildren
  AuthenticatedNovelsRouteRoute: typeof AuthenticatedNovelsRouteRouteWithChildren
  AuthenticatedProjectsRouteRoute: typeof AuthenticatedProjectsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSystemWorkflowsRouteRoute: typeof AuthenticatedSystemWorkflowsRouteRouteWithChildren
  AuthenticatedComfyuiRoute: typeof AuthenticatedComfyuiRoute
  AuthenticatedCookieSettingsRoute: typeof AuthenticatedCookieSettingsRoute
  AuthenticatedFlowRoute: typeof AuthenticatedFlowRoute
  AuthenticatedIntelligenceAnalysisRoute: typeof AuthenticatedIntelligenceAnalysisRoute
  AuthenticatedModelSettingsRoute: typeof AuthenticatedModelSettingsRoute
  AuthenticatedRetrievalTestRoute: typeof AuthenticatedRetrievalTestRoute
  AuthenticatedTestDemoRoute: typeof AuthenticatedTestDemoRoute
  AuthenticatedThinkingModelsRoute: typeof AuthenticatedThinkingModelsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentsDocIdRoute: typeof AuthenticatedDocumentsDocIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedAiMusicIndexRoute: typeof AuthenticatedAiMusicIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedTemplatesComponentsBasicComponentsRoute: typeof AuthenticatedTemplatesComponentsBasicComponentsRoute
  AuthenticatedTemplatesComponentsUserSearchRoute: typeof AuthenticatedTemplatesComponentsUserSearchRoute
  AuthenticatedTemplatesLayoutStandardLayoutRoute: typeof AuthenticatedTemplatesLayoutStandardLayoutRoute
  AuthenticatedTemplatesLayoutStandardListLayoutRoute: typeof AuthenticatedTemplatesLayoutStandardListLayoutRoute
  AuthenticatedTemplatesLayoutTabLayoutRoute: typeof AuthenticatedTemplatesLayoutTabLayoutRoute
  AuthenticatedTemplatesLayoutTopNavLayoutRoute: typeof AuthenticatedTemplatesLayoutTopNavLayoutRoute
  AuthenticatedTemplatesComponentsIndexRoute: typeof AuthenticatedTemplatesComponentsIndexRoute
  AuthenticatedTemplatesLayoutIndexRoute: typeof AuthenticatedTemplatesLayoutIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCanvasRouteRoute: AuthenticatedCanvasRouteRouteWithChildren,
  AuthenticatedDiariesRouteRoute: AuthenticatedDiariesRouteRouteWithChildren,
  AuthenticatedKnowledgeBaseRouteRoute:
    AuthenticatedKnowledgeBaseRouteRouteWithChildren,
  AuthenticatedNovelsRouteRoute: AuthenticatedNovelsRouteRouteWithChildren,
  AuthenticatedProjectsRouteRoute: AuthenticatedProjectsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSystemWorkflowsRouteRoute:
    AuthenticatedSystemWorkflowsRouteRouteWithChildren,
  AuthenticatedComfyuiRoute: AuthenticatedComfyuiRoute,
  AuthenticatedCookieSettingsRoute: AuthenticatedCookieSettingsRoute,
  AuthenticatedFlowRoute: AuthenticatedFlowRoute,
  AuthenticatedIntelligenceAnalysisRoute:
    AuthenticatedIntelligenceAnalysisRoute,
  AuthenticatedModelSettingsRoute: AuthenticatedModelSettingsRoute,
  AuthenticatedRetrievalTestRoute: AuthenticatedRetrievalTestRoute,
  AuthenticatedTestDemoRoute: AuthenticatedTestDemoRoute,
  AuthenticatedThinkingModelsRoute: AuthenticatedThinkingModelsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentsDocIdRoute: AuthenticatedDocumentsDocIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedAiMusicIndexRoute: AuthenticatedAiMusicIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedTemplatesComponentsBasicComponentsRoute:
    AuthenticatedTemplatesComponentsBasicComponentsRoute,
  AuthenticatedTemplatesComponentsUserSearchRoute:
    AuthenticatedTemplatesComponentsUserSearchRoute,
  AuthenticatedTemplatesLayoutStandardLayoutRoute:
    AuthenticatedTemplatesLayoutStandardLayoutRoute,
  AuthenticatedTemplatesLayoutStandardListLayoutRoute:
    AuthenticatedTemplatesLayoutStandardListLayoutRoute,
  AuthenticatedTemplatesLayoutTabLayoutRoute:
    AuthenticatedTemplatesLayoutTabLayoutRoute,
  AuthenticatedTemplatesLayoutTopNavLayoutRoute:
    AuthenticatedTemplatesLayoutTopNavLayoutRoute,
  AuthenticatedTemplatesComponentsIndexRoute:
    AuthenticatedTemplatesComponentsIndexRoute,
  AuthenticatedTemplatesLayoutIndexRoute:
    AuthenticatedTemplatesLayoutIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
