# Project Memory

> Auto-generated by Memory Loop. Do not delete this file.
> Last updated: {UPDATED_AT}

## Project Context

{PROJECT_CONTEXT}

## Active Goals

{ACTIVE_GOALS}

## Decisions Log

{DECISIONS_LOG}

## Gotchas

{GOTCHAS}

## Completed

{COMPLETED}

## Status

{STATUS}
