/**
 * 批量新增具有教育价值的PBL项目
 * 素材来源：小学科学、道德与法治、语文、数学等教材重点单元
 * 不限制总数，越多越好
 */

import fs from 'fs';
import path from 'path';
import db from '../config/database';

function makeSteps(title: string, steps: string[]): any[] {
  const templates = [
    { title: '准备材料', image_desc: 'materials and tools neatly arranged on a desk' },
    { title: '学习探究', image_desc: 'learning process with reference materials and notes' },
    { title: '动手实践', image_desc: 'hands-on activity in progress' },
    { title: '观察记录', image_desc: 'notebook and observation tools' },
    { title: '思考分析', image_desc: 'analysis and reflection with diagrams' },
    { title: '展示分享', image_desc: 'final result presentation and display' },
  ];
  return steps.map((s, i) => ({
    step: i + 1,
    title: templates[i].title,
    content: s,
    image_prompt: `${title} project, ${templates[i].image_desc}, educational illustration, clean and simple style`
  }));
}

const NEW_TASKS = [
  // ========== 科学实验 (8个) ==========
  {
    title: '酸碱指示剂（红甘蓝实验）',
    description: '你知道怎么判断一种液体是酸性还是碱性吗？用紫甘蓝（红甘蓝）煮出来的紫色水，遇到醋会变红，遇到小苏打水会变蓝！这就是天然的酸碱指示剂。在这个实验中，你将测试家里各种液体的酸碱性，成为"小小化学家"！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：紫甘蓝（半个）、热水、白醋、小苏打、柠檬汁、肥皂水、透明杯子若干\n2. 将紫甘蓝切碎放入热水中浸泡10分钟，得到紫色汁液\n3. 将紫色汁液分别倒入装有不同测试液体的杯子中\n4. 观察颜色变化：变红=酸性，变蓝/绿=碱性，不变=中性\n5. 测试家里至少5种液体（牛奶、橙汁、自来水、洗洁精水等）\n6. 制作"酸碱性颜色对照表"',
    reference_materials: '1. 视频推荐：搜索"紫甘蓝酸碱指示剂"\n2. 科学原理：紫甘蓝中含有花青素，是一种天然酸碱指示剂，遇到酸性物质变红，遇到碱性物质变蓝绿色\n3. pH值：pH<7酸性，pH=7中性，pH>7碱性\n4. 生活中的酸碱：醋（酸性）、小苏打（碱性）、纯水（中性）、柠檬（酸性）、肥皂（碱性）',
    visual_prompt: 'Purple cabbage juice in several clear glasses showing different colors, red in vinegar glass, blue in baking soda glass, purple in plain water, various test liquids like lemon juice and soap water, pH test experiment on a wooden table, clean science illustration',
    steps: makeSteps('酸碱指示剂', [
      '准备材料：紫甘蓝、热水、白醋、小苏打、柠檬汁、透明杯子、勺子',
      '学习酸碱概念：什么是酸、什么是碱、什么是中性，了解pH值的含义',
      '制作紫甘蓝汁：将紫甘蓝切碎放入热水中浸泡10分钟，过滤得到紫色汁液',
      '测试各种液体：将紫甘蓝汁分别加入白醋、小苏打水、柠檬汁、肥皂水、牛奶中，观察颜色变化',
      '思考：为什么紫甘蓝汁遇到不同液体会变色？花青素是怎么工作的？',
      '制作"酸碱性颜色对照表"，向家人展示每种液体的酸碱性',
    ]),
  },
  {
    title: '表面张力与肥皂泡',
    description: '为什么水黾（一种小虫子）能在水面上行走？为什么水滴是圆形的？这些都是"表面张力"的魔法！在这个实验中，你将探索水的表面张力，尝试用肥皂水吹出最大的泡泡，还要做一个让胡椒粉"逃跑"的有趣实验！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '2-5',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：碗、水、胡椒粉、洗洁精、吸管、肥皂水、甘油、细铁丝（做泡泡圈）\n2. 胡椒粉实验：碗中装水，撒上胡椒粉，手指蘸一点洗洁精后触碰水面，观察胡椒粉"逃跑"\n3. 硬币滴水实验：用滴管在硬币上滴水，数一数最多能滴多少滴而不溢出\n4. 自制泡泡水：洗洁精+水+少许甘油，用吸管或铁丝圈吹泡泡\n5. 观察不同形状的泡泡圈吹出的泡泡有什么不同\n6. 了解表面张力在生活中的应用',
    reference_materials: '1. 视频推荐：搜索"表面张力实验 小学生"\n2. 科学原理：水的表面有一层"薄膜"（表面张力），像一张有弹性的网。洗洁精能破坏水的表面张力，所以胡椒粉会被"推开"\n3. 为什么水滴是圆的？表面张力让水滴尽可能缩小表面积，而球形是表面积最小的形状\n4. 生活中的表面张力：水黾在水面行走、露珠是圆的、肥皂泡是圆的',
    visual_prompt: 'Surface tension science experiment, bowl of water with pepper flakes scattering away from a soapy finger, shiny soap bubbles floating in the air, a coin covered with water droplets, bubble wand and soap solution on a table, clean bright educational illustration',
    steps: makeSteps('表面张力与肥皂泡', [
      '准备材料：碗、水、胡椒粉、洗洁精、吸管、肥皂水、甘油、硬币、滴管',
      '胡椒粉实验：碗中装水撒胡椒粉，手指蘸洗洁精轻触水面，观察胡椒粉迅速散开',
      '硬币滴水：用滴管在一元硬币上滴水，数一数最多能滴多少滴而不溢出',
      '制作泡泡水：洗洁精+水+甘油混合，用吸管吹泡泡，观察泡泡的形状和颜色',
      '思考：为什么胡椒粉会逃跑？为什么硬币上能滴那么多水？为什么泡泡是圆的？',
      '展示你的实验成果，解释表面张力的原理',
    ]),
  },
  {
    title: '杠杆与简单机械',
    description: '阿基米德说过："给我一个支点，我就能撬起地球！"你想体验用一根木棍撬起重物的感觉吗？在这个实验中，你将用尺子、橡皮和硬币，亲手制作一个杠杆，探索支点位置如何影响力量大小，理解"省力"和"费力"的原理！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：长尺子（或直尺）、橡皮（或小木块，做支点）、硬币若干（做重物）、夹子、绳子\n2. 将尺子放在橡皮上，一端放硬币，另一端用手指按压\n3. 移动支点（橡皮）的位置，感受用力大小的变化\n4. 记录：支点靠近重物时省力、支点远离重物时费力\n5. 找找生活中的杠杆：剪刀、镊子、开瓶器、筷子、跷跷板\n6. 了解其他简单机械：滑轮、斜面、轮轴',
    reference_materials: '1. 视频推荐：搜索"杠杆原理实验 小学生"\n2. 科学原理：杠杆平衡条件——动力×动力臂=阻力×阻力臂。动力臂越长越省力，阻力臂越短越省力\n3. 省力杠杆：支点靠近重物（如开瓶器、撬棍）；费力杠杆：支点靠近用力点（如镊子、筷子）；等臂杠杆：支点在中间（如跷跷板、天平）\n4. 简单机械家族：杠杆、滑轮、斜面、轮轴、螺旋',
    visual_prompt: 'Simple lever experiment on a wooden table, a ruler balanced on an eraser as a fulcrum, coins stacked on one end and a finger pressing the other end, diagram showing force arm and resistance arm, scissors and bottle opener as examples of levers, clean educational illustration',
    steps: makeSteps('杠杆与简单机械', [
      '准备材料：长尺子、橡皮（支点）、硬币若干、夹子、绳子',
      '搭建杠杆：将尺子放在橡皮上，一端放5枚硬币，另一端用手指按压，感受力量',
      '移动支点位置：支点靠近硬币（省力）、支点靠近手指（费力），各做3次记录',
      '寻找生活中的杠杆：找出至少5种使用杠杆原理的工具（剪刀、筷子、开瓶器等）',
      '思考：为什么筷子是费力杠杆？费力杠杆有什么好处？跷跷板为什么能平衡？',
      '画出杠杆原理图，标注支点、动力臂、阻力臂，向家人展示',
    ]),
  },
  {
    title: '摩擦力大比拼',
    description: '为什么在冰面上走容易滑倒？为什么汽车轮胎上有花纹？这些都和摩擦力有关！在这个实验中，你将用不同材料测试摩擦力的大小，看看什么东西最滑、什么东西最粗糙，理解摩擦力在生活中的重要性！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '2-5',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：木板（或硬纸板）、不同材料表面（砂纸、毛巾、塑料袋、蜡纸）、橡皮（或小玩具车）、尺子\n2. 将木板一端抬高形成一个斜坡\n3. 将橡皮放在不同表面的斜坡上，慢慢增加斜坡角度，记录橡皮开始滑动时的角度\n4. 角度越大，说明摩擦力越大\n5. 测试至少5种不同表面的摩擦力\n6. 了解摩擦力在生活中的应用：花纹鞋底、轮胎花纹、冰雪路面撒沙',
    reference_materials: '1. 视频推荐：搜索"摩擦力实验 小学生"\n2. 科学原理：摩擦力是两个接触面之间的阻力，粗糙表面摩擦力大，光滑表面摩擦力小\n3. 摩擦力的大小和什么有关？接触面的粗糙程度、物体的重量（压力越大摩擦力越大）\n4. 生活应用：鞋底花纹增加摩擦力防滑；汽车轮胎花纹增加抓地力；给门轴加润滑油减少摩擦力；冰雪路面撒沙子增加摩擦力',
    visual_prompt: 'Friction experiment on a tilted wooden board, a small block sliding down different surfaces, sandpaper rough surface, smooth plastic surface, towel fabric surface, an angle ruler measuring the slope, clean physics experiment illustration',
    steps: makeSteps('摩擦力大比拼', [
      '准备材料：木板、砂纸、毛巾、塑料袋、蜡纸、橡皮、尺子、量角器',
      '搭建斜坡：将木板一端抬高，分别铺上不同材料（砂纸、毛巾、塑料袋、蜡纸）',
      '测试摩擦力：将橡皮放在不同材料的斜坡上，慢慢增加角度，记录橡皮开始滑动时的角度',
      '对比分析：按角度从大到小排列，摩擦力最大的材料（角度最大）到摩擦力最小的材料',
      '思考：为什么冰面上容易滑倒？为什么鞋子底有花纹？为什么汽车轮胎有花纹？',
      '制作"摩擦力排行榜"，展示并向家人解释摩擦力在生活中的应用',
    ]),
  },
  {
    title: '声音的传播',
    description: '声音是怎么传到我们耳朵里的？为什么在真空里听不到声音？声音可以在水里传播吗？在这个实验中，你将用简单的材料探索声音传播的秘密，制作一个"土电话"，理解声音需要介质才能传播！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '2-5',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：两个纸杯、一根长线（约3米）、牙签、音叉（或勺子）、水盆\n2. 制作土电话：将线穿过两个纸杯底部，用牙签固定\n3. 和家长测试土电话：拉直线，一人对着纸杯说话，另一人听\n4. 声音在水中传播：敲击音叉后放入水中，耳朵贴近水面听\n5. 声音在固体中传播：敲击桌子，耳朵贴在桌面上听\n6. 了解声音的三要素：音调（高低）、响度（大小）、音色（特色）',
    reference_materials: '1. 视频推荐：搜索"声音传播实验 小学生"\n2. 科学原理：声音是物体振动产生的，通过介质（空气、水、固体）以波的形式传播。真空不能传声\n3. 声音在不同介质中的传播速度：固体最快（约5000m/s），液体次之（约1500m/s），气体最慢（约340m/s）\n4. 为什么土电话能传声？声音通过线的振动传播，固体传声比空气更清晰',
    visual_prompt: 'Sound wave experiment, two paper cups connected by a long string as a tin can telephone, tuning fork vibrating in water creating ripples, ear pressed against a wooden table, sound wave diagram, clean educational illustration',
    steps: makeSteps('声音的传播', [
      '准备材料：两个纸杯、长线、牙签、音叉（或勺子）、水盆',
      '制作土电话：将线穿过两个纸杯底部，用牙签固定，拉直线测试通话效果',
      '水中传声：敲击音叉后放入水盆中，耳朵贴近水面听声音',
      '固体传声：敲击桌子，耳朵贴在桌面上听，对比空气中听到的声音',
      '思考：为什么在太空里听不到声音？为什么土电话的线要拉直？为什么把耳朵贴在铁轨上能听到远处的火车？',
      '展示你的土电话和实验记录，解释声音传播的原理',
    ]),
  },
  {
    title: '大气压的威力',
    description: '你看不见空气，但空气有巨大的力量！一个杯子装满水，用一张纸盖住杯口，倒过来水不会流出来——这就是大气压的魔力！在这个实验中，你将用几个神奇的小实验感受大气压的存在，理解我们周围空气的巨大力量！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：玻璃杯、水、硬纸片（或扑克牌）、吸管、塑料瓶、热水、气球\n2. 覆杯实验：杯中装满水，用纸片盖住杯口，快速倒过来，观察纸片托住水不掉\n3. 瓶吞鸡蛋：玻璃瓶口放一个剥壳的熟鸡蛋，瓶中点燃纸片消耗氧气，鸡蛋被吸进瓶中\n4. 吸管原理：用吸管喝饮料，解释为什么液体能上升\n5. 马德堡半球模拟：用两个吸盘挂钩互相对吸，尝试拉开\n6. 了解大气压在生活中的应用：吸盘挂钩、吸管、注射器、抽水机',
    reference_materials: '1. 视频推荐：搜索"大气压实验 小学生"\n2. 科学原理：地球周围包裹着厚厚的大气层，大气对物体表面产生的压强约为101千帕（每平方厘米约1公斤力）。杯子倒过来时，外部大气压向上托住纸片，大于杯内水的重力，水就不会流出来\n3. 历史上的马德堡半球实验：1654年，德国马德堡市长用16匹马才拉开两个抽成真空的半球，证明了大气压的巨大力量',
    visual_prompt: 'Atmospheric pressure experiment, an upside-down glass of water covered by a card with water not spilling out, a hard-boiled egg being sucked into a glass bottle, two suction cups stuck together, a straw in a glass of water, clean physics experiment illustration',
    steps: makeSteps('大气压的威力', [
      '准备材料：玻璃杯、水、硬纸片、吸管、塑料瓶、热水、气球、吸盘挂钩',
      '覆杯实验：杯中装满水，用纸片盖住杯口，快速倒过来，观察纸片稳稳托住水',
      '瓶吞鸡蛋：玻璃瓶口放剥壳熟鸡蛋，瓶中点燃纸张耗尽氧气，观察鸡蛋被吸进瓶中',
      '吸盘实验：两个吸盘挂钩对吸在一起，尝试拉开，感受大气压的力量',
      '思考：为什么吸管能吸起饮料？为什么宇航员在太空要穿宇航服？为什么高山上煮饭不容易熟？',
      '制作"大气压实验报告"，向家人展示实验并解释大气压的原理',
    ]),
  },
  {
    title: '水的三态变化',
    description: '水会变魔术！它可以是流动的液体，可以变成硬硬的冰块，还可以变成看不见的水蒸气。为什么水有这么多变化？在这个实验中，你将观察水从固态到液态到气态的变化过程，理解"融化"、"沸腾"、"蒸发"、"凝结"、"凝固"这些概念！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '1-4',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：冰块、小锅（或金属碗）、温度计、透明玻璃杯、盖子、热水壶\n2. 观察冰块融化：记录冰块在室温下融化的时间\n3. 观察沸腾：加热水直到沸腾，观察气泡、记录温度（100℃时水沸腾）\n4. 观察凝结：热水倒入玻璃杯，盖上盖子，观察盖子内壁的水珠\n5. 观察蒸发：在两个相同的盘子中倒入等量水，一个放在阳光下，一个放在阴凉处，比较蒸发速度\n6. 画出水的三态变化图',
    reference_materials: '1. 视频推荐：搜索"水的三态变化 小学生"\n2. 科学原理：水在0℃以下结冰（凝固），冰在0℃以上融化；水在100℃时沸腾变成水蒸气（汽化）；水蒸气遇冷变成水（凝结）；水在常温下也会慢慢变成水蒸气（蒸发）\n3. 水的三态变化口诀：固态→液态（融化），液态→固态（凝固），液态→气态（汽化），气态→液态（凝结），固态→气态（升华）\n4. 为什么烧水时锅盖上有水珠？水蒸气遇到冷的锅盖凝结成小水滴',
    visual_prompt: 'States of water experiment, ice cubes melting in a bowl, pot of boiling water with steam rising, glass of hot water with condensation droplets on the lid, a diagram showing water cycle with solid liquid gas states, clean educational science illustration',
    steps: makeSteps('水的三态变化', [
      '准备材料：冰块、小锅、温度计、透明玻璃杯、盖子、热水壶、两个盘子',
      '融化实验：记录冰块在室温下完全融化需要多长时间，观察温度变化',
      '沸腾实验：加热水至沸腾，观察气泡从底部升起，记录沸腾时的温度（100℃）',
      '凝结实验：热水倒入玻璃杯，盖上盖子，观察盖子内壁水珠的形成',
      '思考：为什么洗完澡后浴室镜子会起雾？为什么湿衣服晾在阳光下干得快？为什么冬天呼出的气是白色的？',
      '画出水的三态变化图，标注融化、凝固、汽化、凝结、升华五种变化',
    ]),
  },
  {
    title: '燃烧的条件',
    description: '火是怎么燃烧起来的？为什么用湿布盖在火上能灭火？在这个实验中，你将通过几个小实验，搞清楚燃烧需要哪三个条件，理解灭火的原理，还能学到重要的消防安全知识！',
    category: 'science',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：蜡烛（3支）、火柴、透明玻璃杯（大小各一个）、湿布、金属盘\n2. 实验一（需要氧气）：点燃一支蜡烛，用玻璃杯罩住，观察蜡烛熄灭\n3. 实验二（需要可燃物）：在金属盘上点燃蜡烛，观察蜡烛本身是可燃物\n4. 实验三（需要温度）：将湿布靠近蜡烛火焰但不接触，观察火焰情况\n5. 总结燃烧三要素：可燃物、氧气（助燃物）、达到燃点的温度\n6. 了解灭火原理：去掉任意一个条件就能灭火',
    reference_materials: '1. 视频推荐：搜索"燃烧三要素实验 小学生"\n2. 科学原理：燃烧需要三个条件同时满足——可燃物、氧气（助燃物）、达到燃点。缺一不可，这就是"火三角"\n3. 灭火方法：用水浇（降温）、用灭火器（隔绝氧气）、移除可燃物（如关闭煤气阀门）\n4. 安全提醒：本实验必须在成人监督下进行！',
    visual_prompt: 'Combustion experiment, a candle burning under a clear glass jar being deprived of oxygen, a candle burning on a metal plate, three candles demonstrating the fire triangle, fire safety poster, clean educational science illustration',
    steps: makeSteps('燃烧的条件', [
      '准备材料：蜡烛3支、火柴、透明玻璃杯（大小各一个）、金属盘',
      '缺氧实验：点燃蜡烛，用小玻璃杯罩住，观察火焰慢慢熄灭，记录时间；用大杯子再试一次',
      '对比实验：同时点燃两支蜡烛，一支用杯子罩住，一支不罩，观察哪支先灭',
      '总结燃烧三要素：可燃物（蜡烛）、氧气（空气中）、温度（火柴点燃），缺一不可',
      '思考：为什么用水能灭火？为什么油锅着火不能用水浇？为什么森林火灾很难扑灭？',
      '画出"火三角"示意图，向家人解释燃烧的三个条件和灭火的原理',
    ]),
  },

  // ========== 自然探索 (6个) ==========
  {
    title: '食物链与生态网',
    description: '你知道草原上的兔子和狼之间有什么关系吗？如果狼灭绝了，草原会发生什么？在这个项目中，你将学习食物链的概念，了解生产者、消费者和分解者的角色，绘制一幅生态系统的食物网！',
    category: 'nature',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：大白纸、彩笔、动植物的图片（可从书上或网上找）\n2. 学习食物链的概念：谁吃谁，能量从哪来到哪去\n3. 认识三个角色：生产者（植物，用阳光制造养分）、消费者（动物，吃植物或其他动物）、分解者（细菌、真菌，分解死去的生物）\n4. 画出至少3条食物链：如草→虫子→青蛙→蛇→鹰\n5. 将多条食物链组合成食物网\n6. 了解生态平衡的重要性',
    reference_materials: '1. 视频推荐：搜索"食物链 小学生"\n2. 科学原理：食物链描述了生态系统中能量和物质的传递。植物（生产者）通过光合作用制造有机物，草食动物吃植物，肉食动物吃草食动物，分解者分解所有死去的生物\n3. 如果食物链中的某个环节消失会怎样？比如狼灭绝→兔子大量繁殖→草被吃光→草原变沙漠\n4. 人类在食物链中的位置：人类是杂食动物，既吃植物也吃动物，处于食物链的顶端',
    visual_prompt: 'Food chain and food web diagram on a large paper, arrows showing energy flow from grass to rabbit to fox, producer consumer decomposer icons, forest ecosystem illustration with plants animals and fungi, colorful educational chart',
    steps: makeSteps('食物链与生态网', [
      '准备材料：大白纸、彩笔、动植物图片（可画可打印）',
      '学习食物链概念：生产者（植物）→初级消费者（草食动物）→次级消费者（肉食动物）→分解者',
      '画出3条食物链：草原（草→兔→狐狸）、森林（树叶→虫→鸟→蛇）、海洋（海藻→小鱼→大鱼→鲨鱼）',
      '将食物链组合成食物网，用箭头连接"谁吃谁"',
      '思考：如果杀虫剂杀死了所有虫子，森林里的鸟会怎样？如果人类过度捕鱼，海洋会怎样？',
      '展示你的食物网图，向家人解释生态平衡的重要性',
    ]),
  },
  {
    title: '树叶分类图鉴',
    description: '你注意过吗？不同树的叶子形状千差万别！有的像扇子（银杏），有的像手掌（枫树），有的像针一样（松树）。在这个项目中，你将收集不同种类的树叶，学习按形状分类，制作一本属于自己的"树叶图鉴"！',
    category: 'nature',
    difficulty: 'beginner',
    grade_level: '1-4',
    estimated_time: '40分钟',
    requirements: '1. 准备材料：收集至少10种不同形状的树叶、厚书（压叶子用）、白纸、胶水、彩笔\n2. 将收集的树叶夹在厚书中压平，放置2-3天\n3. 学习树叶的分类：针形（松树）、扇形（银杏）、掌形（枫树）、心形（紫荆）、椭圆形（桂花）、针形（松树）\n4. 将压干的叶子贴在白纸上，标注名称、形状、采集时间和地点\n5. 了解叶子为什么有不同的形状\n6. 制作"树叶分类图鉴"册子',
    reference_materials: '1. 视频推荐：搜索"树叶分类 小学生"\n2. 叶子的形状分类：针形、扇形、掌形、心形、椭圆形、披针形、圆形、卵形\n3. 叶子为什么有不同的形状？适应不同的环境：针形叶减少水分蒸发（松树），扇形叶适合采光（银杏），大型叶适合热带雨林\n4. 叶子的结构：叶柄、叶脉、叶片。叶脉像一个运输网络，输送水分和养分',
    visual_prompt: 'Leaf classification collection, various leaves of different shapes arranged on white paper, ginkgo fan-shaped leaf, maple palm-shaped leaf, pine needle leaf, each labeled with name and shape type, a magnifying glass, pressed leaves in a book, nature craft scene',
    steps: makeSteps('树叶分类图鉴', [
      '准备材料：收集至少10种不同树种的树叶、厚书、白纸、胶水、彩笔',
      '将收集的树叶夹在厚书中压平，等待2-3天（可提前准备）',
      '学习叶形分类：针形、扇形、掌形、心形、椭圆形、披针形，识别每种叶子的形状',
      '将压干的叶子贴在白纸上，标注名称、形状类型、采集地点和日期',
      '思考：为什么松树的叶子是针形的？为什么热带植物的叶子通常很大？',
      '装订成"树叶分类图鉴"册子，向家人展示你的收藏',
    ]),
  },
  {
    title: '自制堆肥',
    description: '你知道吗？你每天扔掉的果皮、菜叶其实可以变成植物的"营养大餐"！这就是堆肥。在这个项目中，你将学习如何把厨余垃圾变成肥料，了解有机物分解的过程，成为"环保小达人"！',
    category: 'nature',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '40分钟',
    requirements: '1. 准备材料：带盖子的塑料桶（或泡沫箱）、果皮、菜叶、咖啡渣、干树叶、土壤、铲子\n2. 在桶底铺一层干树叶，再铺一层厨余垃圾，再铺一层土壤，重复分层\n3. 每周搅拌一次，保持湿润但不太湿\n4. 观察堆肥的变化：颜色、气味、温度\n5. 记录堆肥成熟的时间（约4-8周）\n6. 用成熟的堆肥给植物施肥，观察效果',
    reference_materials: '1. 视频推荐：搜索"家庭堆肥 小学生"\n2. 科学原理：堆肥是利用微生物（细菌、真菌）分解有机物，将厨余垃圾转化为富含养分的腐殖质。这个过程需要氧气、水分和适宜的温度\n3. 适合堆肥的：果皮、菜叶、咖啡渣、茶叶渣、蛋壳、干树叶、纸屑\n4. 不适合堆肥的：肉类、油脂、奶制品（会发臭、招虫子）、塑料、金属',
    visual_prompt: 'DIY compost bin made from a plastic container, layered with brown dry leaves green vegetable scraps and soil, a small garden trowel, a thermometer in the compost, rich dark compost soil, outdoor gardening scene, educational environmental illustration',
    steps: makeSteps('自制堆肥', [
      '准备材料：带盖塑料桶、果皮、菜叶、咖啡渣、干树叶、土壤、铲子',
      '学习堆肥原理：微生物分解有机物，需要氧气、水分和适宜温度',
      '分层堆肥：桶底铺干树叶→铺厨余垃圾→铺土壤→重复，最后盖上一层厚土',
      '每周搅拌一次，保持湿润，记录堆肥的变化（颜色、气味、温度）',
      '思考：为什么堆肥会发热？为什么不能把肉放进堆肥？堆肥对土壤有什么好处？',
      '用成熟的堆肥给植物施肥，对比施肥前后的植物生长情况',
    ]),
  },
  {
    title: '池塘微生物观察',
    description: '一滴池塘水里藏着一个小世界！你相信吗？在一滴水里，可能有成千上万个小生物在游来游去。在这个项目中，你将用显微镜（或放大镜）观察池塘水中的微生物，发现一个肉眼看不见的奇妙世界！',
    category: 'nature',
    difficulty: 'intermediate',
    grade_level: '4-6',
    estimated_time: '40分钟',
    requirements: '1. 准备材料：池塘水（或鱼缸水、雨水）、显微镜（或高倍放大镜）、载玻片、盖玻片、滴管、笔记本\n2. 用滴管取一滴池塘水放在载玻片上\n3. 在显微镜下观察，调整焦距直到看清\n4. 寻找微生物：草履虫（像拖鞋）、水蚤（像小虾）、水绵（绿色丝状）、轮虫（有旋转的"轮子"）\n5. 画出你看到的微生物\n6. 了解微生物在生态系统中的角色',
    reference_materials: '1. 视频推荐：搜索"显微镜下的池塘水"\n2. 常见微生物：草履虫（单细胞动物，靠纤毛运动）、水蚤（小型甲壳动物，有透明的壳）、水绵（藻类，绿色丝状，能进行光合作用）、轮虫（多细胞动物，头部有旋转的纤毛轮）\n3. 微生物的作用：分解有机物、是食物链的基础、维持水体生态平衡\n4. 一滴水中的世界：1毫升池塘水中可能有数百到数千个微生物',
    visual_prompt: 'Microscope on a desk with a drop of pond water on a glass slide, magnified view showing tiny microorganisms like paramecium and daphnia, notebook with sketches of microbes, pond water sample jar, clean biology experiment illustration',
    steps: makeSteps('池塘微生物观察', [
      '准备材料：池塘水、显微镜、载玻片、盖玻片、滴管、笔记本',
      '学习显微镜的使用方法：放玻片→低倍镜→调焦→观察',
      '取一滴池塘水放在载玻片上，盖上盖玻片，在显微镜下观察',
      '寻找并画出至少3种微生物：草履虫、水蚤、水绵、轮虫等',
      '思考：为什么池塘水看起来是绿色的？微生物在自然界中扮演什么角色？',
      '展示你画的微生物图鉴，向家人介绍这些"看不见的小生命"',
    ]),
  },
  {
    title: '风的测量',
    description: '你知道今天刮的是什么风吗？风力有多大？你能自己做一个小装置来测量风速吗？在这个项目中，你将学习用风向标和风速计来测量风，理解风是怎么形成的，成为"测风小专家"！',
    category: 'nature',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：纸杯、吸管、大头针、铅笔、硬纸板、指南针、剪刀\n2. 制作风向标：用硬纸板做箭头，吸管做轴，铅笔做底座，放在室外，观察箭头指向\n3. 制作风速计：将4个纸杯对称固定在吸管十字架上，用大头针做轴，风吹时纸杯会旋转\n4. 用风速计记录每天的风速（旋转的快慢）\n5. 学习风力等级：微风（树叶响）、强风（树枝摇）、大风（举伞难）\n6. 了解风的成因：空气流动（热空气上升，冷空气补充）',
    reference_materials: '1. 视频推荐：搜索"风的测量 小学生"\n2. 风力等级（蒲福风级）：0级无风，1-2级微风（树叶动），3-4级和风（小旗飘），5-6级强风（大树摇），7-8级大风（举伞难），9级以上暴风\n3. 风是怎么形成的？太阳照射地面，热空气上升，形成低压区；冷空气从高压区流向低压区，就形成了风\n4. 风向的命名：风从哪个方向吹来就叫什么风，比如北风就是从北面吹来的风',
    visual_prompt: 'DIY wind vane and anemometer made from paper cups and straws, wind direction arrow on a pencil stand, paper cup anemometer spinning in the wind, weather observation tools on a outdoor table, blue sky with clouds, educational science craft',
    steps: makeSteps('风的测量', [
      '准备材料：纸杯、吸管、大头针、铅笔、硬纸板、指南针、剪刀',
      '制作风向标：硬纸板剪成箭头和尾翼，固定在吸管上，用大头针穿过吸管插在铅笔上',
      '制作风速计：4个纸杯对称固定在吸管十字架上，大头针做轴，风吹时纸杯会旋转',
      '连续一周记录风向和风速，制作"风力记录表"',
      '思考：为什么海边风比较大？为什么白天和晚上的风向可能不同？台风是怎么形成的？',
      '展示你的风向标和风速计，向家人解释风的成因和测量方法',
    ]),
  },
  {
    title: '化石制作',
    description: '你见过恐龙化石吗？化石是古代生物留下的"石头印记"，它们告诉我们几亿年前地球上发生的故事。在这个项目中，你将用石膏或面团，亲手制作一个"化石"，模拟自然界化石形成的过程！',
    category: 'nature',
    difficulty: 'beginner',
    grade_level: '2-5',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：石膏粉（或面粉+盐）、水、树叶、贝壳、小玩具恐龙、盘子、食用油\n2. 将树叶或贝壳涂一层薄油（防粘），放在盘子里\n3. 将石膏粉加水调成糊状，倒入盘子盖住树叶\n4. 等待石膏硬化（约30分钟-1小时），取出树叶，留下清晰的印记\n5. 用颜料给"化石"上色，让它看起来更真实\n6. 了解真正的化石是怎么形成的',
    reference_materials: '1. 视频推荐：搜索"化石制作 小学生"\n2. 科学原理：真正的化石是古代生物的遗体或遗迹，被泥沙掩埋后，经过数百万年的压力和化学变化，矿物质逐渐替代了原来的有机物，形成了石头化的化石\n3. 化石的种类：实体化石（如恐龙骨骼）、模铸化石（如叶子印痕）、遗迹化石（如恐龙脚印、粪便）\n4. 为什么化石很重要？它们帮助科学家了解地球的历史、生物的演化、古代的环境',
    visual_prompt: 'DIY fossil making, plaster cast with leaf or shell imprint, paint and brushes for coloring the fossil, real fossil examples nearby, rocks and excavation tools, hands-free craft scene on a table covered with newspaper, educational illustration',
    steps: makeSteps('化石制作', [
      '准备材料：石膏粉、水、树叶、贝壳、小玩具恐龙、盘子、食用油、颜料',
      '学习化石知识：化石是怎么形成的？为什么大多数化石在岩石中找到？',
      '制作化石：树叶涂油放在盘中，倒入石膏糊，等待硬化后取出树叶',
      '给化石上色：用颜料给"化石"涂上类似石头的颜色，让它看起来更真实',
      '思考：为什么恐龙化石那么珍贵？为什么有些生物没有留下化石？',
      '展示你的"化石收藏"，向家人讲述化石形成的过程',
    ]),
  },

  // ========== 生活实践 (8个) ==========
  {
    title: '火灾逃生我知道',
    description: '火灾是家庭中最常见的危险之一。你知道着火时应该怎么逃生吗？烟雾是往上飘的还是往下沉的？为什么着火时要弯腰匍匐前进？在这个项目中，你将学习火灾逃生知识，制定家庭火灾逃生计划，成为"消防小卫士"！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '1-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：纸、笔、红色彩笔、家庭平面图\n2. 学习火灾逃生"三要"：要用湿毛巾捂住口鼻、要弯腰匍匐前进（烟雾往上飘，下面空气好）、要走楼梯不乘电梯\n3. 学习火灾逃生"三不"：不贪恋财物、不乘坐电梯、不盲目跳楼\n4. 检查家中火灾隐患：电器是否过载、燃气阀门是否关闭、逃生通道是否畅通\n5. 绘制家庭火灾逃生路线图，标注至少两条逃生路线\n6. 和家人进行一次火灾逃生演练',
    reference_materials: '1. 视频推荐：搜索"儿童火灾逃生教育"\n2. 火灾逃生口诀：小火快逃，大火关门，湿毛巾捂口鼻，弯腰匍匐走\n3. 为什么烟雾往上升？热空气密度小，向上升，烟雾中有毒气体在上方聚集，所以下面的空气相对干净\n4. 为什么不能乘电梯？火灾时电梯可能断电被困，电梯井像一个大烟囱，烟雾会迅速充满',
    visual_prompt: 'Fire safety education scene, house floor plan with red escape route arrows, smoke detector on ceiling, fire extinguisher, wet towel, emergency exit sign, fire safety poster, bright educational illustration, no people',
    steps: makeSteps('火灾逃生我知道', [
      '准备材料：纸、笔、红色彩笔、家庭平面图',
      '学习火灾逃生知识：三要三不，烟雾上升原理，为什么弯腰匍匐',
      '排查家中火灾隐患：检查插座、燃气、逃生通道',
      '绘制家庭火灾逃生路线图，标注至少两条路线和集合点',
      '思考：如果房间门很烫，应该开门还是不开？如果身上着火怎么办？',
      '和家人进行一次火灾逃生演练，展示你的逃生计划',
    ]),
  },
  {
    title: '网络安全我知道',
    description: '你上网时有没有遇到过奇怪的事情？陌生人加你好友、奇怪的链接让你点、游戏里有人让你报密码？这些都是网络安全的陷阱！在这个项目中，你将学习如何保护自己的网络安全，识别网络骗局，安全上网！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：纸、笔、彩笔\n2. 学习网络安全"五不"：不随便加陌生人好友、不点击不明链接、不透露个人信息（姓名、地址、学校、密码）、不轻信中奖信息、不随便下载软件\n3. 了解常见的网络陷阱：钓鱼链接、假中奖、游戏代充、冒充好友\n4. 学习设置强密码：字母+数字+符号，至少8位，不同网站用不同密码\n5. 制作"网络安全守则"海报\n6. 向家人分享你的网络安全知识',
    reference_materials: '1. 视频推荐：搜索"儿童网络安全教育"\n2. 个人信息包括：真实姓名、家庭地址、学校名称、电话号码、身份证号、银行卡号、密码\n3. 什么是钓鱼链接？看起来像正常网站的假网站，骗你输入账号密码\n4. 强密码怎么设？大小写字母+数字+特殊符号，至少8位，不用生日、姓名等容易猜到的信息\n5. 遇到可疑情况怎么办？立即告诉家长，不要自己处理',
    visual_prompt: 'Internet safety education poster, computer screen with shield and lock icon, password strength meter, "do not share" warning signs for personal information, safe browsing illustration, lock and key symbol, clean educational graphic',
    steps: makeSteps('网络安全我知道', [
      '准备材料：纸、笔、彩笔、网络安全知识资料',
      '学习网络安全"五不"原则，了解每种网络陷阱的具体例子',
      '识别网络陷阱：分析3个真实的网络骗局案例，找出可疑之处',
      '学习设置强密码：设计一个自己记得住但别人猜不到的密码',
      '思考：为什么不能在网上随便加陌生人好友？为什么不能随便点链接？',
      '制作"网络安全守则"海报，向家人分享你的网络安全知识',
    ]),
  },
  {
    title: '认识细菌与正确洗手',
    description: '你的手上现在有多少细菌？你以为干净的手，其实可能藏着成千上万个细菌！在这个项目中，你将通过一个有趣的实验"看到"细菌，学习正确洗手的方法，成为"健康小卫士"！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '1-4',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：面包片（3片）、密封袋、肥皂、水、洗手液\n2. 实验一：用没洗过的手摸一片面包，放入密封袋\n3. 实验二：用清水冲一下手后摸另一片面包，放入密封袋\n4. 实验三：用肥皂和洗手液正确洗手后摸第三片面包，放入密封袋\n5. 观察3-5天后，面包上霉菌的生长情况\n6. 学习"七步洗手法"：内外夹弓大立腕',
    reference_materials: '1. 视频推荐：搜索"七步洗手法"\n2. 科学原理：手上有很多细菌和真菌，面包是它们的"美食"。细菌多的面包会更快发霉\n3. 七步洗手法口诀：内（掌心对掌心）、外（手背）、夹（指缝）、弓（指关节）、大（大拇指）、立（指尖）、腕（手腕）\n4. 什么时候要洗手？饭前便后、外出回家、摸宠物后、打喷嚏后、接触垃圾后',
    visual_prompt: 'Hand washing experiment, three sealed bags with bread slices showing different mold growth levels, a diagram of the seven-step hand washing method, soap and hand sanitizer, a sink with running water, clean bathroom scene, educational hygiene illustration',
    steps: makeSteps('认识细菌与正确洗手', [
      '准备材料：面包片3片、密封袋3个、肥皂、洗手液',
      '实验设置：分别用"不洗手""清水冲""正确洗手"三种方式摸面包片，放入密封袋标记',
      '学习七步洗手法：内-外-夹-弓-大-立-腕，每个步骤至少5秒',
      '每天观察面包片的变化，记录霉菌出现的时间、颜色和面积',
      '思考：为什么清水冲手不如用肥皂洗得干净？为什么要用肥皂洗手？',
      '展示实验结果，向家人演示正确的七步洗手法',
    ]),
  },
  {
    title: '学做一道简单的菜',
    description: '你会做菜吗？哪怕是从最简单的做起——煎一个鸡蛋、拌一盘黄瓜、煮一碗面条！在这个项目中，你将在家长的指导下，学习做一道菜，了解食材的处理方法，掌握基本的烹饪技能，成为"小小厨师"！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '2-6',
    estimated_time: '40分钟',
    requirements: '1. 选择一道简单的菜：番茄炒蛋、凉拌黄瓜、煮面条、蛋炒饭、水果沙拉等\n2. 列出食材清单，和家人在超市购买食材\n3. 在家长指导下洗菜、切菜（注意刀具安全）\n4. 在家长指导下使用炉灶烹饪（注意用火安全）\n5. 记录烹饪过程：每个步骤用了什么材料、多长时间\n6. 和家人一起品尝，记录大家的评价',
    reference_materials: '1. 视频推荐：搜索"儿童学做菜 入门"\n2. 厨房安全：切菜时手指弯曲（猫爪手），远离刀刃；用火时锅铲要干燥（防止油溅）；锅把手朝里放（防止碰翻）\n3. 推荐的入门菜谱：番茄炒蛋（简单美味）、水果沙拉（不用火）、蛋炒饭（练习翻锅）、凉拌黄瓜（练习刀工）\n4. 基本的调味料：盐（咸）、糖（甜）、酱油（咸鲜）、醋（酸）',
    visual_prompt: 'Simple cooking scene, kitchen counter with ingredients for scrambled eggs with tomatoes, cutting board with vegetables, a frying pan on the stove, cooking utensils, recipe card, clean kitchen illustration, no people',
    steps: makeSteps('学做一道简单的菜', [
      '选择一道菜，列出食材清单，和家人一起购买食材',
      '学习厨房安全知识：刀具使用、炉灶安全、防烫伤',
      '在家长指导下洗菜、切菜、烹饪，全程记录每个步骤',
      '完成菜品，和家人一起品尝，记录评价',
      '思考：为什么炒菜要先放油？为什么煮面条要等水开了再放面条？',
      '整理你的菜谱和烹饪过程，向家人展示你的"厨师首秀"',
    ]),
  },
  {
    title: '校园防欺凌',
    description: '你在学校有没有遇到过被人欺负的情况？或者看到别的同学被欺负？欺凌不只是打人，说难听的话、故意孤立同学、在网上骂人，这些也是欺凌。在这个项目中，你将学习识别欺凌，学会保护自己和帮助他人，成为"友善小卫士"！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '1-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：纸、笔、彩笔\n2. 学习识别三种欺凌：身体欺凌（打、推、踢）、言语欺凌（骂人、起外号、嘲笑）、关系欺凌（孤立、排挤、造谣）\n3. 学习遇到欺凌怎么办：不要害怕、大声说不、迅速离开、告诉老师/家长\n4. 学习"旁观者"该怎么做：不要围观、报告老师、支持被欺负的同学\n5. 制作"友善校园"宣传海报\n6. 和同学讨论：如果看到有人被欺负，你会怎么做？',
    reference_materials: '1. 视频推荐：搜索"校园防欺凌教育"\n2. 欺凌不只是打人：语言暴力（骂人、起外号）、社交暴力（孤立、传谣言）、网络暴力（网上骂人）都是欺凌\n3. 被欺凌了怎么办？记住"三步法"：大声说"不"（明确拒绝）→快速离开（保护自己）→告诉大人（求助老师/家长）\n4. 如果你是旁观者：你的沉默就是在纵容欺凌。勇敢站出来，或者悄悄告诉老师',
    visual_prompt: 'Anti-bullying education poster, a stop sign with hand symbol, colorful friendly school illustration, hearts and helping hands, kindness and respect messages, bright positive educational graphic, no people',
    steps: makeSteps('校园防欺凌', [
      '准备材料：纸、笔、彩笔',
      '学习识别三种欺凌：身体欺凌、言语欺凌、关系欺凌，了解每种的具体表现',
      '学习应对欺凌"三步法"：大声说不→快速离开→告诉大人',
      '讨论旁观者的责任：如果你看到同学被欺负，应该怎么做？',
      '思考：为什么有些同学会欺负别人？为什么被欺负的同学不敢告诉老师？',
      '制作"友善校园"海报，写下你的防欺凌宣言',
    ]),
  },
  {
    title: '认识与表达情绪',
    description: '你有时候会莫名其妙地生气、难过、害怕吗？这些感觉都是正常的情绪！在这个项目中，你将学习认识各种情绪，用"情绪温度计"给自己的情绪打分，学会用健康的方式表达情绪，成为"情绪小达人"！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '1-4',
    estimated_time: '25分钟',
    requirements: '1. 准备材料：纸、彩笔、尺子\n2. 认识基本情绪：快乐、悲伤、愤怒、害怕、惊讶、厌恶\n3. 制作"情绪温度计"：从0到10，0代表很平静，10代表情绪爆炸\n4. 每天记录自己的情绪变化：什么时候开心、什么时候生气\n5. 学习情绪调节方法：深呼吸（吸气4秒，呼气6秒）、数到10、找人倾诉、运动\n6. 制作"情绪调节工具箱"卡片',
    reference_materials: '1. 视频推荐：搜索"儿童情绪管理"\n2. 六种基本情绪：快乐、悲伤、愤怒、害怕、惊讶、厌恶（每个人都有的基本情绪）\n3. 情绪没有好坏：愤怒和悲伤也是正常的，重要的是怎么表达\n4. 情绪调节技巧：深呼吸（像吹气球一样慢慢呼气）、数数法（从1数到10）、转移注意力（做喜欢的事）、倾诉（找信任的人说话）\n5. 不要用伤害自己或他人的方式发泄情绪',
    visual_prompt: 'Emotional awareness chart, emotion thermometer from 0 to 10 with different color zones, six basic emotion faces represented as simple icons, calm-down toolbox with cards showing coping strategies, bright colorful educational poster, no people',
    steps: makeSteps('认识与表达情绪', [
      '准备材料：白纸、彩笔、尺子',
      '认识六种基本情绪：画出六种情绪的表情简笔画',
      '制作"情绪温度计"：0-10刻度，标注不同情绪状态的位置',
      '连续一周记录情绪变化：每天早晚记录情绪温度和触发事件',
      '思考：生气的时候做什么能让自己冷静下来？为什么说出来比憋着好？',
      '制作"情绪调节工具箱"卡片集，向家人展示你的情绪管理方法',
    ]),
  },
  {
    title: '正确刷牙护牙齿',
    description: '你每天刷牙吗？你真的刷对了吗？在这个项目中，你将学习牙齿的结构、蛀牙是怎么形成的，以及正确的刷牙方法，保护你的牙齿不被蛀牙"攻击"！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '1-4',
    estimated_time: '25分钟',
    requirements: '1. 准备材料：牙刷、牙膏、镜子、牙齿模型图（可画）、鸡蛋、白醋（鸡蛋实验用）\n2. 鸡蛋壳实验：鸡蛋放入白醋中，观察蛋壳被酸腐蚀的过程（模拟蛀牙）\n3. 学习牙齿结构：门牙（切食物）、犬牙（撕食物）、臼齿（磨食物）\n4. 学习巴氏刷牙法：45度角对准牙龈沟，小幅度水平颤动，每个牙面刷10次\n5. 制作"刷牙打卡表"，连续一周记录刷牙情况\n6. 了解对牙齿好的食物（牛奶、蔬菜）和坏的食物（糖果、碳酸饮料）',
    reference_materials: '1. 视频推荐：搜索"巴氏刷牙法 儿童"\n2. 科学原理：蛀牙是细菌分解食物残渣产生酸，酸腐蚀牙齿表面（牙釉质）造成的。鸡蛋壳（主要成分碳酸钙）和白醋反应，模拟了酸腐蚀牙齿的过程\n3. 牙齿的结构：牙釉质（最外层，最硬）、牙本质、牙髓（有神经和血管）\n4. 为什么吃完甜食要刷牙/漱口？糖是细菌的食物，细菌吃完糖产生酸，酸腐蚀牙齿',
    visual_prompt: 'Tooth brushing education, an egg in a glass of vinegar showing shell being dissolved, a diagram of tooth structure showing enamel dentin and pulp, toothbrush at 45-degree angle, brushing chart with checkmarks, clean bathroom scene, dental hygiene illustration',
    steps: makeSteps('正确刷牙护牙齿', [
      '准备材料：牙刷、牙膏、镜子、鸡蛋、白醋、杯子',
      '鸡蛋实验：鸡蛋放入白醋中，观察蛋壳被酸腐蚀的过程（模拟蛀牙形成）',
      '学习牙齿结构：门牙、犬牙、臼齿的位置和功能，牙釉质的作用',
      '学习巴氏刷牙法：45度角，小幅度颤动，每个牙面刷10次，用镜子检查',
      '思考：为什么碳酸饮料对牙齿不好？为什么每天要刷两次牙？',
      '制作"刷牙打卡表"，坚持一周正确刷牙并记录',
    ]),
  },
  {
    title: '自行车安全骑行',
    description: '你会骑自行车吗？骑车上学或出去玩时，你知道怎么保证安全吗？在这个项目中，你将学习自行车安全骑行的规则，认识自行车的结构，了解基本的交通规则，安全快乐地骑行！',
    category: 'life',
    difficulty: 'beginner',
    grade_level: '2-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：自行车、头盔、反光背心（或亮色衣服）、纸、笔\n2. 学习骑车安全装备：头盔（必须戴）、护膝护肘、反光条\n3. 学习骑车交通规则：靠右行驶、不逆行、不闯红灯、转弯要打手势\n4. 学习骑车前检查：刹车灵不灵、轮胎有没有气、链条有没有松\n5. 了解交通标志中与自行车相关的标志\n6. 和家长一起进行一次安全骑行',
    reference_materials: '1. 视频推荐：搜索"儿童自行车安全"\n2. 骑车安全口诀：头盔戴好再出发，刹车检查不能差，靠右行驶不逆行，转弯手势要记牢\n3. 自行车转弯手势：左转伸出左手，右转伸出右手，停车举手过头\n4. 为什么骑自行车要戴头盔？头部是人体最脆弱的部位，头盔能吸收撞击力，保护大脑\n5. 我国规定：未满12周岁不能骑自行车上路',
    visual_prompt: 'Bicycle safety education scene, a bicycle with helmet and reflective gear, a diagram showing proper hand signals for turning and stopping, bicycle parts labeled, safety checklist poster, traffic signs for cyclists, clean outdoor educational illustration',
    steps: makeSteps('自行车安全骑行', [
      '准备材料：自行车、头盔、反光背心、纸、笔',
      '学习骑车安全装备和骑车前安全检查（刹车、轮胎、链条）',
      '学习骑车交通规则：靠右行驶、不逆行、转弯手势（左转左臂、右转右臂、停车举臂）',
      '认识与自行车相关的交通标志，画出从家到学校的安全骑行路线',
      '思考：为什么未满12岁不能骑车上路？为什么头盔那么重要？',
      '制作"自行车安全骑行守则"，和家人一起完成一次安全骑行',
    ]),
  },

  // ========== 人文社科 (5个) ==========
  {
    title: '认识世界地图',
    description: '地球上有七大洲和四大洋，你住在中国，中国在亚洲的东部。你知道中国在地球上的哪个位置吗？世界上最长的河、最高的山、最大的沙漠都在哪里？在这个项目中，你将认识世界地图，了解七大洲四大洋，成为"世界地理小达人"！',
    category: 'humanities',
    difficulty: 'beginner',
    grade_level: '2-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：世界地图（打印或从书上找）、彩笔、纸\n2. 认识七大洲：亚洲、非洲、北美洲、南美洲、欧洲、大洋洲、南极洲\n3. 认识四大洋：太平洋、大西洋、印度洋、北冰洋\n4. 找到中国在亚洲的位置，标注邻国\n5. 认识世界之最：最高的山（珠穆朗玛峰）、最长的河（尼罗河）、最大的沙漠（撒哈拉）、最大的雨林（亚马逊）\n6. 制作"世界地理知识卡"',
    reference_materials: '1. 视频推荐：搜索"世界地图 儿童版"\n2. 七大洲口诀：亚非北南美，南极欧大洋\n3. 四大洋：太平洋（最大最深）、大西洋（第二）、印度洋（第三）、北冰洋（最小最浅）\n4. 中国的位置：亚洲东部，太平洋西岸，邻国14个（俄罗斯、朝鲜、蒙古、印度、越南等）\n5. 世界之最：珠穆朗玛峰8848米（最高）、尼罗河6671公里（最长）、撒哈拉沙漠920万平方公里（最大）、亚马逊雨林（最大热带雨林）',
    visual_prompt: 'Colorful world map on a table, seven continents colored in different colors, four oceans labeled in blue, China highlighted on the map, compass rose, world landmarks icons, bright educational geography illustration',
    steps: makeSteps('认识世界地图', [
      '准备材料：世界地图、彩笔、纸',
      '认识七大洲：用不同颜色标注七大洲，记住各洲名称和位置',
      '认识四大洋：用蓝色标注四大洋，了解哪个最大哪个最小',
      '找到中国在亚洲的位置，标注中国的邻国',
      '思考：为什么南极洲没有国家？为什么太平洋叫"太平"洋？',
      '制作"世界地理知识卡"，向家人介绍七大洲四大洋',
    ]),
  },
  {
    title: '中国建筑之美',
    description: '你去过故宫吗？看过江南水乡的白墙黑瓦吗？见过福建的土楼吗？中国各地的建筑风格千差万别，每一种都蕴含着当地的文化和智慧。在这个项目中，你将探索中国不同地区的建筑风格，了解建筑背后的故事！',
    category: 'humanities',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：纸、彩笔、中国建筑图片（可从书上或网上找）\n2. 认识中国四大建筑风格：北方四合院、江南水乡民居、福建土楼、陕北窑洞\n3. 了解每种建筑的特点：四合院（四面围合、中间庭院）、江南民居（白墙黑瓦、小桥流水）、土楼（圆形或方形、防御性强）、窑洞（依山而建、冬暖夏凉）\n4. 了解建筑与自然环境的关系：为什么北方有四合院？为什么南方有吊脚楼？\n5. 画出你最喜欢的中国建筑风格\n6. 制作"中国建筑风格图鉴"',
    reference_materials: '1. 视频推荐：搜索"中国建筑之美"\n2. 建筑与气候的关系：北方四合院（防风保暖）、江南水乡（排水通风）、窑洞（冬暖夏凉）、傣族竹楼（防潮防虫）\n3. 有趣的建筑：故宫（世界上最大的宫殿建筑群）、长城（全长2万多公里）、布达拉宫（建在红山上的宫殿）、苏州园林（一步一景）\n4. 中国传统建筑的特点：对称布局、木结构为主、飞檐翘角、雕梁画栋',
    visual_prompt: 'Chinese traditional architecture collection, courtyard house with central garden, white-walled black-tiled Jiangnan water town buildings, round Fujian tulou earth building, cave dwellings on loess plateau, traditional Chinese architectural styles, educational illustration',
    steps: makeSteps('中国建筑之美', [
      '准备材料：纸、彩笔、中国建筑图片',
      '认识四种中国建筑风格：四合院、江南民居、福建土楼、陕北窑洞',
      '了解每种建筑的特点和与自然环境的关系',
      '画出你最喜欢的中国建筑风格，标注建筑特色',
      '思考：为什么北方和南方的建筑风格不同？为什么古人不用钉子就能造出木结构建筑？',
      '制作"中国建筑风格图鉴"，向家人展示你学到的建筑知识',
    ]),
  },
  {
    title: '京剧脸谱艺术',
    description: '你有没有好奇过，为什么京剧演员要把脸涂成各种颜色？红色代表忠诚、白色代表奸诈、黑色代表刚正……每一种颜色都有它的含义！在这个项目中，你将学习京剧脸谱的色彩密码，了解脸谱背后的历史故事，制作一个属于自己的脸谱面具！',
    category: 'humanities',
    difficulty: 'beginner',
    grade_level: '2-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：白色面具（或纸盘）、彩笔、颜料、京剧脸谱参考图\n2. 学习脸谱颜色的含义：红（忠勇，如关羽）、白（奸诈，如曹操）、黑（刚正，如包拯）、蓝（勇猛，如窦尔敦）、黄（残暴）、绿（侠义）、金（神仙）\n3. 学习脸谱的图案：三块瓦脸、十字门脸、碎脸等\n4. 选择一个你喜欢的角色，在面具上画出他的脸谱\n5. 了解京剧的基本知识：生旦净丑四个行当\n6. 展示你的脸谱作品，讲述背后的故事',
    reference_materials: '1. 视频推荐：搜索"京剧脸谱 儿童"\n2. 脸谱颜色密码：红忠紫孝，黑正粉老，水白奸邪，油白狂傲，黄狠灰贪，蓝勇绿暴，神佛精灵金银普照\n3. 京剧四大行当：生（男性角色）、旦（女性角色）、净（花脸，性格鲜明的男性）、丑（喜剧角色）\n4. 经典脸谱人物：关羽（红脸，忠义）、包拯（黑脸，铁面无私）、曹操（白脸，奸雄）、孙悟空（猴脸，机智勇敢）',
    visual_prompt: 'Beijing opera facial makeup art, several blank masks painted with traditional Chinese opera face patterns in red black white blue colors, paintbrushes and paint pots, reference pictures of Peking opera masks, Chinese cultural art craft scene, educational illustration',
    steps: makeSteps('京剧脸谱艺术', [
      '准备材料：白色面具（或纸盘）、彩笔、颜料、脸谱参考图',
      '学习脸谱颜色含义：红色=忠勇，白色=奸诈，黑色=刚正，蓝色=勇猛，金色=神仙',
      '学习脸谱图案类型：三块瓦脸、十字门脸、碎脸，选择一种来设计',
      '在面具上绘制你选择的脸谱角色，注意颜色和图案的搭配',
      '思考：为什么京剧要用脸谱？脸谱和角色性格有什么关系？',
      '展示你的脸谱作品，讲述你画的这个角色的故事',
    ]),
  },
  {
    title: '中国画入门',
    description: '中国画和西洋画有什么不同？为什么中国画喜欢"留白"？为什么中国画家用毛笔和墨汁就能画出千变万化的效果？在这个项目中，你将学习中国画的基本技法，尝试用毛笔和墨汁画一幅山水或花鸟，体验中国画的独特魅力！',
    category: 'humanities',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '40分钟',
    requirements: '1. 准备材料：毛笔（大中小各一支）、宣纸（或毛边纸）、墨汁、调色盘、国画颜料\n2. 学习中国画的基本技法：中锋、侧锋、逆锋、点染、勾勒\n3. 学习墨分五色：焦、浓、重、淡、清（通过加水来调出不同深浅的墨色）\n4. 选择画一幅简单的花鸟画（如竹子、梅花、兰花）或山水画\n5. 了解中国画的特点：留白、写意、诗书画印合一\n6. 展示你的作品',
    reference_materials: '1. 视频推荐：搜索"中国画入门 儿童"\n2. 中国画的工具：文房四宝——笔（毛笔）、墨（墨汁）、纸（宣纸）、砚（砚台）\n3. 中国画的特点：写意不写实（追求神似而非形似）、留白（给观者想象空间）、诗书画印合一（画上有题诗、签名和印章）\n4. 墨分五色：焦墨（最浓）、浓墨、重墨、淡墨、清墨（最淡），通过加水来调出不同深浅',
    visual_prompt: 'Chinese ink painting setup, brush pen and ink stick on ink stone, rice paper with simple bamboo or orchid painting, Chinese painting colors and palette, scroll painting style, traditional Chinese art supplies, clean artistic illustration',
    steps: makeSteps('中国画入门', [
      '准备材料：毛笔、宣纸、墨汁、调色盘、国画颜料',
      '学习中国画基本技法：中锋、侧锋、逆锋，练习画线条和墨色',
      '学习墨分五色：焦浓重淡清，通过加水练习调出不同深浅的墨色',
      '画一幅简单的花鸟画（竹子、兰花、梅花）或山水画',
      '思考：中国画为什么喜欢"留白"？为什么中国画家用毛笔不用刷子？',
      '展示你的中国画作品，解释你用了哪些技法',
    ]),
  },
  {
    title: '认识中国朝代',
    description: '中国有五千年的历史，经历了多少朝代？每个朝代有什么著名的故事？"夏商与西周，东周分两段，春秋和战国，一统秦两汉……"在这个项目中，你将学习中国历史朝代顺序，了解每个朝代的重要事件，制作"朝代时间轴"！',
    category: 'humanities',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：长条纸（或几张纸拼接）、彩笔、尺子、中国历史朝代歌\n2. 学习朝代歌：夏商与西周，东周分两段，春秋和战国，一统秦两汉，三分魏蜀吴，二晋前后沿，南北朝并立，隋唐五代传，宋元明清后，皇朝至此完\n3. 了解每个朝代的重要事件（至少选5个朝代深入了解）\n4. 在长条纸上画出"朝代时间轴"，标注每个朝代的起止年份\n5. 给每个朝代画一个代表图标（如秦朝=兵马俑、唐朝=唐诗、宋朝=指南针）\n6. 了解中国历史"四大发明"分别出现在哪个朝代',
    reference_materials: '1. 视频推荐：搜索"中国历史朝代歌"\n2. 中国主要朝代及重要事件：夏（第一个王朝）、商（甲骨文）、周（分封制）、秦（统一六国、兵马俑、长城）、汉（丝绸之路）、唐（唐诗、盛世）、宋（四大发明之三：印刷术、指南针、火药）、元（马可波罗来华）、明（郑和下西洋）、清（最后一个王朝）\n3. 四大发明：造纸术（汉）、印刷术（宋）、指南针（宋）、火药（唐/宋）',
    visual_prompt: 'Chinese dynasty timeline on a long scroll of paper, each dynasty marked with a different color and a representative icon, Qin dynasty terracotta warrior, Tang dynasty poem, Song dynasty compass, Ming dynasty ship, educational historical illustration',
    steps: makeSteps('认识中国朝代', [
      '准备材料：长条纸（拼接）、彩笔、尺子、历史朝代歌',
      '学习朝代歌，背诵并理解每个朝代的顺序',
      '选择5个朝代深入了解：秦（统一六国）、汉（丝绸之路）、唐（盛世）、宋（科技发明）、明（郑和下西洋）',
      '在长条纸上画"朝代时间轴"，标注朝代起止年份和代表事件',
      '思考：为什么每个朝代都会灭亡？为什么唐朝是中国历史上最强盛的朝代之一？',
      '展示你的朝代时间轴，向家人讲述中国历史的大致脉络',
    ]),
  },

  // ========== 创意制作 (5个) ==========
  {
    title: '纸桥承重大挑战',
    description: '一张普通的打印纸能承受多大的重量？如果把它折成不同的形状呢？在这个项目中，你将用纸设计桥梁，测试不同形状的承重能力，像真正的工程师一样设计和优化你的"纸桥"！',
    category: 'creative',
    difficulty: 'beginner',
    grade_level: '2-6',
    estimated_time: '35分钟',
    requirements: '1. 准备材料：A4纸若干、硬币（做砝码）、两本书（做桥墩）、胶带\n2. 实验一：一张平纸放在两本书之间，测试能放多少硬币\n3. 实验二：将纸折成"瓦楞形"（像纸箱内部那样），测试承重\n4. 实验三：将纸卷成纸筒，多个纸筒排列，测试承重\n5. 实验四：将纸折成"拱形"，测试承重\n6. 比较哪种形状的承重能力最强，总结原理',
    reference_materials: '1. 视频推荐：搜索"纸桥承重实验 小学生"\n2. 科学原理：平纸只有一层，容易弯折；瓦楞形增加了支撑面，分散了压力；纸筒是圆柱形，受力均匀；拱形把压力转化为向两侧的推力\n3. 为什么很多桥是拱形？拱形将向下的重力转化为向两侧的推力，桥墩承受了推力，所以拱桥非常坚固\n4. 工程师的思维：设计→测试→优化→再测试，不断改进',
    visual_prompt: 'Paper bridge engineering challenge, several paper bridges of different shapes spanning between two books, flat paper, corrugated paper, paper tubes, and arch-shaped paper, coins stacked on top as weights, engineering experiment on a table, clean illustration',
    steps: makeSteps('纸桥承重大挑战', [
      '准备材料：A4纸若干、硬币、两本书（做桥墩）、胶带',
      '平纸桥：一张平纸搭在两本书之间，测试最多能放多少硬币',
      '瓦楞纸桥：将纸折成瓦楞形，测试承重，记录结果',
      '纸筒桥：将纸卷成多个纸筒排列，测试承重，记录结果',
      '思考：哪种形状承重最强？为什么？真实的桥梁为什么多采用拱形？',
      '制作"承重能力排行榜"，向家人展示你的纸桥工程师之旅',
    ]),
  },
  {
    title: '自制万花筒',
    description: '万花筒里为什么有那么多漂亮的花纹？转一圈，图案就变了！这个神奇的效果来自光的反射。在这个项目中，你将用镜面纸和纸筒，亲手制作一个万花筒，观察光在镜面间多次反射形成的对称图案！',
    category: 'creative',
    difficulty: 'beginner',
    grade_level: '2-5',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：纸筒（卫生纸芯或保鲜膜芯）、镜面纸（或反光塑料片）、透明塑料片、彩色透明珠子或碎纸片、胶带\n2. 将镜面纸裁成三条长条（宽度等于纸筒半径），镜面朝内，用胶带粘成三棱柱\n3. 将三棱柱放入纸筒中\n4. 纸筒一端用透明塑料片封住，放上彩色珠子，再封一层\n5. 从另一端看，旋转纸筒，观察彩色图案的变化\n6. 了解光的反射原理：三面镜子互相反射，形成对称图案',
    reference_materials: '1. 视频推荐：搜索"自制万花筒 小学生"\n2. 科学原理：万花筒利用三面镜子的多次反射，将底部的彩色碎片反射出无数个对称影像，形成美丽的图案\n3. 为什么是三面镜子？两面镜子形成二维对称，三面镜子形成三维对称图案，更加丰富\n4. 万花筒的发明：1816年由苏格兰科学家大卫·布鲁斯特发明，原名Kaleidoscope，意为"观看美丽形状的仪器"',
    visual_prompt: 'DIY kaleidoscope made from a cardboard tube, mirror strips inside forming a triangular prism, colorful beads and confetti at the bottom, the viewing end showing beautiful symmetrical patterns, craft supplies on a table, educational craft illustration',
    steps: makeSteps('自制万花筒', [
      '准备材料：纸筒、镜面纸、透明塑料片、彩色珠子、胶带、剪刀',
      '制作三棱镜：将镜面纸裁成三条长条，镜面朝内，用胶带粘成三棱柱',
      '组装万花筒：将三棱柱放入纸筒，一端封透明片+彩色珠子',
      '观察万花筒：旋转纸筒，观察图案的变化，记录你看到的图案特点',
      '思考：为什么万花筒的图案都是对称的？如果换成两面镜子会怎样？',
      '展示你的万花筒，解释光的反射原理',
    ]),
  },
  {
    title: '自制潜望镜',
    description: '潜艇里的人怎么看到海面上的情况？潜水艇有一个"潜望镜"，可以让光拐弯，让你看到被挡住的东西！在这个项目中，你将用两面镜子和一个纸盒，亲手制作一个潜望镜，理解光的反射原理！',
    category: 'creative',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：长条纸盒（或自己用纸板做）、两面小镜子（45度角放置）、胶带、剪刀\n2. 了解潜望镜的原理：光从上方的镜子反射到下方的镜子，再反射到你的眼睛\n3. 在纸盒的两端各开一个窗口，将镜子以45度角固定在两端\n4. 调整镜子角度，确保能从下面看到上面的景象\n5. 测试：用潜望镜看桌子底下或墙后面的东西\n6. 了解光的反射定律：入射角等于反射角',
    reference_materials: '1. 视频推荐：搜索"自制潜望镜 小学生"\n2. 科学原理：光的反射定律——入射角等于反射角。潜望镜利用两面镜子，让光经过两次45度反射，实现"拐弯"看东西\n3. 真实的潜望镜：潜艇上的潜望镜不仅有镜子，还有透镜组来放大远处的物体，可以360度旋转\n4. 生活中的应用：除了潜艇，建筑工地上用潜望镜看管道内部，交警用来看车底',
    visual_prompt: 'DIY periscope made from a long cardboard box with two mirrors at 45-degree angles, light ray diagram showing the path of light reflecting off mirrors, scissors and tape on a craft table, optics experiment, educational illustration',
    steps: makeSteps('自制潜望镜', [
      '准备材料：长条纸盒、两面小镜子、胶带、剪刀',
      '学习光的反射定律：入射角=反射角，理解潜望镜的工作原理',
      '制作潜望镜：在纸盒两端各开窗口，将镜子以45度角固定',
      '测试潜望镜：用潜望镜看桌子底下、墙后面、柜子顶上',
      '思考：为什么镜子要45度角？如果角度不对会怎样？为什么潜艇需要潜望镜？',
      '展示你的潜望镜，画出光路图解释工作原理',
    ]),
  },
  {
    title: '简易降落伞',
    description: '为什么降落伞能让人从高空安全降落？空气阻力是怎么"托住"降落伞的？在这个项目中，你将用塑料袋和绳子，亲手制作一个降落伞，观察它如何缓慢降落，理解空气阻力和重力的对抗！',
    category: 'creative',
    difficulty: 'beginner',
    grade_level: '2-5',
    estimated_time: '25分钟',
    requirements: '1. 准备材料：塑料袋（或垃圾袋）、细绳（4根）、小玩具（做降落伞的"人"）、胶带、剪刀\n2. 将塑料袋剪成正方形（约30cm×30cm）\n3. 在正方形的四个角各系一根绳子\n4. 四根绳子的另一端系在一起，绑上小玩具\n5. 从高处（阳台或楼梯）释放降落伞，观察降落过程\n6. 尝试不同大小的伞面，比较降落速度',
    reference_materials: '1. 视频推荐：搜索"自制降落伞 小学生"\n2. 科学原理：降落伞张开时，伞面与空气接触面积大，产生很大的空气阻力，抵消了重力，使降落伞缓慢下降\n3. 为什么伞面越大降落越慢？伞面越大，空气阻力越大，重力相同的情况下，降落速度越慢\n4. 真实的降落伞：军用降落伞通常在1000米左右打开，伞面直径约7-10米，可以让人安全着陆',
    visual_prompt: 'DIY parachute made from a plastic bag with strings and a small toy figure, floating gently downward, air resistance diagram, craft supplies on a table, outdoor scene with blue sky, clean educational illustration',
    steps: makeSteps('简易降落伞', [
      '准备材料：塑料袋、细绳4根、小玩具、胶带、剪刀',
      '制作伞面：将塑料袋剪成正方形，四角各系一根绳子',
      '组装降落伞：四根绳子另一端系在一起，绑上小玩具',
      '从高处释放降落伞，观察降落过程，记录降落时间',
      '思考：为什么伞面越大降落越慢？如果伞面有个洞会怎样？为什么宇航员返回舱也用降落伞？',
      '尝试不同大小的伞面，比较降落速度，展示你的实验结论',
    ]),
  },
  {
    title: '自制弹簧秤',
    description: '你知道体重秤是怎么知道你有多重的吗？橡皮筋有个神奇的特性：拉得越长，用的力越大！在这个项目中，你将用橡皮筋和尺子，亲手制作一个弹簧秤，用它来称各种小物品的重量！',
    category: 'creative',
    difficulty: 'beginner',
    grade_level: '3-6',
    estimated_time: '30分钟',
    requirements: '1. 准备材料：橡皮筋（若干）、尺子、回形针（做挂钩）、小纸杯（做秤盘）、绳子、已知重量的物品（如硬币）\n2. 将橡皮筋挂在尺子顶端，下方挂回形针做的挂钩\n3. 在挂钩下挂小纸杯，测量橡皮筋的长度（空载时）\n4. 在纸杯中放入已知重量的物品（如5枚硬币），测量橡皮筋的长度\n5. 在尺子上标记刻度，制作简易弹簧秤\n6. 用弹簧秤称其他小物品，比较轻重',
    reference_materials: '1. 视频推荐：搜索"自制弹簧秤 小学生"\n2. 科学原理：胡克定律——在弹性限度内，弹簧的伸长量（被拉长的长度）与受到的拉力成正比。拉力越大，弹簧拉得越长\n3. 为什么要用橡皮筋？橡皮筋有弹性，拉长后能恢复原状，这种特性叫"弹性"\n4. 生活中的弹簧秤：菜市场用的弹簧秤、体重秤、拉力器、弹簧门',
    visual_prompt: 'DIY spring scale made from a ruler with rubber bands hanging from the top, a paper cup basket attached with paper clips, coins inside as weights, measurement markings on the ruler, simple physics experiment on a table, educational illustration',
    steps: makeSteps('自制弹簧秤', [
      '准备材料：橡皮筋、尺子、回形针、小纸杯、绳子、硬币',
      '组装弹簧秤：橡皮筋挂在尺子顶端，下方挂回形针挂钩和小纸杯',
      '标定刻度：放入已知重量的硬币（5枚、10枚、15枚），记录橡皮筋长度',
      '用你的弹簧秤称其他小物品，估算它们的重量',
      '思考：如果橡皮筋拉得太长会怎样？为什么弹簧秤有最大称重？',
      '展示你的弹簧秤，解释为什么橡皮筋拉得越长称得越重',
    ]),
  },

  // ========== 编程技术 (4个) ==========
  {
    title: '英文单词记忆器',
    description: '你想用Scratch做一个帮助你背单词的小程序吗？这个程序会随机显示英文单词，让你选择正确的中文意思，答对了加分，答错了扣分——像玩游戏一样背单词！',
    category: 'programming',
    difficulty: 'intermediate',
    grade_level: '3-6',
    estimated_time: '45分钟',
    requirements: '1. 准备：电脑、Scratch在线或离线版\n2. 设计程序功能：显示英文单词→4个选项（含1个正确答案）→点击选择→判断对错→计分\n3. 创建变量：分数（score）、单词列表（word list）\n4. 编写逻辑：随机从列表中选词、显示选项、判断点击、更新分数\n5. 添加音效和动画，让做对和做错有不同的反馈\n6. 测试并分享给同学',
    reference_materials: '1. Scratch教程推荐：搜索"Scratch单词记忆器"\n2. 核心模块：列表（存储单词和翻译）、随机数（随机选词）、广播（不同角色之间的通信）、变量（计分）\n3. 编程思维：怎么确保四个选项中只有一个正确答案？怎么让四个选项随机排列？\n4. 拓展：可以添加更多单词列表、增加难度等级、添加计时器',
    visual_prompt: 'Scratch programming interface on a computer screen, a vocabulary quiz game showing an English word with four Chinese answer choices, colorful code blocks, score counter, green flag button, clean tech illustration',
    steps: makeSteps('英文单词记忆器', [
      '准备：打开Scratch，创建新项目',
      '设计程序：规划界面——单词显示区、4个选项按钮、分数显示',
      '创建变量和列表：分数（score）、单词列表（英文）、翻译列表（中文）',
      '编写核心逻辑：随机选词→显示4个选项（含正确答案）→判断点击→更新分数',
      '思考：怎么确保正确答案不总是出现在同一个位置？怎么让游戏越来越难？',
      '测试你的单词记忆器，邀请同学来玩并收集反馈',
    ]),
  },
  {
    title: '电子相册制作',
    description: '你有很多照片想要展示吗？在这个项目中，你将用Scratch或PPT制作一个电子相册，包含翻页、自动播放、添加文字说明等功能，展示你的照片和故事！',
    category: 'programming',
    difficulty: 'beginner',
    grade_level: '2-6',
    estimated_time: '40分钟',
    requirements: '1. 准备：电脑、照片素材（电子版）、Scratch或PPT\n2. 如果用Scratch：导入照片作为角色/背景，添加"上一页""下一页"按钮，编写翻页逻辑\n3. 如果用PPT：插入照片，添加幻灯片切换动画，添加文字说明\n4. 设计相册的主题：如"我的暑假""我的宠物""我的家庭""美丽的校园"\n5. 添加背景音乐和翻页动画\n6. 展示你的电子相册',
    reference_materials: '1. 教程推荐：搜索"Scratch电子相册"或"PPT相册制作"\n2. Scratch实现思路：每张照片是一个背景，用变量记录当前页码，点"下一页"变量+1切换背景\n3. PPT实现思路：每张幻灯片放一张照片，用"切换"功能添加翻页效果，用"插入音频"添加背景音乐\n4. 好的相册特点：照片清晰、文字简洁、配色协调、有故事线',
    visual_prompt: 'Digital photo album on a computer screen, colorful photos arranged in a slideshow format, navigation buttons for next and previous, a photo album cover page with title, clean modern tech illustration',
    steps: makeSteps('电子相册制作', [
      '准备：电脑、照片素材（至少10张）、Scratch或PPT',
      '选择主题，整理照片，规划相册的故事线',
      '制作相册：导入照片，添加"上一页""下一页"按钮，编写翻页逻辑',
      '美化相册：添加文字说明、翻页动画、背景音乐',
      '思考：为什么电子相册比纸质相册更方便？还有哪些展示照片的方式？',
      '展示你的电子相册，向家人分享你的照片故事',
    ]),
  },
  {
    title: '天气查询小工具',
    description: '你想做一个能查天气的小程序吗？在这个项目中，你将用Scratch或简单的网页，制作一个天气查询工具，输入城市名称就能显示天气信息，还能根据天气给出穿衣建议！',
    category: 'programming',
    difficulty: 'intermediate',
    grade_level: '4-6',
    estimated_time: '45分钟',
    requirements: '1. 准备：电脑、Scratch或HTML编辑器\n2. 设计界面：输入框（城市名）、查询按钮、结果显示区（天气、温度、穿衣建议）\n3. 用Scratch实现：创建城市和天气的列表，根据输入的城市名查找对应天气\n4. 用HTML实现：创建简单的网页，包含输入框和结果显示\n5. 添加穿衣建议逻辑：如温度>30℃建议穿短袖，温度<10℃建议穿棉袄\n6. 测试并完善',
    reference_materials: '1. 教程推荐：搜索"Scratch天气查询"\n2. Scratch实现思路：创建两个列表（城市列表和天气列表），输入城市名后遍历列表找到对应天气\n3. HTML实现思路：用JavaScript的if-else判断条件，根据输入给出不同结果\n4. 编程思维：条件判断（if-else）、列表查找、用户输入处理',
    visual_prompt: 'Weather query tool on a computer screen, a search box with city name input, weather result showing temperature and weather icon, clothing suggestion based on temperature, clean modern tech interface, educational illustration',
    steps: makeSteps('天气查询小工具', [
      '准备：电脑、Scratch或HTML编辑器',
      '设计界面：输入框、查询按钮、天气结果显示区、穿衣建议区',
      '创建数据：建立城市和天气的对应列表（至少5个城市）',
      '编写查询逻辑：输入城市名→查找天气→显示结果→给出穿衣建议',
      '思考：如果输入的城市不在列表中怎么办？怎么让天气数据更准确？',
      '测试你的天气查询工具，向同学展示',
    ]),
  },
  {
    title: '数学图形绘制',
    description: '用Scratch画正方形、三角形、圆形、五角星……一边画图一边学数学！在这个项目中，你将用Scratch编程绘制各种几何图形，理解角度和边长的关系，数学和编程一起学！',
    category: 'programming',
    difficulty: 'beginner',
    grade_level: '2-5',
    estimated_time: '40分钟',
    requirements: '1. 准备：电脑、Scratch\n2. 画正方形：前进100步→右转90度→重复4次（理解正方形4个角都是90度）\n3. 画三角形：前进100步→右转120度→重复3次（理解三角形内角和180度，每个角60度，外角120度）\n4. 画五角星：前进100步→右转144度→重复5次\n5. 画圆形：前进1步→右转1度→重复360次\n6. 设计一个用多种图形组成的图案（如房子、机器人、花朵）',
    reference_materials: '1. Scratch教程推荐：搜索"Scratch画图形"\n2. 数学知识：正方形每个内角90度（外角也是90度）；三角形内角和180度，正三角形每个内角60度（外角120度）；五角星顶点角度36度（外角144度）；圆形可以看做无数条边的正多边形\n3. 编程思维：循环（重复执行）、变量（控制边长和颜色）、模式识别（不同图形都遵循"移动+旋转"的模式）\n4. 拓展：用变量控制边长，画不同大小的图形；用彩色画笔，画彩虹图形',
    visual_prompt: 'Scratch programming interface showing geometric shape drawing, a colorful square triangle circle and star drawn on the stage, Scratch code blocks with repeat loops and turn degrees, clean educational programming illustration',
    steps: makeSteps('数学图形绘制', [
      '准备：打开Scratch，添加画笔扩展',
      '画正方形：前进100步→右转90度→重复4次，理解正方形角度',
      '画三角形和五角星：前进100步→右转120度（三角形）或144度（五角星），各重复对应次数',
      '画圆形：前进1步→右转1度→重复360次，理解圆和正多边形的关系',
      '思考：为什么画正方形右转90度而画三角形右转120度？如果画六边形要转多少度？',
      '设计一个由多种图形组成的图案，展示你的编程+数学作品',
    ]),
  },
];

async function main() {
  const jsonPath = path.join(__dirname, '..', 'data', 'tasks_v3.json');

  // 1. 读取当前JSON
  console.log('[1/3] 读取当前 tasks_v3.json...');
  let tasks = JSON.parse(fs.readFileSync(jsonPath, 'utf-8')) as any[];
  const beforeCount = tasks.length;
  console.log(`  当前任务数: ${beforeCount}`);

  // 2. 添加新任务
  console.log(`[2/3] 添加 ${NEW_TASKS.length} 个新任务...`);
  tasks.push(...NEW_TASKS);
  console.log(`  任务总数: ${beforeCount} -> ${tasks.length}`);

  // 分类统计
  const cats: Record<string, number> = {};
  tasks.forEach((t: any) => cats[t.category] = (cats[t.category] || 0) + 1);
  console.log('  新分类统计:', JSON.stringify(cats));

  // 3. 写入JSON
  console.log('[3/3] 写入 tasks_v3.json 并插入数据库...');
  fs.writeFileSync(jsonPath, JSON.stringify(tasks, null, 2), 'utf-8');

  // 插入数据库
  const insertTask = db.prepare(
    `INSERT INTO tasks (title, description, category, difficulty, requirements, reference_materials, grade_level, estimated_time, steps_json, ai_video_url, external_video_url, status, created_by)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'published', NULL)`
  );

  const insertMany = db.transaction(() => {
    for (const t of NEW_TASKS) {
      insertTask.run(
        t.title, t.description, t.category, t.difficulty,
        t.requirements, t.reference_materials, t.grade_level, t.estimated_time,
        JSON.stringify(t.steps || []), '', ''
      );
    }
  });

  insertMany();
  console.log(`  已插入 ${NEW_TASKS.length} 个新任务到数据库`);
  console.log(`\n新增任务列表:`);
  NEW_TASKS.forEach(t => console.log(`  + ${t.title} [${t.category}]`));
  console.log('\n完成!');
}

main().catch(console.error);