# -*- coding: utf-8 -*-
import os

out_dir = r'd:\工作备份\ptrade\trae work\创造力大塞'
out_path = os.path.join(out_dir, 'gaosan-complete.js')


def c(items):
    return '<br>'.join(items)


subjects = {}

# ============== 语文 ==============
subjects['语文'] = [
    ('论述类文本阅读', '论点论据论证分析', c([
        '论点是作者的主张和观点，常出现在标题、首段尾、段首段尾、结尾处。',
        '论据包括事实论据和道理论据，用于支撑和证明论点。',
        '论证是用论据证明论点的过程和方法。',
        '常见论证方法：举例论证、道理论证、对比论证、比喻论证、引用论证、类比论证、归谬法。',
        '论证思路答题模板：本文首先通过……提出……论点，然后运用……论证方法展开论述，最后得出……结论。',
        '答题三步骤：标画关键信息→理清结构层次→概括段意提炼观点。'
    ])),
    ('论述类文本阅读', '论述类文本常见陷阱类型', c([
        '偷换概念：将原文中的关键词换成近义词、反义词或将概念内涵外延改变。',
        '强加因果：把没有因果关系的两件事说成有因果关系。',
        '因果倒置：将原因和结果互换位置。',
        '以偏概全：用局部代替整体、用个别代替一般（注意表范围/数量/程度的词语）。',
        '混淆时态：把"将然"说成"已然"，把"未然"说成"已然"（注意"已经/将要/可能/或许/一定"）。',
        '混淆模态：把可能说成必然，把或然说成肯定。',
        '混淆是非：将原文肯定的意思说成否定，或相反。',
        '曲解文意：对原文词句做出错误的表面化理解。',
        '张冠李戴：将甲的观点说成乙的观点，或把甲的事说成乙的事。',
        '无中生有：选项内容在原文中找不到依据。',
        '答题技巧：找原句→找差异→辨真伪。'
    ])),
    ('实用类文本阅读', '新闻传记报告访谈阅读技巧', c([
        '新闻阅读：关注导语（5W1H：who/what/when/where/why/how）、主体、背景、结语。',
        '消息结构：倒金字塔式（最重要→次要）。',
        '新闻语言特点：准确、客观、简洁、及时。',
        '传记阅读：关注传主生平事迹、成就贡献、精神品质、时代背景。',
        '传记答题要点：概括事迹→分析形象→探究价值→联系现实。',
        '报告阅读：关注数据、图表、结论，把握核心观点与建议。',
        '访谈阅读：梳理问答层次，关注提问策略与回答要点。',
        '实用类文本通用技巧：筛选整合→概括归纳→分析评价→探究延伸。',
        '答题时注意文本特征：真实性、客观性、时效性、典型性。'
    ])),
    ('文学类文本阅读', '小说散文综合阅读', c([
        '小说三要素：人物、情节、环境。',
        '小说答题角度：人物形象分析、情节作用、环境描写作用、主题探究、艺术手法。',
        '人物形象答题模板：……是一个……（身份）的人，从……（原文）可以看出他具有……（性格）的特点。',
        '情节作用：①结构上（伏笔/铺垫/照应/推动/转折）②内容上（突出人物/揭示主题/制造悬念）。',
        '环境描写作用：①渲染气氛②烘托人物③推动情节④暗示主题⑤交代背景。',
        '散文特点：形散神不散、意境优美、语言凝练、情感真挚。',
        '散文类型：叙事散文、抒情散文、议论散文。',
        '散文答题角度：线索梳理、情感变化、表现手法、语言特色、意蕴探究。',
        '线索类型：以物为线、以情为线、以事为线、以时为线、以地为线。'
    ])),
    ('文学类文本阅读', '叙述视角与人物形象塑造', c([
        '叙述视角：第一人称"我"（真实亲切、有限视角、便于抒情）、第三人称（全知全能、客观灵活）、第二人称（直接对话、亲切感人）。',
        '有限视角vs全知视角：有限视角由人物自身叙述，留悬念；全知视角由叙述者掌控一切。',
        '叙述方式：顺叙、倒叙（制造悬念、突出主题）、插叙（补充背景、丰富内容）、补叙（补充交代）、平叙（花开两朵各表一枝）。',
        '人物形象塑造方法：正面描写（肖像/语言/动作/心理/神态/细节）、侧面描写（环境烘托/他人衬托/物象象征）。',
        '细节描写作用：刻画性格、推动情节、渲染氛围、揭示主题。',
        '答题时要做到：点出手法+结合文本+分析效果。'
    ])),
    ('文言文阅读', '文言文断句技巧', c([
        '断句三步骤：①通读全文理解大意②利用标志点断开③结合语法仔细验证。',
        '标志一：虚词。句首（夫、盖、凡、若夫、至若、且夫、故夫、今夫、嗟夫、呜呼、噫、嘻、乃、遂、而、则、于是、然而、然则、虽、虽然、若、如、苟、倘、即、使、向使、假使、岂、其、何其、胡、何、焉、安、孰）。',
        '标志二：句末虚词（也、矣、乎、哉、与、欤、耶、邪、焉、耳、而已、矣哉、也哉、也与）。',
        '标志三：对话标志（曰、云、言、语、道、白、谓、对）。',
        '标志四：特殊句式（……者，……也/何……之有/不亦……乎/何……为/无乃……乎/得无……乎）。',
        '标志五：修辞手法（对偶、排比、反复、顶真）。',
        '标志六：名词代词（作主语在句首、作宾语在句末）。',
        '常见错误：把专有名词（地名、人名、官职名、年号）断开。',
        '练习方法：多朗读培养语感，熟悉常见虚词用法。'
    ])),
    ('文言文阅读', '古代文化常识', c([
        '天文地理：九州、中原、四海、六合、八荒、江左/江右、山东/山西、河东/河西、河北/河南。',
        '纪年纪时：年号纪年、干支纪年、帝王纪年。夜半/鸡鸣/平旦/日出/食时/隅中/日中/日昳/晡时/日入/黄昏/人定。',
        '节日时令：元日、人日、上元、寒食、清明、上巳、端午、七夕、中元、中秋、重阳、冬至、腊日、除夕。',
        '姓名称谓：名、字、号、谥号、庙号、年号、籍贯、郡望、官职。谦称（寡人、臣、仆、不才、妾、愚）、敬称（君、公、卿、子、先生、足下、执事、陛下）。',
        '科举考试：童试→秀才；乡试→举人（第一解元）；会试→贡士（第一会元）；殿试→进士（第一状元/第二榜眼/第三探花）。连中三元。',
        '官职任免：拜/除/授（授官）、迁/擢/陟（升官）、谪/贬/放/左迁（贬官）、罢/黜/免（免官）、转/徙/调（调动）、兼/领（兼职）、署/权（代理）。',
        '礼乐制度：五礼（吉礼/嘉礼/军礼/宾礼/凶礼）、六艺（礼乐射御书数）。',
        '宗法制度：嫡长子继承制、大宗小宗、昭穆、五服。',
        '学习方法：分类整理、反复记忆、结合语境。'
    ])),
    ('文言文阅读', '文言文翻译直译六字诀', c([
        '留：保留古今意义相同的词、专有名词（人名、地名、官职名、年号、书名、器物名）。',
        '换：用现代词汇替换古代词汇（如"吾"换"我"、"余"换"我"、"汝"换"你"）。',
        '补：补充省略成分（主语、谓语、宾语、介词）。',
        '删：删除无实在意义的虚词（发语词、音节助词、衬字）。',
        '调：调整语序（宾语前置、定语后置、状语后置、主谓倒装）。',
        '选：选择恰当义项（一词多义中选择最符合语境的）。',
        '翻译原则：直译为主，意译为辅；字字落实，文从字顺。',
        '评分标准：关键词（采分点）翻译准确占分，大意通顺占分。',
        '常见固定句式：如……何/奈……何/若……何（把……怎么样）、无乃……乎（恐怕……吧）、得无……乎（莫非……吧）、不亦……乎（不也……吗）、何……之有（有什么……呢）、唯……是……（只……）。',
        '词类活用：名词活用为动词、名词作状语、动词活用为名词、形容词活用为动词/名词、使动用法、意动用法、为动用法。'
    ])),
    ('古代诗歌鉴赏', '炼字炼句与表达技巧', c([
        '炼字类型：动词（最富表现力）、形容词（描摹情态）、副词（修饰限制）、数量词（强调突出）、叠词（增强韵律）。',
        '炼字答题模板：①解释该字在句中的含义②展开联想把该字放入原句描述景象③点出该字烘托了怎样的意境或表达了怎样的感情。',
        '炼句常考：对仗句、哲理句、抒情句、写景句、警句。',
        '表达方式：记叙、描写、抒情、议论、说明（诗歌主要是描写+抒情）。',
        '抒情手法：直接抒情（直抒胸臆）、间接抒情（借景抒情、融情于景、情景交融、托物言志、借古讽今、借事抒情）。',
        '描写手法：正面描写、侧面描写、白描、细节描写、动静结合、虚实结合、远近结合、视听结合、色彩渲染、点面结合。',
        '修辞手法：比喻、拟人、夸张、对偶、排比、反复、设问、反问、借代、对比、衬托、顶真、互文。',
        '表现手法：对比、衬托、烘托、渲染、用典、象征、联想、想象、虚实、动静、抑扬、托物起兴、以小见大、卒章显志。',
        '答题要求：先点明手法，再结合诗句具体分析，最后说明表达效果。'
    ])),
    ('古代诗歌鉴赏', '诗歌形象意境与情感思想', c([
        '人物形象：①抒情主人公自己的形象（如李白的豪放形象）②作品刻画的人物形象（如征人、思妇、隐士、游子）。',
        '事物形象：咏物诗中托物言志的物象（如梅、兰、竹、菊、松、荷、蝉、雁）。',
        '景物形象：由一系列意象构成的画面图景。',
        '常见意象：月（思乡、怀人）、柳（送别、留恋）、菊花（高洁、隐逸）、梅花（坚强、不屈）、梧桐（凄凉、悲伤）、杜鹃（悲苦、乡愁）、鸿雁（思乡、传信）、芭蕉（孤独、忧愁）、浮云（漂泊、游子）。',
        '意境类型：雄浑壮丽、壮阔苍茫、苍凉悲壮、闲适恬淡、清幽明净、明丽清新、萧疏凄寂、孤寂冷清、萧瑟凄凉、繁华热烈。',
        '意境答题：描绘图景+概括特点（用两到三个双音节词）+分析情感。',
        '情感思想：忧国忧民、建功报国、思乡怀人、长亭送别、怀才不遇、寄情山水、归隐田园、昔盛今衰、吊古伤今、讽喻现实、爱恨情愁。',
        '答题要求：先概括情感，再结合诗句分析，要用到情感术语。'
    ])),
    ('成语辨析与病句', '成语辨析五大易错类型', c([
        '望文生义：只按字面意思理解。如"差强人意"是大体让人满意，不是不让人满意。"不刊之论"是不可改动的言论，不是不能刊登。"文不加点"是写文章一气呵成不用涂改，不是不加标点。',
        '张冠李戴：用错对象。如"汗牛充栋"形容书籍多，不能形容人。"巧夺天工"形容人工技艺，不能形容自然。"美轮美奂"形容建筑，不能形容风景。',
        '褒贬误用：感情色彩不当。如"无所不为"是贬义词，什么坏事都干。"处心积虑"是贬义。"叹为观止"是褒义，赞美到极点。',
        '谦敬错位：谦辞用于自己，敬辞用于别人。如"抛砖引玉""蓬荜生辉"是谦辞，不能说别人。"鼎力相助"是敬辞，不能说自己。',
        '不合语境：成语与语境矛盾或重复。如"津津乐道地说"（重复）、"一位莘莘学子"（矛盾）、"突然恍然大悟"（重复）。',
        '常见误用成语：首当其冲、万人空巷、炙手可热、登堂入室、目无全牛、三人成虎、侧目而视、马革裹尸、期期艾艾、胸无城府、耳提面命、有口皆碑、不足为训、不可理喻、不以为然、不以为意。'
    ])),
    ('成语辨析与病句', '病句六大类型详解', c([
        '类型一：语序不当。①定语顺序不当（领属/数量/动词性/形容词性/名词性+中心语）②状语顺序不当（目的/时间/处所/范围/情态/对象+中心语）③关联词位置不当（同前异后）④并列词语排序不当⑤分句位置不当。',
        '类型二：搭配不当。①主谓搭配不当②动宾搭配不当③主宾搭配不当④修饰语与中心语搭配不当⑤一面与两面搭配不当⑥关联词搭配不当。',
        '类型三：成分残缺或赘余。残缺：①主语残缺（介词滥用导致）②谓语残缺③宾语残缺④中心语残缺⑤关联词残缺。赘余：语义重复、堆砌词语。常见赘余：凯旋归来、悬殊很大、十分酷爱、非常奢侈、约……左右。',
        '类型四：结构混乱。①句式杂糅（两种说法混在一起）②中途易辙（一句话没说完就另起一句）③藕断丝连（把上句尾作下句头）。常见杂糅：本着……为原则、以……即可、是为了……为目的、对于……问题上、由于……下、原因是……造成的。',
        '类型五：表意不明。①歧义（多义词、多音词、停顿不同、指代不明、修饰两可）②指代不明。',
        '类型六：不合逻辑。①自相矛盾②范围不清③强加因果④否定失当（防止/避免/切忌+不）⑤不合事理⑥主客倒置。',
        '辨析方法：语感审读法、主干压缩法、造句类比法、逻辑分析法、标志搜寻法（关联词、介词、并列词、两面词、否定词、数量词、代词）。'
    ])),
    ('语言表达', '语言表达连贯与图文转换', c([
        '连贯三条件：统一的话题、合理的句序、语言的衔接与呼应。',
        '句序类型：时间顺序、空间顺序、逻辑顺序（总分/因果/递进/并列/主次）。',
        '衔接方法：前后陈述对象一致、前后句式一致、前后呼应、前后词语关联。',
        '补写句子技巧：看位置（总起句/总结句/过渡句/仿写句）、看前后呼应、看逻辑关系。',
        '流程图解题：①理清层次②关注箭头③说明顺序（由上而下/由左到右）④语言简洁。',
        '思维导图解题：把握层级关系，分清总括与分述。',
        '图表题解题：①看标题②看纵横坐标③看图例④看数据变化（最大/最小/趋势/拐点）⑤按要求作答。',
        '漫画题解题：①看标题②看画面③看文字④联系现实⑤揭示寓意。',
        '徽标题解题：分析构图元素、说明顺序（整体到局部）、揭示寓意（象征义）。',
        '答题原则：准确、简明、连贯、得体。'
    ])),
    ('作文', '作文审题立意与议论文结构', c([
        '新材料作文审题三方法：①抓关键词句法②由果溯因法③多角度切入法。',
        '任务驱动作文：完成试题规定的任务（明确写作对象/文体/内容/格式），体现权衡与选择。',
        '议论文三要素：论点、论据、论证。',
        '常见结构：①总分式②并列式③层进式（是什么-为什么-怎么办）④对照式⑤引议联结式。',
        '引议联结四段法：引（引材料，亮观点）→议（举事例，分析论证）→联（联系实际，深化主旨）→结（总结全文，强化观点）。',
        '开头方法：开门见山、引用名言、排比造势、设问引思、叙议结合、比喻导入。',
        '结尾方法：总结收束、卒章显志、号召劝诫、引用升华、首尾呼应、留白余韵。',
        '段落写作五步法：立（立片言以居要）→释（阐释过渡）→引（引用材料/事例）→析（分析说理：因果/假设/对比/比喻/归纳/演绎）→结（收束点题）。',
        '论据类型：事实论据（史实、事例、数据）、道理论据（名言、警句、俗语、理论）。',
        '论据要求：真实、典型、新颖、贴切。',
        '论证方法：举例论证、道理论证、对比论证、比喻论证、引用论证、因果论证、假设论证、类比论证。',
        '高分作文要点：立意深刻、材料丰富、结构严谨、语言优美、文面整洁。'
    ]))
]

# ============== 数学 ==============
subjects['数学'] = [
    ('集合与简易逻辑', '集合运算与充分必要条件', c([
        '集合三特性：确定性、互异性、无序性。注意互异性检验，特别是含参数集合需检验是否重复。',
        '常见数集：N(自然数)、N*(正整数)、Z(整数)、Q(有理数)、R(实数)、C(复数)。',
        '元素与集合：∈(属于)、∉(不属于)；集合与集合：⊆(子集)、⊂(真子集)、=(相等)。',
        '集合运算：交集A∩B、并集A∪B、补集∁UA。Venn图是重要工具。',
        '德摩根定律：∁U(A∩B)=(∁UA)∪(∁UB)，∁U(A∪B)=(∁UA)∩(∁UB)。',
        '子集个数：含n个元素的集合有2^n个子集，2^n-1个真子集，2^n-1个非空子集，2^n-2个非空真子集。',
        '命题：原命题、逆命题、否命题、逆否命题。互为逆否的命题同真同假。',
        '充分必要条件：A⇒B则A是B的充分条件，B是A的必要条件。A⇔B则互为充要条件。',
        '判断方法：定义法、集合法(A⊆B则A是B的充分条件)、传递法。',
        '逻辑联结词：且(∧)、或(∨)、非(¬)。全真为真(∧)，有真为真(∨)，真假相反(¬)。',
        '全称命题与特称命题的否定：∀→∃，∃→∀，再否定结论。'
    ])),
    ('函数', '函数性质综合（单调性/奇偶性/周期性/对称性）', c([
        '单调性定义：∀x1<x2∈D，f(x1)<f(x2)则单调递增；f(x1)>f(x2)则单调递减。',
        '判断单调性方法：①定义法（作差/作商）②导数法③图像法④复合函数"同增异减"。',
        '复合函数单调性：内外层单调性相同则增，相反则减。',
        '奇偶性：f(-x)=f(x)为偶函数（图像关于y轴对称）；f(-x)=-f(x)为奇函数（图像关于原点对称）。',
        '奇函数性质：f(0)=0（0在定义域内时）；f(x)+f(-x)=0。',
        '单调性与奇偶性综合：奇函数在对称区间上单调性相同；偶函数在对称区间上单调性相反。',
        '周期性：f(x+T)=f(x)对∀x∈D成立，则T为周期。常见周期：|f(x+a)=-f(x)|→T=2|a|；f(x+a)=1/f(x)→T=2|a|。',
        '对称性：f(a+x)=f(a-x)或f(x)=f(2a-x)则图像关于x=a对称；f(a+x)+f(a-x)=2b则关于点(a,b)中心对称。',
        '函数平移：f(x)→f(x-a)+b：右移a上移b。f(x)→f(x+a)+b：左移a上移b。',
        '翻折变换：|f(x)|（下翻上）、f(|x|)（右保留、右翻左）。',
        '易错点：讨论单调性必须在定义域内；奇偶性前提是定义域关于原点对称。'
    ])),
    ('基本初等函数', '指数对数幂函数二次函数综合', c([
        '指数函数y=a^x(a>0,a≠1)：a>1时递增过(0,1)，0<a<1时递减过(0,1)。',
        '对数函数y=log_ax(a>0,a≠1)：a>1时递增过(1,0)，0<a<1时递减过(1,0)。',
        '幂函数y=x^α：α>0时在(0,+∞)递增；α<0时在(0,+∞)递减；α=0时常数函数y=1(x≠0)。',
        '指数对数互化：a^b=N⇔log_aN=b。',
        '对数运算法则：log_a(MN)=log_aM+log_aN；log_a(M/N)=log_aM-log_aN；log_aM^n=n·log_aM。',
        '换底公式：log_aN=log_bN/log_ba=lnN/lna=lgN/lga。推论：log_ab·log_bc·log_ca=1。',
        '二次函数三种形式：一般式y=ax²+bx+c、顶点式y=a(x-h)²+k、零点式y=a(x-x1)(x-x2)。',
        '二次函数对称轴：x=-b/(2a)；顶点(-b/(2a),(4ac-b²)/(4a))；零点x=(-b±√(b²-4ac))/(2a)。',
        '二次函数区间最值：讨论对称轴与区间位置关系（左、内、右三种情况）。',
        '对数不等式：log_aX>b，a>1时X>a^b；0<a<1时0<X<a^b。注意定义域X>0。',
        '指数对数底数不同时，利用换底公式统一底数或利用图像比较。'
    ])),
    ('函数零点与导数', '函数零点与方程根及导数几何意义', c([
        '函数零点定义：使f(x)=0的实数x。零点是数不是点。',
        '零点存在定理：f(x)在[a,b]连续且f(a)·f(b)<0，则(a,b)内至少有一个零点。',
        '零点个数判断方法：①解方程法②图像法③导数法（分析单调性+端点值）。',
        '二分法：每次取区间中点，根据f(中点)符号缩小区间，直到满足精度。',
        '数形结合：f(x)=g(x)的根即y=f(x)与y=g(x)交点的横坐标。',
        '导数定义：f\'(x0)=lim[Δx→0](f(x0+Δx)-f(x0))/Δx。',
        '导数几何意义：f\'(x0)是曲线y=f(x)在点(x0,f(x0))处切线的斜率k。切线方程：y-f(x0)=f\'(x0)(x-x0)。',
        '基本求导公式：(x^n)\'=nx^(n-1)、(sinx)\'=cosx、(cosx)\'=-sinx、(e^x)\'=e^x、(a^x)\'=a^x·lna、(lnx)\'=1/x、(log_ax)\'=1/(xlna)。',
        '运算法则：(f±g)\'=f\'±g\'、(fg)\'=f\'g+fg\'、(f/g)\'=(f\'g-fg\')/g²、[f(g(x))]\'=f\'(g(x))·g\'(x)（链式法则）。',
        '过某点P作切线：设切点(x0,f(x0))，切线过P代入方程解x0。注意"在P处"与"过P"的区别。',
        '公切线问题：分别设两曲线上切点，写出两条切线方程，令斜率相等且截距相等求解。'
    ])),
    ('导数应用', '导数与函数单调性极值最值', c([
        '导数与单调性：f\'(x)>0则f(x)递增；f\'(x)<0则f(x)递减；f\'(x)=0处单调性可能变化。',
        '求单调区间步骤：①求定义域②求f\'(x)③求f\'(x)=0的根④列表（划分区间、判断符号、确定单调）。',
        '极值定义：x0附近左侧增右侧减则f(x0)为极大值；左侧减右侧增则为极小值。f\'(x0)=0是极值必要不充分条件。',
        '求极值步骤：f\'(x)=0求根→判断根两侧f\'(x)符号→确定是极大还是极小。',
        '闭区间[a,b]上的最值：比较端点值f(a),f(b)和区间内极值，最大即最大值，最小即最小值。',
        '开区间上的最值：结合单调性和极限趋势分析。',
        '含参数的单调性讨论：对f\'(x)的符号分类讨论（按二次项系数、判别式、根的大小关系）。',
        '三次函数f(x)=ax³+bx²+cx+d：f\'(x)=3ax²+2bx+c，极值点即f\'(x)=0的两根（Δ>0时）。',
        'f(x)≥a恒成立⇔f(x)_min≥a；f(x)≤a恒成立⇔f(x)_max≤a。',
        '存在性问题：∃x使f(x)≥a⇔f(x)_max≥a。',
        '易错点：f\'(x0)=0不能直接说x0是极值点，必须验证两侧符号变化。'
    ])),
    ('导数应用', '导数与不等式证明及构造函数', c([
        '不等式证明常见思路：①构造函数求最值②放缩法③数学归纳法④利用已知不等式。',
        '构造F(x)=f(x)-g(x)，证明F(x)≥0（或≤0）在指定区间恒成立。',
        '单变量不等式：构造辅助函数，求导分析单调性极值，利用函数最值证明。',
        '双变量不等式：可固定一个变元，将另一变元视为变量；或作差构造新函数。',
        '分离参数法：a≥f(x)恒成立⇔a≥f(x)_max；a≤f(x)恒成立⇔a≤f(x)_min。',
        '常用不等式放缩：①e^x≥x+1（x=0取等）②lnx≤x-1（x=1取等）③sinx≤x≤tanx（0<x<π/2）④x/(x+1)≤ln(1+x)≤x。',
        '对数平均值不等式：√(ab)<(a-b)/(lna-lnb)<(a+b)/2（a≠b>0）。',
        '构造函数技巧：①移项作差②分离参数③齐次化④对数单身狗（将lnx单独放一边）⑤指数找基友（将e^x与多项式组合）。',
        '已知f\'(x)+f(x)>0，构造F(x)=e^x·f(x)；已知f\'(x)-f(x)>0，构造F(x)=f(x)/e^x。',
        '已知xf\'(x)+f(x)>0，构造F(x)=x·f(x)；已知xf\'(x)-f(x)>0，构造F(x)=f(x)/x。',
        '不等式恒成立求参数范围：优先分离参数，再求函数最值。'
    ])),
    ('导数应用', '导数与函数零点及综合应用', c([
        '零点个数判断：讨论f(x)单调性+极值+端点值，分析图像与x轴交点数。',
        '三步法：①求f\'(x)列表分析单调性极值②计算端点值和极值的正负③结合图像得出零点个数。',
        '零点分布：已知零点个数求参数范围，通过图像分析临界位置（极值点处f(x)=0）。',
        '两个函数图像交点问题：转化为F(x)=f(x)-g(x)的零点问题。',
        '分离参数讨论零点：a=h(x)，分析y=a与y=h(x)交点个数（常需画h(x)图像）。',
        '导数综合题：常结合函数性质、不等式、零点、含参数讨论。',
        '含参讨论的层次：①最高次项系数是否为0②判别式Δ符号③根的大小关系④根是否在定义域内。',
        '分类讨论标准：不重不漏、逐级分层、先简后繁。',
        '三次函数零点个数：与x轴三个交点→两极值异号；两个交点→一极值为0；一个交点→两极值同号。',
        '设而不求技巧：导数为0的方程不可解时，设根为x0，利用f\'(x0)=0消元化简。',
        '函数不等式链：综合运用单调性、极值、不等式放缩，逐层推进证明。'
    ])),
    ('三角函数与解三角形', '三角函数综合与解三角形', c([
        '任意角三角函数：sinα=y/r，cosα=x/r，tanα=y/x。一全二正弦三切四余弦。',
        '同角基本关系：sin²α+cos²α=1；tanα=sinα/cosα。',
        '诱导公式：奇变偶不变，符号看象限。',
        '和差角公式：sin(α±β)=sinαcosβ±cosαsinβ；cos(α±β)=cosαcosβ∓sinαsinβ；tan(α±β)=(tanα±tanβ)/(1∓tanαtanβ)。',
        '二倍角：sin2α=2sinαcosα；cos2α=cos²α-sin²α=2cos²α-1=1-2sin²α；tan2α=2tanα/(1-tan²α)。',
        '降幂扩角：sin²α=(1-cos2α)/2；cos²α=(1+cos2α)/2；sinαcosα=sin2α/2。',
        '辅助角公式：asinx+bcosx=√(a²+b²)sin(x+φ)，tanφ=b/a。最大值√(a²+b²)，最小值-√(a²+b²)。',
        'y=Asin(ωx+φ)+B：A=(最大值-最小值)/2，B=(最大值+最小值)/2，周期T=2π/|ω|。φ由特殊点求。',
        '正弦定理：a/sinA=b/sinB=c/sinC=2R（R外接圆半径）。',
        '余弦定理：a²=b²+c²-2bc·cosA；cosA=(b²+c²-a²)/(2bc)。',
        '三角形面积：S=½ah_a=½absinC=½bcsinA=½casinB=abc/(4R)。',
        '解三角形类型：①已知两角一边→正弦②已知两边一对角→正弦（注意两解）③已知两边一夹角→余弦④已知三边→余弦。',
        '三角恒等变换技巧：切化弦、降幂、角的配凑（如2A=(A+B)+(A-B)）。',
        '易错点：两边一对角时可能两解，需检验大边对大角。'
    ])),
    ('平面向量与数列', '平面向量数量积与数列通项求和', c([
        '向量概念：向量（既有大小又有方向）、零向量、单位向量、平行向量、相等向量、相反向量。',
        '向量运算：加法（三角形法则、平行四边形法则）、减法、数乘、数量积。',
        '数量积：a·b=|a||b|cosθ=a1b1+a2b2。a·a=|a|²。',
        '向量平行：a∥b⇔a=λb⇔a1b2-a2b1=0。',
        '向量垂直：a⊥b⇔a·b=0⇔a1b1+a2b2=0。',
        '向量投影：b在a方向上的投影=|b|cosθ=a·b/|a|。',
        '向量模长：|a+b|²=(a+b)·(a+b)=|a|²+2a·b+|b|²。',
        '三角形四心向量形式：G是重心⇔GA+GB+GC=0；O是外心⇔|OA|=|OB|=|OC|；H是垂心⇔HA·HB=HB·HC=HC·HA；I是内心⇔aIA+bIB+cIC=0。',
        '等差数列：a_n=a1+(n-1)d；S_n=n(a1+a_n)/2=na1+n(n-1)d/2。若m+n=p+q则a_m+a_n=a_p+a_q。',
        '等比数列：a_n=a1·q^(n-1)；S_n=a1(1-q^n)/(1-q)(q≠1)。若m+n=p+q则a_m·a_n=a_p·a_q。',
        '求通项方法：①观察法②公式法③累加法（a_{n+1}-a_n=f(n)）④累乘法（a_{n+1}/a_n=f(n)）⑤构造法（a_{n+1}=pa_n+q构造等比）⑥取倒数⑦S_n与a_n关系（n=1时a1=S1；n≥2时a_n=S_n-S_{n-1}）。',
        '求和方法：①公式法②分组求和③裂项相消（1/[n(n+k)]=(1/k)(1/n-1/(n+k))）④错位相减（等差×等比）⑤倒序相加。',
        '数列与函数：数列可看作定义域为N*的函数。',
        '数列不等式：放缩法、数学归纳法、函数单调性法。'
    ])),
    ('不等式', '基本不等式柯西绝对值与线性规划', c([
        '基本不等式：√(ab)≤(a+b)/2（a,b>0，当且仅当a=b取等）。',
        '三个正数：(a+b+c)/3≥∛(abc)（a,b,c>0）。',
        '常用变形：①a+b≥2√(ab)②ab≤((a+b)/2)²③a²+b²≥2ab④a/b+b/a≥2（a,b同号）。',
        '最值条件：一正二定三相等。和定积最大，积定和最小。',
        '对勾函数f(x)=x+k/x(k>0)：(0,√k)递减，(√k,+∞)递增。最小值2√k。',
        '柯西不等式：(a1²+a2²)(b1²+b2²)≥(a1b1+a2b2)²。等号当a1/b1=a2/b2时成立。',
        '绝对值不等式：|a|-|b|≤|a±b|≤|a|+|b|。',
        '|x-a|+|x-b|的最小值=|a-b|（当x在a,b之间时）；|x-a|-|x-b|的最大值=|a-b|，最小值=-|a-b|。',
        '线性规划：①画可行域②目标函数z=ax+by平移直线找最值③检查边界点。',
        '可行域求最优解：①画图平移法②顶点代值法。',
        '目标函数类型：①线性型z=ax+by②斜率型z=(y-b)/(x-a)③距离型z=√((x-a)²+(y-b)²)或z=(x-a)²+(y-b)²。',
        '含参线性规划：根据最优解位置反推参数范围。'
    ])),
    ('立体几何', '空间几何体与空间向量', c([
        '空间几何体：棱柱、棱锥、棱台、圆柱、圆锥、圆台、球。',
        '侧面积与表面积：S直棱柱侧=ch；S正棱锥侧=½ch\'；S圆柱侧=2πrl；S圆锥侧=πrl；S球=4πR²。',
        '体积：V柱体=Sh；V锥体=Sh/3；V台体=(S+√(SS\')+S\')h/3；V球=4πR³/3。',
        '三视图：正视图、侧视图、俯视图。长对正、高平齐、宽相等。',
        '直观图（斜二测）：x轴水平，y轴与x轴成45°，y方向长度减半。原图面积:直观图面积=2√2:1。',
        '空间位置关系：线线平行/垂直、线面平行/垂直、面面平行/垂直。',
        '线面平行判定：平面外一条直线与平面内一条直线平行，则该直线与此平面平行。',
        '线面垂直判定：一条直线与一个平面内两条相交直线都垂直，则该直线与此平面垂直。',
        '面面平行判定：一个平面内的两条相交直线与另一个平面都平行，则这两个平面平行。',
        '面面垂直判定：一个平面过另一个平面的一条垂线，则这两个平面互相垂直。',
        '空间向量：直线方向向量、平面法向量。线线角、线面角、二面角均可向量求。',
        '线线角θ：cosθ=|v1·v2|/(|v1||v2|)。θ∈[0,π/2]。',
        '线面角θ：sinθ=|v·n|/(|v||n|)。θ∈[0,π/2]。',
        '二面角θ：cosθ=n1·n2/(|n1||n2|)或其相反数，需判断锐角钝角。θ∈[0,π]。',
        '点到平面距离：d=|PA·n|/|n|。',
        '空间向量建系：优先找两两垂直的三条直线作为坐标轴。'
    ])),
    ('解析几何', '直线与圆及圆锥曲线综合', c([
        '直线斜率：k=tanα=(y2-y1)/(x2-x1)。α∈[0,π)。',
        '直线方程：点斜式y-y0=k(x-x0)、斜截式y=kx+b、两点式、截距式、一般式Ax+By+C=0。',
        '两直线关系：l1∥l2⇔k1=k2且b1≠b2；l1⊥l2⇔k1·k2=-1；交点即方程组的解。',
        '点到直线距离：d=|Ax0+By0+C|/√(A²+B²)。两平行线距离d=|C1-C2|/√(A²+B²)。',
        '圆的方程：标准(x-a)²+(y-b)²=r²；一般x²+y²+Dx+Ey+F=0（D²+E²-4F>0）。',
        '直线与圆：d<r相交；d=r相切；d>r相离。弦长=2√(r²-d²)。',
        '圆与圆：外离d>r1+r2；外切d=r1+r2；相交|r1-r2|<d<r1+r2；内切d=|r1-r2|；内含d<|r1-r2|。',
        '椭圆：|PF1|+|PF2|=2a(2a>|F1F2|)。标准x²/a²+y²/b²=1(a>b>0,c²=a²-b²)。离心率e=c/a∈(0,1)。',
        '双曲线：||PF1|-|PF2||=2a(2a<|F1F2|)。标准x²/a²-y²/b²=1。渐近线y=±(b/a)x。离心率e=c/a>1。',
        '抛物线：|PF|=d（d为P到准线距离）。标准y²=2px(p>0)。焦点(p/2,0)，准线x=-p/2。e=1。',
        '焦点三角形：椭圆中△PF1F2周长=2a+2c，面积=b²tan(θ/2)；双曲线中面积=b²cot(θ/2)。',
        '直线与圆锥曲线：联立方程消元→判别式Δ→韦达定理x1+x2=-b/a，x1x2=c/a。',
        '弦长公式：|AB|=√(1+k²)|x1-x2|=√(1+k²)√[(x1+x2)²-4x1x2]。',
        '面积问题：S=½|AB|·d（d为点到直线距离）或分割为两个三角形。',
        '定点定值：①设参建立方程②消参得到常数或定点。',
        '设而不求：利用韦达定理，整体代入，不求解具体根。',
        '轨迹方程：直接法、定义法、代入法（相关点法）、参数法、交轨法。',
        '易错点：斜率不存在的情况不要漏；双曲线只有一支的情况；判别式验证。'
    ])),
    ('概率统计', '概率计算与统计分布列', c([
        '古典概型：P(A)=A包含基本事件数/总基本事件数。',
        '几何概型：P(A)=A的测度（长度/面积/体积）/总测度。',
        '互斥事件：P(A∪B)=P(A)+P(B)（A、B互斥）。',
        '对立事件：P(A)+P(Ā)=1。',
        '条件概率：P(B|A)=P(AB)/P(A)。',
        '独立事件：P(AB)=P(A)·P(B)。',
        '独立重复试验（二项分布）：P(X=k)=C(n,k)p^k(1-p)^(n-k)。X~B(n,p)。E(X)=np，D(X)=np(1-p)。',
        '超几何分布：P(X=k)=C(M,k)C(N-M,n-k)/C(N,n)。E(X)=nM/N。',
        '正态分布：X~N(μ,σ²)。曲线关于x=μ对称，σ越小越瘦高。3σ原则：P(μ-σ<X<μ+σ)≈0.6827；P(μ-2σ<X<μ+2σ)≈0.9545；P(μ-3σ<X<μ+3σ)≈0.9973。',
        '标准正态：X~N(0,1)。Z=(X-μ)/σ标准化。',
        '期望E(X)=Σx_i·p_i；方差D(X)=Σ(x_i-E(X))²·p_i=E(X²)-[E(X)]²；标准差σ(X)=√D(X)。',
        '线性性质：E(aX+b)=aE(X)+b；D(aX+b)=a²D(X)。',
        '统计图表：频率分布直方图（频率=小矩形面积）、茎叶图、散点图。',
        '平均数与方差在直方图中：取组中值×频率求和得均值；方差为各组(组中值-均值)²×频率之和。',
        '回归分析：线性回归方程ŷ=bx+a必过样本中心点(x̄,ȳ)。b=Σ(xi-x̄)(yi-ȳ)/Σ(xi-x̄)²。',
        '独立性检验：K²=n(ad-bc)²/[(a+b)(c+d)(a+c)(b+d)]。K²越大越有关联。临界值2.706/3.841/6.635/10.828。',
        '排列组合：A(n,m)=n!/(n-m)!；C(n,m)=n!/[m!(n-m)!]。',
        '组合性质：C(n,m)=C(n,n-m)；C(n,m)+C(n,m-1)=C(n+1,m)。',
        '二项式定理：(a+b)^n=ΣC(n,k)a^(n-k)b^k。通项T_{k+1}=C(n,k)a^(n-k)b^k。系数和：令a=b=1得2^n。'
    ])),
    ('复数与框图', '复数运算与算法框图与推理', c([
        '复数：z=a+bi（a实部，b虚部）。i²=-1。',
        '复数相等：a+bi=c+di⇔a=c且b=d。',
        '复数运算：(a+bi)±(c+di)=(a±c)+(b±d)i；(a+bi)(c+di)=(ac-bd)+(ad+bc)i。',
        '复数除法：分母实数化，乘以共轭复数。(a+bi)/(c+di)=(a+bi)(c-di)/(c²+d²)。',
        '共轭复数：z̄=a-bi。z·z̄=a²+b²=|z|²。',
        '复数模：|z|=√(a²+b²)。|z1·z2|=|z1|·|z2|；|z1/z2|=|z1|/|z2|；|z^n|=|z|^n。',
        '复数几何意义：复平面上的点(a,b)；与原点连线构成的向量OZ。',
        '|z-z0|=r表示以z0对应点为圆心、r为半径的圆。',
        '算法框图：顺序结构、条件结构（选择结构）、循环结构（当型/直到型）。',
        '当型：先判断后执行；直到型：先执行后判断。',
        '输出框、处理框、判断框（菱形）、起止框、流程线。',
        '循环框图解题：列步计算（第1次、第2次……）找规律直到跳出循环。',
        '合情推理：归纳推理（特殊→一般）、类比推理（特殊→特殊）。',
        '演绎推理：三段论（大前提、小前提、结论）。',
        '证明方法：综合法（由因导果）、分析法（执果索因）、反证法（假设结论不成立→矛盾）、数学归纳法（归纳奠基、归纳递推、结论）。'
    ]))
]

# ============== 英语 ==============
subjects['英语'] = [
    ('词汇', '高考核心词汇分类记忆与高级替换', c([
        '名词核心：抽象类(advantage, benefit, consequence, influence, impact, phenomenon, situation, approach, attempt, effort)；具体类(device, facility, alternative, alternative)。',
        '动词核心：表达类(express, convey, indicate, demonstrate, reveal, reflect, suggest, imply)；变化类(change, transform, alter, modify, shift, vary, adjust)；引起类(cause, give rise to, lead to, result in, bring about, contribute to)。',
        '形容词核心：positive/negative, significant/essential/beneficial/harmful/effective/available/reasonable/considerable。',
        '副词核心：however, therefore, thus, consequently, moreover, furthermore, nevertheless, meanwhile, eventually, gradually, particularly, specifically。',
        '高级词汇替换：important→essential/significant/vital/crucial；good→beneficial/positive/favorable/remarkable；bad→harmful/negative/adverse/undesirable；big→massive/enormous/significant/considerable；think→believe/argue/maintain/claim/hold the view that；many→numerous/a variety of/a wide range of；because→due to/owing to/on account of/as a result of；but→however/nevertheless/whereas/yet；so→therefore/thus/accordingly/consequently；very→extremely/highly/greatly/fairly。',
        'one替换：one of the most important、the first one、a big one。',
        '搭配能力：动词+名词(make/do/take/have/give/pay)；形容词+名词；介词搭配。',
        '构词法（派生）：-tion/-sion/-ment/-ness/-ity表名词；-able/-ible/-ful/-less/-ous/-ive/-al/-ary表形容词；-ly表副词；en-/-en-/-ize/-ise表动词；un-/in-/im-/dis-/mis-表否定；re-再；pre-/post-前后；anti-反对；inter-之间；super-超级；trans-转变。',
        '构词法（合成）：名词+名词=复合名词(bookstore, website, smartphone)；形容词+名词=复合名词(fastfood, greenhouse)；动词+副词=复合名词(breakthrough, output, input)；形容词+现在分词=复合形容词(hardworking, good-looking)。',
        '构词法（转化）：water n.水→v.浇水；hand n.手→v.传递；empty adj.空的→v.倒空；better adj.→v.改善；cool adj.→v./n.。',
        '常见短语动词：break系列(break down/up/out/off/through/in)；bring系列(bring up/about/back/forward/out/in)；call系列(call off/on/up/for/in)；come系列(come up/across/about/out/down to)；get系列(get up/on/off/along/through/down to)；give系列(give up/out/in/off/away/back to)；go系列(go up/down/out/on/off/through/over/with)；look系列(look up/down/on/for/into/through/after)；make系列(make up/for/out/up for/of)；put系列(put up/off/on/out/up with/forward/through)；take系列(take up/on/off/out/over/in/after)；turn系列(turn up/down/on/off/out/to/over/into)。',
        '易混词辨析：affect（v.影响）vs effect（n.效果/v.实现）；raise（vt.举起/养育）vs rise（vi.上升）；arise（vi.出现/问题产生）；lie（lay/lain躺、lied/lied说谎）vs lay（laid/laid放置/下蛋）；sit（sat）vs set（set放置/设定）；hanged（绞死）vs hung（悬挂）；economic（经济的）vs economical（节俭的）；historic（有历史意义的）vs historical（历史的/与历史有关的）；respectable（值得尊敬的）vs respectful（尊敬人的）vs respective（各自的）；sensitive（敏感的）vs sensible（明智的）；adapt（适应/改编）vs adopt（采用/收养）vs adept（熟练的）；principal（adj.主要的/n.校长/本金）vs principle（n.原则）；stationary（静止的）vs stationery（文具）；desert（沙漠/v.抛弃）vs dessert（甜点）；loose（松的）vs lose（丢失）。',
        '记忆策略：词根词缀记忆、分类联想记忆、语境记忆、词块记忆、艾宾浩斯遗忘曲线复习。'
    ])),
    ('语法填空', '语法填空高频考点系统归纳', c([
        '题型特点：一篇200词左右短文，10空，考点覆盖词法句法。',
        '考点一：冠词（a/an/the）。泛指用a/an（元音开头an），特指用the。常见：a/an+adj.+n.；the+比较级（两者中更……的）；the+姓氏复数（一家人）。',
        '考点二：介词。常见搭配：①时间介词（in/on/at/since/for/by/during/through）②地点介词（in/on/at/to/off/along/across/through）③固定搭配（depend on, focus on, comment on, result in, lead to, due to, owing to, account for, be known for/as/to, be good at, be interested in）。',
        '考点三：代词。①人称代词主格/宾格（I/me, you/you, he/him, she/her, it/it, we/us, they/them）②物主代词（my/mine, your/yours, his/his, her/hers, its/its, our/ours, their/theirs）③反身代词（myself, yourself, himself, herself, itself, ourselves, yourselves, themselves）④不定代词（some/any, many/much, few/a few, little/a little, all, both, either, neither, none, one, each, every, other, another）⑤it用法（形式主语、形式宾语、强调句型、指代时间/距离/天气）。',
        '考点四：非谓语动词。①to do（不定式：表目的、将来、作主语/宾语/定语/状语/补语）②doing（动名词/现在分词：表主动进行、作主语/宾语/定语/状语/补语）③done（过去分词：表被动完成、作定语/状语/补语）。',
        '重点非谓语句型：It is + adj. + for/of sb. to do；It is no use/good doing；It takes sb. time to do；feel like doing；cannot help doing/to do；have difficulty/trouble (in) doing；look forward to doing；devote...to doing；be used to doing；prefer doing to doing；suggest/advise/consider doing；allow/permit/forbid sb. to do；make/let/have sb. do；see/hear/watch/notice sb. do/doing；with+宾语+to do/doing/done（独立主格）。',
        '考点五：从句。①定语从句（who/whom/whose/which/that/as关系代词；where/when/why关系副词。注意非限定性从句用which不用that；介词+which/whom）②名词性从句（主语从句、宾语从句、表语从句、同位语从句。引导词that/if/whether/what/who/whom/whose/which/when/where/why/how/whatever/whoever/whichever）③状语从句（时间when/while/as/since/before/after/until/till/as soon as；条件if/unless/once/provided；让步though/although/even if/however/whatever/no matter；原因because/as/since/now that；目的so that/in order that；结果so...that/such...that；比较as...as/than；方式as/as if；地点where/wherever）。',
        '考点六：时态语态。常用时态：一般现在时（主动do/does，被动am/is/are done）、一般过去时（did/was were done）、一般将来时（will do/be going to do；will be done）、现在进行时（is/am/are doing；is being done）、过去进行时（was/were doing；was being done）、现在完成时（have/has done；have/has been done）、过去完成时（had done；had been done）、现在完成进行时（have/has been doing）。',
        '时态判断：根据时间状语、上下文语境、逻辑关系。',
        '考点七：词性转换。①名词→形容词（use→useful/useless；care→careful/careless；nature→natural；tradition→traditional；danger→dangerous）②形容词→名词（important→importance；different→difference；happy→happiness；safe→safety）③形容词→副词（加ly：quick→quickly；careful→carefully；去e加ly：true→truly；变y为i加ly：happy→happily；特殊：good→well）④动词→名词（加ment/tion/sion/ing/er/or：develop→development；educate→education；decide→decision；mean→meaning；teach→teacher）。',
        '考点八：形容词副词比较级最高级。①单音节/部分双音节：+er/+est或特殊（good→better→best；bad→worse→worst；many/much→more→most；little→less→least；far→farther/further→farthest/furthest；old→older/elder→oldest/eldest）②多音节：more/most+原级。',
        '重点句型：as+原级+as；比较级+than；the+比较级+of the two；the+最高级+范围；比较级+and+比较级（越来越）；the+比较级,the+比较级（越……越……）。',
        '答题步骤：①读全文把握大意②分析句子结构③判断词性④确定具体形式⑤检查时态语态单复数。'
    ])),
    ('短文改错', '短文改错常见错误与技巧', c([
        '题型特点：一篇约100词短文，10处错误，1处正确（有时无）。',
        '错误类型（按频率）：动词时态语态错误、名词单复数错误、介词错误、冠词错误、代词错误、形容词副词混用、比较级最高级错误、从句引导词错误、非谓语错误、逻辑错误、缺词多词。',
        '动词错误：①时态：上下文时态不一致（如现在时改过去时）②语态：被动没加be③主谓一致：主语单复数与谓语不一致（第三人称单数漏s）④并列结构动词形式不一致。',
        '名词错误：可数名词没加复数、不可数名词加了复数、a/an+不可数名词、one/some/each后名词形式错误。',
        '介词错误：固定搭配中的介词错误（listen the music→listen to the music）；时间地点介词错用（in a cold morning→on a cold morning）；多余介词或漏介词。',
        '冠词错误：泛指漏a/an、特指漏the、不可数名词加a/an、元音开头用a、a an混用。',
        '代词错误：人称代词/物主代词/反身代词错误；指代性别/单复数错误；one/ones/it/them使用错误；反身代词与主语不一致。',
        '形容词副词混用：系动词后用副词→改形容词；修饰动词用形容词→改副词；修饰全句应该用副词。',
        '比较级最高级错误：原级与比较级混用；more/most与比较级最高级重复（more better）；比较级前没加the的情况。',
        '从句引导词错误：定语从句that/which/who/where/when误用；what引导名词性从句；if与whether辨析；which与what引导名词从句差异。',
        '非谓语错误：to do/doing/done用错；介词后接动词原形→接doing；并列结构非谓语形式不一致。',
        '逻辑错误：and→but；so→but；but→however；肯定否定误用；语义矛盾。',
        '缺词：名词前缺冠词、及物动词后缺宾语、系动词缺表语、固定短语缺词。',
        '多词：冗余的冠词/介词/代词/连接词、不定式前多余的to。',
        '常正确的：高级词汇、复杂结构、难以一眼判断的地方。',
        '答题技巧：逐句分析主谓宾定状补→检查各类可能错误→通读检查→注意常见陷阱（hard→hardly；late→lately；most→mostly；already→yet）。'
    ])),
    ('阅读理解', '阅读理解各类题型解题攻略', c([
        '题型分类：细节理解题、推理判断题、词义猜测题、主旨大意题、作者态度意图题。',
        '应用文解题（A篇）：广告、通知、说明书、海报、指南。特点：信息密集、有小标题、含数字价格时间。技巧：先看题目再找答案→关键词定位→注意大写专有名词数字符号→排除干扰项。',
        '细节理解题特点：考查对具体事实的把握。常见提问：Which of the following is true/mentioned? According to the passage, who/what/when/where/why/how...?',
        '细节题解题：①通读全文理解大意②关键词定位原文③对照选项仔细比较④注意同义替换与反向表达。',
        '正误判断题技巧：看清TRUE/NOT TRUE/MENTIONED/NOT MENTIONED/EXCEPT/INCLUDE。',
        '推理判断题特点：不是原文直接信息，需分析推断。常见提问：It can be inferred from the passage that... The author implies/suggests that... What can we learn/conclude from...? What is implied but not stated?',
        '推理题解题三不原则：①不要选直接原句（那是细节不是推理）②不要选过度推断（超出文章范围）③不要选与常识相符但文章无依据。',
        '词义猜测题技巧：①定义法（that is, namely, in other words）②举例法（such as, for example）③对比法（but, however, unlike, while）④因果法（because, so, therefore）⑤构词法（词根词缀）⑥上下文语境⑦指代关系（it/this/that指代前文）。',
        '主旨大意题技巧：①看标题/首段/末段②找高频词/关键词③看各段首句④注意首段转折后的内容⑤记叙文看故事寓意⑥议论文看论点⑦说明文看说明对象和特点。',
        '常见干扰：①以偏概全（只概括某段）②过度扩大（范围太大）③无中生有④偷换概念。',
        '选标题题：选最凝练、最核心、最有吸引力的。',
        '作者态度题：积极类（positive, optimistic, approving, supportive, favorable, sympathetic, appreciative, enthusiastic）；消极类（negative, pessimistic, disapproving, critical, skeptical, suspicious, doubtful, opposed, worried, disappointed）；中立类（objective, neutral, impartial, indifferent, ambiguous, cautious, matter-of-fact, uninterested）。',
        '态度判断方法：看作者用词的感情色彩（褒义/贬义/中性）、看论点偏向、看特殊符号和引号。',
        '七选五解题：①看位置（段首→主题句；段中→过渡句；段尾→总结句）②找关键词（原词/同义词/近义词/上下义词）③找过渡词（however, therefore, moreover, besides, for example, in other words, that is, on the contrary, in contrast）④看逻辑关系⑤代入验证。',
        '阅读理解通用策略：①快速浏览抓主旨②仔细阅读找细节③推理判断不武断④词义猜测看语境⑤主旨大意看首尾⑥作者态度看用词⑦干扰选项常陷阱（张冠李戴、偷换概念、以偏概全、无中生有、因果倒置、过于绝对、曲解原意）。'
    ])),
    ('完形填空', '完形填空解题技巧与逻辑分析', c([
        '完形特点：一篇200-300词短文，20空，考查词汇、语法、语境、逻辑。',
        '解题步骤：①通读全文掌握主旨（跳过空格，关注首段）②逐句分析先易后难（语法搭配词汇逻辑）③复读全文验证答案（通顺性、连贯性）。',
        '语境解题：根据上下文暗示→前呼后应→前后文信息互补。',
        '逻辑解题：转折(but, however, yet, although, though, instead, on the contrary)、因果(because, for, as, since, therefore, so, thus, consequently, as a result)、递进(moreover, furthermore, besides, in addition, also, too, what is more, worse still)、并列(and, or, as well as, both...and, either...or, neither...nor, not only...but also)、对比(while, whereas, on one hand...on the other hand, some...others...)。',
        '复现解题：原词复现、同义词复现、反义词复现、上下义词复现、结构复现。',
        '搭配解题：①动词固定搭配(take advantage of, make use of, pay attention to, take into consideration/account, attach importance to, play a role/part in, have an effect/influence/impact on)②形容词介词搭配(be good at, be interested in, be satisfied with, be concerned about/for, be responsible for, be aware of, be capable of, be consistent with)③名词介词搭配(key to, answer to, solution to, reason for, cause of, attitude towards/to, approach to)。',
        '情感色彩解题：作者感情基调（褒义/贬义/中性）决定选词方向。',
        '记叙文完形：关注故事时间线、人物关系、事件发展、情感变化、结尾升华。',
        '议论文完形：关注论点论据、逻辑连接、作者立场。',
        '说明文完形：关注说明顺序、事物特征、因果关系。',
        '高频词汇：动词(manage, try, attempt, offer, afford, promise, persuade, allow, permit, admit, remind, realize, recognize, accept, receive, achieve, accomplish, succeed, fail, remain, stay, leave, keep, hold, support, maintain, survive, recover)；名词(opportunity, chance, choice, alternative, decision, effort, attempt, purpose, aim, goal, target, intention, desire, passion, courage, wisdom, strength, ability, talent, skill, experience, knowledge, information, message, announcement, statement, comment, opinion, view, attitude, behavior, manner, action, activity)；形容词(willing, eager, anxious, nervous, curious, patient, generous, modest, proud, ashamed, embarrassed, confused, puzzled, shocked, astonished, amazed, surprised, excited, delighted, pleased, satisfied, disappointed, frustrated, exhausted, worn-out, relieved, relaxed, comfortable, convenient, available, accessible, affordable, reasonable, reliable, responsible, professional, efficient, effective, successful, valuable, important, essential, significant, necessary, beneficial, harmful, dangerous, risky, safe, secure, certain, sure, likely, possible, probable, common, ordinary, general, normal, regular, usual, frequent, rare, unique, special, particular, specific, individual, personal, private, public, social, cultural, historical, traditional, modern, advanced, ancient, natural, artificial, digital, virtual, realistic, practical, theoretical, academic, scientific, technical, technological, economic, political, environmental, educational, medical, industrial, agricultural, commercial, financial, legal, moral, ethical, spiritual, mental, physical, emotional, psychological, social, cultural, historical, traditional, modern, contemporary, current, recent, previous, former, latter, next, upcoming, future, past, present, permanent, temporary, constant, steady, stable, gradual, rapid, slow, immediate, instant, urgent, emergency, important, significant, essential, vital, crucial, critical, serious, severe, minor, major, primary, secondary, basic, fundamental, simple, complex, complicated, sophisticated, advanced, basic, elementary, intermediate, advanced, high-level, top-level, world-class, high-quality, first-class, second-to-none, state-of-the-art, cutting-edge, leading-edge, brand-new, brand-new-style, old-fashioned, out-of-date, up-to-date, modern-style, latest, recent, current, contemporary, present-day, modern-day, present-time, nowadays, today, currently, presently, shortly, immediately, instantly, quickly, rapidly, swiftly, promptly, speedily, hastily, hurriedly, slowly, gradually, steadily, eventually, finally, ultimately, in the end, at last, at length, in conclusion, in summary, in short, in brief, in a word, to sum up, all in all, generally speaking, broadly speaking, roughly speaking, strictly speaking, strictly, precisely, exactly, specifically, particularly, especially, notably, primarily, mainly, mostly, chiefly, largely, generally, commonly, normally, usually, frequently, regularly, often, sometimes, occasionally, rarely, seldom, hardly, barely, scarcely, never, ever, always, forever, constantly, continuously, continually, repeatedly, again and again, over and over, time and again, time after time, time and time again, day after day, year after year, one after another, one by one, step by step, little by little, bit by bit, piece by piece, side by side, hand in hand, face to face, back to back, shoulder to shoulder, arm in arm, neck and neck, head to head, toe to toe, eye to eye, heart to heart, mind to mind, soul to soul, spirit to spirit, hand to hand, mouth to mouth, ear to ear, nose to nose, tooth to tooth, nail to nail, hair to hair, skin to skin, bone to bone, flesh to flesh, blood to blood, life to life, death to death, start to finish, beginning to end, from start to finish, from beginning to end, from first to last, from head to toe, from top to bottom, from side to side, from east to west, from north to south, from left to right, from right to left, from front to back, from back to front, from inside to outside, from outside to inside, from here to there, from there to here, from now on, from then on, from today on, from yesterday on, from this day forward, from that day forward, from this point on, from that point on, from now onwards, from then onwards, from today onwards, from this moment on, from that moment on, from this second on, from that second on, from now until, from then until, from today until, from this day until, from that day until, from this time until, from that time until, from this point until, from that point until, from now till, from then till, from today till, from this day till, from that day till, from this time till, from that time till, from this point till, from that point till, from now through, from then through, from today through, from this day through, from that day through, from this time through, from that time through, from this point through, from that point through, from now up to, from then up to, from today up to, from this day up to, from that day up to, from this time up to, from that time up to, from this point up to, from that point up to, from now down to, from then down to, from today down to, from this day down to, from that day down to, from this time down to, from that time down to, from this point down to, from that point down to)。',
        '最后复读：检查语法通顺、逻辑合理、主旨明确。'
    ])),
    ('书面表达', '书信格式与各类书信写作', c([
        '英语书信格式：①信头（发信人地址日期，右上角）②称呼（Dear..., 左侧）③正文（分段写）④结尾敬语（Yours sincerely/faithfully/truly, 右下）⑤签名。',
        '高考常考书信：道歉信、感谢信、建议信、申请信、投诉信、邀请信、询问信、介绍信、推荐信、祝贺信、慰问信、通知。',
        '道歉信：①说明道歉事由②解释原因（不找借口）③提出补救措施④再次道歉请求谅解。常用语：I am writing to apologize for...; I feel terribly sorry that...; Please forgive me for...; I promise that...; To make up for...。',
        '感谢信：①表达感谢②说明感谢的具体事情③评价这件事的意义④再次表达感谢或希望回报。常用语：I am writing to express my sincere gratitude for...; I would like to convey my heartfelt thanks to you for...; Without your help, I would never have...; I really appreciate what you have done for me。',
        '建议信：①说明写信目的②提出具体建议（2-3条）③解释为什么这样建议④希望建议被采纳。常用语：I am writing to share my suggestions on...; I would like to offer some advice on...; Here are my suggestions/advice/tips/recommendations; First... Besides... Furthermore...; I hope you will find these suggestions helpful/useful/practical/beneficial。',
        '申请信（申请学校/职位）：①说明申请什么及信息来源②自我介绍（个人情况/教育/经验/能力）③表达愿望与承诺④附相关材料请求回复。常用语：I am writing to apply for...; I am writing in response to your advertisement for...; I would like to apply for the position/post of...; I graduated from...; I have experience in...; I am good at.../I have a good command of...; I would appreciate it if you could...。',
        '投诉信：①说明投诉对象及问题②描述问题发生经过及造成的不便③提出解决方案（退款/更换/修理/道歉）④希望尽快处理。常用语：I am writing to complain about...; I am writing to express my dissatisfaction/disappointment with...; I regret to inform you that...; I hope/believe/trust that you will...; I would be grateful if you could...。注意语气要礼貌不要粗鲁。',
        '邀请信：①说明邀请事由②邀请谁参加③活动时间地点内容④期待对方接受邀请。常用语：I am writing to invite you to...; I wonder if you could come to...; It would be a great honor/privilege/pleasure for us if you could...; The activity will be held on...at...; I really hope you can make it。',
        '通知：标题NOTICE、发布单位、日期时间、事件、地点、对象、注意事项、联系方式。常用语：There will be a... to be held on...; All the students are welcome to...; Anyone who is interested in... please...; Please be present on time; Please sign up before...。',
        '演讲稿：①开场白（问候+自我介绍+主题）②主体（分点阐述）③结尾（总结+感谢）。常用语：Good morning/afternoon/evening, ladies and gentlemen; I am honored/pleased/delighted to have the opportunity to speak to you today about...; Today I would like to talk about...; First of all... Secondly... Last but not least...; In conclusion/To sum up/In short...; Thank you for your attention/for listening。',
        '倡议书：①倡议背景/原因②倡议的具体内容/做法③呼吁大家参与④表达决心。常用语：Nowadays, ... is becoming more and more...; It is high time that we...; Here are some suggestions for us to follow; First... Second... Third...; I hope all of us will...; Let us take action right now!。',
        '议论文写作：①提出观点②论证（举例/引用/因果/对比）③总结升华。正反观点型：开头引入→观点一+理由→观点二+理由→个人观点。',
        '高级句型提升：倒装句（Never/Seldom/Little/Hardly/Rarely/Only.../So.../Such...置于句首）；强调句（It is/was + 被强调部分 + that/who + 其他）；虚拟语气（If I were you/If it had not been for/I wish/I would rather）；分词作状语（Having done.../Done...）；with复合结构（with + n./pron. + to do/doing/done/adj./adv./prep.）；非谓语动词开头（To do... is.../Doing... is...）；定语从句（which/who/that/where/when/why引导）；名词性从句（what/that/whether/whatever引导）；状语从句（though/if/because/so...that引导）；并列句（and/but/so/or/for连接）。',
        '高级词汇运用：用significantly替代very；用beneficial替代good；用consequently替代so；用nevertheless替代but；用numerous替代many；用a wide range of替代different kinds of。',
        '连接过渡词：表递进(furthermore, moreover, besides, in addition, what is more, on top of that, additionally)；表转折(however, nevertheless, nonetheless, yet, but, on the contrary, in contrast, by contrast, conversely)；表因果(therefore, thus, consequently, as a result, because of this, due to this, for this reason, hence, accordingly)；表列举(first, first of all, to begin with, in the first place, second, besides, in addition, furthermore, moreover, what is more, finally, last but not least, eventually)；表举例(for example, for instance, such as, like, take... for example, a case in point is, as an illustration, to illustrate)；表总结(in conclusion, in summary, in short, in brief, all in all, to sum up, in a word, overall, generally speaking)；表对比(on one hand...on the other hand, for one thing...for another, in comparison with, compared with/to, by comparison, by contrast)；表强调(indeed, in fact, actually, as a matter of fact, certainly, definitely, absolutely, obviously, apparently, evidently, clearly, particularly, specifically, especially, notably, most importantly, above all, first and foremost, primarily, chiefly)；表时间(at present, currently, now, these days, nowadays, today, recently, lately, in recent years, in the past few decades, at the same time, meanwhile, in the meantime, simultaneously, eventually, finally, ultimately, in the end, at last, previously, formerly, earlier, before, prior to, after, afterwards, later, following, subsequent, next, then, after that, from then on, from now on, in future, in the future, soon, shortly, in the near future, immediately, instantly, right now, right away, at once, promptly, as soon as possible, the moment, the minute, the instant, hardly...when, no sooner...than)。',
        '作文高分要点：①内容完整要点齐全②结构清晰层次分明③语法正确错误少④表达多样句式丰富⑤词汇高级搭配地道⑥书写工整卷面整洁⑦字数恰当（100-120-150词）。'
    ]))
]

# ============== 物理 ==============
subjects['物理'] = [
    ('力学综合', '牛顿定律与连接体传送带问题', c([
        '牛顿第一定律（惯性定律）：一切物体总保持匀速直线运动状态或静止状态，除非外力迫使它改变。',
        '牛顿第二定律：F合=ma。矢量式，a与F合方向相同。',
        '牛顿第三定律：作用力与反作用力大小相等方向相反，作用在两个物体上，性质相同同时产生同时消失。',
        '受力分析顺序：重力→弹力→摩擦力→其他力（电场力、磁场力等）。',
        '弹力判断：看接触物体是否有形变（挤压/拉伸/弯曲）。方向垂直接触面或沿绳/弹簧。',
        '摩擦力：①静摩擦力0<f≤fmax=μsN，方向与相对运动趋势相反②滑动摩擦力f=μkN，方向与相对运动方向相反。',
        '正交分解：将力分解到垂直方向，ΣF_x=ma_x，ΣF_y=ma_y。',
        '连接体问题（相同加速度）：先整体求a=F/(M+m)，再隔离求相互作用力。',
        '连接体内力：T=F·m/(M+m)（当F作用在M上拉m时）。内力与F位置相反。',
        '传送带问题分析：①判断物体与传送带速度关系②确定摩擦力方向与大小③求加速度④列运动学方程求时间/位移。',
        '水平传送带：物体速度v0<v带→先加速后匀速；v0=v带→匀速；v0>v带→先减速后匀速。',
        '倾斜传送带：需比较μ与tanθ大小。μ≥tanθ物体能与带相对静止；μ<tanθ物体始终滑动。',
        '板块模型：判断板块是否相对滑动→假设共速，由静摩擦f静≤μmg判断→若不共速则分别求加速度→临界条件v1=v2。',
        '超重失重：a向上→超重（视重>实重）；a向下→失重（视重<实重）；a=g且向下→完全失重。',
        '实验：验证牛顿第二定律（小车、打点计时器、砝码盘）→平衡摩擦力、满足m<<M。'
    ])),
    ('运动学', '运动学综合与追击相遇问题', c([
        '基本概念：质点、参考系、时间/时刻、位移/路程、速度/速率、加速度。',
        '平均速度：v̄=Δx/Δt（矢量）；平均速率：路程/时间（标量）。瞬时速度：Δt→0时的平均速度。',
        '加速度：a=Δv/Δt=(v-v0)/t。a与v同向加速反向减速。',
        '匀变速直线运动公式：v=v0+at、x=v0t+½at²、v²-v0²=2ax、x=(v0+v)t/2、v̄=(v0+v)/2。',
        '中间时刻速度：v_{t/2}=(v0+v)/2=v̄；中间位置速度：v_{x/2}=√((v0²+v²)/2)。匀加速时v_{x/2}>v_{t/2}。',
        '连续相等时间T内位移差：Δx=aT²。推广：x_m-x_n=(m-n)aT²。',
        '自由落体：v=gt、h=½gt²、v²=2gh。',
        '竖直上抛：v=v0-gt、h=v0t-½gt²、v²-v0²=-2gh。上升时间t=v0/g，最大高度h=v0²/(2g)。',
        '追及相遇问题：①两物体同地出发：x1=x2时相遇②不同地：x1+Δx0=x2时相遇。',
        '追及条件：①速度相等是临界（相距最远/最近）②位移关系满足追上③二次方程判别式Δ≥0有解。',
        'v-t图像：斜率=加速度，面积=位移，面积差=两物体位移差。',
        '多过程问题：分段分析，注意两段交接处速度相同、位移之和为总位移。',
        '斜面上抛：a=gsinθ（光滑）；a=gsinθ+μgcosθ（向上滑）；a=gsinθ-μgcosθ（向下滑，μ<tanθ时）。',
        '曲线运动条件：合外力与速度不在一直线上。特点：速度方向沿切线、加速度指向轨迹凹侧、轨迹弯向合力方向。',
        '平抛运动：水平匀速x=v0t，竖直自由下落y=½gt²。合速度v=√(v0²+g²t²)，方向tanα=gt/v0。合位移s=√(x²+y²)，方向tanθ=y/x=gt/(2v0)。',
        '斜抛运动：斜向上抛v_x=v0cosθ，v_y=v0sinθ-gt。射程R=v0²sin(2θ)/g，最大高度H=v0²sin²θ/(2g)，飞行时间T=2v0sinθ/g。',
        '圆周运动：线速度v=Δs/Δt=2πr/T，角速度ω=Δθ/Δt=2π/T=2πf，向心加速度a=v²/r=ω²r=ωv，向心力F=mv²/r=mω²r。',
        '圆周运动向心力来源：分析沿半径方向的合力。常见：绳（光圆轨道内侧）→最高点最小速度√(gr)；杆（圆管）→最高点速度可为0；凸拱桥→最大速度√(gr)。',
        '万有引力：F=Gm1m2/r²。行星/卫星：GmM/r²=mv²/r=mω²r=m(4π²/T²)r=ma。',
        '天体密度：ρ=3πr³/(GT²R³)。近地卫星时r=R，ρ=3π/(GT²)。',
        '变轨问题：低轨→高轨需加速两次（椭圆近地点、远地点各一次）；高轨→低轨减速两次。',
        '双星三星：各星绕质心做圆周运动，相互引力提供向心力，角速度相同。',
        '宇宙速度：第一宇宙速度v1=√(gR)=7.9km/s；第二v2=11.2km/s；第三v3=16.7km/s。'
    ])),
    ('电磁学', '电场磁场与带电粒子运动', c([
        '库仑定律：F=kq1q2/r²，k=9×10^9 N·m²/C²。仅适用于真空中点电荷。',
        '电场强度：E=F/q（定义式），E=kQ/r²（点电荷），E=U/d（匀强电场）。',
        '电场线特点：正电荷出发负电荷终止、不闭合不相交、疏密表示强弱、切线方向为E方向。',
        '电势能与电势：φ=Ep/q（电势定义）；U_AB=φ_A-φ_B=W_AB/q。',
        '电场力做功：W=qU_AB=q(φ_A-φ_B)，与路径无关只与初末位置有关。',
        '匀强电场中：U=Ed（d为沿E方向距离）。',
        '电容器：C=Q/U（定义式），C=εrS/(4πkd)（平行板）。充电后断开Q不变；保持连接U不变。',
        '带电粒子在电场中加速：qU=½mv²-½mv0²。',
        '带电粒子在电场中偏转（类平抛）：水平L=v0t，竖直y=½at²=½(qE/m)t²=qUL²/(2mdv0²)。偏转角tanθ=v_y/v0=qUL/(mdv0²)。',
        '电流：I=Δq/Δt；I=nqSv（微观）；I=U/R（欧姆定律，仅适用于金属/电解液）。',
        '串联并联：R串=R1+R2+...；1/R并=1/R1+1/R2+...；I相同U相加（串）；U相同I相加（并）。',
        '闭合电路欧姆定律：I=ε/(R+r)或ε=U外+U内。路端电压U=ε-Ir，随外电阻增大而增大。',
        '电功率：P=UI=I²R=U²/R；电源总功率P总=εI；输出功率P出=UI=I²R；P出最大时R=r，Pmax=ε²/(4r)。',
        '磁场基本概念：磁感线、磁感应强度B=F/(IL)（I⊥B时）。单位特斯拉T=Wb/m²。',
        '安培力：F=BIL（I⊥B时，方向左手定则）；F=BILsinθ（I与B夹角θ）。',
        '洛伦兹力：f=qvB（v⊥B时，方向左手定则，正电荷受力方向）；f=qvBsinθ；永远不做功。',
        '带电粒子在匀强磁场中做圆周运动：qvB=mv²/r→r=mv/(qB)，T=2πm/(qB)。半径与速度有关，周期与速度无关。',
        '粒子在磁场中运动解题：①确定圆心（洛伦兹力方向垂线交点）②确定半径（几何关系）③确定圆心角θ（弦切角、偏转角）④求时间t=θT/(2π)。',
        '边界问题：直线边界（进出对称）、圆形边界（沿半径方向射入沿半径射出）、三角形边界。',
        '临界问题：轨迹与边界相切时为临界状态。',
        '质谱仪：加速qU=½mv²，偏转r=mv/(qB)，得比荷q/m=2U/(B²r²)。',
        '回旋加速器：最大动能Ek=q²B²R²/(2m)，与加速电压无关。',
        '复合场（叠加场）：重力、电场力、洛伦兹力同时存在。匀速直线运动→合力为0；匀速圆周运动→重力与电场力平衡，洛伦兹力提供向心力；复杂运动→用动能定理或能量守恒。'
    ])),
    ('电磁感应', '楞次定律与法拉第电磁感应定律', c([
        '磁通量：Φ=BS_⊥=BScosθ（θ为B与S法线夹角）。单位韦伯Wb。',
        '感应电流产生条件：闭合回路磁通量变化。',
        '楞次定律：感应电流的磁场总是阻碍引起感应电流的磁通量变化。"阻碍"不是"阻止"，是"延缓"。',
        '楞次定律推广：①阻碍原磁通量变化（增反减同）②阻碍相对运动（来拒去留）③使回路面积变化（增缩减扩）④阻碍原电流变化（自感）。',
        '右手定则（切割磁感线）：伸开右手，B穿手心，拇指指向导体运动方向，四指指向感应电流方向（感应电动势方向）。',
        '法拉第电磁感应定律：ε=n·ΔΦ/Δt。平均电动势。',
        '动生电动势（导体切割）：ε=BLv（B、L、v两两垂直）；ε=BLv⊥（v与B有夹角取垂直分量）。',
        '旋转切割：导体绕一端垂直B旋转，ε=½BωL²；绕圆心旋转，ε=0（两端等势）。',
        '线圈转动：N匝S面积在B中以角速度ω转动，ε=NBSω·sinωt（从中性面开始计时）。最大值εm=NBSω。',
        '感应电荷量：q=I平均·Δt=(ε/R)·Δt=(nΔΦ/Δt/R)·Δt=nΔΦ/R。',
        '安培力做功：通电导体受安培力运动时，安培力做负功→电能转化为机械能（电动机）；外力推动导体切割磁感线，安培力做正功→机械能转化为电能（发电机）。',
        '电磁感应图像：Φ-t图、B-t图、ε-t图、I-t图、F-t图。斜率与面积的物理意义。',
        '导轨问题：棒在导轨上运动→感应电流→安培力→加速度变化→牛顿运动定律+能量守恒。',
        '能量守恒：克服安培力做的功=产生的电能=焦耳热=I²Rt。',
        '自感：通电自感（灯泡逐渐变亮）、断电自感（灯泡闪亮后熄灭）。',
        '涡流：块状金属在变化磁场中产生涡旋电流→发热（电磁炉、涡流制动、涡流探测）。'
    ])),
    ('交变电流与变压器', '交变电流与理想变压器', c([
        '交变电流：大小和方向都随时间做周期性变化的电流。',
        '正弦交变电流产生：线圈在匀强磁场中匀速转动。',
        '瞬时值：e=εm·sinωt（从中性面计时）；e=εm·cosωt（从垂直中性面计时）。',
        '最大值：εm=NBSω=NΦmω。',
        '有效值：让交流电与恒定电流通过相同电阻，相同时间产生相同热量，该恒定电流的数值。正弦交流电：ε=εm/√2，U=Um/√2，I=Im/√2。',
        '平均值：用平均电动势求，ε平均=nΔΦ/Δt。',
        '周期频率：T=2π/ω，f=1/T。市电：220V 50Hz。',
        '理想变压器：无漏磁、无铜损、无铁损。',
        '基本关系：U1/U2=n1/n2（原副线圈电压比=匝数比）；I1/I2=n2/n1（只有一个副线圈时电流比=匝数反比）；P1=P2即U1I1=U2I2（输入功率=输出功率）。',
        '多个副线圈：U1/n1=U2/n2=U3/n3=...；n1I1=n2I2+n3I3+...。',
        '变压器动态分析：①U1不变则U2不变（负载变化U2不变）②负载变化→R变→I2变→P2变→P1变→I1变。',
        '远距离输电：输电线功率损失P损=I²R线=U损²/R线=P²R线/U²。减小损失方法：减小电阻R或提高输电电压U。',
        '输电流程：升压变压器→高压输电→降压变压器→用户。U损=IR线，U用户=U2-U损。',
        '正弦交流电图像：e-t图为正弦曲线，t=0处为0→从峰值面开始；t=0处为最大值→从中性面开始。',
        '最大值有效值平均值使用场合：①电器铭牌标注/保险丝熔断电流→有效值②电容器击穿电压→最大值③通过电量→平均值④热量计算→有效值。'
    ])),
    ('热学光学近代', '热学综合与光学综合', c([
        '分子动理论：①物质由分子组成②分子永不停息做无规则运动（布朗运动、扩散）③分子间存在相互作用力（引力+斥力，都随距离增大而减小，斥力变化更快）。',
        '分子大小：分子直径约10^-10m；阿伏加德罗常数NA=6.02×10^23/mol。',
        '分子热运动：温度越高运动越剧烈。速率分布呈"中间多两头少"。',
        '分子力与分子势能：r<r0时斥力主导，r减小E_p增大；r=r0时E_p最小；r>r0时引力主导，r增大E_p增大。',
        '内能：物体内所有分子动能+分子势能总和。温度是分子平均动能标志。理想气体内能只与温度和物质的量有关。',
        '热力学第一定律：ΔU=Q+W。符号规则：W外界对气体做功为正，Q气体吸热为正，ΔU增加为正。',
        '理想气体状态方程：pV=nRT=p0V0/T0。一定质量：pV/T=C。',
        '等温变化（玻意耳定律）：pV=C；等容变化（查理定律）：p/T=C；等压变化（盖-吕萨克定律）：V/T=C。',
        '气体压强：大量分子频繁碰撞器壁产生。p=nmv̄²/3。微观上与分子数密度和平均动能有关；宏观上与温度体积有关。',
        '热力学第二定律：①热量不能自发地从低温物体传到高温物体（克劳修斯表述）②不可能从单一热源吸热使之完全变成功而不产生其他影响（开尔文表述）。熵增原理：自发过程熵总是增加。',
        '光的折射：n=sinθ1/sinθ2=v1/v2=λ1/λ2。光从真空射入介质n>1。',
        '全反射：光从光密介质射向光疏介质，入射角≥临界角C，sinC=1/n。',
        '光的干涉：两列相干光（频率相同相位差恒定）叠加。双缝干涉条纹间距Δy=λL/d。',
        '光的衍射：单缝衍射、圆孔衍射、圆板衍射（泊松亮斑）。条件：障碍物尺寸与波长差不多或更小。',
        '光的偏振：横波特性。自然光通过偏振片成为偏振光。',
        '电磁波谱：无线电波、红外线、可见光、紫外线、X射线、γ射线。频率升高波长减小。',
        '光电效应：入射光频率超过极限频率时，金属表面发射光电子。爱因斯坦光电效应方程：hν=W0+Ek_max。',
        '波粒二象性：光既有波动性（干涉衍射偏振）又有粒子性（光电效应）。实物粒子也有波动性（德布罗意波λ=h/p）。',
        '原子结构：α粒子散射实验→核式结构。玻尔模型：轨道量子化、能级跃迁、光子发射hν=E_m-E_n。',
        '原子核：天然放射现象→α射线(氦核)、β射线(电子)、γ射线(光子)。α衰变Z-2,N-2；β衰变Z+1,N-1。',
        '核反应：聚变（轻核结合）、裂变（重核分裂）。质量亏损→核能E=Δmc²。'
    ])),
    ('力学实验', '力学实验与数据处理', c([
        '实验一：研究匀变速直线运动（打点计时器）。电火花计时器220V交流电，电磁打点计时器4-6V低压交流电。f=50Hz，T=0.02s。',
        '纸带处理：①求瞬时速度v_n=(x_n+x_{n+1})/(2T)（中间时刻速度等于平均速度）②求加速度逐差法a=[(x4+x5+x6)-(x1+x2+x3)]/(9T²)。',
        'v-t图像求a：斜率即加速度a=Δv/Δt。',
        '实验二：验证牛顿第二定律。①平衡摩擦力（小车重力分力平衡摩擦）②满足m<<M（砝码质量远小于小车质量，否则系统误差大）③用控制变量法：保持M不变研究a-F，保持F不变研究a-M（实际画a-1/M图为直线更直观）。',
        '实验三：验证机械能守恒定律。自由下落过程mgh=½mv²。选第1、2点间距接近2mm的纸带（自由下落起始）。v_n=(x_n+x_{n+1})/(2T)。验证gh_n=½v_n²。',
        '实验四：验证力的平行四边形定则。用两个弹簧测力计拉橡皮条→记录两力大小方向；再用一个弹簧测力计拉到同一位置→记录合力。两次位置必须相同（效果等效）。',
        '实验五：探究动能定理。小车在橡皮筋作用下运动，橡皮筋做功与小车获得速度关系。1条做功W，2条做功2W……测出速度v，画W-v²图验证是否为直线。',
        '游标卡尺读数：主尺读数（mm）+ 游标尺对齐刻度×精度。精度：10分度0.1mm，20分度0.05mm，50分度0.02mm。不估读。',
        '螺旋测微器读数：固定刻度（含半毫米刻度线）+ 可动刻度×0.01mm（估读一位）。总精度0.001mm。',
        '误差分析：系统误差（实验原理/装置缺陷，不可避免，可改进）、偶然误差（测量读数误差，多次测量减小）。',
        '有效数字：从第一个非零数字起的所有数字。1.20为三位有效数字，0.012为两位。',
        '数据处理方法：①列表法②作图法③逐差法④平均法⑤最小二乘法（线性回归）。',
        '图像法：①坐标选择（尽量使图线居中）②标度选择（使图线倾斜45°左右）③描点连线（直线或光滑曲线）④截距和斜率的物理意义。',
        '实验设计原则：科学性、可行性、准确性、简洁性、安全性。控制变量法很重要。'
    ])),
    ('电学实验', '电学实验与传感器应用', c([
        '实验一：测定金属电阻率。原理ρ=RS/L。R用伏安法测，S=πd²/4（d由螺旋测微器测），L用米尺。',
        '实验二：描绘小灯泡伏安特性曲线。小灯泡灯丝电阻随温度升高而增大。①电流表外接（因R_V>>R_灯）②滑动变阻器分压式（电压从0开始）。',
        '伏安法选择：内接法R测=R真+R_A（偏大）适合大电阻；外接法R测=R真R_V/(R真+R_V)（偏小）适合小电阻。判据：R真>√(R_A·R_V)用内接，反之外接。',
        '滑动变阻器接法：①分压式（电压从0开始、要求电压范围大、R滑<<R待测时）②限流式（节能、简单、电流不要求从0起）。',
        '实验三：测定电源电动势和内阻。方法一：伏安法（电流表+电压表+滑动变阻器），U=ε-Ir→U-I图纵截距ε、斜率绝对值r。方法二：安阻法（电流表+电阻箱）。方法三：伏阻法（电压表+电阻箱）。',
        '内阻测量误差：电流表内接→ε测=ε真，r测=r真+R_A（偏大）；电流表外接→ε测<ε真，r测<r真（偏小）。实际作图法误差已包含在内。',
        '实验四：多用电表使用。①电压档（并联被测）②电流档（串联被测）③电阻档（黑笔接内部电源正极，红笔接负极）。电阻档每次换档要重新欧姆调零。测量时断电、隔离被测电路。',
        '实验五：电表改装。①电流表改装电压表：串联大电阻R=(U/Ig)-Rg。②电流表扩大量程：并联小电阻R=IgRg/(I-Ig)。③校准：与标准表对比，画校准曲线。',
        '二极管特性：单向导电性。正向偏置（P接正N接负）导通，反向偏置截止。正向电阻小反向电阻大。',
        '传感器：将非电信号转为电信号。①热敏电阻（温度→电阻，NTC温度升高电阻减小）②光敏电阻（光强→电阻，光照越强电阻越小）③金属热电阻（温度升高电阻增大，线性好）④霍尔元件（磁感应强度→电压）⑤压力传感器、位移传感器、加速度传感器、光电传感器、温度传感器。',
        '传感器应用：①温度控制（热敏电阻+比较器+继电器）②光控开关（光敏电阻+逻辑电路）③称重（压力传感器）④速度测量（光电门）⑤加速度测量（智能手机）。',
        '数字电路：与门（全1出1）、或门（有1出1）、非门（0→1,1→0）、与非门、或非门。',
        '实验误差分析：电表内阻、接触电阻、读数误差、温度影响、电源内阻变化。减小误差：多次测量取平均、选合适量程、改进电路设计。'
    ]))
]

# ============== 化学 ==============
subjects['化学'] = [
    ('物质的量与化学计算', '阿伏加德罗常数陷阱与化学计算综合', c([
        '物质的量n=N/NA=m/M=V/Vm=cV。单位：摩尔mol。',
        '阿伏加德罗常数NA≈6.02×10^23/mol。注意：是每摩尔物质含有的基本单元数。',
        'NA题常见陷阱一：气体摩尔体积适用条件。①必须是气体②必须是标准状况（0℃/101kPa或273K/1atm）。标准状况下非气体：H2O、SO3、CCl4、苯、汽油、酒精、HF、CH2Cl2、CHCl3、NO2（部分二聚）、碳原子数大于4的烃。',
        '陷阱二：物质结构。①质子数/电子数/中子数计算（注意同位素H/D/T）②化学键数（SiO2中每个Si与4个O成键→含4mol Si-O键；金刚石/晶体硅中每个C/Si与4个成键；P4中6mol P-P键；S8中8mol S-S键；石墨中1.5mol C-C键；苯中无C=C双键是大π键）。',
        '陷阱三：电子转移。歧化反应（Cl2+H2O/NaOH→1mol Cl2转移1mol e）；归中反应；金属与酸/水反应（Na/Mg/Al失电子数由金属量计算）；电解CuCl2/NaCl/H2O；Fe/Cu与Fe3+反应（Fe+2Fe3+=3Fe2+转移2e）。',
        '陷阱四：弱电解质电离与盐的水解。弱酸弱碱不能完全电离；可水解的盐溶液中离子数目改变（Fe3+、Al3+、Cu2+、NH4+、CO3^2-、S2-、F-、CH3COO-）。',
        '陷阱五：溶液中的粒子数。未给溶液体积不能算物质的量；要区分溶质分子与溶剂水分子；胶体粒子是多个分子聚集体，1mol FeCl3水解得到的Fe(OH)3胶粒远小于NA。',
        '陷阱六：混合物极值法。如判断1mol NO与1mol O2反应后分子数→2NO+O2=2NO2但部分NO2二聚为N2O4，分子数小于2NA。',
        '陷阱七：反应的可逆性。可逆反应不能完全进行（合成氨、SO2与O2、H2+I2、酯化反应、弱酸弱碱电离）。',
        '陷阱八：特殊反应。Fe与冷浓硫酸/浓硝酸钝化；Fe足量与稀HNO3生成Fe2+；Fe不足生成Fe3+；常温下Cl2与NaOH反应生成Cl-和ClO-；加热生成Cl-和ClO3-。',
        '化学计算方法：①质量守恒（反应前后总质量不变；某元素质量守恒）②原子/离子守恒③电荷守恒（溶液中正负电荷总数相等）④得失电子守恒（氧化还原反应）⑤关系式法（多步反应找关系式）⑥差量法（质量差/体积差/物质的量差）⑦极值法（极端假设判断范围）⑧讨论法（分类讨论多解）⑨十字交叉法（二元混合物）。',
        '溶液pH计算：①强酸pH=-lgc(H+)②强碱先求c(OH-)再求pOH=14-pH③弱酸弱碱用Ka/Kb近似④酸碱混合先判断谁过量再计算⑤pH=a的强酸与pH=b的强碱等体积混合，若a+b=14则恰好中和；a+b>14碱过量；a+b<14酸过量。',
        '滴定计算：c标准V标准=c待测V待测。注意指示剂选择：强酸滴定强碱用甲基橙；强碱滴定强酸用酚酞。终点判断：最后一滴加入，指示剂颜色变化且半分钟不变。'
    ])),
    ('离子反应与氧化还原', '离子反应与氧化还原综合', c([
        '电解质：在水溶液或熔融状态下能导电的化合物。强电解质：强酸（HCl/HBr/HI/H2SO4/HNO3/HClO4）、强碱（NaOH/KOH/Ba(OH)2/Ca(OH)2）、大多数盐。弱电解质：弱酸、弱碱、水。',
        '非电解质：在水溶液和熔融状态下都不导电的化合物。如大多数有机物、某些非金属氧化物。',
        '离子方程式书写：①写（化学方程式）②拆（强电解质拆为离子）③删（删去左右相同离子）④查（电荷守恒、原子守恒）。',
        '不能拆的物质：弱电解质、难溶物、气体、氧化物、单质、浓硫酸（浓度大时）、非电解质。',
        '微溶物：作反应物时澄清溶液拆、浑浊不拆；作生成物时不拆。如Ca(OH)2、Ag2SO4、CaSO4、MgCO3。',
        '离子共存：①生成沉淀不能共存（AgCl/BaSO4/CaCO3/Fe(OH)3/Cu(OH)2等）②生成气体（CO2/SO2/NH3）③生成弱电解质（H2O、弱酸、弱碱）④发生氧化还原⑤发生双水解⑥发生络合反应（Fe3+与SCN-）。',
        '有色离子：Fe2+（浅绿）、Fe3+（黄/棕黄）、Cu2+（蓝）、MnO4-（紫）、Cr2O7^2-（橙）、CrO4^2-（黄）、Fe(SCN)3（血红）。',
        '酸性条件下不能共存的离子：OH-、CO3^2-、HCO3-、SO3^2-、HSO3-、S2-、HS-、ClO-、F-、CH3COO-、PO4^3-、H2PO4-、HPO4^2-、SiO3^2-、AlO2-、CN-。',
        '碱性条件下不能共存的离子：H+、Fe3+、Fe2+、Cu2+、Al3+、Mg2+、NH4+、HCO3-、HSO3-、HS-、H2PO4-、HPO4^2-。',
        '氧化还原离子对：①强氧化性：MnO4-（H+）、NO3-（H+）、ClO-、Fe3+、Cr2O7^2-（H+）、H2O2（H+）②强还原性：Fe2+、I-、S2-、SO3^2-、HSO3-、Br-。①+②可发生反应。特殊：Fe3+与Fe2+不反应；NO3-在中性/碱性无强氧化性。',
        '双水解：Al3+与CO3^2-/HCO3-/S2-/HS-/AlO2-/ClO-；Fe3+与CO3^2-/HCO3-/AlO2-/ClO-；NH4+与AlO2-/SiO3^2-。',
        '氧化还原概念：升失氧还→化合价升高、失去电子、被氧化（发生氧化反应）、作还原剂；降得还氧→化合价降低、得到电子、被还原（发生还原反应）、作氧化剂。',
        '常见氧化剂：活泼非金属（Cl2/O2/Br2/F2）、含高价元素的化合物（浓H2SO4/HNO3/KMnO4/K2Cr2O7/Fe3+/HClO/MnO2）、过氧化物（H2O2/Na2O2）。',
        '常见还原剂：活泼金属（K/Na/Mg/Al/Zn/Fe）、某些非金属（H2/C/S）、含低价元素的化合物（HI/HBr/H2S/SO2/Na2SO3/Na2S2O3/Fe2+/C/CO）。',
        '氧化性还原性强弱判断：①根据反应方程式（氧化剂>氧化产物；还原剂>还原产物）②根据活动性顺序③根据反应条件（是否加热、浓度大小）④根据反应剧烈程度⑤根据原电池电解池⑥根据元素周期律。',
        '氧化还原反应配平：标价→列变→求最小公倍数→配系数→检验（原子守恒电荷守恒）。',
        '离子方程式正误判断：①事实（反应是否能发生、产物是否正确）②拆分（强弱电解质）③守恒（电荷原子）④配比（如Ba(OH)2与H2SO4，Ba2++2OH-+2H++SO4^2-=BaSO4↓+2H2O）⑤量的关系（过量/少量）。',
        '与量有关的离子方程式：①Al3+与NaOH（少量NaOH生成Al(OH)3；过量生成AlO2-）②Fe与稀HNO3（少量Fe生成Fe3+；过量Fe生成Fe2+）③Na2CO3与HCl（逐滴加入先生成HCO3-再生成CO2）④Ca(OH)2与NaHCO3（Ca(OH)2少量/过量不同）⑤Cl2与FeBr2（少量Cl2先氧化Fe2+；过量两者都氧化）。',
        '陌生氧化还原反应：根据化合价升降规律判断产物、根据介质判断H+/OH-/H2O的存在。'
    ])),
    ('物质结构元素周期律', '元素推断与化学键', c([
        '原子结构：原子核（质子Z+中子N）+核外电子。质量数A=Z+N。',
        '核素：具有一定质子和中子数的原子。同位素：同元素不同核素（同Z不同N）。',
        '核外电子排布规律：①能量最低②每层最多2n²③最外层≤8④次外层≤18⑤倒数第三层≤32。',
        '电子式书写：①原子（元素符号+点/×标最外层电子）②离子化合物（阳离子直接写、阴离子加括号标电荷）③共价化合物（共用电子对）④注意孤对电子不要漏写（NH3/N2/H2O等）。',
        '元素周期表：7个周期（短1-3、长4-7），16个族（7主族7副族+VIII族+0族）。周期数=电子层数；主族序数=最外层电子数。',
        '分区：s区（IA、IIA）、p区（IIIA-VIIA、0族）、d区（IIIB-VIII）、ds区（IB、IIB）、f区（镧系、锕系）。',
        '周期律：①原子半径（同周期从左到右减小；同主族从上到下增大）②金属性非金属性（同周期左→右金属性减弱非金属性增强；同主族上→下金属性增强非金属性减弱）③最高价氧化物对应水化物酸碱性（金属性越强碱性越强；非金属性越强酸性越强）④氢化物稳定性（非金属性越强越稳定）⑤第一电离能（总体增大趋势，IIA、VA反常）⑥电负性（同周期增大、同主族减小）。',
        '金属性强弱判断：①与水/酸反应剧烈程度②最高价氧化物水化物碱性③置换反应④阳离子氧化性（越弱金属性越强）⑤原电池负极金属性强。',
        '非金属性强弱判断：①与H2化合难易②氢化物稳定性③最高价氧化物水化物酸性④置换反应⑤阴离子还原性（越弱非金属性越强）。',
        '元素推断突破口：①周期表位置关系②原子序数关系③特殊结构（最外层电子数=次外层/最内层/电子层数等）④特殊含量（地壳中O>Si>Al>Fe；空气中N>O；人体中O>C>H）⑤特殊性质（半导体Si、Ge；两性Al/Be；形成化合物种类最多C；最活泼非金属F；最强碱Cs；常温液态金属Hg/非金属Br2）。',
        '常见10电子微粒：分子（Ne/HF/H2O/NH3/CH4）；阳离子（Na+/Mg2+/Al3+/NH4+/H3O+）；阴离子（F-/O2-/N3-/OH-/NH2-）。',
        '常见18电子微粒：分子（Ar/HCl/H2S/PH3/SiH4/F2/H2O2/N2H4/C2H6/CH3OH/CH3F/CH3NH2）；阳离子（K+/Ca2+）；阴离子（Cl-/S2-/HS-/O2^2-/P3-）。',
        '化学键：①离子键（阴阳离子静电作用，活泼金属与活泼非金属）②共价键（共用电子对，非金属之间）③金属键（金属阳离子与自由电子）。',
        '共价键分类：①极性键（不同原子间电子对偏移）②非极性键（相同原子间）③配位键（一方提供孤对电子另一方提供空轨道形成）。',
        'σ键与π键：单键都是σ；双键一个σ一个π；三键一个σ两个π。σ键头碰头π键肩并肩。',
        '键参数：键能（越大越稳定）、键长（越短越稳定）、键角（决定空间结构）。',
        '电子式常见错误：①漏写孤对电子②离子键加③共价键不加括号④电荷与化合价混淆⑤未满足8电子稳定结构（H为2、B为6、P可10、S可12等例外）。',
        '等电子体：原子总数相同、价电子总数相同。具有相似结构和性质。CO/N2；CO2/N2O/CS2/SCN-；SO3/NO3-/BF3；SO2/O3；PO4^3-/SO4^2-/ClO4-；P4/CH4。'
    ])),
    ('化学反应原理', '反应热速率平衡综合', c([
        '反应热（焓变）：ΔH=生成物总能量-反应物总能量。ΔH<0放热；ΔH>0吸热。单位kJ/mol。',
        '常见放热：燃烧、中和、金属与酸、大多数化合、自发氧化还原。常见吸热：大多数分解、C+CO2、C+H2O(g)、Ba(OH)2·8H2O+NH4Cl、水解。',
        '热化学方程式书写：①注明状态（s/l/g/aq）②ΔH数值与系数对应③注明温度压强（常温常压可不）④ΔH正负号不能省略。',
        '燃烧热：1mol纯物质完全燃烧生成稳定氧化物放出的热量。H→H2O(l)、C→CO2(g)、S→SO2(g)、N→N2(g)。',
        '中和热：强酸强碱稀溶液生成1mol H2O的反应热。ΔH=-57.3kJ/mol。弱酸弱碱电离吸热使数值偏小；浓溶液放热更多。',
        '盖斯定律：反应热只与始态终态有关，与路径无关。多步反应ΔH相加。',
        '反应速率：v=Δc/Δt。单位mol/(L·s)或mol/(L·min)。不同物质速率比=系数比。',
        '影响因素：①浓度（增大速率增大；固体/纯液体浓度不变无影响）②温度（升温速率增大）③压强（气体反应，加压等效于浓缩）④催化剂（降低活化能显著增大正逆速率）⑤其他（光照/电磁波/超声波/溶剂/反应物接触面积）。',
        '活化能Ea：活化分子平均能量-反应物平均能量。催化剂降低Ea。',
        '化学平衡标志：①v正=v逆（同一物质消耗速率=生成速率；不同物质速率比=系数比但方向相反）②各物质浓度/质量/体积分数/物质的量分数不变③颜色不变（有颜色物质）④密度/平均分子量等视情况。',
        '平衡移动：勒夏特列原理。改变条件平衡向减弱这种改变的方向移动。',
        '影响平衡的因素：①浓度（增大反应物或减小生成物→正向）②温度（升温→吸热方向）③压强（加压→气体体积减小方向；等体反应不移动）④催化剂（同等改变正逆速率不移动）。',
        '平衡常数：K=生成物浓度幂/反应物浓度幂。只与温度有关。K越大正向进行程度越大。',
        '平衡常数书写：①固体/纯液体不写入②系数为幂③逆向反应K\'=1/K④反应加倍K\'=K^n。',
        '平衡三段式：起/始/转/变/平/衡。设变化量为x，根据系数关系求各物质平衡浓度。',
        '平衡转化率：α=已反应/初始×100%。注意：两种反应物增加一种浓度，另一种转化率增大而自身转化率减小。',
        '平衡判断：①浓度商Q<K→正向②Q=K→平衡③Q>K→逆向。',
        '等效平衡：恒温恒容等体积反应→等效转化后各物质起始量相同则等效；恒温恒容不等体积→各物质起始量相同才全等；恒温恒压→等效转化后比例相同即等效。',
        '反应方向判断：ΔH<0有利于自发；ΔS>0有利于自发。综合判据ΔG=ΔH-TΔS<0则自发。',
        '平衡图像分析：①v-t图（浓度变化、温度变化、压强变化、催化剂影响）②n-t/c-t图（拐点先到先平衡说明温度高压强大）③平衡移动图（坐标含T/P时作辅助线判断）。'
    ])),
    ('水溶液离子平衡', '三大守恒与离子浓度大小比较', c([
        '电解质溶液：①强电解质完全电离②弱电解质部分电离，存在电离平衡③可水解的盐促进水电离④酸碱抑制水电离。',
        '水的电离：H2O⇌H++OH-。Kw=c(H+)·c(OH-)=10^-14（25℃），10^-12（100℃）。Kw只与温度有关。',
        'pH=-lgc(H+)；pOH=-lgc(OH-)；pH+pOH=14（25℃）。',
        '电离平衡常数：弱酸HA⇌H++A-，Ka=c(H+)·c(A-)/c(HA)；弱碱BOH⇌B++OH-，Kb=c(B+)·c(OH-)/c(BOH)。Ka/Kb越大越强。',
        '盐类水解：有弱才水解，越弱越水解，谁强显谁性，都强显中性。',
        '水解规律：①强酸强碱盐（NaCl/KNO3）→中性②强酸弱碱盐（NH4Cl/AlCl3/CuSO4）→酸性③强碱弱酸盐（CH3COONa/Na2CO3/NaF）→碱性④弱酸弱碱盐→看阴阳离子水解程度相对强弱。',
        '多元弱酸根分步水解，第一步为主。Na2CO3水解：CO3^2-+H2O⇌HCO3-+OH-（主）；HCO3-+H2O⇌H2CO3+OH-（次）。',
        '水解影响因素：①升温促进水解②稀释促进水解（浓度减小水解程度增大）③加入酸碱抑制或促进。',
        '离子浓度大小比较：单一溶液→先判断溶质再分析电离水解主次。',
        'Na2CO3溶液：c(Na+)>c(CO3^2-)>c(OH-)>c(HCO3-)>c(H+)。',
        'NaHCO3溶液：水解>电离→碱性，c(Na+)>c(HCO3-)>c(OH-)>c(H+)>c(CO3^2-)。',
        'CH3COONa溶液：c(Na+)>c(CH3COO-)>c(OH-)>c(H+)。',
        'NH4Cl溶液：c(Cl-)>c(NH4+)>c(H+)>c(OH-)。',
        '混合溶液：①先看是否反应②判断最终溶质及浓度③比较电离与水解谁为主④NH3·H2O与NH4Cl等浓度混合→电离>水解→碱性；CH3COOH与CH3COONa等浓度→电离>水解→酸性；HCN与NaCN等浓度→水解>电离→碱性。',
        '三大守恒：①电荷守恒（正负电荷总数相等，