# Generated by Django 4.2.16 on 2026-03-07 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, help_text='用于诊断缓存的代码哈希值', max_length=64, verbose_name='代码哈希')),
                ('error_type', models.CharField(blank=True, help_text='Python错误类型（如NameError）', max_length=50, null=True, verbose_name='错误类型')),
                ('diagnosis_text', models.TextField(help_text='LLM或模板生成的诊断建议', verbose_name='诊断内容')),
                ('source', models.CharField(choices=[('llm', 'LLM生成'), ('template', '规则模板'), ('cache', '缓存命中')], db_index=True, default='template', max_length=20, verbose_name='诊断来源')),
                ('latency_ms', models.IntegerField(default=0, help_text='诊断生成耗时（毫秒）', verbose_name='响应延迟(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='problems.problem', verbose_name='关联题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL, verbose_name='关联学生')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='submissions.submission', verbose_name='关联提交')),
            ],
            options={
                'verbose_name': '诊断记录',
                'verbose_name_plural': '诊断记录',
                'db_table': 'diagnosis_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['problem', 'error_type', '-created_at'], name='diagnosis_r_problem_2a7645_idx'), models.Index(fields=['student', 'problem', '-created_at'], name='diagnosis_r_student_a2efef_idx'), models.Index(fields=['code_hash', 'error_type'], name='diagnosis_r_code_ha_2689b4_idx')],
            },
        ),
    ]
