# Generated by Django 4.2.16 on 2026-03-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='diagnosis_payload',
            field=models.TextField(blank=True, help_text='JSON格式的结构化诊断结果', null=True, verbose_name='结构化诊断数据'),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='error_message',
            field=models.TextField(blank=True, help_text='诊断失败时的错误信息', null=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='model_name',
            field=models.CharField(blank=True, help_text='如qwen2.5-coder:7b', max_length=100, null=True, verbose_name='模型名称'),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='prompt_version',
            field=models.CharField(blank=True, help_text='用于论文实验复现', max_length=20, null=True, verbose_name='Prompt版本'),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='provider',
            field=models.CharField(blank=True, help_text='如ollama、openai等', max_length=50, null=True, verbose_name='LLM提供商'),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='schema_version',
            field=models.CharField(blank=True, help_text='诊断输出结构版本', max_length=20, null=True, verbose_name='Schema版本'),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待诊断'), ('processing', '诊断中'), ('success', '成功'), ('fallback', '降级'), ('failed', '失败')], db_index=True, default='pending', max_length=20, verbose_name='诊断状态'),
        ),
    ]
