tunnel: 0b0cfb87-3373-4154-a4c8-d82c0ec3d0a9
credentials-file: /Users/inftorc/Desktop/cloudonline/cloud-platform/credentials/cloud-platform.json
protocol: http2

ingress:
  - hostname: cloud.daodun.xyz
    service: http://localhost:8800
  - service: http_status:404
