services:
  - type: web
    name: kindchat
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: PORT
        value: 10000
    plan: free