# Generated by Django 5.2.15 on 2026-06-29 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scene_id", models.IntegerField(verbose_name="场景编号")),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("narration", models.TextField(verbose_name="旁白")),
                ("dialogue", models.TextField(verbose_name="对话")),
            ],
            options={
                "verbose_name": "剧情场景",
                "verbose_name_plural": "剧情场景",
                "ordering": ["theme", "scene_id"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=50, unique=True, verbose_name="标识符"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="名称")),
                ("emoji", models.CharField(max_length=10, verbose_name="图标")),
                ("tag", models.CharField(max_length=50, verbose_name="标签")),
                ("desc", models.TextField(verbose_name="描述")),
                ("duration", models.CharField(max_length=20, verbose_name="时长")),
                ("image", models.CharField(max_length=100, verbose_name="图片路径")),
                (
                    "card_title",
                    models.CharField(max_length=100, verbose_name="卡片标题"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "非遗主题",
                "verbose_name_plural": "非遗主题",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="选项文本")),
                ("next_scene_id", models.IntegerField(verbose_name="下一场景编号")),
                ("letter", models.CharField(max_length=1, verbose_name="选项字母")),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="theater.scene",
                        verbose_name="所属场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "分支选项",
                "verbose_name_plural": "分支选项",
                "ordering": ["scene", "letter"],
            },
        ),
        migrations.AddField(
            model_name="scene",
            name="theme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenes",
                to="theater.theme",
                verbose_name="所属主题",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scene",
            unique_together={("theme", "scene_id")},
        ),
        migrations.CreateModel(
            name="CardSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_key", models.CharField(max_length=10, verbose_name="路径键")),
                ("summary", models.TextField(verbose_name="摘要文本")),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_summaries",
                        to="theater.theme",
                        verbose_name="所属主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "卡片摘要",
                "verbose_name_plural": "卡片摘要",
                "unique_together": {("theme", "path_key")},
            },
        ),
    ]
