# Generated by Django 4.2 on 2026-01-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单原价')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际支付价格')),
                ('product_info', models.JSONField(verbose_name='购买商品信息')),
                ('payment_method', models.SmallIntegerField(choices=[(1, '微信'), (2, '校园卡'), (3, '支付宝')], verbose_name='支付方式')),
                ('payment_status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '支付成功'), (2, '已退款')], default=0, verbose_name='支付状态')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='物流单号')),
                ('logistics_status', models.JSONField(blank=True, null=True, verbose_name='物流状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('arrive_time', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics', to='order.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '物流信息表',
                'verbose_name_plural': '物流信息表',
                'db_table': 'logistics',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='商品数量')),
                ('is_selected', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否选中')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.product', verbose_name='关联商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '购物车表',
                'verbose_name_plural': '购物车表',
                'db_table': 'shopping_cart',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
