import { User, CurrentUser } from '../types';

// 模拟用户库
export const mockUsers: User[] = [
  {
    id: 'u1',
    name: '机车小王子',
    age: 28,
    gender: 'male',
    avatar: '',
    bio: '热爱风和自由，周末必骑。川藏线已打卡，下一个目标：独库公路！',
    interests: ['t1', 't23', 't16', 't19'],
    location: '成都',
    occupation: '自由摄影师',
    matchCount: 156,
  },
  {
    id: 'u2',
    name: '麻将少女',
    age: 25,
    gender: 'female',
    avatar: '',
    bio: '周末三缺一喊我！清一色杠上开花是我的最爱~ 也喜欢下厨做点小菜。',
    interests: ['t11', 't24', 't25', 't13'],
    location: '重庆',
    occupation: 'UI设计师',
    matchCount: 203,
  },
  {
    id: 'u3',
    name: '追风骑士',
    age: 30,
    gender: 'male',
    avatar: '',
    bio: '哈雷爱好者，也喜欢周末约朋友打麻将喝啤酒。认为人生就该自由自在。',
    interests: ['t1', 't11', 't12', 't26'],
    location: '北京',
    occupation: '创业公司CEO',
    matchCount: 189,
  },
  {
    id: 'u4',
    name: '山野旅人',
    age: 26,
    gender: 'female',
    avatar: '',
    bio: '背包客一枚，喜欢登山露营，也爱读书和摄影。理想生活是边旅行边工作。',
    interests: ['t9', 't16', 't17', 't19', 't23'],
    location: '大理',
    occupation: '自由撰稿人',
    matchCount: 178,
  },
  {
    id: 'u5',
    name: '健身达人Kevin',
    age: 27,
    gender: 'male',
    avatar: '',
    bio: '健身5年老炮儿，最近迷上了瑜伽和骑行。自律即自由！',
    interests: ['t4', 't2', 't8', 't5'],
    location: '上海',
    occupation: '健身教练',
    matchCount: 312,
  },
  {
    id: 'u6',
    name: '麻神理工学姐',
    age: 29,
    gender: 'female',
    avatar: '',
    bio: '工作中是严肃的算法工程师，牌桌上是大杀四方的麻神。也爱骑摩托兜风~',
    interests: ['t11', 't1', 't31', 't33', 't30'],
    location: '深圳',
    occupation: '算法工程师',
    matchCount: 145,
  },
  {
    id: 'u7',
    name: '音符流浪者',
    age: 24,
    gender: 'male',
    avatar: '',
    bio: '吉他弹唱、路边演出、音乐节常客。最近在学习烘焙，想给喜欢的人做甜点。',
    interests: ['t21', 't14', 't27', 't26'],
    location: '杭州',
    occupation: '独立音乐人',
    matchCount: 221,
  },
  {
    id: 'u8',
    name: '喵星驻京办',
    age: 26,
    gender: 'female',
    avatar: '',
    bio: '家里三只猫主子的铲屎官。喜欢瑜伽、画画，周末偶尔搓两圈麻将。',
    interests: ['t28', 't8', 't20', 't11'],
    location: '北京',
    occupation: '宠物医生',
    matchCount: 167,
  },
  {
    id: 'u9',
    name: '代码诗人',
    age: 31,
    gender: 'male',
    avatar: '',
    bio: '全栈工程师，热爱开源。业余喜欢骑摩托车跑山，打打篮球，看看动漫。',
    interests: ['t31', 't1', 't5', 't32', 't33'],
    location: '广州',
    occupation: '全栈工程师',
    matchCount: 134,
  },
  {
    id: 'u10',
    name: '厨房里的冒险家',
    age: 27,
    gender: 'female',
    avatar: '',
    bio: '美食就是我的诗和远方！擅长川菜粤菜，最近在研究咖啡拉花。也爱摄影记录美食。',
    interests: ['t24', 't25', 't26', 't19'],
    location: '成都',
    occupation: '美食博主',
    matchCount: 289,
  },
  {
    id: 'u11',
    name: '雪豹突击队',
    age: 29,
    gender: 'male',
    avatar: '',
    bio: '冬天滑雪，夏天骑摩托，秋天登山，春天跑步。一年四季都在路上！',
    interests: ['t10', 't1', 't9', 't3'],
    location: '哈尔滨',
    occupation: '体育老师',
    matchCount: 198,
  },
  {
    id: 'u12',
    name: '书海浮萍',
    age: 25,
    gender: 'female',
    avatar: '',
    bio: '一个月至少读4本书，偏爱文学和哲学。也喜欢书法和古琴，周末有空搓麻将。',
    interests: ['t17', 't22', 't21', 't11'],
    location: '南京',
    occupation: '语文教师',
    matchCount: 145,
  },
];

// 当前用户模拟
export const mockCurrentUser: CurrentUser = {
  id: 'me',
  name: '骑行探索者',
  age: 26,
  gender: 'male',
  avatar: '',
  bio: '热爱生活，喜欢骑行看世界，偶尔约朋友搓麻将。期待遇到志同道合的伙伴！',
  interests: ['t2', 't11', 't19', 't23', 't26'],
  location: '杭州',
  occupation: '产品经理',
  email: 'rider@example.com',
  matchCount: 0,
};

// 头像色板
const avatarColors = [
  '#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4',
  '#FFEAA7', '#DDA0DD', '#98D8C8', '#F7DC6F',
  '#BB8FCE', '#85C1E9', '#F8C471', '#82E0AA',
];

export function getAvatarColor(index: number): string {
  return avatarColors[index % avatarColors.length];
}

export function getInitials(name: string): string {
  return name.slice(0, 2);
}
