package dao.impl;
import bean.*;
import dao.*;
import util.JDBCUtil;
import java.sql.*;
import java.util.*;

public class PathologyExamOrderDAOImpl implements PathologyExamOrderDAO {
    private <T> List<T> queryList(String sql, java.util.function.Function<ResultSet,T> mapper, Object... params) {
        List<T> list = new ArrayList<>();
        try (JDBCUtil.QueryResult qr = JDBCUtil.executeQuery(sql, params)) { ResultSet rs = qr.getResultSet(); while(rs.next()) list.add(mapper.apply(rs)); } catch(Exception e){ e.printStackTrace(); }
        return list;
    }
    @Override public int insert(PathologyExamOrder o){return JDBCUtil.executeInsert("INSERT INTO pathology_exam_order(pathology_no,patient_id,patient_name,medical_record_no,admission_no,doctor_id,doctor_name,dept_id,dept_name,specimen_source,specimen_type,specimen_site,clinical_diagnosis,surgery_info,clinical_history,status,gross_description,microscopic_description,pathology_diagnosis,immunohistochemistry,molecular_test,pathologist_id,pathologist_name,report_time,is_urgent,urgent_result,total_amount)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",o.getPathologyNo(),o.getPatientId(),o.getPatientName(),o.getMedicalRecordNo(),o.getAdmissionNo(),o.getDoctorId(),o.getDoctorName(),o.getDeptId(),o.getDeptName(),o.getSpecimenSource(),o.getSpecimenType(),o.getSpecimenSite(),o.getClinicalDiagnosis(),o.getSurgeryInfo(),o.getClinicalHistory(),o.getStatus(),o.getGrossDescription(),o.getMicroscopicDescription(),o.getPathologyDiagnosis(),o.getImmunohistochemistry(),o.getMolecularTest(),o.getPathologistId(),o.getPathologistName(),o.getReportTime(),o.getIsUrgent(),o.getUrgentResult(),o.getTotalAmount());}
    @Override public int update(PathologyExamOrder o){return JDBCUtil.executeUpdate("UPDATE pathology_exam_order SET status=?,gross_description=?,microscopic_description=?,pathology_diagnosis=?,immunohistochemistry=?,molecular_test=?,pathologist_id=?,pathologist_name=?,report_time=?WHERE id=?",o.getStatus(),o.getGrossDescription(),o.getMicroscopicDescription(),o.getPathologyDiagnosis(),o.getImmunohistochemistry(),o.getMolecularTest(),o.getPathologistId(),o.getPathologistName(),o.getReportTime(),o.getId());}
    @Override public PathologyExamOrder findById(int id){List<PathologyExamOrder>l=queryList("SELECT*FROM pathology_exam_order WHERE id=?",this::mapPEO,id);return l.isEmpty()?null:l.get(0);}
    @Override public List<PathologyExamOrder> findPathologyByPatientId(int patientId){return queryList("SELECT*FROM pathology_exam_order WHERE patient_id=?ORDER BY create_time DESC",this::mapPEO,patientId);}
    @Override public List<PathologyExamOrder> findPathologies(String status,int page,int size){String sql="SELECT*FROM pathology_exam_order WHERE 1=1";List<Object>params=new ArrayList<>();if(status!=null&&!status.isEmpty()){sql+=" AND status=?";params.add(status);}sql+=" ORDER BY create_time DESC LIMIT ?,?";params.add((page-1)*size);params.add(size);return queryList(sql,this::mapPEO,params.toArray(new Object[0]));}
    private PathologyExamOrder mapPEO(ResultSet rs){try{PathologyExamOrder o=new PathologyExamOrder();o.setId(rs.getInt("id"));o.setPathologyNo(rs.getString("pathology_no"));o.setPatientId(rs.getInt("patient_id"));o.setPatientName(rs.getString("patient_name"));o.setMedicalRecordNo(rs.getString("medical_record_no"));o.setAdmissionNo(rs.getString("admission_no"));o.setDoctorId(rs.getInt("doctor_id"));o.setDoctorName(rs.getString("doctor_name"));o.setDeptId(rs.getInt("dept_id"));o.setDeptName(rs.getString("dept_name"));o.setSpecimenSource(rs.getString("specimen_source"));o.setSpecimenType(rs.getString("specimen_type"));o.setSpecimenSite(rs.getString("specimen_site"));o.setClinicalDiagnosis(rs.getString("clinical_diagnosis"));o.setSurgeryInfo(rs.getString("surgery_info"));o.setClinicalHistory(rs.getString("clinical_history"));o.setStatus(rs.getString("status"));o.setGrossDescription(rs.getString("gross_description"));o.setMicroscopicDescription(rs.getString("microscopic_description"));o.setPathologyDiagnosis(rs.getString("pathway_diagnosis"));o.setImmunohistochemistry(rs.getString("immunohistochemistry"));o.setMolecularTest(rs.getString("molecular_test"));if(rs.getObject("pathologist_id")!=null)o.setPathologistId(rs.getInt("pathologist_id"));o.setPathologistName(rs.getString("pathologist_name"));o.setReportTime(rs.getTimestamp("report_time"));o.setIsUrgent(rs.getInt("is_urgent"));o.setUrgentResult(rs.getString("urgent_result"));o.setTotalAmount(rs.getBigDecimal("total_amount"));o.setCreateTime(rs.getTimestamp("create_time"));o.setUpdateTime(rs.getTimestamp("update_time"));return o;}catch(SQLException e){return null;}}
}
