package dao.impl;
import bean.AdverseEvent;
import dao.AdverseEventDAO;
import util.JDBCUtil;
import java.sql.*;
import java.util.*;

public class AdverseEventDAOImpl implements AdverseEventDAO {
    private <T> List<T> queryList(String sql, java.util.function.Function<ResultSet,T> mapper, Object... params) {
        List<T> list = new ArrayList<>();
        try (JDBCUtil.QueryResult qr = JDBCUtil.executeQuery(sql, params)) { ResultSet rs = qr.getResultSet(); while(rs.next()) list.add(mapper.apply(rs)); } catch(Exception e){ e.printStackTrace(); }
        return list;
    }
    @Override public int insert(AdverseEvent e){return JDBCUtil.executeInsert("INSERT INTO adverse_event(event_no,event_type,event_level,occur_time,occur_location,dept_id,dept_name,patient_id,patient_name,medical_record_no,admission_no,involved_staff_ids,involved_staff_names,event_description,immediate_action,reporter_id,reporter_name,status,tracking_status)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",e.getEventNo(),e.getEventType(),e.getEventLevel(),e.getOccurTime(),e.getOccurLocation(),e.getDeptId(),e.getDeptName(),e.getPatientId(),e.getPatientName(),e.getMedicalRecordNo(),e.getAdmissionNo(),e.getInvolvedStaffIds(),e.getInvolvedStaffNames(),e.getEventDescription(),e.getImmediateAction(),e.getReporterId(),e.getReporterName(),e.getStatus(),e.getTrackingStatus());}
    @Override public int update(AdverseEvent e){return JDBCUtil.executeUpdate("UPDATE adverse_event SET root_cause_analysis=?,reviewer_id=?,reviewer_name=?,review_time=?,review_result=?,improvement_plan=?,tracking_status=?,status=?WHERE id=?",e.getRootCauseAnalysis(),e.getReviewerId(),e.getReviewerName(),e.getReviewTime(),e.getReviewResult(),e.getImprovementPlan(),e.getTrackingStatus(),e.getStatus(),e.getId());}
    @Override public AdverseEvent findById(int id){List<AdverseEvent>l=queryList("SELECT*FROM adverse_event WHERE id=?",this::mapAE,id);return l.isEmpty()?null:l.get(0);}
    @Override public List<AdverseEvent> findByDeptId(int deptId){return queryList("SELECT*FROM adverse_event WHERE dept_id=?ORDER BY occur_time DESC",this::mapAE,deptId);}
    @Override public List<AdverseEvent> findEvents(String eventType,String status,int page,int size){String sql="SELECT*FROM adverse_event WHERE 1=1";List<Object>params=new ArrayList<>();if(eventType!=null&&!eventType.isEmpty()){sql+=" AND event_type=?";params.add(eventType);}if(status!=null&&!status.isEmpty()){sql+=" AND status=?";params.add(status);}sql+=" ORDER BY occur_time DESC LIMIT ?,?";params.add((page-1)*size);params.add(size);return queryList(sql,this::mapAE,params.toArray(new Object[0]));}
    private AdverseEvent mapAE(ResultSet rs){try{AdverseEvent e=new AdverseEvent();e.setId(rs.getInt("id"));e.setEventNo(rs.getString("event_no"));e.setEventType(rs.getString("event_type"));e.setEventLevel(rs.getString("event_level"));e.setOccurTime(rs.getTimestamp("occur_time"));e.setOccurLocation(rs.getString("occur_location"));e.setDeptId(rs.getInt("dept_id"));e.setDeptName(rs.getString("dept_name"));if(rs.getObject("patient_id")!=null)e.setPatientId(rs.getInt("patient_id"));e.setPatientName(rs.getString("patient_name"));e.setMedicalRecordNo(rs.getString("medical_record_no"));e.setAdmissionNo(rs.getString("admission_no"));e.setInvolvedStaffIds(rs.getString("involved_staff_ids"));e.setInvolvedStaffNames(rs.getString("involved_staff_names"));e.setEventDescription(rs.getString("event_description"));e.setImmediateAction(rs.getString("immediate_action"));e.setRootCauseAnalysis(rs.getString("root_cause_analysis"));e.setReporterId(rs.getInt("reporter_id"));e.setReporterName(rs.getString("reporter_name"));e.setReportTime(rs.getTimestamp("report_time"));if(rs.getObject("reviewer_id")!=null)e.setReviewerId(rs.getInt("reviewer_id"));e.setReviewerName(rs.getString("reviewer_name"));e.setReviewTime(rs.getTimestamp("review_time"));e.setReviewResult(rs.getString("review_result"));e.setImprovementPlan(rs.getString("improvement_plan"));e.setTrackingStatus(rs.getString("tracking_status"));e.setStatus(rs.getString("status"));e.setIsHidden(rs.getInt("is_hidden"));e.setCreateTime(rs.getTimestamp("create_time"));e.setUpdateTime(rs.getTimestamp("update_time"));return e;}catch(SQLException ex){return null;}}
}
