# Generated by Django 4.2.16 on 2026-03-09 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：2024级计算机1班', max_length=100, verbose_name='班级名称')),
                ('description', models.TextField(blank=True, help_text='班级的详细说明', null=True, verbose_name='班级描述')),
                ('academic_year', models.CharField(blank=True, help_text='例如：2024-2025', max_length=20, null=True, verbose_name='学年')),
                ('semester', models.CharField(blank=True, help_text='例如：第一学期', max_length=20, null=True, verbose_name='学期')),
                ('is_active', models.BooleanField(default=True, help_text='未激活的班级不会在前端显示', verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='任课教师')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'class',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='teacher.class', verbose_name='班级')),
                ('student', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '班级学生',
                'verbose_name_plural': '班级学生',
                'db_table': 'class_student',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['class_obj', 'student'], name='class_stude_class_o_a465a6_idx')],
                'unique_together': {('class_obj', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['teacher', 'is_active'], name='class_teacher_1641d4_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year', 'semester'], name='class_academi_8e21d5_idx'),
        ),
    ]
