# Generated by Django 4.2.16 on 2026-03-10 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='作业的简短标题', max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(blank=True, help_text='作业的详细说明', null=True, verbose_name='作业描述')),
                ('deadline', models.DateTimeField(blank=True, help_text='作业提交截止日期', null=True, verbose_name='截止时间')),
                ('instructions', models.TextField(blank=True, help_text='详细的作业要求和说明', null=True, verbose_name='作业说明')),
                ('is_published', models.BooleanField(default=False, help_text='只有发布的作业学生才能看到', verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'assignment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='TEMP', help_text='学生通过此代码加入班级', max_length=20, unique=True, verbose_name='班级代码'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['code'], name='class_code_acfb48_idx'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='创建教师'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='problems',
            field=models.ManyToManyField(help_text='作业包含的题目列表', related_name='assignments', to='problems.problem', verbose_name='关联题目'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['class_obj', 'is_published'], name='assignment_class_o_048781_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by', '-created_at'], name='assignment_created_03fb7e_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['deadline'], name='assignment_deadlin_b87611_idx'),
        ),
    ]
