# Generated by Django 4.2.16 on 2026-03-11 14:16

import apps.teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assignment_class_code_class_class_code_acfb48_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default=apps.teacher.models.generate_class_code, help_text='学生通过此代码加入班级', max_length=20, unique=True, verbose_name='班级代码'),
        ),
    ]
