# Generated by Django 4.2.16 on 2026-03-07 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.TextField(help_text='学生提交的Python代码', verbose_name='提交代码')),
                ('run_status', models.CharField(choices=[('pending', '待运行'), ('success', '运行成功'), ('fail', '测试失败'), ('error', '运行错误')], db_index=True, default='pending', max_length=20, verbose_name='运行状态')),
                ('score', models.IntegerField(default=0, help_text='测试用例通过率得分（0-100）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='得分')),
                ('stdout_text', models.TextField(blank=True, help_text='程序运行的标准输出内容', null=True, verbose_name='标准输出')),
                ('error_type', models.CharField(blank=True, help_text='Python错误类型（如NameError）', max_length=50, null=True, verbose_name='错误类型')),
                ('error_trace', models.TextField(blank=True, help_text='完整的错误堆栈信息', null=True, verbose_name='错误堆栈')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='problems.problem', verbose_name='关联题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交学生')),
            ],
            options={
                'verbose_name': '代码提交记录',
                'verbose_name_plural': '代码提交记录',
                'db_table': 'submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'problem', '-created_at'], name='submission_student_981492_idx'), models.Index(fields=['problem', 'run_status'], name='submission_problem_1eeab7_idx')],
            },
        ),
    ]
