# Generated by Django 4.2.16 on 2026-03-09 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, default='', help_text='教师对代码的评价和建议', verbose_name='教师评语'),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_score',
            field=models.IntegerField(blank=True, help_text='教师给出的评分（0-100）', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='教师评分'),
        ),
    ]
