package dao.impl;
import bean.BloodTransfusionOrder;
import dao.BloodTransfusionOrderDAO;
import util.JDBCUtil;
import java.sql.*;
import java.util.*;

public class BloodTransfusionOrderDAOImpl implements BloodTransfusionOrderDAO {
    private <T> List<T> queryList(String sql, java.util.function.Function<ResultSet,T> mapper, Object... params) {
        List<T> list = new ArrayList<>();
        try (JDBCUtil.QueryResult qr = JDBCUtil.executeQuery(sql, params)) { ResultSet rs = qr.getResultSet(); while(rs.next()) list.add(mapper.apply(rs)); } catch(Exception e){ e.printStackTrace(); }
        return list;
    }
    @Override public int insert(BloodTransfusionOrder o){return JDBCUtil.executeInsert("INSERT INTO blood_transfusion_order(transfusion_no,patient_id,patient_name,admission_no,doctor_id,doctor_name,dept_id,dept_name,blood_type,rh_type,transfusion_purpose,product_type,quantity,unit,urgency,transfusion_date,abo_antibody_screen,irregular_antibody,cross_match_result,blood_bag_no,donor_blood_type)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",o.getTransfusionNo(),o.getPatientId(),o.getPatientName(),o.getAdmissionNo(),o.getDoctorId(),o.getDoctorName(),o.getDeptId(),o.getDeptName(),o.getBloodType(),o.getRhType(),o.getTransfusionPurpose(),o.getProductType(),o.getQuantity(),o.getUnit(),o.getUrgency(),o.getTransfusionDate(),o.getAboAntibodyScreen(),o.getIrregularAntibody(),o.getCrossMatchResult(),o.getBloodBagNo(),o.getDonorBloodType());}
    @Override public int update(BloodTransfusionOrder o){return JDBCUtil.executeUpdate("UPDATE blood_transfusion_order SET start_time=?,end_time=?,transfused_amount=?,reaction_type=?,reaction_handling=?,status=?,nurse_id=?,nurse_name=?WHERE id=?",o.getStartTime(),o.getEndTime(),o.getTransfusedAmount(),o.getReactionType(),o.getReactionHandling(),o.getStatus(),o.getNurseId(),o.getNurseName(),o.getId());}
    @Override public BloodTransfusionOrder findById(int id){List<BloodTransfusionOrder>l=queryList("SELECT*FROM blood_transfusion_order WHERE id=?",this::mapBTO,id);return l.isEmpty()?null:l.get(0);}
    @Override public List<BloodTransfusionOrder> findTransfusionsByPatientId(int patientId){return queryList("SELECT*FROM blood_transfusion_order WHERE patient_id=?ORDER BY create_time DESC",this::mapBTO,patientId);}
    @Override public List<BloodTransfusionOrder> findTransfusions(String status,int page,int size){String sql="SELECT*FROM blood_transfusion_order WHERE 1=1";List<Object>params=new ArrayList<>();if(status!=null&&!status.isEmpty()){sql+=" AND status=?";params.add(status);}sql+=" ORDER BY create_time DESC LIMIT ?,?";params.add((page-1)*size);params.add(size);return queryList(sql,this::mapBTO,params.toArray(new Object[0]));}
    private BloodTransfusionOrder mapBTO(ResultSet rs){try{BloodTransfusionOrder o=new BloodTransfusionOrder();o.setId(rs.getInt("id"));o.setTransfusionNo(rs.getString("transfusion_no"));o.setPatientId(rs.getInt("patient_id"));o.setPatientName(rs.getString("patient_name"));o.setAdmissionNo(rs.getString("admission_no"));o.setDoctorId(rs.getInt("doctor_id"));o.setDoctorName(rs.getString("doctor_name"));o.setDeptId(rs.getInt("dept_id"));o.setDeptName(rs.getString("dept_name"));o.setBloodType(rs.getString("blood_type"));o.setRhType(rs.getString("rh_type"));o.setTransfusionPurpose(rs.getString("transfusion_purpose"));o.setProductType(rs.getString("product_type"));o.setQuantity(rs.getInt("quantity"));o.setUnit(rs.getString("unit"));o.setUrgency(rs.getString("urgency"));o.setTransfusionDate(rs.getDate("transfusion_date"));o.setAboAntibodyScreen(rs.getString("abo_antibody_screen"));o.setIrregularAntibody(rs.getString("irregular_antibody"));o.setCrossMatchResult(rs.getString("cross_match_result"));o.setBloodBagNo(rs.getString("blood_bag_no"));o.setDonorBloodType(rs.getString("donor_blood_type"));o.setStartTime(rs.getTimestamp("start_time"));o.setEndTime(rs.getTimestamp("end_time"));o.setTransfusedAmount(rs.getInt("transfused_amount"));o.setReactionType(rs.getString("reaction_type"));o.setReactionHandling(rs.getString("reaction_handling"));o.setStatus(rs.getString("status"));if(rs.getObject("approver_id")!=null)o.setApproverId(rs.getInt("approver_id"));o.setApproverName(rs.getString("approver_name"));o.setApproveTime(rs.getTimestamp("approve_time"));if(rs.getObject("nurse_id")!=null)o.setNurseId(rs.getInt("nurse_id"));o.setNurseName(rs.getString("nurse_name"));o.setCreateTime(rs.getTimestamp("create_time"));o.setUpdateTime(rs.getTimestamp("update_time"));return o;}catch(SQLException e){return null;}}
}
