package dao.impl;
import bean.ImagingExamOrder;
import dao.ImagingExamOrderDAO;
import util.JDBCUtil;
import java.sql.*;
import java.util.*;

public class ImagingExamOrderDAOImpl implements ImagingExamOrderDAO {
    private <T> List<T> queryList(String sql, java.util.function.Function<ResultSet,T> mapper, Object... params) {
        List<T> list = new ArrayList<>();
        try (JDBCUtil.QueryResult qr = JDBCUtil.executeQuery(sql, params)) { ResultSet rs = qr.getResultSet(); while(rs.next()) list.add(mapper.apply(rs)); } catch(Exception e){ e.printStackTrace(); }
        return list;
    }
    @Override public int insert(ImagingExamOrder o){return JDBCUtil.executeInsert("INSERT INTO imaging_exam_order(exam_no,patient_id,patient_name,medical_record_no,admission_no,doctor_id,doctor_name,dept_id,dept_name,exam_modality,exam_part,exam_items,clinical_diagnosis,exam_purpose,contrast_agent,allergy_history,status,appointment_time,exam_time,technician_id,technician_name,radiologist_id,radiologist_name,report_time,image_count,storage_path,total_amount)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",o.getExamNo(),o.getPatientId(),o.getPatientName(),o.getMedicalRecordNo(),o.getAdmissionNo(),o.getDoctorId(),o.getDoctorName(),o.getDeptId(),o.getDeptName(),o.getExamModality(),o.getExamPart(),o.getExamItems(),o.getClinicalDiagnosis(),o.getExamPurpose(),o.getContrastAgent(),o.getAllergyHistory(),o.getStatus(),o.getAppointmentTime(),o.getExamTime(),o.getTechnicianId(),o.getTechnicianName(),o.getRadiologistId(),o.getRadiologistName(),o.getReportTime(),o.getImageCount(),o.getStoragePath(),o.getTotalAmount());}
    @Override public int update(ImagingExamOrder o){return JDBCUtil.executeUpdate("UPDATE imaging_exam_order SET status=?,exam_time=?,technician_id=?,technician_name=?,radiologist_id=?,radiologist_name=?,report_time=?,image_count=?WHERE id=?",o.getStatus(),o.getExamTime(),o.getTechnicianId(),o.getTechnicianName(),o.getRadiologistId(),o.getRadiologistName(),o.getReportTime(),o.getImageCount(),o.getId());}
    @Override public ImagingExamOrder findById(int id){List<ImagingExamOrder>l=queryList("SELECT*FROM imaging_exam_order WHERE id=?",this::mapIEO,id);return l.isEmpty()?null:l.get(0);}
    @Override public List<ImagingExamOrder> findExamsByPatientId(int patientId){return queryList("SELECT*FROM imaging_exam_order WHERE patient_id=?ORDER BY create_time DESC",this::mapIEO,patientId);}
    @Override public List<ImagingExamOrder> findExams(String modality,String status,int page,int size){String sql="SELECT*FROM imaging_exam_order WHERE 1=1";List<Object>params=new ArrayList<>();if(modality!=null&&!modality.isEmpty()){sql+=" AND exam_modality=?";params.add(modality);}if(status!=null&&!status.isEmpty()){sql+=" AND status=?";params.add(status);}sql+=" ORDER BY create_time DESC LIMIT ?,?";params.add((page-1)*size);params.add(size);return queryList(sql,this::mapIEO,params.toArray(new Object[0]));}
    private ImagingExamOrder mapIEO(ResultSet rs){try{ImagingExamOrder o=new ImagingExamOrder();o.setId(rs.getInt("id"));o.setExamNo(rs.getString("exam_no"));o.setPatientId(rs.getInt("patient_id"));o.setPatientName(rs.getString("patient_name"));o.setMedicalRecordNo(rs.getString("medical_record_no"));o.setAdmissionNo(rs.getString("admission_no"));o.setDoctorId(rs.getInt("doctor_id"));o.setDoctorName(rs.getString("doctor_name"));o.setDeptId(rs.getInt("dept_id"));o.setDeptName(rs.getString("dept_name"));o.setExamModality(rs.getString("exam_modality"));o.setExamPart(rs.getString("exam_part"));o.setExamItems(rs.getString("exam_items"));o.setClinicalDiagnosis(rs.getString("clinical_diagnosis"));o.setExamPurpose(rs.getString("exam_purpose"));o.setContrastAgent(rs.getString("contrast_agent"));o.setAllergyHistory(rs.getString("allergy_history"));o.setStatus(rs.getString("status"));o.setAppointmentTime(rs.getTimestamp("appointment_time"));o.setExamTime(rs.getTimestamp("exam_time"));if(rs.getObject("technician_id")!=null)o.setTechnicianId(rs.getInt("technician_id"));o.setTechnicianName(rs.getString("technician_name"));if(rs.getObject("radiologist_id")!=null)o.setRadiologistId(rs.getInt("radiologist_id"));o.setRadiologistName(rs.getString("radiologist_name"));o.setReportTime(rs.getTimestamp("report_time"));o.setImageCount(rs.getInt("image_count"));o.setStoragePath(rs.getString("storage_path"));o.setTotalAmount(rs.getBigDecimal("total_amount"));o.setCreateTime(rs.getTimestamp("create_time"));o.setUpdateTime(rs.getTimestamp("update_time"));return o;}catch(SQLException e){return null;}}
}
