package dao.impl;
import bean.InfectiousDiseaseReport;
import dao.InfectiousDiseaseReportDAO;
import util.JDBCUtil;
import java.sql.*;
import java.util.*;

public class InfectiousDiseaseReportDAOImpl implements InfectiousDiseaseReportDAO {
    private <T> List<T> queryList(String sql, java.util.function.Function<ResultSet,T> mapper, Object... params) {
        List<T> list = new ArrayList<>();
        try (JDBCUtil.QueryResult qr = JDBCUtil.executeQuery(sql, params)) { ResultSet rs = qr.getResultSet(); while(rs.next()) list.add(mapper.apply(rs)); } catch(Exception e){ e.printStackTrace(); }
        return list;
    }
    @Override public int insert(InfectiousDiseaseReport r){return JDBCUtil.executeInsert("INSERT INTO infectious_disease_report(report_no,disease_code,disease_name,disease_category,patient_id,patient_name,gender,age,id_card,phone,address,workplace,diagnosis_date,onset_date,symptoms,lab_results,epidemiology_info,close_contacts,reporter_id,reporter_name,dept_id,dept_name,status,urgent_level)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",r.getReportNo(),r.getDiseaseCode(),r.getDiseaseName(),r.getDiseaseCategory(),r.getPatientId(),r.getPatientName(),r.getGender(),r.getAge(),r.getIdCard(),r.getPhone(),r.getAddress(),r.getWorkplace(),r.getDiagnosisDate(),r.getOnsetDate(),r.getSymptoms(),r.getLabResults(),r.getEpidemiologyInfo(),r.getCloseContacts(),r.getReporterId(),r.getReporterName(),r.getDeptId(),r.getDeptName(),r.getStatus(),r.getUrgentLevel());}
    @Override public int update(InfectiousDiseaseReport r){return JDBCUtil.executeUpdate("UPDATE infectious_disease_report SET death_date=?,cdc_notify_time=?,cdc_feedback=?,status=?WHERE id=?",r.getDeathDate(),r.getCdcNotifyTime(),r.getCdcFeedback(),r.getStatus(),r.getId());}
    @Override public InfectiousDiseaseReport findById(int id){List<InfectiousDiseaseReport>l=queryList("SELECT*FROM infectious_disease_report WHERE id=?",this::mapIDR,id);return l.isEmpty()?null:l.get(0);}
    @Override public List<InfectiousDiseaseReport> findByPatientId(int patientId){return queryList("SELECT*FROM infectious_disease_report WHERE patient_id=?ORDER BY diagnosis_date DESC",this::mapIDR,patientId);}
    @Override public List<InfectiousDiseaseReport> findReports(String diseaseCategory,String status,int page,int size){String sql="SELECT*FROM infectious_disease_report WHERE 1=1";List<Object>params=new ArrayList<>();if(diseaseCategory!=null&&!diseaseCategory.isEmpty()){sql+=" AND disease_category=?";params.add(diseaseCategory);}if(status!=null&&!status.isEmpty()){sql+=" AND status=?";params.add(status);}sql+=" ORDER BY report_time DESC LIMIT ?,?";params.add((page-1)*size);params.add(size);return queryList(sql,this::mapIDR,params.toArray(new Object[0]));}
    private InfectiousDiseaseReport mapIDR(ResultSet rs){try{InfectiousDiseaseReport r=new InfectiousDiseaseReport();r.setId(rs.getInt("id"));r.setReportNo(rs.getString("report_no"));r.setDiseaseCode(rs.getString("disease_code"));r.setDiseaseName(rs.getString("disease_name"));r.setDiseaseCategory(rs.getString("disease_category"));r.setPatientId(rs.getInt("patient_id"));r.setPatientName(rs.getString("patient_name"));r.setGender(rs.getString("gender"));if(rs.getObject("age")!=null)r.setAge(rs.getInt("age"));r.setIdCard(rs.getString("id_card"));r.setPhone(rs.getString("phone"));r.setAddress(rs.getString("address"));r.setWorkplace(rs.getString("workplace"));r.setDiagnosisDate(rs.getDate("diagnosis_date"));r.setDeathDate(rs.getDate("death_date"));r.setOnsetDate(rs.getDate("onset_date"));r.setSymptoms(rs.getString("symptoms"));r.setLabResults(rs.getString("lab_results"));r.setEpidemiologyInfo(rs.getString("epidemiology_info"));r.setCloseContacts(rs.getString("close_contacts"));r.setReporterId(rs.getInt("reporter_id"));r.setReporterName(rs.getString("reporter_name"));r.setReportTime(rs.getTimestamp("report_time"));r.setDeptId(rs.getInt("dept_id"));r.setDeptName(rs.getString("dept_name"));r.setCdcNotifyTime(rs.getTimestamp("cdc_notify_time"));r.setCdcFeedback(rs.getString("cdc_feedback"));r.setStatus(rs.getString("status"));r.setUrgentLevel(rs.getString("urgent_level"));r.setCreateTime(rs.getTimestamp("create_time"));r.setUpdateTime(rs.getTimestamp("update_time"));return r;}catch(SQLException e){return null;}}
}
