package dao.impl;
import bean.*;
import dao.*;
import util.JDBCUtil;
import java.sql.*;
import java.util.*;

public class SurgeryScheduleDAOImpl implements SurgeryScheduleDAO {
    private <T> List<T> queryList(String sql, java.util.function.Function<ResultSet,T> mapper, Object... params) {
        List<T> list = new ArrayList<>();
        try (JDBCUtil.QueryResult qr = JDBCUtil.executeQuery(sql, params)) { ResultSet rs = qr.getResultSet(); while(rs.next()) list.add(mapper.apply(rs)); } catch(Exception e){ e.printStackTrace(); }
        return list;
    }
    @Override public int insert(SurgerySchedule s){return JDBCUtil.executeInsert("INSERT INTO surgery_schedule(surgery_no,patient_id,patient_name,admission_no,bed_no,surgeon_id,surgeon_name,assistant_ids,assistant_names,anesthesiologist_id,anesthesiologist_name,scrub_nurse_id,scrub_nurse_name,circulating_nurse_id,circulating_nurse_name,surgery_name,surgery_code,surgery_type,body_side,incision_type,anesthesia_method,planned_date,planned_start_time,operating_room_id,operating_room_name,preoperative_diagnosis,surgery_indication,risk_level,special_equipment,blood_preparation,status)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",s.getSurgeryNo(),s.getPatientId(),s.getPatientName(),s.getAdmissionNo(),s.getBedNo(),s.getSurgeonId(),s.getSurgeonName(),s.getAssistantIds(),s.getAssistantNames(),s.getAnesthesiologistId(),s.getAnesthesiologistName(),s.getScrubNurseId(),s.getScrubNurseName(),s.getCirculatingNurseId(),s.getCirculatingNurseName(),s.getSurgeryName(),s.getSurgeryCode(),s.getSurgeryType(),s.getBodySide(),s.getIncisionType(),s.getAnesthesiaMethod(),s.getPlannedDate(),s.getPlannedStartTime(),s.getOperatingRoomId(),s.getOperatingRoomName(),s.getPreoperativeDiagnosis(),s.getSurgeryIndication(),s.getRiskLevel(),s.getSpecialEquipment(),s.getBloodPreparation(),s.getStatus());}
    @Override public int update(SurgerySchedule s){return JDBCUtil.executeUpdate("UPDATE surgery_schedule SET status=?,actual_start_time=?,actual_end_time=?,surgery_duration=?WHERE id=?",s.getStatus(),s.getActualStartTime(),s.getActualEndTime(),s.getSurgeryDuration(),s.getId());}
    @Override public SurgerySchedule findById(int id){List<SurgerySchedule>l=queryList("SELECT*FROM surgery_schedule WHERE id=?",this::mapSS,id);return l.isEmpty()?null:l.get(0);}
    @Override public List<SurgerySchedule> findBySurgeonId(int surgeonId){return queryList("SELECT*FROM surgery_schedule WHERE surgeon_id=?ORDER BY planned_date,planned_start_time",this::mapSS,surgeonId);}
    @Override public List<SurgerySchedule> findAll(String status,java.sql.Date date,int page,int size){String sql="SELECT*FROM surgery_schedule WHERE 1=1";List<Object>params=new ArrayList<>();if(status!=null&&!status.isEmpty()){sql+=" AND status=?";params.add(status);}if(date!=null){sql+=" AND planned_date=?";params.add(date.toString());}sql+=" ORDER BY planned_date,planned_start_time LIMIT ?,?";params.add((page-1)*size);params.add(size);return queryList(sql,this::mapSS,params.toArray(new Object[0]));}
    private SurgerySchedule mapSS(ResultSet rs){try{SurgerySchedule s=new SurgerySchedule();s.setId(rs.getInt("id"));s.setSurgeryNo(rs.getString("surgery_no"));s.setPatientId(rs.getInt("patient_id"));s.setPatientName(rs.getString("patient_name"));s.setAdmissionNo(rs.getString("admission_no"));s.setBedNo(rs.getString("bed_no"));s.setSurgeonId(rs.getInt("surgeon_id"));s.setSurgeonName(rs.getString("surgeon_name"));s.setAssistantIds(rs.getString("assistant_ids"));s.setAssistantNames(rs.getString("assistant_names"));if(rs.getObject("anesthesiologist_id")!=null)s.setAnesthesiologistId(rs.getInt("anesthesiologist_id"));s.setAnesthesiologistName(rs.getString("anesthesiologist_name"));if(rs.getObject("scrub_nurse_id")!=null)s.setScrubNurseId(rs.getInt("scrub_nurse_id"));s.setScrubNurseName(rs.getString("scrub_nurse_name"));if(rs.getObject("circulating_nurse_id")!=null)s.setCirculatingNurseId(rs.getInt("circulating_nurse_id"));s.setCirculatingNurseName(rs.getString("circulating_nurse_name"));s.setSurgeryName(rs.getString("surgery_name"));s.setSurgeryCode(rs.getString("surgery_code"));s.setSurgeryType(rs.getString("surgery_type"));s.setBodySide(rs.getString("body_side"));s.setIncisionType(rs.getString("incision_type"));s.setAnesthesiaMethod(rs.getString("anesthesia_method"));s.setPlannedDate(rs.getDate("planned_date"));s.setPlannedStartTime(rs.getTime("planned_start_time"));if(rs.getObject("operating_room_id")!=null)s.setOperatingRoomId(rs.getInt("operating_room_id"));s.setOperatingRoomName(rs.getString("operating_room_name"));s.setPreoperativeDiagnosis(rs.getString("preoperative_diagnosis"));s.setSurgeryIndication(rs.getString("surgery_indication"));s.setRiskLevel(rs.getString("risk_level"));s.setSpecialEquipment(rs.getString("special_equipment"));s.setBloodPreparation(rs.getString("blood_preparation"));s.setStatus(rs.getString("status"));s.setActualStartTime(rs.getTimestamp("actual_start_time"));s.setActualEndTime(rs.getTimestamp("actual_end_time"));s.setSurgeryDuration(rs.getInt("surgery_duration"));s.setCreateTime(rs.getTimestamp("create_time"));s.setUpdateTime(rs.getTimestamp("update_time"));return s;}catch(SQLException e){return null;}}
}
