$newEvents = @'
  {
    id: '-3000-01',
    year: -3000,
    startYear: -3000,
    endYear: -2800,
    title: '苏美尔城邦建立',
    description: '苏美尔人在两河流域建立了乌尔、乌鲁克等早期城邦。',
    category: 'politics',
    region: '亚洲',
    keyFigures: [],
    impact: '开创了城市文明的先河，为后来的巴比伦文明奠定了基础。',
    relatedEvents: [],
    background: '两河流域肥沃的土地和便利的灌溉条件促进了农业发展和人口增长。',
    cause: '约公元前3000年，苏美尔人开始建造城市，形成了早期城邦国家。',
    significance: '苏美尔城邦是人类历史上最早的城市国家之一，其政治组织、宗教信仰和文化成就对后来的文明产生了深远影响。',
  },
  {
    id: '-2800-01',
    year: -2800,
    startYear: -2800,
    endYear: -2600,
    title: '埃及古王国时期',
    description: '古埃及进入古王国时期，建造了吉萨金字塔群。',
    category: 'monarch',
    region: '非洲',
    keyFigures: ['胡夫', '哈夫拉'],
    impact: '古埃及文明达到鼎盛，金字塔成为世界奇迹。',
    relatedEvents: [],
    background: '古埃及统一后，法老们开始建造宏伟的陵墓和神庙。',
    cause: '约公元前2800年，古埃及进入古王国时期，开始大规模建造金字塔。',
    significance: '古王国时期是古埃及文明的黄金时代，金字塔的建造展示了古埃及人高超的建筑技术和社会组织能力。',
  },
  {
    id: '-2600-01',
    year: -2600,
    startYear: -2600,
    endYear: -2400,
    title: '印度河流域文明',
    description: '哈拉帕和摩亨佐-达罗等城市繁荣，印度河流域文明达到鼎盛。',
    category: 'culture',
    region: '亚洲',
    keyFigures: [],
    impact: '创造了高度发达的城市文明，对印度文化产生深远影响。',
    relatedEvents: [],
    background: '印度河流域肥沃的土地和温和的气候促进了农业和商业的发展。',
    cause: '约公元前2600年，印度河流域文明达到鼎盛时期。',
    significance: '印度河流域文明是世界上最早的城市文明之一，其城市规划、排水系统和艺术成就令人惊叹。',
  },
  {
    id: '-2500-01',
    year: -2500,
    startYear: -2500,
    endYear: -2300,
    title: '埃兰文明',
    description: '埃兰人在伊朗高原建立了强大的王国，与两河流域文明交流频繁。',
    category: 'politics',
    region: '亚洲',
    keyFigures: [],
    impact: '成为连接两河流域和伊朗高原的桥梁。',
    relatedEvents: [],
    background: '伊朗高原丰富的矿产资源和战略位置促进了埃兰文明的发展。',
    cause: '约公元前2500年，埃兰人建立了强大的王国。',
    significance: '埃兰文明是古代伊朗高原最重要的文明之一，其文化和艺术对后来的波斯文明产生了重要影响。',
  },
  {
    id: '-2300-01',
    year: -2300,
    startYear: -2300,
    endYear: -2100,
    title: '阿卡德帝国',
    description: '萨尔贡一世统一两河流域，建立阿卡德帝国。',
    category: 'monarch',
    region: '亚洲',
    keyFigures: ['萨尔贡一世'],
    impact: '开创了帝国统治的模式，为后来的帝国建立提供了范例。',
    relatedEvents: [],
    background: '两河流域城邦之间长期征战，萨尔贡一世凭借强大的军事力量统一了整个地区。',
    cause: '约公元前2300年，萨尔贡一世建立阿卡德帝国。',
    significance: '阿卡德帝国是世界历史上第一个帝国，其统治模式被后来的统治者所借鉴。',
  },
  {
    id: '-2100-01',
    year: -2100,
    startYear: -2100,
    endYear: -1900,
    title: '乌尔第三王朝',
    description: '乌尔纳姆建立乌尔第三王朝，颁布世界上最早的成文法典。',
    category: 'treaty',
    region: '亚洲',
    keyFigures: ['乌尔纳姆'],
    impact: '奠定了两河流域文明的法律基础。',
    relatedEvents: [],
    background: '阿卡德帝国灭亡后，两河流域陷入混乱，乌尔纳姆统一了该地区。',
    cause: '约公元前2100年，乌尔纳姆建立乌尔第三王朝。',
    significance: '乌尔第三王朝颁布的《乌尔纳姆法典》是世界上最早的成文法典，对后来的法律体系产生了重要影响。',
  },
  {
    id: '-2000-01',
    year: -2000,
    startYear: -2000,
    endYear: -1800,
    title: '赫梯帝国建立',
    description: '赫梯人在安纳托利亚建立了强大的赫梯帝国。',
    category: 'politics',
    region: '亚洲',
    keyFigures: [],
    impact: '成为中东地区的重要力量，推动了铁器的使用。',
    relatedEvents: [],
    background: '安纳托利亚丰富的矿产资源和战略位置促进了赫梯文明的发展。',
    cause: '约公元前2000年，赫梯人建立了赫梯帝国。',
    significance: '赫梯帝国是世界上最早使用铁器的文明之一，其军事力量和外交手段在中东地区产生了深远影响。',
  },
  {
    id: '-1900-01',
    year: -1900,
    startYear: -1900,
    endYear: -1700,
    title: '古巴比伦王国',
    description: '巴比伦成为两河流域的中心，汉谟拉比统一了该地区。',
    category: 'politics',
    region: '亚洲',
    keyFigures: ['汉谟拉比'],
    impact: '颁布了世界上第一部完整的成文法典。',
    relatedEvents: [],
    background: '两河流域在经历了一段时间的分裂后，巴比伦逐渐崛起。',
    cause: '约公元前1900年，巴比伦成为两河流域的中心城市。',
    significance: '古巴比伦王国的建立标志着两河流域文明的复兴，汉谟拉比法典成为人类法制史上的里程碑。',
  },
  {
    id: '-1800-01',
    year: -1800,
    startYear: -1800,
    endYear: -1600,
    title: '米坦尼王国',
    description: '胡里安人在美索不达米亚北部建立了米坦尼王国。',
    category: 'politics',
    region: '亚洲',
    keyFigures: [],
    impact: '成为连接两河流域和安纳托利亚的重要国家。',
    relatedEvents: [],
    background: '胡里安人在美索不达米亚北部逐渐强大，建立了米坦尼王国。',
    cause: '约公元前1800年，米坦尼王国建立。',
    significance: '米坦尼王国在外交和军事上都取得了重要成就，对中东地区的政治格局产生了影响。',
  },
  {
    id: '-1700-01',
    year: -1700,
    startYear: -1700,
    endYear: -1500,
    title: '克里特文明',
    description: '米诺斯文明在克里特岛达到鼎盛，建造了宏伟的宫殿。',
    category: 'culture',
    region: '欧洲',
    keyFigures: [],
    impact: '开创了古希腊文明的先河，对西方文明产生深远影响。',
    relatedEvents: [],
    background: '克里特岛优越的地理位置和丰富的自然资源促进了文明的发展。',
    cause: '约公元前1700年，米诺斯文明达到鼎盛时期。',
    significance: '克里特文明是欧洲最早的文明之一，其艺术、建筑和宗教对古希腊文明产生了重要影响。',
  },
  {
    id: '-1600-01',
    year: -1600,
    startYear: -1600,
    endYear: -1400,
    title: '迈锡尼文明',
    description: '迈锡尼人在希腊半岛建立了强大的王国，与特洛伊发生战争。',
    category: 'wars',
    region: '欧洲',
    keyFigures: [],
    impact: '成为古希腊文明的重要组成部分。',
    relatedEvents: [],
    background: '希腊半岛的多山地形和沿海位置促进了迈锡尼人的航海和贸易。',
    cause: '约公元前1600年，迈锡尼人建立了迈锡尼文明。',
    significance: '迈锡尼文明是古希腊文明的重要阶段，其军事力量和建筑成就令人印象深刻。',
  },
  {
    id: '-1500-01',
    year: -1500,
    startYear: -1500,
    endYear: -1300,
    title: '新王国时期',
    description: '古埃及进入新王国时期，图特摩斯三世征服了叙利亚和巴勒斯坦。',
    category: 'monarch',
    region: '非洲',
    keyFigures: ['图特摩斯三世'],
    impact: '古埃及成为中东地区的霸主。',
    relatedEvents: [],
    background: '古埃及在经历了一段时间的衰落之后，开始重新崛起。',
    cause: '约公元前1500年，古埃及进入新王国时期。',
    significance: '新王国时期是古埃及文明的鼎盛时期，其疆域达到了历史最大范围。',
  },
  {
    id: '-1400-01',
    year: -1400,
    startYear: -1400,
    endYear: -1200,
    title: '亚述帝国崛起',
    description: '亚述人在美索不达米亚北部崛起，开始大规模扩张。',
    category: 'politics',
    region: '亚洲',
    keyFigures: [],
    impact: '成为中东地区最强大的军事帝国。',
    relatedEvents: [],
    background: '亚述人凭借强大的军事力量和先进的武器，开始征服周边地区。',
    cause: '约公元前1400年，亚述帝国开始崛起。',
    significance: '亚述帝国是古代世界最强大的军事帝国之一，其军事技术和统治方式对后来的帝国产生了重要影响。',
  },
  {
    id: '-1300-01',
    year: -1300,
    startYear: -1300,
    endYear: -1100,
    title: '腓尼基文明',
    description: '腓尼基人在黎巴嫩沿海建立了多个城邦，发展了海上贸易。',
    category: 'economy',
    region: '亚洲',
    keyFigures: [],
    impact: '创造了腓尼基字母，对西方文字产生深远影响。',
    relatedEvents: [],
    background: '腓尼基人凭借优越的地理位置，发展了繁荣的海上贸易。',
    cause: '约公元前1300年，腓尼基文明达到鼎盛时期。',
    significance: '腓尼基字母是世界上最早的拼音字母之一，对后来的希腊字母和拉丁字母产生了重要影响。',
  },
  {
    id: '-1200-01',
    year: -1200,
    startYear: -1200,
    endYear: -1000,
    title: '海上民族入侵',
    description: '海上民族入侵地中海地区，导致迈锡尼文明和赫梯帝国灭亡。',
    category: 'wars',
    region: '全球',
    keyFigures: [],
    impact: '改变了地中海地区的政治格局，开启了黑暗时代。',
    relatedEvents: [],
    background: '公元前12世纪，地中海地区出现了大规模的移民和入侵浪潮。',
    cause: '约公元前1200年，海上民族开始入侵地中海地区。',
    significance: '海上民族的入侵导致了多个古代文明的灭亡，地中海地区进入了长达数百年的黑暗时代。',
  },
  {
    id: '-1100-01',
    year: -1100,
    startYear: -1100,
    endYear: -900,
    title: '以色列王国建立',
    description: '大卫统一以色列部落，建立以色列王国，定都耶路撒冷。',
    category: 'politics',
    region: '亚洲',
    keyFigures: ['大卫'],
    impact: '奠定了犹太民族的基础，对宗教和文化产生深远影响。',
    relatedEvents: [],
    background: '以色列人在经历了长期的游牧生活后，开始在巴勒斯坦地区定居。',
    cause: '约公元前1100年，大卫统一以色列部落，建立以色列王国。',
    significance: '以色列王国的建立是犹太民族历史上的重要事件，耶路撒冷成为犹太教的圣地。',
  },
  {
    id: '-1000-01',
    year: -1000,
    startYear: -1000,
    endYear: -800,
    title: '亚述帝国扩张',
    description: '亚述帝国在提格拉特帕拉沙尔三世统治下大规模扩张。',
    category: 'monarch',
    region: '亚洲',
    keyFigures: ['提格拉特帕拉沙尔三世'],
    impact: '成为古代世界最大的帝国之一。',
    relatedEvents: [],
    background: '亚述帝国凭借强大的军事力量和先进的战术，开始征服周边地区。',
    cause: '约公元前1000年，亚述帝国开始大规模扩张。',
    significance: '亚述帝国的扩张改变了中东地区的政治格局，其军事技术和统治方式对后来的帝国产生了重要影响。',
  },
  {
    id: '-900-01',
    year: -900,
    startYear: -900,
    endYear: -700,
    title: '埃兰王国',
    description: '埃兰人在伊朗高原建立了强大的王国，与亚述帝国长期对抗。',
    category: 'politics',
    region: '亚洲',
    keyFigures: [],
    impact: '成为伊朗高原的重要力量，对波斯文明产生影响。',
    relatedEvents: [],
    background: '伊朗高原丰富的矿产资源和战略位置促进了埃兰文明的发展。',
    cause: '约公元前900年，埃兰王国达到鼎盛时期。',
    significance: '埃兰王国是古代伊朗高原最重要的文明之一，其文化和艺术对后来的波斯文明产生了重要影响。',
  },
  {
    id: '-800-01',
    year: -800,
    startYear: -800,
    endYear: -600,
    title: '希腊古风时期',
    description: '希腊城邦开始兴起，斯巴达和雅典成为希腊的两大强国。',
    category: 'politics',
    region: '欧洲',
    keyFigures: [],
    impact: '奠定了古希腊文明的基础，对西方文明产生深远影响。',
    relatedEvents: [],
    background: '希腊半岛的多山地形和沿海位置促进了城邦的发展。',
    cause: '约公元前800年，希腊城邦开始兴起。',
    significance: '希腊古风时期是古希腊文明的重要阶段，其政治制度、文化和艺术对西方文明产生了深远影响。',
  },
  {
    id: '-700-01',
    year: -700,
    startYear: -700,
    endYear: -500,
    title: '新亚述帝国',
    description: '亚述帝国在萨尔贡二世统治下达到鼎盛，征服了叙利亚和埃及。',
    category: 'monarch',
    region: '亚洲',
    keyFigures: ['萨尔贡二世'],
    impact: '成为古代世界最大的帝国之一，对中东地区产生深远影响。',
    relatedEvents: [],
    background: '亚述帝国凭借强大的军事力量和先进的战术，开始征服周边地区。',
    cause: '约公元前700年，亚述帝国达到鼎盛时期。',
    significance: '新亚述帝国是古代世界最强大的帝国之一，其军事技术和统治方式对后来的帝国产生了重要影响。',
  },
  {
    id: '-600-01',
    year: -600,
    startYear: -600,
    endYear: -400,
    title: '吕底亚王国',
    description: '吕底亚人在安纳托利亚建立了强大的王国，发明了金币。',
    category: 'economy',
    region: '亚洲',
    keyFigures: [],
    impact: '开创了货币经济的先河，对商业发展产生深远影响。',
    relatedEvents: [],
    background: '安纳托利亚丰富的矿产资源和战略位置促进了吕底亚文明的发展。',
    cause: '约公元前600年，吕底亚王国达到鼎盛时期。',
    significance: '吕底亚王国是世界上最早使用金币的国家，其货币制度对后来的商业发展产生了重要影响。',
  },
  {
    id: '-550-01',
    year: -550,
    startYear: -550,
    endYear: -330,
    title: '波斯帝国建立',
    description: '居鲁士大帝建立波斯帝国，统一了伊朗高原。',
    category: 'monarch',
    region: '亚洲',
    keyFigures: ['居鲁士大帝'],
    impact: '成为古代世界最大的帝国之一，对中东和地中海地区产生深远影响。',
    relatedEvents: [],
    background: '伊朗高原的部落逐渐统一，居鲁士大帝开始征服周边地区。',
    cause: '公元前550年，居鲁士大帝建立波斯帝国。',
    significance: '波斯帝国是古代世界最大的帝国之一，其统治方式和文化成就对后来的文明产生了重要影响。',
  },
  {
    id: '-500-01',
    year: -500,
    startYear: -500,
    endYear: -449,
    title: '希波战争',
    description: '希腊城邦与波斯帝国之间爆发大规模战争，希腊最终获胜。',
    category: 'wars',
    region: '欧亚',
    keyFigures: [],
    impact: '保卫了希腊城邦的独立，成为西方文明的重要转折点。',
    relatedEvents: [],
    background: '波斯帝国在大流士一世统治下不断扩张，试图征服希腊城邦。',
    cause: '公元前499年，希腊城邦发动起义，希波战争爆发。',
    significance: '希波战争是古代世界最重要的战争之一，希腊的胜利保卫了西方文明的发展。',
  },
  {
    id: '-460-01',
    year: -460,
    startYear: -460,
    endYear: -399,
    title: '苏格拉底',
    description: '苏格拉底在雅典讲学，开创了西方哲学的先河。',
    category: 'thinker',
    region: '欧洲',
    keyFigures: ['苏格拉底'],
    impact: '奠定了西方哲学的基础，对人类思想产生深远影响。',
    relatedEvents: [],
    background: '雅典在伯里克利时期达到鼎盛，哲学和艺术繁荣。',
    cause: '约公元前460年，苏格拉底开始在雅典讲学。',
    significance: '苏格拉底是西方哲学的创始人之一，其哲学方法和思想对后来的哲学家产生了深远影响。',
  },
  {
    id: '-430-01',
    year: -430,
    startYear: -430,
    endYear: -404,
    title: '伯罗奔尼撒战争',
    description: '雅典与斯巴达之间爆发伯罗奔尼撒战争，斯巴达获胜。',
    category: 'wars',
    region: '欧洲',
    keyFigures: [],
    impact: '结束了雅典的霸权，希腊城邦开始衰落。',
    relatedEvents: [],
    background: '雅典和斯巴达为争夺希腊霸权长期对抗。',
    cause: '公元前431年，伯罗奔尼撒战争爆发。',
    significance: '伯罗奔尼撒战争是希腊城邦之间最激烈的战争，它结束了雅典的霸权，标志着希腊城邦的衰落。',
  },
  {
    id: '-384-01',
    year: -384,
    startYear: -384,
    endYear: -322,
    title: '亚里士多德',
    description: '亚里士多德在雅典创立吕克昂学园，成为古希腊哲学的集大成者。',
    category: 'thinker',
    region: '欧洲',
    keyFigures: ['亚里士多德'],
    impact: '奠定了西方哲学和科学的基础，对人类知识产生深远影响。',
    relatedEvents: [],
    background: '亚里士多德是柏拉图的学生，他在雅典创立了自己的学园。',
    cause: '公元前384年，亚里士多德出生于马其顿。',
    significance: '亚里士多德是古希腊哲学的集大成者，其著作涵盖了哲学、科学、政治等多个领域，对西方文明产生了深远影响。',
  },
  {
    id: '-336-01',
    year: -336,
    startYear: -336,
    endYear: -323,
    title: '亚历山大东征',
    description: '亚历山大大帝率领马其顿军队征服了波斯帝国和埃及。',
    category: 'monarch',
    region: '全球',
    keyFigures: ['亚历山大大帝'],
    impact: '促进了东西方文化的交流和融合，开启了希腊化时代。',
    relatedEvents: [],
    background: '马其顿王国在腓力二世统治下逐渐强大，成为希腊的霸主。',
    cause: '公元前334年，亚历山大大帝率领军队越过赫勒斯滂海峡，开始东征。',
    significance: '亚历山大的东征是世界历史上最伟大的军事远征之一，他征服了从希腊到印度的广阔地区。',
  },
  {
    id: '-323-01',
    year: -323,
    startYear: -323,
    endYear: -30,
    title: '希腊化时代',
    description: '亚历山大帝国分裂后，希腊文化在中东和埃及广泛传播。',
    category: 'culture',
    region: '全球',
    keyFigures: [],
    impact: '促进了东西方文化的交流和融合，对后来的罗马文明产生影响。',
    relatedEvents: [],
    background: '亚历山大帝国分裂后，形成了多个希腊化王国。',
    cause: '公元前323年，亚历山大大帝去世，帝国开始分裂。',
    significance: '希腊化时代是东西方文化交流的重要时期，希腊文化和东方文化相互融合，产生了新的文化形态。',
  },
  {
    id: '-280-01',
    year: -280,
    startYear: -280,
    endYear: -200,
    title: '托勒密王朝',
    description: '托勒密在埃及建立托勒密王朝，亚历山大成为文化中心。',
    category: 'politics',
    region: '非洲',
    keyFigures: ['托勒密'],
    impact: '推动了希腊文化在埃及的传播，建立了亚历山大图书馆。',
    relatedEvents: [],
    background: '亚历山大帝国分裂后，托勒密获得了埃及的统治权。',
    cause: '公元前305年，托勒密正式建立托勒密王朝。',
    significance: '托勒密王朝是希腊化时代最重要的王国之一，亚历山大图书馆成为古代世界最大的知识中心。',
  },
  {
    id: '-264-01',
    year: -264,
    startYear: -264,
    endYear: -146,
    title: '布匿战争',
    description: '罗马与迦太基之间爆发三次布匿战争，罗马最终获胜。',
    category: 'wars',
    region: '欧洲',
    keyFigures: ['汉尼拔'],
    impact: '罗马成为地中海地区的霸主，迦太基被毁灭。',
    relatedEvents: [],
    background: '罗马和迦太基为争夺地中海霸权长期对抗。',
    cause: '公元前264年，第一次布匿战争爆发。',
    significance: '布匿战争是古代世界最重要的战争之一，罗马的胜利使其成为地中海地区的霸主。',
  },
  {
    id: '-202-01',
    year: -202,
    startYear: -202,
    endYear: -202,
    title: '扎马战役',
    description: '罗马将军西庇阿在扎马战役中击败汉尼拔，第二次布匿战争结束。',
    category: 'wars',
    region: '非洲',
    keyFigures: ['西庇阿', '汉尼拔'],
    impact: '罗马成为地中海地区的霸主。',
    relatedEvents: [],
    background: '第二次布匿战争中，汉尼拔率领迦太基军队进攻意大利。',
    cause: '公元前202年，西庇阿在扎马战役中击败汉尼拔。',
    significance: '扎马战役是第二次布匿战争的决定性战役，罗马的胜利使其成为地中海地区的霸主。',
  },
  {
    id: '-146-01',
    year: -146,
    startYear: -146,
    endYear: -146,
    title: '迦太基毁灭',
    description: '罗马军队攻陷迦太基，迦太基被彻底毁灭。',
    category: 'wars',
    region: '非洲',
    keyFigures: [],
    impact: '罗马成为地中海地区唯一的霸主。',
    relatedEvents: [],
    background: '第三次布匿战争中，罗马军队围攻迦太基。',
    cause: '公元前146年，罗马军队攻陷迦太基。',
    significance: '迦太基的毁灭标志着罗马成为地中海地区唯一的霸主，其统治地位无人能挑战。',
  },
  {
    id: '-106-01',
    year: -106,
    startYear: -106,
    endYear: -43,
    title: '凯撒',
    description: '凯撒成为罗马共和国的独裁者，征服了高卢和不列颠。',
    category: 'monarch',
    region: '欧洲',
    keyFigures: ['凯撒'],
    impact: '为罗马帝国的建立奠定了基础。',
    relatedEvents: [],
    background: '罗马共和国后期，内战频繁，凯撒逐渐掌握了政权。',
    cause: '公元前49年，凯撒率军渡过卢比孔河，开始内战。',
    significance: '凯撒是罗马历史上最伟大的将领之一，他的征服为罗马帝国的建立奠定了基础。',
  },
  {
    id: '-44-01',
    year: -44,
    startYear: -44,
    endYear: -44,
    title: '凯撒遇刺',
    description: '凯撒在元老院被布鲁图斯等人刺杀。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['凯撒', '布鲁图斯'],
    impact: '引发了罗马内战，为屋大维建立帝国创造了条件。',
    relatedEvents: [],
    background: '凯撒成为独裁者后，引起了元老院的不满。',
    cause: '公元前44年3月15日，凯撒在元老院被刺杀。',
    significance: '凯撒的遇刺引发了罗马内战，最终屋大维获胜，建立了罗马帝国。',
  },
  {
    id: '-27-01',
    year: -27,
    startYear: -27,
    endYear: 14,
    title: '奥古斯都',
    description: '屋大维被授予"奥古斯都"称号，成为罗马帝国第一位皇帝。',
    category: 'monarch',
    region: '欧洲',
    keyFigures: ['屋大维'],
    impact: '罗马进入黄金时代，疆域达到最大范围。',
    relatedEvents: [],
    background: '屋大维在凯撒遇刺后逐渐掌握了政权，击败了竞争对手。',
    cause: '公元前27年，屋大维被元老院授予"奥古斯都"称号。',
    significance: '奥古斯都是罗马帝国的第一位皇帝，他的统治开启了罗马的黄金时代。',
  },
  {
    id: '0-01',
    year: 0,
    startYear: 0,
    endYear: 33,
    title: '耶稣诞生',
    description: '耶稣基督诞生于巴勒斯坦地区，基督教开始传播。',
    category: 'culture',
    region: '亚洲',
    keyFigures: ['耶稣'],
    impact: '基督教成为世界三大宗教之一，对西方文明产生深远影响。',
    relatedEvents: [],
    background: '公元前1世纪，罗马帝国统治着巴勒斯坦地区，犹太人渴望救世主的到来。',
    cause: '约公元1年，耶稣诞生于巴勒斯坦的伯利恒。',
    significance: '耶稣的诞生标志着基督教的开始，基督教后来成为世界上最大的宗教之一。',
  },
  {
    id: '64-01',
    year: 64,
    startYear: 64,
    endYear: 64,
    title: '罗马大火',
    description: '罗马城发生大火，烧毁了大部分城区。',
    category: 'warning',
    region: '欧洲',
    keyFigures: ['尼禄'],
    impact: '罗马城遭受重创，尼禄的统治受到质疑。',
    relatedEvents: [],
    background: '罗马城在公元64年发生了一场巨大的火灾。',
    cause: '公元64年7月，罗马城发生大火，持续了六天。',
    significance: '罗马大火是古罗马历史上最严重的灾难之一，它烧毁了罗马城的大部分地区。',
  },
  {
    id: '70-01',
    year: 70,
    startYear: 70,
    endYear: 70,
    title: '耶路撒冷毁灭',
    description: '罗马军队攻陷耶路撒冷，摧毁了第二圣殿。',
    category: 'wars',
    region: '亚洲',
    keyFigures: [],
    impact: '犹太人被迫流散，开始了长达两千年的大流散。',
    relatedEvents: [],
    background: '犹太人发动起义反抗罗马统治。',
    cause: '公元70年，罗马军队攻陷耶路撒冷。',
    significance: '耶路撒冷的毁灭标志着犹太人失去了自己的国家，开始了长达两千年的大流散。',
  },
  {
    id: '122-01',
    year: 122,
    startYear: 122,
    endYear: 128,
    title: '哈德良长城',
    description: '罗马皇帝哈德良在不列颠修建长城，抵御蛮族入侵。',
    category: 'technology',
    region: '欧洲',
    keyFigures: ['哈德良'],
    impact: '成为罗马帝国北部边界的重要防御工事。',
    relatedEvents: [],
    background: '罗马帝国在不列颠的统治面临蛮族入侵的威胁。',
    cause: '公元122年，哈德良下令修建长城。',
    significance: '哈德良长城是罗马帝国最著名的防御工事之一，它展示了罗马帝国的军事力量和工程技术。',
  },
  {
    id: '212-01',
    year: 212,
    startYear: 212,
    endYear: 212,
    title: '卡拉卡拉敕令',
    description: '罗马皇帝卡拉卡拉颁布敕令，授予所有自由民罗马公民权。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['卡拉卡拉'],
    impact: '扩大了罗马公民权的范围，促进了帝国的统一。',
    relatedEvents: [],
    background: '罗马帝国在2世纪面临着严重的社会和政治问题。',
    cause: '公元212年，卡拉卡拉颁布敕令。',
    significance: '卡拉卡拉敕令是罗马帝国历史上的重要事件，它授予所有自由民罗马公民权，促进了帝国的统一。',
  },
  {
    id: '284-01',
    year: 284,
    startYear: 284,
    endYear: 305,
    title: '戴克里先改革',
    description: '戴克里先成为罗马皇帝，进行了一系列改革，包括四帝共治。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['戴克里先'],
    impact: '暂时稳定了罗马帝国，为后来的君士坦丁大帝奠定了基础。',
    relatedEvents: [],
    background: '罗马帝国在3世纪面临着严重的危机，经济衰退，政治动荡。',
    cause: '公元284年，戴克里先成为罗马皇帝。',
    significance: '戴克里先的改革暂时稳定了罗马帝国，四帝共治制度为帝国的管理提供了新的模式。',
  },
  {
    id: '313-01',
    year: 313,
    startYear: 313,
    endYear: 313,
    title: '米兰敕令',
    description: '君士坦丁颁布米兰敕令，宣布基督教合法化。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['君士坦丁'],
    impact: '基督教成为罗马帝国的国教，对西方文明产生深远影响。',
    relatedEvents: [],
    background: '基督教在罗马帝国初期受到迫害，但信徒不断增加。',
    cause: '公元313年，君士坦丁颁布米兰敕令。',
    significance: '米兰敕令的颁布是基督教历史上的转折点，基督教从一个受迫害的宗教转变为合法宗教。',
  },
  {
    id: '330-01',
    year: 330,
    startYear: 330,
    endYear: 330,
    title: '君士坦丁堡建立',
    description: '君士坦丁将罗马帝国首都迁至拜占庭，改名为君士坦丁堡。',
    category: 'politics',
    region: '欧亚',
    keyFigures: ['君士坦丁'],
    impact: '奠定了拜占庭帝国的基础，成为东西方文明的交汇点。',
    relatedEvents: [],
    background: '君士坦丁希望建立一个新的首都，远离罗马的政治纷争。',
    cause: '公元330年，君士坦丁将首都迁至拜占庭。',
    significance: '君士坦丁堡的建立标志着罗马帝国重心的东移，成为拜占庭帝国的首都。',
  },
  {
    id: '395-01',
    year: 395,
    startYear: 395,
    endYear: 395,
    title: '罗马帝国分裂',
    description: '罗马帝国分裂为东罗马帝国和西罗马帝国。',
    category: 'politics',
    region: '欧洲',
    keyFigures: [],
    impact: '西罗马帝国逐渐衰落，东罗马帝国继续存在千年。',
    relatedEvents: [],
    background: '罗马帝国后期，政治腐败、经济衰退，帝国难以维持统一。',
    cause: '公元395年，罗马皇帝狄奥多西一世去世，帝国分裂。',
    significance: '罗马帝国的分裂标志着古代世界的终结和中世纪的开始。',
  },
  {
    id: '410-01',
    year: 410,
    startYear: 410,
    endYear: 410,
    title: '罗马被洗劫',
    description: '西哥特人攻陷罗马，洗劫了这座城市。',
    category: 'wars',
    region: '欧洲',
    keyFigures: [],
    impact: '西罗马帝国的威望受到严重打击，加速了其灭亡。',
    relatedEvents: [],
    background: '西罗马帝国后期，日耳曼人不断入侵。',
    cause: '公元410年，西哥特人攻陷罗马。',
    significance: '罗马的被洗劫是西罗马帝国衰落的重要标志，它标志着罗马帝国的辉煌时代结束。',
  },
  {
    id: '451-01',
    year: 451,
    startYear: 451,
    endYear: 451,
    title: '沙隆战役',
    description: '罗马联军在沙隆战役中击败匈奴军队。',
    category: 'wars',
    region: '欧洲',
    keyFigures: ['阿提拉'],
    impact: '阻止了匈奴对西欧的入侵，保卫了基督教文明。',
    relatedEvents: [],
    background: '匈奴帝国在阿提拉统治下不断扩张，威胁着西欧各国。',
    cause: '公元451年，罗马联军在沙隆战役中击败匈奴军队。',
    significance: '沙隆战役是古代世界最重要的战役之一，它阻止了匈奴对西欧的入侵。',
  },
  {
    id: '455-01',
    year: 455,
    startYear: 455,
    endYear: 455,
    title: '汪达尔人洗劫罗马',
    description: '汪达尔人攻陷罗马，再次洗劫了这座城市。',
    category: 'wars',
    region: '欧洲',
    keyFigures: [],
    impact: '西罗马帝国进一步衰落，灭亡已成定局。',
    relatedEvents: [],
    background: '汪达尔人在北非建立了王国，开始进攻意大利。',
    cause: '公元455年，汪达尔人攻陷罗马。',
    significance: '汪达尔人洗劫罗马是西罗马帝国灭亡前的重要事件，它标志着西罗马帝国的彻底衰落。',
  },
  {
    id: '476-01',
    year: 476,
    startYear: 476,
    endYear: 476,
    title: '西罗马帝国灭亡',
    description: '日耳曼人奥多亚克废黜西罗马帝国皇帝，西罗马帝国灭亡。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['奥多亚克'],
    impact: '标志着古代世界的终结和中世纪的开始。',
    relatedEvents: [],
    background: '西罗马帝国后期，政治腐败、经济衰退、军事衰弱。',
    cause: '公元476年，奥多亚克废黜西罗马帝国皇帝。',
    significance: '西罗马帝国的灭亡标志着古代世界的终结和中世纪的开始。',
  },
  {
    id: '527-01',
    year: 527,
    startYear: 527,
    endYear: 565,
    title: '查士丁尼大帝',
    description: '查士丁尼成为拜占庭帝国皇帝，试图恢复罗马帝国的辉煌。',
    category: 'monarch',
    region: '欧亚',
    keyFigures: ['查士丁尼'],
    impact: '编纂了《查士丁尼法典》，为后来的法律体系奠定了基础。',
    relatedEvents: [],
    background: '拜占庭帝国在查士丁尼统治下达到了鼎盛时期。',
    cause: '公元527年，查士丁尼成为拜占庭帝国皇帝。',
    significance: '查士丁尼大帝是拜占庭帝国最伟大的皇帝之一，他的法典对后来的法律体系产生了重要影响。',
  },
  {
    id: '532-01',
    year: 532,
    startYear: 532,
    endYear: 532,
    title: '尼卡暴动',
    description: '君士坦丁堡发生尼卡暴动，查士丁尼镇压了起义。',
    category: 'revolution',
    region: '欧亚',
    keyFigures: ['查士丁尼'],
    impact: '巩固了查士丁尼的统治，重建了君士坦丁堡。',
    relatedEvents: [],
    background: '君士坦丁堡的民众因不满查士丁尼的统治而发动起义。',
    cause: '公元532年，君士坦丁堡发生尼卡暴动。',
    significance: '尼卡暴动是拜占庭帝国历史上最严重的起义之一，查士丁尼的镇压巩固了他的统治。',
  },
  {
    id: '535-01',
    year: 535,
    startYear: 535,
    endYear: 554,
    title: '哥特战争',
    description: '查士丁尼派遣贝利撒留征服意大利，与哥特人进行了长期战争。',
    category: 'wars',
    region: '欧洲',
    keyFigures: ['贝利撒留'],
    impact: '拜占庭帝国短暂恢复了对意大利的统治。',
    relatedEvents: [],
    background: '查士丁尼希望恢复罗马帝国的疆域。',
    cause: '公元535年，贝利撒留率军入侵意大利。',
    significance: '哥特战争是拜占庭帝国试图恢复罗马帝国疆域的重要战争，但最终未能持久。',
  },
  {
    id: '541-01',
    year: 541,
    startYear: 541,
    endYear: 542,
    title: '查士丁尼瘟疫',
    description: '拜占庭帝国爆发大规模瘟疫，造成大量人口死亡。',
    category: 'warning',
    region: '欧亚',
    keyFigures: [],
    impact: '拜占庭帝国国力衰退，查士丁尼的征服计划受阻。',
    relatedEvents: [],
    background: '瘟疫从埃及传入拜占庭帝国，迅速蔓延。',
    cause: '公元541年，瘟疫在拜占庭帝国爆发。',
    significance: '查士丁尼瘟疫是古代世界最严重的瘟疫之一，它造成了大量人口死亡，削弱了拜占庭帝国的国力。',
  },
  {
    id: '568-01',
    year: 568,
    startYear: 568,
    endYear: 774,
    title: '伦巴第人入侵意大利',
    description: '伦巴第人入侵意大利，建立了伦巴第王国。',
    category: 'politics',
    region: '欧洲',
    keyFigures: [],
    impact: '意大利再次陷入分裂，拜占庭帝国失去了对意大利的控制。',
    relatedEvents: [],
    background: '伦巴第人是日耳曼人的一支，他们在6世纪入侵意大利。',
    cause: '公元568年，伦巴第人入侵意大利。',
    significance: '伦巴第人的入侵标志着意大利再次陷入分裂，拜占庭帝国失去了对意大利的控制。',
  },
  {
    id: '610-01',
    year: 610,
    startYear: 610,
    endYear: 641,
    title: '希拉克略',
    description: '希拉克略成为拜占庭帝国皇帝，进行了一系列改革。',
    category: 'monarch',
    region: '欧亚',
    keyFigures: ['希拉克略'],
    impact: '挽救了拜占庭帝国，抵御了萨珊波斯的入侵。',
    relatedEvents: [],
    background: '拜占庭帝国在7世纪面临着严重的外部威胁。',
    cause: '公元610年，希拉克略成为拜占庭帝国皇帝。',
    significance: '希拉克略是拜占庭帝国历史上最重要的皇帝之一，他挽救了拜占庭帝国。',
  },
  {
    id: '622-01',
    year: 622,
    startYear: 622,
    endYear: 632,
    title: '穆罕默德迁徙',
    description: '穆罕默德从麦加迁徙到麦地那，建立了第一个伊斯兰政权。',
    category: 'culture',
    region: '亚洲',
    keyFigures: ['穆罕默德'],
    impact: '伊斯兰教开始传播，阿拉伯帝国崛起。',
    relatedEvents: [],
    background: '穆罕默德在麦加受到迫害，被迫迁徙到麦地那。',
    cause: '公元622年，穆罕默德从麦加迁徙到麦地那。',
    significance: '穆罕默德的迁徙标志着伊斯兰教的开始，伊斯兰历以此为元年。',
  },
  {
    id: '630-01',
    year: 630,
    startYear: 630,
    endYear: 630,
    title: '穆罕默德征服麦加',
    description: '穆罕默德率领穆斯林征服麦加，麦加成为伊斯兰教圣地。',
    category: 'politics',
    region: '亚洲',
    keyFigures: ['穆罕默德'],
    impact: '伊斯兰教在阿拉伯半岛确立了统治地位。',
    relatedEvents: [],
    background: '穆罕默德在麦地那建立政权后，开始征服阿拉伯半岛。',
    cause: '公元630年，穆罕默德率领穆斯林征服麦加。',
    significance: '穆罕默德征服麦加标志着伊斯兰教在阿拉伯半岛确立了统治地位。',
  },
  {
    id: '632-01',
    year: 632,
    startYear: 632,
    endYear: 632,
    title: '穆罕默德去世',
    description: '穆罕默德去世，阿布·伯克尔成为第一任哈里发。',
    category: 'politics',
    region: '亚洲',
    keyFigures: ['穆罕默德', '阿布·伯克尔'],
    impact: '伊斯兰教开始向外扩张，阿拉伯帝国开始建立。',
    relatedEvents: [],
    background: '穆罕默德去世后，阿拉伯半岛需要新的领导人。',
    cause: '公元632年，穆罕默德去世。',
    significance: '穆罕默德的去世标志着伊斯兰教先知时代的结束，阿拉伯帝国开始建立。',
  },
  {
    id: '636-01',
    year: 636,
    startYear: 636,
    endYear: 636,
    title: '雅穆克战役',
    description: '阿拉伯军队在雅穆克战役中击败拜占庭帝国军队。',
    category: 'wars',
    region: '亚洲',
    keyFigures: [],
    impact: '阿拉伯帝国开始征服叙利亚和巴勒斯坦。',
    relatedEvents: [],
    background: '阿拉伯帝国在哈里发的领导下开始向外扩张。',
    cause: '公元636年，阿拉伯军队在雅穆克战役中击败拜占庭帝国军队。',
    significance: '雅穆克战役是阿拉伯帝国扩张的重要战役，它为阿拉伯帝国征服叙利亚和巴勒斯坦奠定了基础。',
  },
  {
    id: '642-01',
    year: 642,
    startYear: 642,
    endYear: 642,
    title: '征服埃及',
    description: '阿拉伯军队征服埃及，拜占庭帝国失去了对埃及的控制。',
    category: 'wars',
    region: '非洲',
    keyFigures: [],
    impact: '阿拉伯帝国获得了重要的粮食产地，国力增强。',
    relatedEvents: [],
    background: '阿拉伯帝国在征服叙利亚后，开始进攻埃及。',
    cause: '公元642年，阿拉伯军队征服埃及。',
    significance: '埃及的征服是阿拉伯帝国扩张的重要一步，它为阿拉伯帝国提供了重要的粮食和财富。',
  },
  {
    id: '651-01',
    year: 651,
    startYear: 651,
    endYear: 651,
    title: '征服萨珊波斯',
    description: '阿拉伯军队征服萨珊波斯帝国，波斯成为阿拉伯帝国的一部分。',
    category: 'wars',
    region: '亚洲',
    keyFigures: [],
    impact: '阿拉伯帝国成为中东地区的霸主。',
    relatedEvents: [],
    background: '阿拉伯帝国在征服叙利亚和埃及后，开始进攻萨珊波斯。',
    cause: '公元651年，阿拉伯军队征服萨珊波斯。',
    significance: '萨珊波斯的征服标志着阿拉伯帝国成为中东地区的霸主，波斯文明融入了伊斯兰文明。',
  },
  {
    id: '661-01',
    year: 661,
    startYear: 661,
    endYear: 750,
    title: '倭马亚王朝',
    description: '穆阿维叶建立倭马亚王朝，阿拉伯帝国进入鼎盛时期。',
    category: 'politics',
    region: '全球',
    keyFigures: ['穆阿维叶'],
    impact: '阿拉伯帝国疆域达到最大，文化和科学繁荣。',
    relatedEvents: [],
    background: '阿拉伯帝国在经历了内乱后，穆阿维叶建立了倭马亚王朝。',
    cause: '公元661年，穆阿维叶成为哈里发，建立倭马亚王朝。',
    significance: '倭马亚王朝是阿拉伯帝国历史上最辉煌的时期之一，其疆域达到了历史最大范围。',
  },
  {
    id: '711-01',
    year: 711,
    startYear: 711,
    endYear: 718,
    title: '征服伊比利亚半岛',
    description: '阿拉伯军队征服伊比利亚半岛，建立了安达卢斯王国。',
    category: 'wars',
    region: '欧洲',
    keyFigures: [],
    impact: '伊斯兰文明传入欧洲，对西班牙和葡萄牙的文化产生深远影响。',
    relatedEvents: [],
    background: '阿拉伯帝国在倭马亚王朝时期不断扩张，开始向欧洲进军。',
    cause: '公元711年，阿拉伯将领塔里克率领军队入侵伊比利亚半岛。',
    significance: '阿拉伯征服伊比利亚半岛是伊斯兰文明向西扩张的重要事件，它使伊比利亚半岛成为伊斯兰世界的一部分长达八百年。',
  },
  {
    id: '732-01',
    year: 732,
    startYear: 732,
    endYear: 732,
    title: '普瓦捷战役',
    description: '法兰克王国在普瓦捷战役中击败阿拉伯军队。',
    category: 'wars',
    region: '欧洲',
    keyFigures: ['查理·马特'],
    impact: '阻止了阿拉伯帝国对西欧的进一步入侵。',
    relatedEvents: [],
    background: '阿拉伯帝国在征服伊比利亚半岛后，开始进攻法兰克王国。',
    cause: '公元732年，法兰克王国在普瓦捷战役中击败阿拉伯军队。',
    significance: '普瓦捷战役是欧洲历史上最重要的战役之一，它阻止了阿拉伯帝国对西欧的进一步入侵。',
  },
  {
    id: '750-01',
    year: 750,
    startYear: 750,
    endYear: 1258,
    title: '阿拔斯王朝',
    description: '阿拔斯王朝建立，阿拉伯帝国进入新的时期。',
    category: 'politics',
    region: '亚洲',
    keyFigures: [],
    impact: '巴格达成为文化和科学中心，伊斯兰文明达到鼎盛。',
    relatedEvents: [],
    background: '倭马亚王朝被阿拔斯王朝取代，阿拉伯帝国的重心东移。',
    cause: '公元750年，阿拔斯王朝建立。',
    significance: '阿拔斯王朝是阿拉伯帝国历史上最重要的时期之一，巴格达成为文化和科学中心。',
  },
  {
    id: '768-01',
    year: 768,
    startYear: 768,
    endYear: 814,
    title: '查理曼大帝',
    description: '查理曼成为法兰克王国国王，建立了庞大的帝国。',
    category: 'monarch',
    region: '欧洲',
    keyFigures: ['查理曼'],
    impact: '统一了西欧大部分地区，被教皇加冕为"罗马人的皇帝"。',
    relatedEvents: [],
    background: '法兰克王国在查理曼统治下不断扩张。',
    cause: '公元768年，查理曼成为法兰克王国国王。',
    significance: '查理曼大帝是中世纪欧洲最伟大的统治者之一，他的帝国成为后来神圣罗马帝国的基础。',
  },
  {
    id: '800-01',
    year: 800,
    startYear: 800,
    endYear: 800,
    title: '查理曼加冕',
    description: '教皇利奥三世在罗马圣彼得大教堂为查理曼加冕为皇帝。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['查理曼', '利奥三世'],
    impact: '查理曼成为"罗马人的皇帝"，奠定了神圣罗马帝国的基础。',
    relatedEvents: [],
    background: '查理曼统一了西欧大部分地区，教皇为他加冕。',
    cause: '公元800年，教皇利奥三世为查理曼加冕。',
    significance: '查理曼的加冕标志着西欧的统一，为神圣罗马帝国的建立奠定了基础。',
  },
  {
    id: '843-01',
    year: 843,
    startYear: 843,
    endYear: 843,
    title: '凡尔登条约',
    description: '查理曼帝国分裂为东法兰克、中法兰克和西法兰克三个部分。',
    category: 'treaty',
    region: '欧洲',
    keyFigures: [],
    impact: '奠定了后来德国、法国和意大利的基础。',
    relatedEvents: [],
    background: '查理曼去世后，他的子孙为争夺帝国继承权发生内战。',
    cause: '公元843年，查理曼的三个孙子签订凡尔登条约，瓜分了帝国。',
    significance: '凡尔登条约是欧洲历史上最重要的条约之一，它奠定了后来德国、法国和意大利的基础。',
  },
  {
    id: '871-01',
    year: 871,
    startYear: 871,
    endYear: 899,
    title: '阿尔弗雷德大帝',
    description: '阿尔弗雷德成为英格兰国王，抵御了维京人的入侵。',
    category: 'monarch',
    region: '欧洲',
    keyFigures: ['阿尔弗雷德'],
    impact: '奠定了英格兰王国的基础，推动了教育和文化的发展。',
    relatedEvents: [],
    background: '英格兰在9世纪面临着维京人的入侵。',
    cause: '公元871年，阿尔弗雷德成为英格兰国王。',
    significance: '阿尔弗雷德大帝是英格兰历史上最伟大的国王之一，他抵御了维京人的入侵，奠定了英格兰王国的基础。',
  },
  {
    id: '962-01',
    year: 962,
    startYear: 962,
    endYear: 1806,
    title: '神圣罗马帝国',
    description: '奥托一世被教皇加冕为"罗马人的皇帝"，神圣罗马帝国建立。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['奥托一世'],
    impact: '成为中欧地区最重要的政治实体，延续了近千年。',
    relatedEvents: [],
    background: '东法兰克王国在奥托一世统治下不断强大。',
    cause: '公元962年，奥托一世被教皇加冕为皇帝。',
    significance: '神圣罗马帝国是欧洲历史上最重要的政治实体之一，延续了近千年。',
  },
  {
    id: '1000-01',
    year: 1000,
    startYear: 1000,
    endYear: 1000,
    title: '千年庆典',
    description: '欧洲各地庆祝基督教千年，宗教热情达到高潮。',
    category: 'culture',
    region: '欧洲',
    keyFigures: [],
    impact: '推动了宗教建筑和艺术的发展。',
    relatedEvents: [],
    background: '基督教在欧洲已经传播了一千年，人们期待着千年的到来。',
    cause: '公元1000年，欧洲各地庆祝基督教千年。',
    significance: '千年庆典是中世纪欧洲宗教生活中的重要事件，它推动了宗教建筑和艺术的发展。',
  },
  {
    id: '1054-01',
    year: 1054,
    startYear: 1054,
    endYear: 1054,
    title: '东西教会分裂',
    description: '基督教分裂为东正教和天主教，东西方教会正式决裂。',
    category: 'culture',
    region: '欧洲',
    keyFigures: [],
    impact: '基督教分裂为两大教派，影响持续至今。',
    relatedEvents: [],
    background: '东西方教会在教义和权力上存在长期分歧。',
    cause: '公元1054年，教皇利奥九世和君士坦丁堡牧首互相开除教籍。',
    significance: '东西教会分裂是基督教历史上的重大事件，它标志着东西方教会的正式决裂。',
  },
  {
    id: '1066-01',
    year: 1066,
    startYear: 1066,
    endYear: 1066,
    title: '诺曼征服',
    description: '诺曼底公爵威廉征服英格兰，建立诺曼王朝。',
    category: 'politics',
    region: '欧洲',
    keyFigures: ['威廉'],
    impact: '改变了英格兰的政治、文化和社会结构。',
    relatedEvents: [],
    background: '英格兰国王爱德华去世后，威廉声称自己有继承权。',
    cause: '公元1066年，威廉在黑斯廷斯战役中击败英格兰军队。',
    significance: '诺曼征服是英国历史上的重要转折点，它将法国文化和制度引入英格兰。',
  },
  {
    id: '1096-01',
    year: 1096,
    startYear: 1096,
    endYear: 1291,
    title: '十字军东征',
    description: '欧洲基督徒发起十字军东征，试图夺回圣地耶路撒冷。',
    category: 'wars',
    region: '全球',
    keyFigures: [],
    impact: '促进了东西方文化交流，对欧洲和中东产生深远影响。',
    relatedEvents: [],
    background: '塞尔柱土耳其人占领了耶路撒冷，基督教徒渴望夺回圣地。',
    cause: '公元1096年，教皇乌尔班二世号召十字军东征。',
    significance: '十字军东征是中世纪欧洲最重要的军事行动，它促进了东西方文化交流，对欧洲和中东产生了深远影响。',
  },
  {
    id: '1147-01',
    year: 1147,
    startYear: 1147,
    endYear: 1149,
    title: '第二次十字军东征',
    description: '欧洲基督徒发起第二次十字军东征，试图支援埃德萨伯国。',
    category: 'wars',
    region: '全球',
    keyFigures: [],
    impact: '未能达到目标，十字军运动开始衰落。',
    relatedEvents: [],
    background: '埃德萨伯国被塞尔柱土耳其人占领，欧洲基督徒发起第二次十字军东征。',
    cause: '公元1147年，第二次十字军东征开始。',
    significance: '第二次十字军东征未能达到目标，标志着十字军运动开始衰落。',
  },
  {
    id: '1189-01',
    year: 1189,
    startYear: 1189,
    endYear: 1192,
    title: '第三次十字军东征',
    description: '欧洲基督徒发起第三次十字军东征，理查一世参与其中。',
    category: 'wars',
    region: '全球',
    keyFigures: ['理查一世', '萨拉丁'],
    impact: '理查一世与萨拉丁达成停战协议，耶路撒冷仍在穆斯林控制下。',
    relatedEvents: [],
    background: '萨拉丁夺回了耶路撒冷，欧洲基督徒发起第三次十字军东征。',
    cause: '公元1189年，第三次十字军东征开始。',
    significance: '第三次十字军东征是十字军运动中最著名的一次，理查一世与萨拉丁的对决成为历史传奇。',
  },
  {
    id: '1202-01',
    year: 1202,
    startYear: 1202,
    endYear: 1204,
    title: '第四次十字军东征',
    description: '十字军攻陷君士坦丁堡，洗劫了这座城市。',
    category: 'wars',
    region: '欧亚',
    keyFigures: [],
    impact: '拜占庭帝国受到重创，东西方教会关系进一步恶化。',
    relatedEvents: [],
    background: '十字军在前往圣地的途中，被威尼斯人说服攻打君士坦丁堡。',
    cause: '公元1204年，十字军攻陷君士坦丁堡。',
    significance: '第四次十字军东征是十字军运动中最具争议的一次，它对拜占庭帝国造成了严重破坏。',
  },
  {
    id: '1215-01',
    year: 1215,
    startYear: 1215,
    endYear: 1215,
    title: '大宪章',
    description: '英格兰国王约翰签署大宪章，限制了国王的权力。',
    category: 'treaty',
    region: '欧洲',
    keyFigures: ['约翰'],
    impact: '奠定了英国宪法的基础，对民主制度产生深远影响。',
    relatedEvents: [],
    background: '英格兰贵族不满约翰国王的统治，迫使他签署大宪章。',
    cause: '公元1215年6月15日，约翰国王签署大宪章。',
    significance: '大宪章是英国宪法的基础，它限制了国王的权力，保障了贵族的权利，对民主制度产生了深远影响。',
  },
  {
    id: '1230-01',
    year: 1230,
    startYear: 1230,
    endYear: 1240,
    title: '蒙古西征',
    description: '蒙古帝国发动第二次西征，征服了俄罗斯和东欧。',
    category: 'wars',
    region: '全球',
    keyFigures: ['拔都'],
    impact: '蒙古帝国疆域达到最大，对欧洲产生深远影响。',
    relatedEvents: [],
    background: '蒙古帝国在成吉思汗去世后，继续扩张。',
    cause: '公元1230年，蒙古帝国发动第二次西征。',
    significance: '蒙古西征是世界历史上最重要的军事远征之一，它征服了从东亚到东欧的广阔地区。',
  },
  {
    id: '1248-01',
    year: 1248,
    startYear: 1248,
    endYear: 1254,
    title: '第七次十字军东征',
    description: '法国国王路易九世发起第七次十字军东征。',
    category: 'wars',
    region: '全球',
    keyFigures: ['路易九世'],
    impact: '路易九世被俘，十字军东征再次失败。',
    relatedEvents: [],
    background: '路易九世希望通过十字军东征来扩大自己的影响力。',
    cause: '公元1248年，路易九世发起第七次十字军东征。',
    significance: '第七次十字军东征的失败标志着十字军运动的终结。',
  },
  {
    id: '1258-01',
    year: 1258,
    startYear: 1258,
    endYear: 1258,
    title: '蒙古攻陷巴格达',
    description: '蒙古军队攻陷巴格达，阿拔斯王朝灭亡。',
    category: 'wars',
    region: '亚洲',
    keyFigures: [],
    impact: '阿拉伯帝国正式灭亡，伊斯兰文明中心东移。',
    relatedEvents: [],
    background: '蒙古帝国在旭烈兀的率领下进攻阿拔斯王朝。',
    cause: '公元1258年，蒙古军队攻陷巴格达。',
    significance: '巴格达的陷落标志着阿拔斯王朝的灭亡，伊斯兰文明的中心从巴格达转移到了开罗和伊斯坦布尔。',
  },
  {
    id: '1261-01',
    year: 1261,
    startYear: 1261,
    endYear: 1261,
    title: '拜占庭复国',
    description: '拜占庭帝国在米海尔八世的领导下收复君士坦丁堡。',
    category: 'politics',
    region: '欧亚',
    keyFigures: ['米海尔八世'],