export default {
  pages: [
    'pages/index/index',
    'pages/camps/index',
    'pages/camp-detail/index',
    'pages/submit/index',
    'pages/portfolio/index',
    'pages/certificates/index',
    'pages/profile/index',
    'pages/workspace/index',
    'pages/workspace/inquiry',
    'pages/workspace/reflection',
    'pages/workspace/critique',
    'pages/workspace/group',
    'pages/showcase/index',
    'pages/showcase/detail',
    'pages/credits/index',
    'pages/internships/index',
    'pages/resources/index',
    'pages/notifications/index',
    'pages/demand-detail/index',
    'pages/cross-task-detail/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#1677ff',
    navigationBarTitleText: 'PBL项目学习',
    navigationBarTextStyle: 'white',
  },
  tabBar: {
    color: '#8c8c8c',
    selectedColor: '#1677ff',
    backgroundColor: '#ffffff',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/icons/home.png',
        selectedIconPath: 'assets/icons/home-active.png',
      },
      {
        pagePath: 'pages/camps/index',
        text: '营期',
        iconPath: 'assets/icons/camp.png',
        selectedIconPath: 'assets/icons/camp-active.png',
      },
      {
        pagePath: 'pages/portfolio/index',
        text: '作品集',
        iconPath: 'assets/icons/portfolio.png',
        selectedIconPath: 'assets/icons/portfolio-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/icons/profile.png',
        selectedIconPath: 'assets/icons/profile-active.png',
      },
    ],
  },
};