# Generated by Django 4.2 on 2026-01-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100, verbose_name='商户名称')),
                ('merchant_logo', models.URLField(blank=True, max_length=255, null=True, verbose_name='商户Logo链接')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系人电话')),
                ('merchant_address', models.CharField(max_length=255, verbose_name='商户地址')),
                ('merchant_desc', models.TextField(blank=True, null=True, verbose_name='商户描述')),
                ('status', models.SmallIntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '未通过')], default=0, verbose_name='商户状态')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_info', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '商户信息表',
                'verbose_name_plural': '商户信息表',
                'db_table': 'merchant',
            },
        ),
    ]
