database-sync:
  sync-pairs:
    - name: "a2b"
      source:
        type: "mysql"
        url: "jdbc:mysql://localhost:3306/your_source_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
        username: "your_username"
        password: "your_password"
      target:
        type: "mysql"
        url: "jdbc:mysql://localhost:3306/your_target_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
        username: "your_username"
        password: "your_password"
      tables:
        - table: "table1"
          sync-mode: "full"
        - table: "table2"
          incremental-config:
            identifier-expression: "ifnull(update_time, create_time)"
    - name: "c2d"
      source:
        type: "sqlserver"
        url: "jdbc:sqlserver://localhost:1433;database=your_source_db"
        username: "your_username"
        password: "your_username021"
      target:
        type: "mysql"
        url: "jdbc:mysql://localhost:3306/your_target_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
        username: "your_username"
        password: "your_password"
      tables:
        - table: "table3"
          sync-mode: "full"
          zh-converter-config:
            enabled: true
            direction: "t2s"  # s2t: 简体到繁体, t2s: 繁体到简体
        - table: "table4"
          sync-mode: "full"
          zh-converter-config:
            enabled: true
            direction: "t2s"  # s2t: 简体到繁体, t2s: 繁体到简体
  # 定时同步配置
  scheduler:
    tasks:
      - name: "task1"
        enabled: true
        cron: "0 7/10 * * * ?"  # 每十分钟执行一次
        sync-pairs: ["a2b"]
      - name: "task2"
        enabled: true
        cron: "0 39 0/1 * * ?"  # 每1小时执行一次
        sync-pairs: ["c2d"]

logging:
  file:
    name: ./logs/database-sync.log
  logback:
    rollingpolicy:
      max-history: 2
