spring:
  application:
    name: database-sync
  profiles:
    active: pro

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc: DEBUG
    net.dbsync.databasesync: DEBUG
  charset:
    file: UTF-8