# Generated by Django 4.2 on 2026-01-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='优惠券名称')),
                ('type', models.SmallIntegerField(choices=[(1, '满减券'), (2, '折扣券'), (3, '无门槛券')], verbose_name='优惠券类型')),
                ('condition', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='使用条件')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优惠价值')),
                ('start_time', models.DateTimeField(verbose_name='有效期开始时间')),
                ('end_time', models.DateTimeField(verbose_name='有效期结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '优惠券表',
                'verbose_name_plural': '优惠券表',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], default=1, verbose_name='状态')),
                ('get_time', models.DateTimeField(auto_now_add=True, verbose_name='获取时间')),
                ('use_time', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='coupon.coupon', verbose_name='关联优惠券')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_coupons', to='order.order', verbose_name='使用关联的订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户优惠券关联表',
                'verbose_name_plural': '用户优惠券关联表',
                'db_table': 'user_coupon',
            },
        ),
    ]
