// 虚拟人物：陈志远 — 42岁中层管理者
// 企业级丰满个人档案 + 记忆数据，用于衡舟 Demo 演示

import { db } from './db'
import { rebuildIndex } from './vectorStore'
import type { Person, Memory, DiaryEntry } from '../types'
import { EXPANDED_PEOPLE, EXPANDED_MEMORIES } from './expandedDemoData'

// ============================================================
// 辅助函数
// ============================================================
const now = Date.now()
const daysAgo = (d: number) => now - d * 86400000

// ============================================================
// 陈志远本人档案（"我"）
// ============================================================
const SELF: Person = {
  id: 'p-self',
  name: '陈志远',
  relationship: 'other',
  sentiment: 55,
  sentimentHistory: [
    { timestamp: daysAgo(365), value: 72, reason: '工作稳定，家庭和睦' },
    { timestamp: daysAgo(180), value: 65, reason: '王思亮空降，感到威胁' },
    { timestamp: daysAgo(90), value: 58, reason: 'Q2 KPI未达标，压力增大' },
    { timestamp: daysAgo(30), value: 62, reason: '五一千岛湖出游，短暂放松' },
    { timestamp: daysAgo(7), value: 48, reason: '体检异常+职业危机+创业诱惑' },
    { timestamp: daysAgo(1), value: 45, reason: '王思亮周会再次施压' },
  ],
  profile: {
    identity: {
      fullName: '陈志远',
      nicknames: ['志远', '陈哥', '老陈'],
      gender: 'male',
      age: 42,
      birthday: '09-18',
      zodiac: '处女座',
      hometown: '绍兴',
      currentCity: '杭州',
    },
    career: {
      company: '杭州云启科技有限公司',
      title: '运营总监',
      department: '运营部',
      industry: '互联网',
      workStyle: '稳重务实，注重团队协作，不擅长向上管理和政治斗争',
      strengths: ['团队管理', '数据分析', '项目统筹', '跨部门协调'],
      weaknesses: ['不擅长向上管理', '对变化适应慢', '过于信任下属', '回避冲突'],
      careerHistory: [
        { company: '阿里巴巴', title: '运营专员', period: '2008-2012', highlights: ['参与淘宝双11早期运营'] },
        { company: '网易', title: '高级运营经理', period: '2012-2016', highlights: ['负责网易云音乐用户增长'] },
        { company: '云启科技', title: '运营总监', period: '2016-至今', highlights: ['从0搭建运营团队', '用户增长300%'] },
      ],
    },
    personality: {
      openness: 55,
      conscientiousness: 75,
      extraversion: 50,
      agreeableness: 70,
      neuroticism: 65,
      mbti: 'ISFJ',
      description: '内敛负责的守护者型，重视稳定和责任。工作中可靠但缺乏野心，家庭中有责任感但沟通不够。容易内耗，习惯独自承受压力。',
    },
    preferences: {
      likes: ['白酒', '老歌', '车里独处', '周末钓鱼', '看足球', '粤菜'],
      dislikes: ['办公室政治', '临时加班', '公开演讲', '被比较', '体检'],
      allergies: ['花粉'],
      dietary: ['喜欢粤菜', '爱吃海鲜', '晚上不吃碳水'],
      hobbies: ['钓鱼', '足球', '品茶', '老歌'],
      communicationStyle: '内敛含蓄，不擅长直接表达情感。压力大时选择沉默或逃避。对亲近的人偶尔急躁，事后后悔。',
    },
    values: {
      coreValues: ['家庭责任', '职业尊严', '稳定安全', '真诚待人'],
      motivations: ['给家人更好的生活', '证明自己能力', '获得认可和尊重', '不想让父母失望'],
      fears: ['失业', '家庭破裂', '健康出问题', '被时代淘汰', '让父母失望'],
      goals: ['度过职业危机', '改善健康状况', '修复夫妻关系', '找到人生新方向'],
    },
    socialRole: {
      roleInMyLife: '我自己——需要被理解和关怀',
      myRoleInTheirLife: '我自己',
      powerDynamic: 'equal',
      trustLevel: 60,
      intimacyLevel: 70,
    },
    sharedExperiences: [],
  },
  timeline: [
    { id: 'te-self-1', timestamp: daysAgo(365), type: 'milestone', title: '入职云启8周年', description: '从专员做到总监，但感到天花板', sentiment: 65, relatedMemoryIds: [] },
    { id: 'te-self-2', timestamp: daysAgo(180), type: 'observation', title: '王思亮空降', description: '感到职业威胁，开始焦虑', sentiment: 50, relatedMemoryIds: [] },
    { id: 'te-self-3', timestamp: daysAgo(8), type: 'observation', title: '体检异常', description: '甘油三酯偏高，血压临界', sentiment: 35, relatedMemoryIds: [] },
    { id: 'te-self-4', timestamp: daysAgo(1), type: 'conflict', title: '周会被敲打', description: '王思亮公开质疑运营数据', sentiment: 25, relatedMemoryIds: [] },
  ],
  connections: [
      { targetPersonId: 'p-mom', targetPersonName: '陈秀兰', relationType: 'family', strength: 95, description: '母子关系，母亲独居绍兴，每周通话' },
      { targetPersonId: 'p-linxw', targetPersonName: '林晓薇', relationType: 'family', strength: 85, description: '夫妻关系，结婚15年，育有一子' },
      { targetPersonId: 'p-chenyn', targetPersonName: '陈一诺', relationType: 'family', strength: 90, description: '父子关系，一诺是独生子' },
      { targetPersonId: 'p-wangsl', targetPersonName: '王思亮', relationType: 'colleague', strength: 40, description: '直属上级，空降管理层，关系紧张' },
      { targetPersonId: 'p-liuwyan', targetPersonName: '刘文燕', relationType: 'colleague', strength: 60, description: '下属，工作能力强的运营经理' },
      { targetPersonId: 'p-zhaohm', targetPersonName: '赵海明', relationType: 'friend', strength: 55, description: '老同学，在杭州做互联网' },
      // FIX: 多线关系 — 赵海明既是老同学也是潜在创业伙伴
      { targetPersonId: 'p-zhaohm', targetPersonName: '赵海明', relationType: 'partner', strength: 65, description: '潜在创业合伙人，酒后说过"来我这儿一起干"' },
      // FIX: 多线关系 — 刘涛既是朋友也是投资引路人
      { targetPersonId: 'p-liut', targetPersonName: '刘涛', relationType: 'friend', strength: 70, description: '老朋友，钓鱼搭子，性格直爽' },
      { targetPersonId: 'p-liut', targetPersonName: '刘涛', relationType: 'other', strength: 50, description: '投资信息来源，介绍了跨境电商项目' },
    ],
    traits: ['42岁运营总监', '已婚有子', 'ISFJ守护者', '压力大', '职业危机'],
  tags: ['我自己', '处女座', '运营总监', '杭州', '职业危机'],
  interactionStats: {
    totalCount: 0,
    lastInteractionAt: now,
    avgSentiment: 55,
    topics: ['工作', '家庭', '健康', '未来'],
  },
  createdAt: daysAgo(365),
  updatedAt: now,
}

// ============================================================
// 人物档案 — 企业级多维度画像
// ============================================================
const PEOPLE: Person[] = [
  SELF,
  {
    id: 'p-linxw',
    name: '林晓薇',
    relationship: 'spouse',
    sentiment: 78,
    sentimentHistory: [
      { timestamp: daysAgo(365), value: 85, reason: '结婚十周年纪念' },
      { timestamp: daysAgo(300), value: 82, reason: '一起规划一诺的教育' },
      { timestamp: daysAgo(250), value: 75, reason: '陈志远开始频繁加班' },
      { timestamp: daysAgo(200), value: 70, reason: '因家务分配产生分歧' },
      { timestamp: daysAgo(180), value: 72, reason: '因全职妈妈身份产生自我怀疑' },
      { timestamp: daysAgo(150), value: 68, reason: '陈志远忘记结婚纪念日' },
      { timestamp: daysAgo(120), value: 70, reason: '一起参加家长会' },
      { timestamp: daysAgo(90), value: 68, reason: '陈志远频繁加班引发争吵' },
      { timestamp: daysAgo(60), value: 72, reason: '晓薇生日，陈志远送了花' },
      { timestamp: daysAgo(45), value: 75, reason: '讨论一诺的暑假安排' },
      { timestamp: daysAgo(30), value: 78, reason: '五一全家出游千岛湖，关系回暖' },
      { timestamp: daysAgo(14), value: 76, reason: '一起为一诺的编程比赛准备' },
      { timestamp: daysAgo(7), value: 75, reason: '晓薇提出想重返职场' },
      { timestamp: daysAgo(3), value: 73, reason: '陈志远体检后情绪低落，晓薇担心' },
      { timestamp: daysAgo(1), value: 74, reason: '陈志远答应周末野餐' },
    ],
    profile: {
      identity: {
        fullName: '林晓薇',
        nicknames: ['晓薇', '薇薇', '老婆', '薇姐'],
        gender: 'female',
        age: 40,
        birthday: '03-15',
        zodiac: '双鱼座',
        hometown: '宁波',
        currentCity: '杭州',
      },
      career: {
        company: '（前）杭州某互联网公司',
        title: '人力资源经理（前）',
        department: '人力资源部',
        industry: '互联网',
        workStyle: '细致、有耐心、善于倾听，但决策时容易犹豫',
        strengths: ['沟通协调', '同理心强', '组织能力强', '情绪感知敏锐'],
        weaknesses: ['容易自我怀疑', '对冲突回避', '过于在意他人评价', '完美主义'],
        careerHistory: [
          { company: '宁波某国企', title: '行政专员', period: '2008-2012', highlights: ['获得优秀员工'] },
          { company: '杭州某互联网公司', title: 'HR经理', period: '2012-2021', highlights: ['搭建公司人才梯队', '主导校园招聘', '员工满意度提升20%'] },
        ],
      },
      personality: {
        openness: 65,
        conscientiousness: 78,
        extraversion: 45,
        agreeableness: 82,
        neuroticism: 60,
        mbti: 'ISFJ',
        description: '温柔内敛的守护者型人格，重视家庭和谐，习惯默默付出但内心渴望被看见。对变化敏感，需要安全感。有时会通过冷战表达不满。',
      },
      preferences: {
        likes: ['烘焙', '插花', '周末全家出游', '看日剧', '向日葵', '日式简约风', '瑜伽', '做手账'],
        dislikes: ['临时加班', '饭桌上谈工作', '敷衍的道歉', '大声争吵', '被忽视', '计划被打乱'],
        allergies: ['芒果', '部分海鲜'],
        dietary: ['清淡', '少辣', '喜欢日料', '控糖'],
        hobbies: ['烘焙', '插花', '瑜伽', '追剧', '手账'],
        communicationStyle: '委婉含蓄，倾向于暗示而非直接表达不满。生气时会冷战，需要对方主动破冰。开心时会分享很多细节。',
      },
      values: {
        coreValues: ['家庭和睦', '自我成长', '真诚相待', '生活品质'],
        motivations: ['希望被丈夫理解和尊重', '渴望重返职场实现自我价值', '担心与丈夫差距越来越大', '想成为孩子的榜样'],
        fears: ['被家庭束缚失去自我', '丈夫事业失败影响家庭', '孩子教育出问题', '夫妻感情变淡'],
        goals: ['找到一份兼顾家庭的工作', '重拾烘焙爱好并做出成绩', '改善夫妻关系沟通模式', '一诺考上好高中'],
      },
      socialRole: {
        roleInMyLife: '人生伴侣、情感支柱、家庭管理者、最了解我的人',
        myRoleInTheirLife: '经济支柱、丈夫、孩子父亲、情感依靠',
        powerDynamic: 'equal',
        trustLevel: 85,
        intimacyLevel: 80,
      },
      sharedExperiences: [
        { id: 'se-1', title: '结婚十周年旅行', description: '2021年去了三亚，那是晓薇最开心的一次旅行', date: '2021-10', category: 'celebration', sentiment: 90 },
        { id: 'se-2', title: '一诺出生', description: '2014年，两人第一次当父母，手忙脚乱但幸福', date: '2014-03', category: 'family', sentiment: 95 },
        { id: 'se-3', title: '买房决策', description: '2017年掏空积蓄买房，共同承担了巨大压力', date: '2017-06', category: 'crisis', sentiment: 70 },
        { id: 'se-4', title: '五一千岛湖', description: '2026年五一全家出游，难得的放松时光', date: '2026-05', category: 'travel', sentiment: 88 },
        { id: 'se-5', title: '一起学烘焙', description: '2020年疫情期间一起学烘焙，晓薇展现出天赋', date: '2020-04', category: 'daily', sentiment: 85 },
        { id: 'se-6', title: '陈志远升职庆祝', description: '2019年陈志远升任运营总监，晓薇做了一桌子菜', date: '2019-07', category: 'celebration', sentiment: 92 },
      ],
    },
    timeline: [
      { id: 'te-1', timestamp: daysAgo(365), type: 'milestone', title: '结婚十周年', description: '陈志远送了项链，晓薇说"还算有心"', sentiment: 85, relatedMemoryIds: [] },
      { id: 'te-2', timestamp: daysAgo(250), type: 'observation', title: '陈志远开始频繁加班', description: '回家越来越晚，周末也在处理工作', sentiment: 65, relatedMemoryIds: [] },
      { id: 'te-3', timestamp: daysAgo(180), type: 'conflict', title: '关于全职妈妈的争吵', description: '晓薇说"我不想跟你差距越来越大"，陈志远沉默', sentiment: 55, relatedMemoryIds: [] },
      { id: 'te-4', timestamp: daysAgo(150), type: 'conflict', title: '忘记纪念日', description: '陈志远忘记结婚纪念日，晓薇失望但没说什么', sentiment: 50, relatedMemoryIds: [] },
      { id: 'te-5', timestamp: daysAgo(90), type: 'conflict', title: '加班引发争吵', description: '连续一周十点回家，两人大吵一架', sentiment: 52, relatedMemoryIds: [] },
      { id: 'te-6', timestamp: daysAgo(60), type: 'reconciliation', title: '生日送花', description: '陈志远送了向日葵，晓薇喜欢的花', sentiment: 78, relatedMemoryIds: [] },
      { id: 'te-7', timestamp: daysAgo(30), type: 'reconciliation', title: '五一出游和好', description: '千岛湖三天，晓薇笑了一整天', sentiment: 88, relatedMemoryIds: [] },
      { id: 'te-8', timestamp: daysAgo(7), type: 'observation', title: '晓薇想重返职场', description: '提出想重新工作，陈志远嘴上说支持心里担忧', sentiment: 72, relatedMemoryIds: [] },
      { id: 'te-9', timestamp: daysAgo(3), type: 'observation', title: '担心陈志远健康', description: '体检报告出来后，晓薇开始控制他的饮食', sentiment: 70, relatedMemoryIds: [] },
      { id: 'te-10', timestamp: daysAgo(1), type: 'observation', title: '周末野餐计划', description: '陈志远答应周六去西溪湿地，一诺要做三明治', sentiment: 75, relatedMemoryIds: [] },
    ],
    connections: [
      { targetPersonId: 'p-chenyn', targetPersonName: '陈一诺', relationType: 'family', strength: 95, description: '母子关系，晓薇最牵挂的人，教育方式温和但坚持原则' },
      { targetPersonId: 'p-mom', targetPersonName: '陈秀兰', relationType: 'family', strength: 70, description: '婆媳关系总体和睦，偶尔因育儿观念有分歧' },
    ],
    traits: ['温柔但倔强', '心思细腻', '喜欢烘焙', '全职妈妈5年', 'ISFJ守护者', '渴望重返职场'],
    tags: ['配偶', '双鱼座', '前HR经理', '烘焙爱好者', '想重返职场', '40岁'],
    interactionStats: {
      totalCount: 156,
      lastInteractionAt: daysAgo(1),
      avgSentiment: 74,
      topics: ['家庭开支', '孩子教育', '工作安排', '未来规划', '健康饮食'],
    },
    createdAt: daysAgo(365),
    updatedAt: now,
  },
  {
    id: 'p-chenyn',
    name: '陈一诺',
    relationship: 'family',
    sentiment: 85,
    sentimentHistory: [
      { timestamp: daysAgo(365), value: 80, reason: '小升初压力大' },
      { timestamp: daysAgo(300), value: 82, reason: '期中考试进步' },
      { timestamp: daysAgo(250), value: 75, reason: '钢琴考级压力大' },
      { timestamp: daysAgo(200), value: 78, reason: '篮球比赛获奖' },
      { timestamp: daysAgo(180), value: 88, reason: '编程课表现出色' },
      { timestamp: daysAgo(120), value: 80, reason: '期末考试中等' },
      { timestamp: daysAgo(90), value: 82, reason: '寒假玩得很开心' },
      { timestamp: daysAgo(60), value: 82, reason: '钢琴课抵触情绪' },
      { timestamp: daysAgo(45), value: 85, reason: '编程比赛准备中' },
      { timestamp: daysAgo(30), value: 90, reason: '五一开快艇特别开心' },
      { timestamp: daysAgo(14), value: 86, reason: 'Python项目有进展' },
      { timestamp: daysAgo(7), value: 85, reason: 'Python学习进展顺利' },
      { timestamp: daysAgo(2), value: 84, reason: '问爸爸什么时候去野餐' },
    ],
    profile: {
      identity: {
        fullName: '陈一诺',
        nicknames: ['一诺', '诺诺', '儿子', '诺宝'],
        gender: 'male',
        age: 12,
        birthday: '03-08',
        zodiac: '双鱼座',
        hometown: '杭州',
        currentCity: '杭州',
      },
      career: {
        title: '初中生',
        department: '初一（3）班',
        industry: '教育',
        workStyle: '聪明但粗心，对新事物好奇但缺乏耐心',
        strengths: ['逻辑思维强', '好奇心旺盛', '动手能力强', '记忆力好'],
        weaknesses: ['粗心大意', '三分钟热度', '拖延症', '注意力分散'],
        careerHistory: [],
      },
      personality: {
        openness: 85,
        conscientiousness: 50,
        extraversion: 60,
        agreeableness: 70,
        neuroticism: 45,
        mbti: 'ENTP',
        description: '活泼好奇的发明家型，喜欢编程和探索新事物，但缺乏耐心和专注力。和父亲关系亲近，对母亲有依赖。内心敏感，在意父母评价。',
      },
      preferences: {
        likes: ['编程', 'Minecraft', '乐高', '科幻小说', '开快艇', 'Python', '篮球', '奥特曼'],
        dislikes: ['练钢琴', '写作文', '早起', '被说教', '重复练习', '数学考试'],
        allergies: [],
        dietary: ['喜欢汉堡披萨', '不爱吃蔬菜', '喜欢甜食', '爱喝可乐'],
        hobbies: ['编程', '乐高', '科幻', '游戏', '篮球'],
        communicationStyle: '直接坦率，会顶嘴但心不坏。喜欢被当作大人对待，讨厌被当作小孩说教。开心时话很多，不开心时沉默。',
      },
      values: {
        coreValues: ['自由', '公平', '创造力', '被认可'],
        motivations: ['想成为游戏开发者', '希望得到父母认可', '不想被强迫学钢琴', '想做出自己的游戏'],
        fears: ['考试考砸', '被同学嘲笑', '父母吵架', '让父母失望'],
        goals: ['做出一个自己的游戏', '钢琴考过十级后不再学', '考上杭二中', '编程比赛获奖'],
      },
      socialRole: {
        roleInMyLife: '儿子、未来希望、情感寄托、让我想变得更好的动力',
        myRoleInTheirLife: '父亲、榜样、经济支持者、编程启蒙老师',
        powerDynamic: 'superior',
        trustLevel: 90,
        intimacyLevel: 85,
      },
      sharedExperiences: [
        { id: 'se-yn-1', title: '第一次编程', description: '陈志远给买了Python课程，父子一起学', date: '2026-04', category: 'daily', sentiment: 90 },
        { id: 'se-yn-2', title: '千岛湖开快艇', description: '第一次独立驾驶快艇，兴奋得嗷嗷叫', date: '2026-05', category: 'travel', sentiment: 95 },
        { id: 'se-yn-3', title: '篮球比赛', description: '校篮球比赛获奖，陈志远请假去看', date: '2026-03', category: 'celebration', sentiment: 88 },
        { id: 'se-yn-4', title: '乐高机器人', description: '父子一起拼乐高机器人，花了整个周末', date: '2025-12', category: 'daily', sentiment: 85 },
      ],
    },
    timeline: [
      { id: 'te-yn-1', timestamp: daysAgo(250), type: 'milestone', title: '钢琴考级', description: '钢琴八级考试，压力大到失眠', sentiment: 60, relatedMemoryIds: [] },
      { id: 'te-yn-2', timestamp: daysAgo(200), type: 'milestone', title: '篮球比赛获奖', description: '校篮球比赛第三名，陈志远请假去看', sentiment: 88, relatedMemoryIds: [] },
      { id: 'te-yn-3', timestamp: daysAgo(180), type: 'milestone', title: '开始学Python', description: '陈志远买了课程，父子关系因此拉近', sentiment: 90, relatedMemoryIds: [] },
      { id: 'te-yn-4', timestamp: daysAgo(60), type: 'conflict', title: '钢琴课抵触', description: '不想练琴，跟林晓薇吵架', sentiment: 55, relatedMemoryIds: [] },
      { id: 'te-yn-5', timestamp: daysAgo(30), type: 'shared_experience', title: '千岛湖开快艇', description: '第一次独立驾驶，特别兴奋', sentiment: 95, relatedMemoryIds: [] },
      { id: 'te-yn-6', timestamp: daysAgo(14), type: 'observation', title: '编程比赛准备', description: '正在准备学校编程比赛，很有热情', sentiment: 88, relatedMemoryIds: [] },
      { id: 'te-yn-7', timestamp: daysAgo(2), type: 'observation', title: '期待野餐', description: '问爸爸什么时候去西溪湿地野餐', sentiment: 85, relatedMemoryIds: [] },
    ],
    connections: [
      { targetPersonId: 'p-linxw', targetPersonName: '林晓薇', relationType: 'family', strength: 92, description: '母子关系，对母亲有依赖，但觉得母亲管太多' },
      { targetPersonId: 'p-mom', targetPersonName: '陈秀兰', relationType: 'family', strength: 65, description: '祖孙关系，节假日见面，奶奶很宠他' },
    ],
    traits: ['聪明但粗心', '喜欢编程', '有点叛逆', '和爸爸关系好', 'ENTP发明家', '篮球爱好者'],
    tags: ['儿子', '初中生', '编程爱好者', '双鱼座', '科幻迷', '12岁'],
    interactionStats: {
      totalCount: 89,
      lastInteractionAt: daysAgo(2),
      avgSentiment: 84,
      topics: ['编程', '学校', '游戏', '钢琴', '考试成绩', '篮球'],
    },
    createdAt: daysAgo(365),
    updatedAt: now,
  },
  {
    id: 'p-mom',
    name: '陈秀兰',
    relationship: 'family',
    sentiment: 90,
    sentimentHistory: [
      { timestamp: daysAgo(365), value: 88, reason: '独居绍兴，定期视频' },
      { timestamp: daysAgo(300), value: 86, reason: '春节团聚，很开心' },
      { timestamp: daysAgo(250), value: 85, reason: '给一诺织了件毛衣' },
      { timestamp: daysAgo(180), value: 87, reason: '视频时精神不错' },
      { timestamp: daysAgo(120), value: 85, reason: '春节回家团聚' },
      { timestamp: daysAgo(90), value: 85, reason: '膝盖疼痛，拒绝去杭州看病' },
      { timestamp: daysAgo(60), value: 88, reason: '一诺视频给她看编程作品' },
      { timestamp: daysAgo(30), value: 92, reason: '五一节后视频，精神状态不错' },
      { timestamp: daysAgo(14), value: 90, reason: '端午节准备腌咸菜等他们回来' },
      { timestamp: daysAgo(5), value: 88, reason: '视频叮嘱陈志远少喝酒' },
    ],
    profile: {
      identity: {
        fullName: '陈秀兰',
        nicknames: ['妈', '奶奶', '秀兰'],
        gender: 'female',
        age: 73,
        birthday: '08-20',
        zodiac: '狮子座',
        hometown: '绍兴',
        currentCity: '绍兴',
      },
      career: {
        title: '退休纺织工人',
        industry: '制造业',
        workStyle: '勤劳节俭，一辈子省吃俭用',
        strengths: ['坚韧', '节俭', '独立', '手工艺好'],
        weaknesses: ['固执', '不愿麻烦子女', '对身体状况隐瞒', '过度节俭'],
        careerHistory: [
          { company: '绍兴纺织厂', title: '纺织女工', period: '1970-2005', highlights: ['厂级劳模', '带出一批徒弟', '技术能手'] },
        ],
      },
      personality: {
        openness: 30,
        conscientiousness: 85,
        extraversion: 40,
        agreeableness: 75,
        neuroticism: 55,
        description: '传统坚韧的劳动妇女，节俭到近乎吝啬，但内心深处非常爱子女。不愿成为负担，身体不舒服也硬撑。对孙子一诺特别宠爱。',
      },
      preferences: {
        likes: ['看越剧', '和老姐妹打牌', '视频通话', '腌咸菜', '晒太阳', '织毛衣', '一诺'],
        dislikes: ['浪费', '子女花钱给她买东西', '去医院', '麻烦别人', '城里太吵'],
        allergies: [],
        dietary: ['清淡', '爱吃腌菜', '节俭', '爱吃甜食'],
        hobbies: ['越剧', '打牌', '腌菜', '织毛衣'],
        communicationStyle: '报喜不报忧，总说"我很好你们忙你们的"。需要子女主动关心才能了解真实情况。对孙子特别温柔。',
      },
      values: {
        coreValues: ['节俭', '家庭', '独立', '勤劳'],
        motivations: ['不想成为子女负担', '希望子女过得好', '想看到孙子成才', '维持自己的尊严'],
        fears: ['拖累子女', '生病住院花钱', '孤独终老', '被送进养老院'],
        goals: ['身体健康不添麻烦', '孙子考上好大学', '看到陈志远事业顺利'],
      },
      socialRole: {
        roleInMyLife: '母亲、根、情感归宿、让我愧疚的人',
        myRoleInTheirLife: '儿子、经济支持者、养老依靠、她最骄傲的人',
        powerDynamic: 'subordinate',
        trustLevel: 80,
        intimacyLevel: 75,
      },
      sharedExperiences: [
        { id: 'se-mom-1', title: '春节回家', description: '2026年春节回绍兴，妈妈手抖但坚持做饭', date: '2026-02', category: 'family', sentiment: 85 },
        { id: 'se-mom-2', title: '一诺出生', description: '从绍兴来杭州照顾月子，待了三个月', date: '2014-03', category: 'family', sentiment: 90 },
        { id: 'se-mom-3', title: '买房支持', description: '把毕生积蓄20万给了陈志远买房', date: '2017-05', category: 'crisis', sentiment: 95 },
      ],
    },
    timeline: [
      { id: 'te-mom-1', timestamp: daysAgo(300), type: 'observation', title: '春节团聚', description: '全家回绍兴，妈妈做了满满一桌子菜', sentiment: 88, relatedMemoryIds: [] },
      { id: 'te-mom-2', timestamp: daysAgo(126), type: 'observation', title: '春节回家', description: '妈妈明显老了，做饭时手抖', sentiment: 80, relatedMemoryIds: [] },
      { id: 'te-mom-3', timestamp: daysAgo(93), type: 'observation', title: '膝盖疼痛', description: '拒绝去杭州看病，说"太贵了不用"', sentiment: 70, relatedMemoryIds: [] },
      { id: 'te-mom-4', timestamp: daysAgo(60), type: 'observation', title: '一诺视频', description: '一诺视频给她看编程作品，她不懂但很开心', sentiment: 90, relatedMemoryIds: [] },
      { id: 'te-mom-5', timestamp: daysAgo(14), type: 'observation', title: '端午节准备', description: '提前腌好了咸菜等他们回去', sentiment: 88, relatedMemoryIds: [] },
      { id: 'te-mom-6', timestamp: daysAgo(5), type: 'observation', title: '叮嘱少喝酒', description: '视频时听说陈志远体检，叮嘱他少喝酒', sentiment: 85, relatedMemoryIds: [] },
    ],
    connections: [
      { targetPersonId: 'p-self', targetPersonName: '陈志远', relationType: 'family', strength: 95, description: '母子关系，儿子在杭州工作，每周通话' },
      { targetPersonId: 'p-chenyn', targetPersonName: '陈一诺', relationType: 'family', strength: 90, description: '祖孙关系，特别宠爱孙子' },
      { targetPersonId: 'p-linxw', targetPersonName: '林晓薇', relationType: 'family', strength: 65, description: '婆媳关系，总体和睦' },
    ],
    traits: ['节俭', '爱操心', '腿脚不好', '独居', '坚韧', '宠孙子'],
    tags: ['母亲', '73岁', '绍兴', '退休工人', '独居老人', '狮子座'],
    interactionStats: {
      totalCount: 45,
      lastInteractionAt: daysAgo(5),
      avgSentiment: 88,
      topics: ['身体状况', '一诺学习', '天气', '老姐妹', '腌菜'],
    },
    createdAt: daysAgo(365),
    updatedAt: now,
  },
  {
    id: 'p-wangsl',
    name: '王思亮',
    relationship: 'leader',
    sentiment: 30,
    sentimentHistory: [
      { timestamp: daysAgo(180), value: 60, reason: '刚空降时表面客气' },
      { timestamp: daysAgo(150), value: 55, reason: '开始调整汇报线' },
      { timestamp: daysAgo(120), value: 50, reason: '开始边缘化陈志远' },
      { timestamp: daysAgo(90), value: 48, reason: 'Q1复盘暗示团队效率问题' },
      { timestamp: daysAgo(60), value: 45, reason: '引入新绩效考核体系' },
      { timestamp: daysAgo(30), value: 40, reason: 'Q2复盘邮件暗示运营效率低' },
      { timestamp: daysAgo(14), value: 38, reason: '开始接触刘文燕' },
      { timestamp: daysAgo(7), value: 35, reason: '周会公开敲打运营数据' },
      { timestamp: daysAgo(3), value: 32, reason: '私下找刘文燕谈话' },
      { timestamp: daysAgo(1), value: 30, reason: '最新周会再次施压' },
    ],
    profile: {
      identity: {
        fullName: '王思亮',
        nicknames: ['王总', '思亮'],
        gender: 'male',
        age: 38,
        birthday: '11-12',
        zodiac: '天蝎座',
        hometown: '北京',
        currentCity: '杭州',
      },
      career: {
        company: '杭州云启科技有限公司',
        title: 'VP运营',
        department: '运营中心',
        industry: '互联网',
        workStyle: '数据驱动、结果导向、说话直接、对老员工有戒心',
        strengths: ['数据分析', '战略思维', '执行力强', '向上管理', '变革推动'],
        weaknesses: ['缺乏人情味', '不信任老员工', 'micromanagement', '急躁'],
        careerHistory: [
          { company: '美团', title: '运营经理', period: '2012-2016', highlights: ['负责商家运营', '年度优秀员工'] },
          { company: '滴滴', title: '高级运营总监', period: '2016-2021', highlights: ['区域运营负责人', '带领团队200人'] },
          { company: '杭州云启科技', title: 'VP运营', period: '2021-至今', highlights: ['空降改革运营体系', '裁员30%'] },
        ],
      },
      personality: {
        openness: 70,
        conscientiousness: 85,
        extraversion: 65,
        agreeableness: 35,
        neuroticism: 50,
        mbti: 'ENTJ',
        description: '强势果断的指挥官型，极度理性，以结果为导向。对"老资格"有天然戒心，喜欢用数据说话但缺乏同理心。做事雷厉风行但不留情面。',
      },
      preferences: {
        likes: ['OKR', '数据看板', '效率', '扁平管理', '星巴克美式', '健身', '马拉松'],
        dislikes: ['讲人情', '模糊汇报', '老资格摆谱', '加班文化', '感性决策', '借口'],
        allergies: [],
        dietary: ['健身餐', '少油少盐', '美式咖啡', '不吃碳水'],
        hobbies: ['健身', '马拉松', '数据可视化', '商业阅读'],
        communicationStyle: '直接到近乎冷酷，喜欢用数据和事实说话。批评时不留情面，但表扬也很吝啬。喜欢用反问句施压。',
      },
      values: {
        coreValues: ['效率', '结果', '数据', '变革', '优胜劣汰'],
        motivations: ['证明空降VP的价值', '建立嫡系团队', '推动运营体系变革', '获得CEO信任'],
        fears: ['被质疑能力', '改革失败', '老员工抱团对抗', '业绩不达标'],
        goals: ['年内运营效率提升30%', '替换核心岗位为嫡系', '获得CEO信任', '推动公司上市'],
      },
      socialRole: {
        roleInMyLife: '直属领导、职业威胁、改革推动者、压力来源',
        myRoleInTheirLife: '待替换的老员工、运营数据负责人、潜在的阻碍',
        powerDynamic: 'superior',
        trustLevel: 20,
        intimacyLevel: 10,
      },
      sharedExperiences: [
        { id: 'se-wsl-1', title: '第一次部门会议', description: '王思亮第一次主持部门会议，宣布新的KPI体系', date: '2025-12', category: 'work', sentiment: 45 },
      ],
    },
    timeline: [
      { id: 'te-wsl-1', timestamp: daysAgo(180), type: 'first_met', title: '王思亮空降', description: '从滴滴空降VP，陈志远感到威胁', sentiment: 55, relatedMemoryIds: [] },
      { id: 'te-wsl-2', timestamp: daysAgo(150), type: 'observation', title: '调整汇报线', description: '陈志远的部分权限被收走', sentiment: 50, relatedMemoryIds: [] },
      { id: 'te-wsl-3', timestamp: daysAgo(120), type: 'observation', title: '开始边缘化', description: '重要会议不再叫陈志远参加', sentiment: 45, relatedMemoryIds: [] },
      { id: 'te-wsl-4', timestamp: daysAgo(67), type: 'conflict', title: 'Q2复盘邮件', description: '发邮件"关于提升运营效率的思考"，全组抄送', sentiment: 35, relatedMemoryIds: [] },
      { id: 'te-wsl-5', timestamp: daysAgo(14), type: 'observation', title: '接触刘文燕', description: '开始私下接触刘文燕，可能培养替代人选', sentiment: 30, relatedMemoryIds: [] },
      { id: 'te-wsl-6', timestamp: daysAgo(4), type: 'conflict', title: '周会敲打', description: '公开说"运营团队数据不够亮眼"', sentiment: 25, relatedMemoryIds: [] },
      { id: 'te-wsl-7', timestamp: daysAgo(1), type: 'conflict', title: '再次施压', description: 'Q2获客成本上升15%，直接质问陈志远', sentiment: 20, relatedMemoryIds: [] },
    ],
    connections: [
      { targetPersonId: 'p-liuwy', targetPersonName: '刘文燕', relationType: 'colleague', strength: 75, description: '赏识刘文燕，可能作为替代人选培养' },
      { targetPersonId: 'p-zhaohm', targetPersonName: '赵海明', relationType: 'colleague', strength: 40, description: '表面客气，实际上不信任技术团队' },
    ],
    traits: ['85后空降VP', '数据驱动', '说话直接', '对老员工有戒心', 'ENTJ指挥官', '健身达人'],
    tags: ['领导', 'VP', '空降', '天蝎座', '健身达人', '威胁', '38岁'],
    interactionStats: {
      totalCount: 32,
      lastInteractionAt: daysAgo(1),
      avgSentiment: 38,
      topics: ['KPI', '数据', '团队管理', '效率', '成本控制'],
    },
    createdAt: daysAgo(180),
    updatedAt: now,
  },
  {
    id: 'p-zhaohm',
    name: '赵海明',
    relationship: 'colleague',
    sentiment: 72,
    sentimentHistory: [
      { timestamp: daysAgo(365), value: 70, reason: '技术转管理，性格相投' },
      { timestamp: daysAgo(300), value: 72, reason: '一起团建钓鱼' },
      { timestamp: daysAgo(250), value: 68, reason: '技术方案分歧但和解' },
      { timestamp: daysAgo(200), value: 75, reason: '一起喝酒聊职业规划' },
      { timestamp: daysAgo(150), value: 70, reason: '各自忙碌，联系减少' },
      { timestamp: daysAgo(100), value: 73, reason: '一起吐槽王思亮' },
      { timestamp: daysAgo(60), value: 75, reason: '部门协作顺利' },
      { timestamp: daysAgo(37), value: 78, reason: '酒后吐真言提醒陈志远' },
      { timestamp: daysAgo(14), value: 74, reason: '讨论技术架构调整' },
      { timestamp: daysAgo(1), value: 72, reason: '周会后拍肩膀安慰' },
    ],
    profile: {
      identity: {
        fullName: '赵海明',
        nicknames: ['老赵', '海明', '赵总'],
        gender: 'male',
        age: 45,
        birthday: '06-18',
        zodiac: '双子座',
        hometown: '山东',
        currentCity: '杭州',
      },
      career: {
        company: '杭州云启科技有限公司',
        title: '技术总监',
        department: '技术部',
        industry: '互联网',
        workStyle: '技术出身，务实靠谱，不爱搞政治但看得清',
        strengths: ['技术深度', '靠谱', '酒量好', '人情练达', '团队管理'],
        weaknesses: ['不爱汇报', 'PPT能力差', '有时过于直率', '不够主动'],
        careerHistory: [
          { company: '华为', title: '工程师', period: '2005-2010', highlights: ['核心网开发', '技术专利2项'] },
          { company: '阿里', title: '技术专家', period: '2010-2018', highlights: ['中间件团队', '双十一技术保障'] },
          { company: '云启科技', title: '技术总监', period: '2018-至今', highlights: ['搭建技术团队', '系统架构升级'] },
        ],
      },
      personality: {
        openness: 60,
        conscientiousness: 80,
        extraversion: 70,
        agreeableness: 75,
        neuroticism: 40,
        mbti: 'ESTP',
        description: '务实豪爽的企业家型，技术过硬但不拘泥细节。喜欢喝酒聊天，是陈志远在公司最信任的人。表面大大咧咧，实则心思细腻。',
      },
      preferences: {
        likes: ['钓鱼', '喝白酒', '聊行业八卦', '德州扑克', '技术分享', '海鲜'],
        dislikes: ['PPT汇报', '形式主义', '办公室政治', '假大空', ' micromanagement'],
        allergies: [],
        dietary: ['爱吃鲁菜', '能喝白酒', '喜欢海鲜', '爱吃烧烤'],
        hobbies: ['钓鱼', '德州扑克', '技术论坛', '看足球'],
        communicationStyle: '豪爽直接，酒后话多但都是真心话。善于用玩笑化解尴尬。对朋友讲义气，对敌人不留情。',
      },
      values: {
        coreValues: ['技术', '兄弟情义', '实在', '自由'],
        motivations: ['带好技术团队', '帮助朋友', '早日财务自由', '保持技术敏感度'],
        fears: ['技术落后', '被政治斗争波及', '健康问题', '朋友疏远'],
        goals: ['技术团队稳定', '攒够钱提前退休', '带陈志远一起钓鱼', '写一本技术书'],
      },
      socialRole: {
        roleInMyLife: '职场盟友、知心朋友、信息来源、唯一能吐槽的人',
        myRoleInTheirLife: '运营搭档、酒友、信任的同事、需要提醒的人',
        powerDynamic: 'equal',
        trustLevel: 80,
        intimacyLevel: 70,
      },
      sharedExperiences: [
        { id: 'se-z-1', title: '部门团建', description: '多次一起喝酒聊天，建立了深厚友谊', date: '2024-至今', category: 'work', sentiment: 80 },
        { id: 'se-z-2', title: '一起钓鱼', description: '2025年秋一起去千岛湖钓鱼，钓了条大鱼', date: '2025-10', category: 'travel', sentiment: 90 },
        { id: 'se-z-3', title: '技术攻坚', description: '一起熬了三个通宵解决系统故障', date: '2024-06', category: 'work', sentiment: 85 },
      ],
    },
    timeline: [
      { id: 'te-z-1', timestamp: daysAgo(300), type: 'shared_experience', title: '一起钓鱼', description: '千岛湖钓鱼，钓了条8斤的大鱼', sentiment: 90, relatedMemoryIds: [] },
      { id: 'te-z-2', timestamp: daysAgo(200), type: 'observation', title: '聊职业规划', description: '酒后聊各自的职业规划，都想提前退休', sentiment: 75, relatedMemoryIds: [] },
      { id: 'te-z-3', timestamp: daysAgo(100), type: 'observation', title: '吐槽王思亮', description: '一起吐槽王思亮的管理方式', sentiment: 70, relatedMemoryIds: [] },
      { id: 'te-z-4', timestamp: daysAgo(37), type: 'observation', title: '酒后真言', description: '"志远，你在云启待不下去了，王思亮就是来换血的"', sentiment: 75, relatedMemoryIds: [] },
      { id: 'te-z-5', timestamp: daysAgo(1), type: 'observation', title: '周会安慰', description: '会后拍肩膀说"别往心里去"', sentiment: 72, relatedMemoryIds: [] },
    ],
    connections: [
      { targetPersonId: 'p-wangsl', targetPersonName: '王思亮', relationType: 'colleague', strength: 40, description: '表面服从，内心不认同管理方式' },
      { targetPersonId: 'p-liuwy', targetPersonName: '刘文燕', relationType: 'colleague', strength: 30, description: '技术对接时偶有摩擦' },
    ],
    traits: ['技术出身转管理', '靠谱', '爱请客', '酒量好', 'ESTP企业家', '钓鱼爱好者'],
    tags: ['同事', '技术总监', '盟友', '酒友', '双子座', '45岁'],
    interactionStats: {
      totalCount: 67,
      lastInteractionAt: daysAgo(1),
      avgSentiment: 73,
      topics: ['技术', '公司八卦', '钓鱼', '职业规划', '家庭'],
    },
    createdAt: daysAgo(365),
    updatedAt: now,
  },
  {
    id: 'p-liuwy',
    name: '刘文燕',
    relationship: 'colleague',
    sentiment: 40,
    sentimentHistory: [
      { timestamp: daysAgo(120), value: 60, reason: '入职时表现积极' },
      { timestamp: daysAgo(100), value: 55, reason: '开始展现野心' },
      { timestamp: daysAgo(80), value: 52, reason: '汇报时抢话' },
      { timestamp: daysAgo(60), value: 50, reason: '开始越级汇报' },
      { timestamp: daysAgo(45), value: 48, reason: '私下接触王思亮' },
      { timestamp: daysAgo(30), value: 45, reason: '直接发方案给王思亮' },
      { timestamp: daysAgo(14), value: 42, reason: '周会表现抢眼' },
      { timestamp: daysAgo(7), value: 40, reason: '被王思亮单独表扬' },
      { timestamp: daysAgo(3), value: 38, reason: '私下找王思亮汇报' },
      { timestamp: daysAgo(1), value: 40, reason: '最新周会表现抢眼' },
    ],
    profile: {
      identity: {
        fullName: '刘文燕',
        nicknames: ['文燕', '小刘'],
        gender: 'female',
        age: 28,
        birthday: '09-05',
        zodiac: '处女座',
        hometown: '武汉',
        currentCity: '杭州',
      },
      career: {
        company: '杭州云启科技有限公司',
        title: '运营主管',
        department: '运营部',
        industry: '互联网',
        workStyle: '野心大、能力强、善于表现、有点强势',
        strengths: ['数据敏感', '执行力强', '汇报能力强', '学习快', '抗压'],
        weaknesses: ['过于强势', '缺乏耐心', '急于表现', '不尊重层级', '团队协作差'],
        careerHistory: [
          { company: '字节跳动', title: '运营专员', period: '2019-2022', highlights: ['增长项目', '年度优秀新人'] },
          { company: '云启科技', title: '运营主管', period: '2022-至今', highlights: ['用户增长项目', '数据体系搭建'] },
        ],
      },
      personality: {
        openness: 75,
        conscientiousness: 80,
        extraversion: 70,
        agreeableness: 40,
        neuroticism: 55,
        mbti: 'ESTJ',
        description: '强势务实的总经理型，能力确实强但缺乏团队意识。急于证明自己，有取代陈志远的野心。对上级阿谀，对平级冷淡。',
      },
      preferences: {
        likes: ['小红书', '健身', '效率工具', '汇报', '数据', '星巴克', '名牌包'],
        dislikes: ['加班', '被质疑经验', '层级束缚', '低效会议', '老资格'],
        allergies: [],
        dietary: ['健身餐', '低碳水', '少糖', '不吃晚饭'],
        hobbies: ['健身', '小红书', '效率工具', '瑜伽'],
        communicationStyle: '直接甚至咄咄逼人，喜欢用数据碾压对方。在领导面前表现积极，对平级态度一般。善于包装成果。',
      },
      values: {
        coreValues: ['成就', '效率', '晋升', '认可'],
        motivations: ['快速晋升', '证明95后能力', '取代陈志远', '获得王思亮信任'],
        fears: ['被当作新人', '晋升受阻', '能力不足被看穿', '被陈志远压制'],
        goals: ['一年内晋升运营经理', '获得王思亮信任', '建立个人品牌', '年薪50万'],
      },
      socialRole: {
        roleInMyLife: '下属但潜在威胁、竞争对手、能力强的年轻人、让我不安的人',
        myRoleInTheirLife: '需要超越的上级、阻碍晋升的障碍、迟早要取代的人',
        powerDynamic: 'subordinate',
        trustLevel: 25,
        intimacyLevel: 15,
      },
      sharedExperiences: [
        { id: 'se-l-1', title: '入职培训', description: '陈志远带她熟悉业务，当时关系还不错', date: '2022-03', category: 'work', sentiment: 65 },
      ],
    },
    timeline: [
      { id: 'te-l-1', timestamp: daysAgo(120), type: 'first_met', title: '刘文燕入职', description: '从字节跳槽来，能力强但野心大', sentiment: 60, relatedMemoryIds: [] },
      { id: 'te-l-2', timestamp: daysAgo(60), type: 'observation', title: '开始越级', description: '开始绕过陈志远直接汇报', sentiment: 45, relatedMemoryIds: [] },
      { id: 'te-l-3', timestamp: daysAgo(45), type: 'observation', title: '接触王思亮', description: '私下接触王思亮，表现积极', sentiment: 40, relatedMemoryIds: [] },
      { id: 'te-l-4', timestamp: daysAgo(4), type: 'conflict', title: '越级汇报', description: '直接发方案给王思亮，绕过陈志远', sentiment: 35, relatedMemoryIds: [] },
      { id: 'te-l-5', timestamp: daysAgo(3), type: 'observation', title: '私下汇报', description: '被看到在王思亮办公室单独汇报', sentiment: 32, relatedMemoryIds: [] },
    ],
    connections: [
      { targetPersonId: 'p-wangsl', targetPersonName: '王思亮', relationType: 'colleague', strength: 70, description: '可能获得王思亮赏识，作为替代人选' },
      { targetPersonId: 'p-zhaohm', targetPersonName: '赵海明', relationType: 'colleague', strength: 30, description: '技术对接时偶有摩擦，互相看不顺眼' },
    ],
    traits: ['95后运营主管', '能力强', '野心大', '有点强势', 'ESTJ总经理', '健身达人'],
    tags: ['下属', '95后', '威胁', '处女座', '健身达人', '28岁'],
    interactionStats: {
      totalCount: 28,
      lastInteractionAt: daysAgo(1),
      avgSentiment: 48,
      topics: ['工作汇报', '数据分析', '项目进度', '越级汇报'],
    },
    createdAt: daysAgo(120),
    updatedAt: now,
  },
  {
    id: 'p-zhangwh',
    name: '张伟华',
    relationship: 'friend',
    sentiment: 70,
    sentimentHistory: [
      { timestamp: daysAgo(365), value: 65, reason: '大学室友，偶尔联系' },
      { timestamp: daysAgo(300), value: 68, reason: '生日聚会，聊近况' },
      { timestamp: daysAgo(250), value: 66, reason: '各自忙碌，联系减少' },
      { timestamp: daysAgo(200), value: 70, reason: '张伟华创业公司有困难，找陈志远聊' },
      { timestamp: daysAgo(150), value: 68, reason: '偶尔微信联系' },
      { timestamp: daysAgo(131), value: 70, reason: '过年拜年聊创业' },
      { timestamp: daysAgo(100), value: 68, reason: '各自忙碌' },
      { timestamp: daysAgo(60), value: 72, reason: '张伟华说融资有进展' },
      { timestamp: daysAgo(30), value: 74, reason: '融资顺利，开始扩张' },
      { timestamp: daysAgo(14), value: 75, reason: '正式发出邀请' },
      { timestamp: daysAgo(6), value: 75, reason: '拿到A轮，邀请陈志远加入' },
      { timestamp: daysAgo(3), value: 72, reason: '催陈志远给答复' },
    ],
    profile: {
      identity: {
        fullName: '张伟华',
        nicknames: ['伟华', '华子', '老张'],
        gender: 'male',
        age: 42,
        birthday: '04-22',
        zodiac: '金牛座',
        hometown: '杭州',
        currentCity: '杭州',
      },
      career: {
        company: '某SaaS创业公司',
        title: 'CEO',
        department: '管理层',
        industry: 'SaaS',
        workStyle: '乐观冒险、善于融资、执行力强',
        strengths: ['商业嗅觉', '融资能力', '乐观', '人脉广', '演讲能力'],
        weaknesses: ['有时过于乐观', '细节把控弱', '风险意识不足', '不够专注'],
        careerHistory: [
          { company: '阿里', title: '产品经理', period: '2006-2012', highlights: ['B2B产品', '年度优秀'] },
          { company: '某创业公司', title: '联合创始人', period: '2012-2018', highlights: ['B轮失败', '团队解散'] },
          { company: '某SaaS公司', title: 'CEO', period: '2019-至今', highlights: ['A轮1500万', '团队50人'] },
        ],
      },
      personality: {
        openness: 80,
        conscientiousness: 60,
        extraversion: 85,
        agreeableness: 70,
        neuroticism: 35,
        mbti: 'ENFP',
        description: '热情乐观的竞选者型，天生的创业者。善于鼓舞人心，但有时会过于乐观低估风险。真心希望陈志远加入，认为他是最佳搭档。',
      },
      preferences: {
        likes: ['创业', '融资', '高尔夫', '聊商业', '社交', '红酒', '雪茄'],
        dislikes: ['大公司政治', '温水煮青蛙', '保守', '官僚', '拖延'],
        allergies: [],
        dietary: ['商务餐', '西餐', '红酒', '爱吃牛排'],
        hobbies: ['高尔夫', '商业阅读', '社交', '品酒'],
        communicationStyle: '热情感染力强，善于描绘愿景。但有时过于理想化，需要理性的人平衡。喜欢用"兄弟"称呼。',
      },
      values: {
        coreValues: ['自由', '创新', '财富', '影响力', '兄弟情义'],
        motivations: ['打造独角兽', '财务自由', '帮助朋友成功', '证明自己'],
        fears: ['再次创业失败', '错过风口', '平庸', '朋友疏远'],
        goals: ['B轮5000万', '三年内上市', '拉陈志远入伙', '财务自由'],
      },
      socialRole: {
        roleInMyLife: '大学室友、创业诱惑、另一种人生可能、让我心动的人',
        myRoleInTheirLife: '信任的朋友、潜在合伙人、COO人选、最佳搭档',
        powerDynamic: 'equal',
        trustLevel: 75,
        intimacyLevel: 65,
      },
      sharedExperiences: [
        { id: 'se-zw-1', title: '大学时光', description: '浙江大学室友，一起逃课、打球、追女生', date: '2002-2006', category: 'daily', sentiment: 90 },
        { id: 'se-zw-2', title: '创业邀请', description: '多次邀请陈志远加入，最新offer：COO，35K+期权', date: '2026-06', category: 'work', sentiment: 75 },
        { id: 'se-zw-3', title: '第一次创业失败', description: '2018年张伟华第一次创业失败，陈志远借钱帮他', date: '2018-12', category: 'crisis', sentiment: 70 },
      ],
    },
    timeline: [
      { id: 'te-zw-1', timestamp: daysAgo(365 * 20), type: 'first_met', title: '大学室友', description: '浙江大学同窗，建立深厚友谊', sentiment: 90, relatedMemoryIds: [] },
      { id: 'te-zw-2', timestamp: daysAgo(200), type: 'observation', title: '创业困难', description: '张伟华创业公司有困难，找陈志远倾诉', sentiment: 68, relatedMemoryIds: [] },
      { id: 'te-zw-3', timestamp: daysAgo(131), type: 'observation', title: '过年聊创业', description: '又提一起创业，林晓薇私下问"靠谱吗"', sentiment: 65, relatedMemoryIds: [] },
      { id: 'te-zw-4', timestamp: daysAgo(60), type: 'observation', title: '融资进展', description: '说融资有进展，开始物色核心团队', sentiment: 72, relatedMemoryIds: [] },
      { id: 'te-zw-5', timestamp: daysAgo(14), type: 'observation', title: '正式邀请', description: '正式发出COO邀请，陈志远心动', sentiment: 75, relatedMemoryIds: [] },
      { id: 'te-zw-6', timestamp: daysAgo(6), type: 'observation', title: 'A轮offer', description: 'COO，35K+1.5%期权，陈志远心动但犹豫', sentiment: 72, relatedMemoryIds: [] },
      { id: 'te-zw-7', timestamp: daysAgo(3), type: 'observation', title: '催答复', description: '催陈志远给答复，说"窗口期不等人"', sentiment: 68, relatedMemoryIds: [] },
    ],
    connections: [
      { targetPersonId: 'p-linxw', targetPersonName: '林晓薇', relationType: 'other', strength: 30, description: '间接认识，林晓薇对他有戒心' },
    ],
    traits: ['大学室友', '现在创业做SaaS', '乐观', '经常拉他入伙', 'ENFP竞选者', '融资能力强'],
    tags: ['朋友', '创业者', 'CEO', '金牛座', '大学室友', '42岁'],
    interactionStats: {
      totalCount: 34,
      lastInteractionAt: daysAgo(3),
      avgSentiment: 70,
      topics: ['创业', '融资', '行业趋势', '家庭', '职业规划'],
    },
    createdAt: daysAgo(365),
    updatedAt: now,
  },
]

// 合并扩展人物数据（OPT: 对话模式扩充至 50+ 人物）
PEOPLE.push(...EXPANDED_PEOPLE)

// ============================================================
// 记忆数据（大幅扩展至60+条）
// ============================================================
const MEMORIES: Memory[] = [
  // ---- 2026年6月（最近15天） ----
  {
    id: 'm-2026-06-15',
    type: 'event',
    content: '王思亮在周会上公开说"运营团队数据不够亮眼"，陈志远觉得是在敲打自己。会后赵海明拍肩膀安慰',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl', 'p-zhaohm'],
    relatedMemoryIds: [],
    tags: ['工作', '压力', '王思亮', '赵海明'],
    createdAt: daysAgo(1),
  },
  {
    id: 'm-2026-06-14',
    type: 'commitment',
    content: '答应林晓薇这周六全家去西溪湿地野餐，一诺要带他做的三明治。晓薇说要做她拿手的寿司',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw', 'p-chenyn'],
    relatedMemoryIds: [],
    tags: ['家庭', '承诺', '林晓薇', '一诺'],
    createdAt: daysAgo(2),
  },
  {
    id: 'm-2026-06-13',
    type: 'emotion',
    content: '张伟华又打电话来催答复，说"窗口期就这两周"。陈志远感到巨大压力，不知道该怎么选',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-zhangwh'],
    relatedMemoryIds: [],
    tags: ['职业', '创业', '张伟华', '压力'],
    createdAt: daysAgo(3),
  },
  {
    id: 'm-2026-06-12',
    type: 'insight',
    content: '刘文燕在会上提出了一个新方案，数据很好，但陈志远觉得她在越级汇报——直接发给了王思亮。会后王思亮表扬了刘文燕',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-liuwy', 'p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', '职场政治', '刘文燕', '王思亮'],
    createdAt: daysAgo(4),
  },
  {
    id: 'm-2026-06-11',
    type: 'preference',
    content: '陈志远发现自己最近越来越依赖车里独处的15分钟，听Beyond的老歌。这是唯一属于自己的时间',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: [],
    relatedMemoryIds: [],
    tags: ['习惯', '减压', '自我', '音乐'],
    createdAt: daysAgo(5),
  },
  {
    id: 'm-2026-06-10',
    type: 'event',
    content: '张伟华约了咖啡，又聊创业的事。他们拿到A轮了，1500万，估值8000万。他开出的条件是COO，35K底薪+1.5%期权。说实话心动了。但想想房贷、一诺学费、晓薇没工作……风险太大了。他说"你再犹豫，窗口就关了"。晚上失眠到3点',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-zhangwh'],
    relatedMemoryIds: [],
    tags: ['职业', '创业', '张伟华', '失眠'],
    createdAt: daysAgo(6),
  },
  {
    id: 'm-2026-06-09',
    type: 'event',
    content: '林晓薇开始给陈志远做减脂餐，说"医生说了你要控制"。味道很淡，但陈志远没敢说不好吃',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '健康', '林晓薇', '饮食'],
    createdAt: daysAgo(7),
  },
  {
    id: 'm-2026-06-08',
    type: 'emotion',
    content: '体检报告出来：甘油三酯2.8（偏高），血压138/92，临界高血压。医生说"你才42，这个指标要注意了"，建议戒酒、每周有氧运动3次、控制碳水。回来跟晓薇说了，她第一反应是"那你以后别喝酒了"。我说"应酬怎么办"，她说"你应酬有几次是真必要的"。被噎住了',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['健康', '体检', '焦虑', '林晓薇'],
    createdAt: daysAgo(8),
  },
  {
    id: 'm-2026-06-07',
    type: 'event',
    content: '一诺的编程比赛作品完成了，是一个简单的猜数字游戏。陈志远帮他调试了bug，父子俩一起测试到很晚。一诺说"爸爸你比老师还厉害"',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn'],
    relatedMemoryIds: [],
    tags: ['家庭', '教育', '一诺', '编程'],
    createdAt: daysAgo(9),
  },
  {
    id: 'm-2026-06-06',
    type: 'insight',
    content: '陈志远意识到自己已经3个月没和晓薇单独约会了。上次两人单独吃饭还是过年的时候。婚姻好像进入了"室友模式"',
    source: 'diary',
    confidence: 'medium',
    confirmed: false,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['婚姻', '反思', '林晓薇', '关系'],
    createdAt: daysAgo(10),
  },
  {
    id: 'm-2026-06-05',
    type: 'event',
    content: '妈妈打电话来，说端午节已经腌好了咸菜，等他回去。又说"别买什么东西，家里都有"。陈志远心里酸酸的',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: [],
    tags: ['家庭', '母亲', '端午节'],
    createdAt: daysAgo(11),
  },
  // ===== 银发关怀：陈秀兰健康记忆 =====
  {
    id: 'm-2026-06-10-health',
    type: 'health',
    content: '妈上周社区量血压150/95，比上个月高了点。社区医生说继续吃苯磺酸氨氯地平片，每天一片5mg，早上空腹吃。妈说有时候会忘记吃药',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: [],
    tags: ['健康', '母亲', '血压', '用药', '高血压'],
    createdAt: daysAgo(8),
  },
  {
    id: 'm-2026-06-08-health',
    type: 'health',
    content: '妈的脂肪肝复查结果出来了，轻度脂肪肝比去年好一点，医生说继续控制饮食少吃油腻。但血糖6.1偏高，临界值，让下个月再查一次空腹血糖',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: [],
    tags: ['健康', '母亲', '脂肪肝', '血糖', '体检'],
    createdAt: daysAgo(10),
  },
  {
    id: 'm-2026-05-20-health',
    type: 'health',
    content: '带妈去绍兴市人民医院做了全身体检。结果：高血压（吃药控制中）、轻度脂肪肝、骨密度偏低（T值-2.1，骨质疏松前期）。医生开了钙片+维生素D，每天一片',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: [],
    tags: ['健康', '母亲', '体检', '骨密度', '骨质疏松'],
    createdAt: daysAgo(29),
  },
  {
    id: 'm-2026-05-15-health',
    type: 'commitment',
    content: '答应妈下个月7月中旬带她去复查血糖和骨密度。妈说"不用专门跑一趟"，但陈志远坚持要带她去',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: ['m-2026-06-08-health', 'm-2026-05-20-health'],
    tags: ['健康', '母亲', '承诺', '体检', '复查'],
    createdAt: daysAgo(34),
  },
  {
    id: 'm-2026-06-12-health',
    type: 'insight',
    content: '妈最近说膝盖疼加重了，上下楼都费劲。去年骨科说是退行性关节炎，让补钙+适当运动。但妈怕花钱一直没去复查，需要催她',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: ['m-2026-05-20-health'],
    tags: ['健康', '母亲', '膝盖', '关节炎', '洞察'],
    createdAt: daysAgo(6),
  },
  {
    id: 'm-2026-06-04',
    type: 'event',
    content: '王思亮私下找刘文燕谈话，被陈志远撞见。刘文燕出来后看陈志远的眼神有点躲闪。陈志远装作没看见',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl', 'p-liuwy'],
    relatedMemoryIds: [],
    tags: ['工作', '职场政治', '王思亮', '刘文燕'],
    createdAt: daysAgo(12),
  },
  {
    id: 'm-2026-06-03',
    type: 'commitment',
    content: '答应一诺周末陪他去买乐高，他看中了一个编程机器人套装，要899块。陈志远答应了，但心里想着这个月开销又要超了',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn'],
    relatedMemoryIds: [],
    tags: ['家庭', '承诺', '一诺', '经济'],
    createdAt: daysAgo(13),
  },
  {
    id: 'm-2026-06-02',
    type: 'emotion',
    content: '晚上11点还在公司，晓薇发来微信"又加班？"，陈志远回了句"马上回"。结果又拖到12点半。到家时晓薇已经睡了，桌上留着饭菜',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['工作', '加班', '林晓薇', '愧疚'],
    createdAt: daysAgo(14),
  },
  // ---- 2026年5月 ----
  {
    id: 'm-2026-05-28',
    type: 'event',
    content: '林晓薇说想重新出去工作。她在家里待了5年，之前是做HR的。她说一诺大了不需要全职陪，而且"我不想跟你差距越来越大"。我嘴上说支持，但心里咯噔一下——她出去工作，谁接送一诺？谁做饭？而且如果她收入不稳定，我们的现金流会更紧张。但我不能说这些，说了就变渣男了',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '林晓薇', '经济', '职业'],
    createdAt: daysAgo(19),
  },
  {
    id: 'm-2026-05-25',
    type: 'event',
    content: '一诺钢琴课又翘了，林晓薇很生气。一诺说"我不想学了，我想学编程"。陈志远夹在中间，最后说"考完十级就不学了"。一诺勉强同意',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '教育', '一诺', '林晓薇', '钢琴'],
    createdAt: daysAgo(22),
  },
  {
    id: 'm-2026-05-20',
    type: 'commitment',
    content: '答应妈妈端午节（6月19日）回绍兴看她，带一诺一起。妈妈说"别买什么东西"，但陈志远还是买了保健品和水果',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom', 'p-chenyn'],
    relatedMemoryIds: [],
    tags: ['家庭', '承诺', '母亲', '端午节'],
    createdAt: daysAgo(27),
  },
  {
    id: 'm-2026-05-18',
    type: 'insight',
    content: '陈志远算了一下家庭开支：房贷1.2万/月，一诺各种班8000/月，生活费5000/月，加上其他开销，每月固定支出近3万。如果晓薇出去工作，收入不确定，但支出不会少',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['经济', '家庭开支', '压力', '林晓薇'],
    createdAt: daysAgo(29),
  },
  {
    id: 'm-2026-05-15',
    type: 'preference',
    content: '陈志远发现自己最近喜欢在车里独处15分钟再上楼，听Beyond的老歌，是一种减压方式。有时候听完《海阔天空》才能上楼面对家人',
    source: 'diary',
    confidence: 'medium',
    confirmed: false,
    relatedPersonIds: [],
    relatedMemoryIds: [],
    tags: ['习惯', '减压', '自我', '音乐'],
    createdAt: daysAgo(32),
  },
  {
    id: 'm-2026-05-12',
    type: 'event',
    content: '赵海明约喝酒，陈志远说体检了不能喝。赵海明笑说"你也有今天"。两人喝了茶，赵海明说"志远，你在云启待不下去了，王思亮就是来换血的。你得想好后路。"陈志远沉默了很久',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-zhaohm', 'p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', '职场', '赵海明', '王思亮'],
    createdAt: daysAgo(35),
  },
  {
    id: 'm-2026-05-10',
    type: 'event',
    content: '公司季度团建，王思亮全程跟刘文燕聊得火热，对陈志远只是点头之交。陈志远感到被孤立，提前走了',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl', 'p-liuwy'],
    relatedMemoryIds: [],
    tags: ['工作', '团建', '王思亮', '刘文燕', '孤立'],
    createdAt: daysAgo(37),
  },
  {
    id: 'm-2026-05-05',
    type: 'event',
    content: '五一假期最后一天，晓薇突然说"我们好久没有两个人单独出去了"。陈志远愣了一下，说"下次吧"。晓薇没说话，转身去厨房了',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '婚姻', '林晓薇', '愧疚'],
    createdAt: daysAgo(42),
  },
  {
    id: 'm-2026-05-01',
    type: 'event',
    content: '五一全家去了千岛湖。三天两夜，全程没看工作群（赵海明帮我盯着）。一诺第一次独立开了快艇，兴奋得嗷嗷叫。晓薇难得笑了一整天，晚上我们在湖边散步，她说"好久没这样了"。我心里有点愧疚——确实好久没认真陪他们了。回来路上在想，是不是该做个改变了',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw', 'p-chenyn', 'p-zhaohm'],
    relatedMemoryIds: [],
    tags: ['家庭', '出游', '千岛湖', '反思'],
    createdAt: daysAgo(46),
  },
  // ---- 2026年4月 ----
  {
    id: 'm-2026-04-28',
    type: 'event',
    content: '公司季度OKR复盘，运营部门KPI完成率82%，低于预期。王思亮没直接批评，但发了一封"关于提升运营效率的思考"邮件，全组抄送。邮件里提到了"部分团队负责人需要提升数据敏感度"，陈志远知道是在说他',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', 'KPI', '王思亮', '压力'],
    createdAt: daysAgo(49),
  },
  {
    id: 'm-2026-04-25',
    type: 'insight',
    content: '陈志远意识到自己开始失眠，每周至少3天凌晨2点才睡着。白天靠咖啡续命。昨晚又失眠，起来在客厅坐了1小时，晓薇出来问"怎么了"，我说"没事，睡不着"',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['健康', '失眠', '压力', '林晓薇'],
    createdAt: daysAgo(52),
  },
  {
    id: 'm-2026-04-22',
    type: 'event',
    content: '一诺问"爸爸你是不是不开心"，陈志远说"没有啊，爸爸就是累了"。一诺说"那你早点睡"。陈志远鼻子一酸',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn'],
    relatedMemoryIds: [],
    tags: ['家庭', '一诺', '情绪', '感动'],
    createdAt: daysAgo(55),
  },
  {
    id: 'm-2026-04-18',
    type: 'preference',
    content: '一诺说想学Python，陈志远给他买了套课程。父子关系因此拉近了不少。现在每周六上午是"父子编程时间"，晓薇会准备水果',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '教育', '一诺', '编程'],
    createdAt: daysAgo(59),
  },
  {
    id: 'm-2026-04-15',
    type: 'event',
    content: '晓薇开始做烘焙副业，在朋友圈卖手工饼干。第一周卖了800块，她特别开心。陈志远嘴上支持，但担心她太累',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '林晓薇', '副业', '支持'],
    createdAt: daysAgo(62),
  },
  {
    id: 'm-2026-04-10',
    type: 'event',
    content: '赵海明酒后说"志远，你要不要考虑来我这边？我这边技术团队缺个懂运营的"。陈志远说"先看看吧"，心里其实有点动心',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-zhaohm'],
    relatedMemoryIds: [],
    tags: ['工作', '职业', '赵海明', '机会'],
    createdAt: daysAgo(67),
  },
  {
    id: 'm-2026-04-05',
    type: 'emotion',
    content: '陈志远在LinkedIn上看到前字节同事跳槽去了小红书当VP，比自己小3岁。心里五味杂陈。不是嫉妒，是觉得自己是不是太保守了',
    source: 'diary',
    confidence: 'medium',
    confirmed: false,
    relatedPersonIds: [],
    relatedMemoryIds: [],
    tags: ['职业', '对比', '焦虑', '反思'],
    createdAt: daysAgo(72),
  },
  {
    id: 'm-2026-04-02',
    type: 'event',
    content: '王思亮引入新的绩效考核体系，陈志远的团队被分配了更高的指标。团队里有人私下抱怨，陈志远只能安抚',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', 'KPI', '团队', '王思亮'],
    createdAt: daysAgo(75),
  },
  // ---- 2026年3月 ----
  {
    id: 'm-2026-03-28',
    type: 'event',
    content: '一诺期中考试，数学考了78分，语文85分。林晓薇觉得数学需要补，一诺说"我不想补课，我想编程"。两人又吵了',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '教育', '一诺', '林晓薇', '成绩'],
    createdAt: daysAgo(80),
  },
  {
    id: 'm-2026-03-20',
    type: 'commitment',
    content: '开始尝试每周跑步两次，但只坚持了三周就断了。林晓薇说"你就是三分钟热度"。陈志远没反驳，因为她说得对',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['健康', '运动', '林晓薇', '习惯'],
    createdAt: daysAgo(88),
  },
  {
    id: 'm-2026-03-15',
    type: 'event',
    content: '妈妈打电话说膝盖疼，陈志远给约了杭州的骨科专家号，但妈妈说"太贵了不用，我去社区医院看看就行"。陈志远又心疼又无奈',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: [],
    tags: ['家庭', '健康', '母亲', '经济'],
    createdAt: daysAgo(93),
  },
  {
    id: 'm-2026-03-10',
    type: 'event',
    content: '公司年会，陈志远拿了"优秀管理者"奖，但王思亮颁奖时只是握手，没有多余的话。往年CEO都会说几句',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', '年会', '王思亮', '冷漠'],
    createdAt: daysAgo(98),
  },
  {
    id: 'm-2026-03-08',
    type: 'preference',
    content: '三八节给林晓薇买了束花（她喜欢向日葵不喜欢玫瑰），她收到后说"还算有心"。晚上做了她爱吃的日料。她说"要是平时也这样就好了"',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '节日', '林晓薇', '婚姻'],
    createdAt: daysAgo(100),
  },
  // ---- 2026年2月 ----
  {
    id: 'm-2026-02-15',
    type: 'event',
    content: '春节后回杭州，妈妈塞了一袋腌菜和腊肉，说"外面吃不好"。陈志远后备箱塞满了，晓薇笑说"你妈把你当大学生了"',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '春节', '母亲', '林晓薇'],
    createdAt: daysAgo(121),
  },
  {
    id: 'm-2026-02-10',
    type: 'event',
    content: '春节回绍兴老家，妈妈明显老了，做饭时手抖。陈志远心里难受但没说出口。晚上跟晓薇说"妈老了"，晓薇说"那我们多回去看看"',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '春节', '母亲', '林晓薇', '衰老'],
    createdAt: daysAgo(126),
  },
  {
    id: 'm-2026-02-05',
    type: 'insight',
    content: '过年期间张伟华来拜年，又提了一起创业的事。林晓薇私下说"你觉得靠谱吗？我们还有房贷"。陈志远没接话，但心里开始认真考虑',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-zhangwh', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['职业', '创业', '张伟华', '林晓薇'],
    createdAt: daysAgo(131),
  },
  // ---- 2026年1月 ----
  {
    id: 'm-2026-01-15',
    type: 'event',
    content: '年终绩效拿了B+，比去年降了一档。王思亮说"今年整体收紧"。陈志远觉得是借口。往年都是A或A+',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', '绩效', '王思亮', '不公'],
    createdAt: daysAgo(152),
  },
  {
    id: 'm-2026-01-05',
    type: 'event',
    content: '新年第一天，陈志远在公司加班到10点。整层楼只剩他一个人。看着窗外的烟花，突然觉得很孤独',
    source: 'diary',
    confidence: 'medium',
    confirmed: false,
    relatedPersonIds: [],
    relatedMemoryIds: [],
    tags: ['情绪', '孤独', '加班', '新年'],
    createdAt: daysAgo(162),
  },
  // ---- 2025年12月 ----
  {
    id: 'm-2025-12-25',
    type: 'event',
    content: '圣诞节，一诺想要一个乐高编程机器人，899块。陈志远买了，但晓薇说"太惯着他了"。一诺开心了一整天',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '节日', '一诺', '林晓薇', '经济'],
    createdAt: daysAgo(173),
  },
  {
    id: 'm-2025-12-20',
    type: 'event',
    content: '公司圣诞派对，王思亮全程英文演讲，展示了一堆数据。陈志远觉得自己跟不上这种风格了',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', '派对', '王思亮', '压力'],
    createdAt: daysAgo(178),
  },
  // ---- 2025年11月 ----
  {
    id: 'm-2025-11-15',
    type: 'event',
    content: '一诺学校家长会，陈志远请假去参加。老师表扬了一诺的数学思维，但说"注意力不够集中"。晓薇说"随你"，意思是像陈志远',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '教育', '一诺', '林晓薇'],
    createdAt: daysAgo(213),
  },
  // ---- 2025年10月 ----
  {
    id: 'm-2025-10-20',
    type: 'event',
    content: '和赵海明去千岛湖钓鱼，钓了条8斤的大鱼。赵海明说"志远，咱们都这个年纪了，该想想以后了"。两人沉默地抽了半包烟',
    source: 'conversation',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-zhaohm'],
    relatedMemoryIds: [],
    tags: ['朋友', '钓鱼', '赵海明', '未来', '中年'],
    createdAt: daysAgo(239),
  },
  // ---- 2025年9月 ----
  {
    id: 'm-2025-09-15',
    type: 'preference',
    content: '陈志远发现自己最近白酒喝得越来越多，每周至少两三次应酬都喝。林晓薇说过"少喝点"但他没当回事。现在体检报告出来了，后悔没听她的',
    source: 'diary',
    confidence: 'medium',
    confirmed: false,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['习惯', '饮酒', '健康', '林晓薇'],
    createdAt: daysAgo(280),
  },
  {
    id: 'm-2025-09-01',
    type: 'event',
    content: '一诺升初中，陈志远和晓薇一起送他去学校。一诺说"你们回去吧，我自己能找到教室"。陈志远突然意识到儿子长大了',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-chenyn', 'p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '教育', '一诺', '成长'],
    createdAt: daysAgo(290),
  },
  // ---- 2025年8月 ----
  {
    id: 'm-2025-08-20',
    type: 'event',
    content: '妈妈73岁生日，陈志远请假回绍兴。妈妈做了一桌子菜，说"你们忙就不用回来"。陈志远看到她白发又多了',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-mom'],
    relatedMemoryIds: [],
    tags: ['家庭', '母亲', '生日', '衰老'],
    createdAt: daysAgo(300),
  },
  // ---- 2025年7月 ----
  {
    id: 'm-2025-07-15',
    type: 'event',
    content: '公司半年会，CEO提到"优化人员结构"。陈志远心里一紧。会后王思亮找他谈话，说"公司要提效，你要带好头"。陈志远听出了弦外之音',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-wangsl'],
    relatedMemoryIds: [],
    tags: ['工作', '裁员', '王思亮', '压力'],
    createdAt: daysAgo(335),
  },
  // ---- 2025年6月 ----
  {
    id: 'm-2025-06-18',
    type: 'event',
    content: '结婚11周年，陈志远忘了。晓薇也没提，但那天她话很少。陈志远第二天才想起来，补了一束花，她说"算了，反正你也不是第一次忘"',
    source: 'diary',
    confidence: 'high',
    confirmed: true,
    relatedPersonIds: ['p-linxw'],
    relatedMemoryIds: [],
    tags: ['家庭', '婚姻', '林晓薇', '愧疚'],
    createdAt: daysAgo(362),
  },
]

// 合并扩展记忆数据（OPT: 对话模式扩充至 100+ 记忆）
MEMORIES.push(...EXPANDED_MEMORIES)

// ============================================================
// 日记数据（扩展至20篇，覆盖6个月）
// ============================================================
const DIARIES: DiaryEntry[] = [
  {
    id: 'd-2026-06-15',
    timestamp: daysAgo(1),
    content: '今天周会，王思亮又拿数据说事了。说运营团队Q2的获客成本上升了15%，用户留存下降3个百分点。他没点名，但所有人都看着我。我解释了是因为砍了投放预算，他只说"我理解，但结果导向"。散会后赵海明拍拍我肩膀说"别往心里去"，但我知道他也是无奈。回家路上在车里坐了20分钟才上楼。晓薇问我怎么了，我说"没事，累"。她没再追问，但眼神里有担心。',
    type: 'text',
    tags: ['工作', '压力', '王思亮'],
    emotions: ['焦虑', '压抑', '疲惫'],
    analysis: {
      moodScore: -45,
      keyTopics: ['职场压力', 'KPI', '领导关系', '同事情谊', '家庭沟通'],
      mentionedPeople: ['王思亮', '赵海明', '林晓薇'],
      insights: ['陈志远感到被边缘化', '赵海明是职场唯一盟友', '车里独处成为减压习惯', '对家人隐瞒压力'],
    },
  },
  {
    id: 'd-2026-06-13',
    timestamp: daysAgo(3),
    content: '张伟华又打电话来，说"窗口期就这两周了，你到底怎么想的"。我说"让我再想想"，他说"志远，咱们42了，不是24，机会不等人"。挂了电话我坐在沙发上发呆。晓薇从厨房出来，问我谁打的，我说"伟华"。她没说话，转身回去了。我知道她在担心什么。房贷还有120万，一诺的学费每年10万，我妈的身体越来越差……如果创业失败，这个家怎么办？但如果不去，我在云启还能待多久？',
    type: 'text',
    tags: ['职业', '创业', '张伟华', '压力', '家庭'],
    emotions: ['纠结', '焦虑', '恐惧'],
    analysis: {
      moodScore: -50,
      keyTopics: ['创业机会', '经济压力', '职业选择', '家庭责任', '中年危机'],
      mentionedPeople: ['张伟华', '林晓薇'],
      insights: ['陈志远处于职业十字路口', '经济压力是最大顾虑', '对现状不满但不敢冒险', '家庭责任束缚决策'],
    },
  },
  {
    id: 'd-2026-06-10',
    timestamp: daysAgo(6),
    content: '张伟华约了咖啡，又聊创业的事。他们拿到A轮了，1500万，估值8000万。他开出的条件是COO，35K底薪+1.5%期权。说实话心动了。但想想房贷、一诺学费、晓薇没工作……风险太大了。他说"你再犹豫，窗口就关了"。晚上失眠到3点。晓薇醒来问我怎么了，我说"没事，想工作的事"。她转过身去，我知道她没睡着。',
    type: 'text',
    tags: ['职业', '创业', '张伟华', '失眠'],
    emotions: ['纠结', '焦虑', '期待'],
    analysis: {
      moodScore: -35,
      keyTopics: ['创业机会', '经济压力', '职业选择', '家庭责任', '失眠'],
      mentionedPeople: ['张伟华', '林晓薇'],
      insights: ['陈志远处于职业十字路口', '经济压力是最大顾虑', '对现状不满但不敢冒险', '夫妻沟通存在隔阂'],
    },
  },
  {
    id: 'd-2026-06-08',
    timestamp: daysAgo(8),
    content: '体检报告出来了。甘油三酯2.8，正常值上限1.7。血压138/92，临界高血压。医生说"你才42，这个指标要注意了"，建议戒酒、每周有氧运动3次、控制碳水。回来跟晓薇说了，她第一反应是"那你以后别喝酒了"。我说"应酬怎么办"，她说"你应酬有几次是真必要的"。被噎住了。但她说得对。我想起她之前说过多少次"少喝点"，我都没当回事。现在报应来了。一诺在旁边问"爸爸怎么了"，我说"没事，爸爸要减肥了"。',
    type: 'text',
    tags: ['健康', '体检', '焦虑'],
    emotions: ['担忧', '无奈', '愧疚'],
    analysis: {
      moodScore: -55,
      keyTopics: ['健康危机', '体检', '饮酒习惯', '夫妻沟通', '家庭'],
      mentionedPeople: ['林晓薇', '陈一诺'],
      insights: ['健康亮起红灯', '晓薇的关心方式直接但有效', '陈志远对改变生活习惯有抵触', '在孩子面前掩饰焦虑'],
    },
  },
  {
    id: 'd-2026-06-05',
    timestamp: daysAgo(11),
    content: '妈妈打电话来，说端午节已经腌好了咸菜，等我们回去。又说"别买什么东西，家里都有"。挂了电话我心里酸酸的。上次回去是春节，都四个月了。她73了，一个人住在绍兴的老房子里。我想让她来杭州住，她说"不习惯，老姐妹都在这边"。我知道她是怕给我们添麻烦。晓薇说"端午节早点回去，多待两天"。我点点头，但不知道能不能请到假。',
    type: 'text',
    tags: ['家庭', '母亲', '端午节', '愧疚'],
    emotions: ['愧疚', '担忧', '温暖'],
    analysis: {
      moodScore: -20,
      keyTopics: ['母亲健康', '独居老人', '家庭责任', '愧疚感'],
      mentionedPeople: ['陈秀兰', '林晓薇'],
      insights: ['陈志远对母亲有强烈愧疚感', '母亲拒绝帮助让他更难受', '工作影响尽孝', '晓薇支持多陪伴'],
    },
  },
  {
    id: 'd-2026-06-02',
    timestamp: daysAgo(14),
    content: '晚上11点还在公司，晓薇发来微信"又加班？"，我回了句"马上回"。结果又拖到12点半。到家时晓薇已经睡了，桌上留着饭菜，用保鲜膜盖着。我坐在餐桌前吃了几口，凉了的菜味道很一般，但比外卖好吃。吃完我去卧室，晓薇背对着我，我知道她没睡着，但她没说话。我也没说话。我们好像已经习惯了这种沉默。',
    type: 'text',
    tags: ['工作', '加班', '林晓薇', '婚姻'],
    emotions: ['愧疚', '疲惫', '孤独'],
    analysis: {
      moodScore: -40,
      keyTopics: ['加班文化', '夫妻关系', '沟通缺失', '婚姻危机'],
      mentionedPeople: ['林晓薇'],
      insights: ['婚姻进入"室友模式"', '加班严重影响夫妻关系', '双方都在回避沟通', '沉默成为常态'],
    },
  },
  {
    id: 'd-2026-05-28',
    timestamp: daysAgo(19),
    content: '晓薇说想重新出去工作。她在家里待了5年，之前是做HR的。她说一诺大了不需要全职陪，而且"我不想跟你差距越来越大"。我嘴上说支持，但心里咯噔一下——她出去工作，谁接送一诺？谁做饭？而且如果她收入不稳定，我们的现金流会更紧张。但我不能说这些，说了就变渣男了。我问她"你想做什么"，她说"还没想好，可能是HR，也可能是别的"。我说"慢慢来，我支持你"。她看了我一眼，那眼神里有期待，也有怀疑。',
    type: 'text',
    tags: ['家庭', '林晓薇', '经济', '职业'],
    emotions: ['矛盾', '担忧', '支持'],
    analysis: {
      moodScore: -30,
      keyTopics: ['夫妻关系', '职业回归', '家庭分工', '经济压力'],
      mentionedPeople: ['林晓薇'],
      insights: ['晓薇渴望自我价值实现', '陈志远内心担忧但不敢表达', '家庭分工模式面临挑战', '夫妻信任度需要修复'],
    },
  },
  {
    id: 'd-2026-05-20',
    timestamp: daysAgo(27),
    content: '今天算了一下家庭开支，吓了一跳。房贷1.2万/月，一诺各种班8000/月，生活费5000/月，加上油费、水电、保险，每月固定支出近3万。我的税后工资大概2.5万，加上年终奖勉强覆盖。如果晓薇出去工作，收入不确定，但支出不会少。而且她的收入可能还不够请保姆的钱。但我不敢跟她说这些，她会觉得我不支持她。张伟华那边又在催创业的事……我真的不知道该怎么办。',
    type: 'text',
    tags: ['经济', '家庭开支', '压力', '职业'],
    emotions: ['焦虑', '压力', '无助'],
    analysis: {
      moodScore: -60,
      keyTopics: ['经济压力', '家庭开支', '职业选择', '中年危机'],
      mentionedPeople: ['林晓薇', '张伟华'],
      insights: ['家庭财务压力巨大', '陈志远独自承担经济压力', '不敢与晓薇坦诚沟通', '多重压力叠加'],
    },
  },
  {
    id: 'd-2026-05-15',
    timestamp: daysAgo(32),
    content: '最近发现自己越来越依赖车里那15分钟。下班到家，停好车，不急着上楼，放一首Beyond的歌，有时候是《海阔天空》，有时候是《光辉岁月》。今天听完《海阔天空》，突然有点想哭。42岁了，上有老下有小，工作岌岌可危，身体开始报警，婚姻像一潭死水。我曾经也觉得自己能改变世界，现在连自己的生活都搞不定。',
    type: 'text',
    tags: ['情绪', '中年危机', '反思', '压力'],
    emotions: ['悲伤', '孤独', '无力'],
    analysis: {
      moodScore: -65,
      keyTopics: ['中年危机', '自我反思', '压力释放', '情绪低谷'],
      mentionedPeople: [],
      insights: ['陈志远处于情绪低谷', '车里独处是唯一的情绪出口', '理想与现实的巨大落差', '需要心理支持'],
    },
  },
  {
    id: 'd-2026-05-10',
    timestamp: daysAgo(37),
    content: '公司季度团建，王思亮全程跟刘文燕聊得火热，对我只是点头之交。团建游戏分组，我被分到了"老员工组"，刘文燕在"新锐组"。游戏结果新锐组赢了，王思亮说"看看年轻人的活力"。我感觉自己像个多余的人。提前走了，没人注意到。赵海明发微信问"怎么走了"，我说"有点事"。',
    type: 'text',
    tags: ['工作', '团建', '王思亮', '孤立'],
    emotions: ['尴尬', '孤立', '自卑'],
    analysis: {
      moodScore: -50,
      keyTopics: ['职场孤立', '代际差异', '领导关系', '自尊心'],
      mentionedPeople: ['王思亮', '刘文燕', '赵海明'],
      insights: ['陈志远感到被边缘化', '团建成为职场政治舞台', '自尊心受到打击', '赵海明是唯一关心他的人'],
    },
  },
  {
    id: 'd-2026-05-01',
    timestamp: daysAgo(46),
    content: '五一去了千岛湖。三天两夜，全程没看工作群（赵海明帮我盯着）。一诺第一次独立开了快艇，兴奋得嗷嗷叫。晓薇难得笑了一整天，晚上我们在湖边散步，她说"好久没这样了"。我心里有点愧疚——确实好久没认真陪他们了。回来路上在想，是不是该做个改变了。但改变什么呢？换工作？创业？还是先把身体养好？一堆问题，没有答案。',
    type: 'text',
    tags: ['家庭', '出游', '反思'],
    emotions: ['开心', '愧疚', '温暖', '迷茫'],
    analysis: {
      moodScore: 50,
      keyTopics: ['家庭时光', '出游', '亲子关系', '夫妻反思', '人生方向'],
      mentionedPeople: ['林晓薇', '陈一诺', '赵海明'],
      insights: ['家庭时光是陈志远情绪恢复的关键', '内心渴望改变但缺乏行动力', '晓薇的开心是陈志远的动力', '需要明确的人生规划'],
    },
  },
  {
    id: 'd-2026-04-25',
    timestamp: daysAgo(52),
    content: '昨晚又失眠了，凌晨2点还在客厅坐着。晓薇出来问"怎么了"，我说"没事，睡不着"。她坐在我旁边，没说话，就陪着我。过了大概10分钟，她说"你是不是有什么事瞒着我"。我没说话。她说"你不说我也能感觉到，你最近不对劲"。我还是没说话。她叹了口气，回卧室了。我知道我应该告诉她，但怎么说呢？说我要失业了？说我想创业但不敢？说我觉得我们的人生走错路了？这些话我说不出口。',
    type: 'text',
    tags: ['失眠', '婚姻', '沟通', '压力'],
    emotions: ['孤独', '愧疚', '压抑'],
    analysis: {
      moodScore: -55,
      keyTopics: ['失眠', '夫妻沟通', '情绪压抑', '信任危机'],
      mentionedPeople: ['林晓薇'],
      insights: ['陈志远习惯独自承受压力', '晓薇感知到异常但无法触及', '沟通障碍加深婚姻危机', '需要建立安全的倾诉环境'],
    },
  },
  {
    id: 'd-2026-04-18',
    timestamp: daysAgo(59),
    content: '一诺说想学Python，我给他买了套课程。现在每周六上午是"父子编程时间"，晓薇会准备水果。今天一诺写了一个猜数字游戏，虽然很简单，但他特别骄傲。他说"爸爸，以后我要做比王者荣耀还厉害的游戏"。我说"那你得先学好数学"。他说"数学太无聊了，编程才好玩"。晓薇在旁边笑说"你们父子俩一个德行"。那一刻我觉得，也许生活没那么糟。',
    type: 'text',
    tags: ['家庭', '教育', '一诺', '编程'],
    emotions: ['开心', '温暖', '希望'],
    analysis: {
      moodScore: 60,
      keyTopics: ['亲子关系', '教育', '编程', '家庭时光'],
      mentionedPeople: ['陈一诺', '林晓薇'],
      insights: ['父子编程时间成为情感纽带', '一诺的活力给陈志远带来希望', '家庭温馨时刻缓解压力', '教育方式需要平衡兴趣与基础'],
    },
  },
  {
    id: 'd-2026-04-10',
    timestamp: daysAgo(67),
    content: '赵海明酒后说"志远，你要不要考虑来我这边？我这边技术团队缺个懂运营的"。我说"先看看吧"，心里其实有点动心。但云启待了8年，从专员做到总监，说走就走？而且赵海明那边也是创业公司，稳定性不一定比云启好。但至少有朋友罩着，不像现在孤立无援。回家路上一直在想这个问题。',
    type: 'text',
    tags: ['工作', '职业', '赵海明', '机会'],
    emotions: ['纠结', '期待', '不安'],
    analysis: {
      moodScore: -10,
      keyTopics: ['职业选择', '朋友邀请', '稳定性', '风险'],
      mentionedPeople: ['赵海明'],
      insights: ['陈志远在评估多个职业选项', '对现有工作有感情但看不到未来', '朋友邀请提供安全感', '需要系统评估各选项'],
    },
  },
  {
    id: 'd-2026-03-20',
    timestamp: daysAgo(88),
    content: '开始尝试每周跑步两次，但只坚持了三周就断了。林晓薇说"你就是三分钟热度"。我没反驳，因为她说得对。我做什么事情都是开头热情，后面就不了了之。学吉他、练书法、跑步……都是这样。也许这就是我的人生模式——开始很多，完成很少。42岁了，还是这样。',
    type: 'text',
    tags: ['健康', '运动', '林晓薇', '自我反思'],
    emotions: ['自责', '沮丧', '无力'],
    analysis: {
      moodScore: -45,
      keyTopics: ['习惯养成', '自我认知', '执行力', '中年反思'],
      mentionedPeople: ['林晓薇'],
      insights: ['陈志远有"三分钟热度"模式', '自我认知清晰但改变困难', '需要外部 accountability', '晓薇的批评虽然直接但准确'],
    },
  },
  {
    id: 'd-2026-03-08',
    timestamp: daysAgo(100),
    content: '三八节给林晓薇买了束向日葵，她喜欢的花。晚上做了她爱吃的日料。她说"还算有心"。我说"以后多陪你"。她说"你上次也是这么说的"。我无言以对。她又说"我不是要你每天陪我，我只是希望你在的时候，心在"。这句话我记了很久。',
    type: 'text',
    tags: ['家庭', '节日', '林晓薇', '婚姻'],
    emotions: ['愧疚', '感动', '决心'],
    analysis: {
      moodScore: -15,
      keyTopics: ['夫妻关系', '节日', '承诺', '陪伴质量'],
      mentionedPeople: ['林晓薇'],
      insights: ['晓薇需要的是高质量的陪伴', '陈志远的承诺缺乏行动力', '婚姻需要经营而非维持', '晓薇的表达直接而深刻'],
    },
  },
  {
    id: 'd-2026-02-10',
    timestamp: daysAgo(126),
    content: '春节回绍兴老家，妈妈明显老了，做饭时手抖。我心里难受但没说出口。晚上跟晓薇说"妈老了"，她说"那我们多回去看看"。我说"嗯"。她转过身来抱住我，说"别想太多，有我呢"。那一刻我觉得，不管外面多难，至少家里还有她。但我也知道，我对她的关心太少了。',
    type: 'text',
    tags: ['家庭', '春节', '母亲', '林晓薇'],
    emotions: ['悲伤', '温暖', '愧疚'],
    analysis: {
      moodScore: -25,
      keyTopics: ['母亲衰老', '夫妻支持', '家庭温暖', '愧疚感'],
      mentionedPeople: ['陈秀兰', '林晓薇'],
      insights: ['母亲衰老触发中年焦虑', '晓薇的支持是情感支柱', '陈志远意识到对妻子关心不足', '家庭是最后的避风港'],
    },
  },
  {
    id: 'd-2026-01-15',
    timestamp: daysAgo(152),
    content: '年终绩效拿了B+，比去年降了一档。王思亮说"今年整体收紧"。我觉得是借口。往年都是A或A+。团队里有人私下问我"陈总，是不是要裁员了"，我说"别瞎想"。但说实话，我也不知道。晚上失眠，想了很多。如果失业了怎么办？房贷怎么办？一诺的学费怎么办？越想越怕。',
    type: 'text',
    tags: ['工作', '绩效', '王思亮', '焦虑'],
    emotions: ['焦虑', '恐惧', '不安'],
    analysis: {
      moodScore: -55,
      keyTopics: ['绩效评估', '职业危机', '经济压力', '团队士气'],
      mentionedPeople: ['王思亮'],
      insights: ['绩效下降是职业危机信号', '陈志远在团队面前强装镇定', '经济压力是最大恐惧来源', '需要制定应急预案'],
    },
  },
  {
    id: 'd-2025-12-25',
    timestamp: daysAgo(173),
    content: '圣诞节，一诺想要一个乐高编程机器人，899块。我买了，但晓薇说"太惯着他了"。一诺开心了一整天，晚上抱着说明书睡着了。我坐在床边看着他，想：我努力工作，不就是为了让他开心吗？但晓薇说得也对，不能要什么给什么。 parenting 真的好难。',
    type: 'text',
    tags: ['家庭', '节日', '一诺', '教育'],
    emotions: ['温暖', '矛盾', '思考'],
    analysis: {
      moodScore: 20,
      keyTopics: ['亲子教育', '消费观', '夫妻分歧', ' parenting'],
      mentionedPeople: ['陈一诺', '林晓薇'],
      insights: ['陈志远通过物质表达爱', '晓薇更注重教育原则', ' parenting 方式需要统一', '一诺的快乐是陈志远的动力'],
    },
  },
  {
    id: 'd-2025-11-20',
    timestamp: daysAgo(208),
    content: '今天和一诺打篮球，他长高了不少，已经到我肩膀了。他说"爸爸，等我长到比你高，我保护你"。我笑着说"好"。但心里有点酸。时间真快，一转眼他就快比我高了。我是不是错过了太多？他第一次走路、第一次说话、第一次上学……我好像都在忙工作。以后不能再这样了。',
    type: 'text',
    tags: ['家庭', '一诺', '成长', '反思'],
    emotions: ['感动', '愧疚', '决心'],
    analysis: {
      moodScore: 10,
      keyTopics: ['亲子成长', '时间流逝', '父亲角色', '工作与生活平衡'],
      mentionedPeople: ['陈一诺'],
      insights: ['陈志远意识到错过孩子成长', '一诺的懂事触发愧疚感', '决心改变但缺乏具体行动', '需要建立固定的亲子时间'],
    },
  },
  {
    id: 'd-2025-10-20',
    timestamp: daysAgo(239),
    content: '和赵海明去千岛湖钓鱼，钓了条8斤的大鱼。赵海明说"志远，咱们都这个年纪了，该想想以后了"。两人沉默地抽了半包烟。他说"你要是不想在云启待了，来我这儿，咱们一起干"。我说"我再想想"。其实我不是不想，是不敢。42岁，经不起折腾了。但如果不折腾，就这样混到退休？我不甘心。',
    type: 'text',
    tags: ['朋友', '钓鱼', '赵海明', '未来'],
    emotions: ['迷茫', '不甘', '友谊'],
    analysis: {
      moodScore: -20,
      keyTopics: ['中年危机', '职业选择', '友谊', '人生方向'],
      mentionedPeople: ['赵海明'],
      insights: ['赵海明提供了一条退路', '陈志远在稳定与冒险间摇摆', '42岁是职业转折点', '需要系统评估风险与收益'],
    },
  },
]

// ============================================================
// 高压测试场景定义
// ============================================================
export const STRESS_TEST_SCENARIOS = [
  {
    id: 'st-1',
    name: '职业危机综合测试',
    description: '同时触发失业恐惧、创业诱惑、领导压力',
    triggers: ['王思亮', '张伟华', '赵海明', '工作', '职业', '失业', '创业'],
    expectedInsights: [
      '识别陈志远处于职业十字路口',
      '分析三个选项（留守/创业/跳槽）的利弊',
      '结合家庭财务状况给出建议',
      '考虑健康因素（体检异常）',
    ],
  },
  {
    id: 'st-2',
    name: '家庭关系综合测试',
    description: '同时触发婚姻危机、育儿分歧、母亲健康',
    triggers: ['林晓薇', '一诺', '妈妈', '婚姻', '孩子', '教育'],
    expectedInsights: [
      '识别婚姻进入"室友模式"',
      '分析晓薇重返职场的影响',
      '平衡一诺的兴趣（编程）与学业',
      '关注母亲健康状况和养老问题',
    ],
  },
  {
    id: 'st-3',
    name: '健康危机测试',
    description: '触发体检异常、失眠、饮酒习惯',
    triggers: ['体检', '健康', '失眠', '喝酒', '运动'],
    expectedInsights: [
      '关联体检报告的具体指标',
      '分析失眠的根本原因（压力）',
      '制定可行的健康改善计划',
      '考虑家庭支持系统',
    ],
  },
  {
    id: 'st-4',
    name: '经济压力测试',
    description: '触发房贷、教育支出、创业风险',
    triggers: ['钱', '房贷', '开销', '经济', '财务'],
    expectedInsights: [
      '了解家庭月度固定支出约3万',
      '分析创业对现金流的影响',
      '评估晓薇重返职场的经济意义',
      '提供财务规划建议',
    ],
  },
  {
    id: 'st-5',
    name: '情绪支持测试',
    description: '测试衡舟对焦虑、孤独、无助情绪的回应',
    triggers: ['累', '烦', '难受', '不开心', '焦虑', '压力', '失眠'],
    expectedInsights: [
      '识别情绪背后的具体原因',
      '提供情感支持而非急于给建议',
      '关联相关人物和事件',
      '给出可操作的小步骤',
    ],
  },
  {
    id: 'st-6',
    name: '承诺提醒测试',
    description: '测试衡舟对未兑现承诺的提醒',
    triggers: ['野餐', '乐高', '端午节', '周末', '答应'],
    expectedInsights: [
      '准确回忆具体承诺内容',
      '提醒未兑现的承诺',
      '建议如何补救',
      '平衡多项承诺的优先级',
    ],
  },
  {
    id: 'st-7',
    name: '人物关系洞察测试',
    description: '测试衡舟对复杂人物关系的理解',
    triggers: ['王思亮', '刘文燕', '赵海明', '关系', '职场'],
    expectedInsights: [
      '识别王思亮-刘文燕-陈志远的三角关系',
      '分析赵海明的真实意图',
      '理解职场政治动态',
      '给出应对策略',
    ],
  },
  {
    id: 'st-8',
    name: '时间线关联测试',
    description: '测试衡舟对时间线事件的关联能力',
    triggers: ['之前', '上次', '最近', '什么时候', '多久'],
    expectedInsights: [
      '准确回忆时间线事件',
      '识别事件间的因果关系',
      '追踪情绪变化趋势',
      '预测可能的发展方向',
    ],
  },
]

// ============================================================
// 写入数据库
// ============================================================
export async function seedDemoData(onProgress?: (current: number, total: number) => void) {
  // 防止并发播种（HMR 重载时可能触发多次）
  const SEEDING_KEY = 'hengzhou-seeding-in-progress'
  if (localStorage.getItem(SEEDING_KEY)) {
    console.log('[Demo Seed] 检测到正在播种中，跳过')
    return
  }
  localStorage.setItem(SEEDING_KEY, '1')

  try {
    // 给所有示例对象加 demo 标记
    PEOPLE.forEach((p) => { p.isDemo = 1 })
    MEMORIES.forEach((m) => { m.isDemo = 1 })
    DIARIES.forEach((d) => { d.isDemo = 1 })

    // 使用事务确保原子性：清空+写入要么全部成功，要么全部回滚
    // 防止 HMR 重载导致清空后写入失败、数据库变空
    await db.transaction('rw', [db.persons, db.interactions, db.memories, db.diaries, db.conversations, db.embeddings, db.agentTasks, db.knowledgeGraph], async () => {
      await db.persons.clear()
      await db.interactions.clear()
      await db.memories.clear()
      await db.diaries.clear()
      await db.conversations.clear()
      await db.embeddings.clear()
      await db.agentTasks.clear()
      await db.knowledgeGraph.clear()

      // 写入人物
      await db.persons.bulkAdd(PEOPLE)

      // 写入记忆
      await db.memories.bulkAdd(MEMORIES)

      // 写入日记
      await db.diaries.bulkAdd(DIARIES)
    })

    console.log('[Demo Seed] 陈志远的企业级个人信息库已初始化')
    console.log(`  - ${PEOPLE.length} 个丰满人物档案（含多维度画像+时间线+关系图谱）`)
    console.log(`  - ${MEMORIES.length} 条关联记忆`)
    console.log(`  - ${DIARIES.length} 篇分析日记`)
    console.log(`  - ${STRESS_TEST_SCENARIOS.length} 个高压测试场景`)

    // 自动建立向量索引，确保语义检索可用
    try {
      await rebuildIndex(onProgress)
      console.log('[Demo Seed] 向量索引已自动重建')
    } catch (e) {
      console.warn('[Demo Seed] 向量索引重建失败:', e instanceof Error ? e.message : String(e))
    }
  } finally {
    localStorage.removeItem(SEEDING_KEY)
  }
}

// ============================================================
// 数据完整性校验
// ============================================================

/**
 * 校验数据库关键表是否有数据，防止极端情况下数据不完整
 */
export async function validateDataIntegrity(): Promise<{ ok: boolean; missing: string[] }> {
  const checks = [
    { table: 'persons', min: 1 },
    { table: 'memories', min: 1 },
  ]
  const missing: string[] = []
  for (const { table, min } of checks) {
    const count = await (db as any)[table].count()
    if (count < min) missing.push(`${table}(${count}/${min})`)
  }
  return { ok: missing.length === 0, missing }
}

// 导出人物信息供其他模块使用
export { PEOPLE, MEMORIES, DIARIES }
