# Generated by Django 4.2.16 on 2026-03-07 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='题目的简短标题', max_length=200, verbose_name='题目标题')),
                ('description', models.TextField(help_text='详细的题目要求和说明', verbose_name='题目描述')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], db_index=True, default='easy', max_length=10, verbose_name='难度等级')),
                ('test_cases_json', models.TextField(default='[]', help_text='JSON格式的测试用例列表', verbose_name='测试用例')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '编程题目',
                'verbose_name_plural': '编程题目',
                'db_table': 'problem',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['difficulty', '-created_at'], name='problem_difficu_3dc18d_idx')],
            },
        ),
    ]
