# Generated by Django 4.2.16 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_class_code'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='指定哪些班级可以看到此题目，留空表示所有学生可见', related_name='problems', to='teacher.class', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='problem',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='题目提交截止日期', null=True, verbose_name='截止时间'),
        ),
        migrations.AddField(
            model_name='problem',
            name='instructions',
            field=models.TextField(blank=True, help_text='详细的题目要求和说明', null=True, verbose_name='题目说明'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_published',
            field=models.BooleanField(default=True, help_text='只有发布的题目学生才能看到', verbose_name='是否发布'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_published', '-created_at'], name='problem_is_publ_796d30_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['deadline'], name='problem_deadlin_69db2b_idx'),
        ),
    ]
