# Generated by Django 4.2.16 on 2026-03-14 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_classes_problem_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='llm_logic_bonus',
            field=models.IntegerField(default=30, help_text='当 LLM 判定逻辑正确时，在原始得分上额外加分的幅度，不超过 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='LLM 逻辑加分（百分比）'),
        ),
    ]
