# Generated by Django 4.2 on 2026-01-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='最后一条消息内容')),
                ('last_message_time', models.DateTimeField(auto_now=True, verbose_name='最后一条消息时间')),
                ('status', models.SmallIntegerField(choices=[(0, '已关闭'), (1, '正常')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='merchant.merchant', verbose_name='关联商户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '会话表',
                'verbose_name_plural': '会话表',
                'db_table': 'conversation',
                'unique_together': {('user', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.SmallIntegerField(choices=[(1, '文本'), (2, '图片')], default=1, verbose_name='消息类型')),
                ('status', models.SmallIntegerField(choices=[(1, '未读'), (2, '已读')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='关联会话')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='user.user', verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='user.user', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息表',
                'verbose_name_plural': '消息表',
                'db_table': 'message',
            },
        ),
    ]
