# Generated by Django 4.2 on 2026-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='邮箱')),
                ('avatar', models.URLField(blank=True, max_length=255, null=True, verbose_name='头像图片链接')),
                ('status', models.SmallIntegerField(choices=[(0, '封禁'), (1, '启用')], default=1, verbose_name='用户状态')),
                ('user_type', models.SmallIntegerField(choices=[(1, '学生'), (2, '商户'), (3, '系统管理员')], verbose_name='用户类型')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户基础信息表',
                'verbose_name_plural': '用户基础信息表',
                'db_table': 'user',
            },
        ),
    ]
