# Generated by Django 4.2 on 2026-01-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_real_name',
            field=models.SmallIntegerField(choices=[(0, '未实名'), (1, '已实名')], default=0, verbose_name='是否实名'),
        ),
    ]
