# Generated by Django 4.2 on 2026-05-03 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='充值金额')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('trade_no', models.CharField(blank=True, max_length=100, verbose_name='交易号')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'db_table': 'recharge_record',
                'ordering': ['-create_time'],
            },
        ),
    ]
