# Generated by Django 4.2 on 2026-05-07 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rechargerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account', '账户问题'), ('payment', '支付问题'), ('product', '商品问题'), ('suggestion', '建议反馈'), ('other', '其他问题')], max_length=20, verbose_name='问题类型')),
                ('content', models.TextField(verbose_name='问题描述')),
                ('status', models.SmallIntegerField(choices=[(0, '未读'), (1, '已读'), (2, '已处理')], default=0, verbose_name='状态')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='管理员回复')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '联系管理员消息',
                'verbose_name_plural': '联系管理员消息',
                'db_table': 'contact_admin',
                'ordering': ['-create_time'],
            },
        ),
    ]
