# Generated by Django 4.2 on 2026-05-07 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_contactadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('status', models.SmallIntegerField(choices=[(0, '未读'), (1, '已读'), (2, '已回复')], default=0, verbose_name='状态')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='管理员回复')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '联系管理员消息',
                'verbose_name_plural': '联系管理员消息',
                'db_table': 'contact_message',
                'ordering': ['-create_time'],
            },
        ),
        migrations.DeleteModel(
            name='ContactAdmin',
        ),
    ]
