# Generated by Django 4.2 on 2026-01-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='is_certified',
        ),
    ]
