# Generated by Django 4.2 on 2026-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_studentinfo_is_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='is_certified',
            field=models.SmallIntegerField(choices=[(0, '未认证'), (1, '已认证')], default=0, verbose_name='是否认证'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='student_card_image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='学生证照片链接'),
        ),
    ]
