import os

dest = r"C:\Users\lawliet\AppData\Roaming\TRAE SOLO CN\ModularData\ai-agent\work-mode-projects\6a50c411efd3f309fec531b2\tutor-assistant\pages\chat-analysis.html"

J = []
J.append('  <script>')
J.append('  (function() {')
J.append("    'use strict';")
J.append('')
J.append('    // === DOM refs ===')
J.append("    var uploadArea = document.getElementById('uploadArea');")
J.append("    var fileInput = document.getElementById('fileInput');")
J.append("    var fileInfoBar = document.getElementById('fileInfoBar');")
J.append("    var fileName = document.getElementById('fileName');")
J.append("    var fileSize = document.getElementById('fileSize');")
J.append("    var analysisResults = document.getElementById('analysisResults');")
J.append("    var emptyState = document.getElementById('emptyState');")
J.append("    var bottomBar = document.getElementById('bottomBar');")
J.append("    var analyzingOverlay = document.getElementById('analyzingOverlay');")
J.append("    var loadSampleBtn = document.getElementById('loadSampleBtn');")
J.append("    var btnReanalyze = document.getElementById('btnReanalyze');")
J.append("    var btnSave = document.getElementById('btnSave');")
J.append("    var contactListEl = document.getElementById('contactList');")
J.append("    var addNewContactBtn = document.getElementById('addNewContactBtn');")
J.append("    var addContactForm = document.getElementById('addContactForm');")
J.append("    var newContactNameInput = document.getElementById('newContactName');")
J.append("    var newStudentNameInput = document.getElementById('newStudentName');")
J.append("    var confirmAddContactBtn = document.getElementById('confirmAddContact');")
J.append("    var cancelAddContactBtn = document.getElementById('cancelAddContact');")
J.append('')
J.append('    // === Contact Management ===')
J.append('    var contacts = [')
J.append("      { id: 1, name: '\u738b\u5988\u5988', student: '\u5c0f\u660e', avatar: '\u738b', selected: false },")
J.append("      { id: 2, name: '\u674e\u7238\u7238', student: '\u5c0f\u7ea2', avatar: '\u674e', selected: false },")
J.append("      { id: 3, name: '\u8d75\u5988\u5988', student: '\u5c0f\u521a', avatar: '\u8d75', selected: false }")
J.append('    ];')
J.append('    var selectedContactId = null;')
J.append('')
J.append('    function renderContacts() {')
J.append('      var html = "";')
J.append('      for (var i = 0; i < contacts.length; i++) {')
J.append('        var c = contacts[i];')
J.append('        var selClass = c.id === selectedContactId ? " selected" : "";')
J.append('        html += \'<div class="contact-item\' + selClass + \'" data-contact-id="\' + c.id + \'">\';')
J.append('        html += \'<div class="contact-item-avatar">\' + escapeHtml(c.avatar) + \'</div>\';')
J.append('        html += \'<div class="contact-item-name">\' + escapeHtml(c.name) + \'</div>\';')
J.append('        html += \'<div class="contact-item-student">\' + escapeHtml(c.student) + \'</div>\';')
J.append('        html += \'</div>\';')
J.append('      }')
J.append('      contactListEl.innerHTML = html;')
J.append('      var items = contactListEl.querySelectorAll(\'.contact-item\');')
J.append('      for (var j = 0; j < items.length; j++) {')
J.append('        (function(item) {')
J.append('          item.addEventListener(\'click\', function() {')
J.append('            var cid = parseInt(this.getAttribute(\'data-contact-id\'), 10);')
J.append('            selectContact(cid);')
J.append('          });')
J.append('        })(items[j]);')
J.append('      }')
J.append('    }')
J.append('')
J.append('    function selectContact(id) {')
J.append('      selectedContactId = id;')
J.append('      for (var i = 0; i < contacts.length; i++) {')
J.append('        contacts[i].selected = (contacts[i].id === id);')
J.append('      }')
J.append('      renderContacts();')
J.append('    }')
J.append('')
J.append('    function addContact(name, student) {')
J.append('      var newId = contacts.length > 0 ? contacts[contacts.length - 1].id + 1 : 1;')
J.append('      var avatar = name.charAt(0);')
J.append('      contacts.push({ id: newId, name: name, student: student, avatar: avatar, selected: false });')
J.append('      selectContact(newId);')
J.append('    }')
J.append('')
J.append("    addNewContactBtn.addEventListener('click', function() {")
J.append("      addContactForm.style.display = 'block';")
J.append("      newContactNameInput.value = '';")
J.append("      newStudentNameInput.value = '';")
J.append("      newContactNameInput.style.borderColor = 'var(--border-default)';")
J.append("      newStudentNameInput.style.borderColor = 'var(--border-default)';")
J.append("      newContactNameInput.focus();")
J.append('    });')
J.append('')
J.append("    cancelAddContactBtn.addEventListener('click', function() {")
J.append("      addContactForm.style.display = 'none';")
J.append('    });')
J.append('')
J.append("    confirmAddContactBtn.addEventListener('click', function() {")
J.append('      var nameVal = newContactNameInput.value.trim();')
J.append('      var studentVal = newStudentNameInput.value.trim();')
J.append('      if (!nameVal) { newContactNameInput.style.borderColor = \'#DC2626\'; return; }')
J.append('      if (!studentVal) { newStudentNameInput.style.borderColor = \'#DC2626\'; return; }')
J.append('      addContact(nameVal, studentVal);')
J.append("      addContactForm.style.display = 'none';")
J.append('    });')
J.append('')
J.append("    newContactNameInput.addEventListener('focus', function() { this.style.borderColor = 'var(--border-default)'; });")
J.append("    newStudentNameInput.addEventListener('focus', function() { this.style.borderColor = 'var(--border-default)'; });")
J.append('    renderContacts();')
J.append('')
J.append('    // === Subject color mapping ===')
J.append('    var subjectColorMap = {')
J.append("      '\u6570\u5b66': 'subject-pill-blue',")
J.append("      '\u82f1\u8bed': 'subject-pill-green',")
J.append("      '\u7269\u7406': 'subject-pill-amber',")
J.append("      '\u5316\u5b66': 'subject-pill-purple'")
J.append('    };')
J.append('    function getSubjectPillClass(subjectName) {')
J.append('      if (subjectColorMap[subjectName]) return subjectColorMap[subjectName];')
J.append("      return 'subject-pill-gray';")
J.append('    }')

with open(dest, 'a', encoding='utf-8') as f:
    f.write('\n'.join(J) + '\n')
print('Part 3a done: DOM refs + contacts + subject colors')
