import os

dest = r"C:\Users\lawliet\AppData\Roaming\TRAE SOLO CN\ModularData\ai-agent\work-mode-projects\6a50c411efd3f309fec531b2\tutor-assistant\pages\chat-analysis.html"

J = []
J.append('')
J.append('      // --- Extract salary with subject awareness ---')
J.append('      var salaryEntries = [];')
J.append('      var seenSalaryKeys = {};')
J.append('')
J.append('      function getLineDate(line) {')
J.append('        var dm = line.match(/(\\d{4})[-\\/](\\d{1,2})[-\\/](\\d{1,2})/);')
J.append('        if (dm) return dm[1] + "\\u5e74" + parseInt(dm[2], 10) + "\\u6708" + parseInt(dm[3], 10) + "\\u65e5";')
J.append('        if (conversationDate) {')
J.append('          var parts = conversationDate.split(/[-\\/]/);')
J.append('          if (parts.length >= 3) return parts[0] + "\\u5e74" + parseInt(parts[1], 10) + "\\u6708" + parseInt(parts[2], 10) + "\\u65e5";')
J.append('        }')
J.append("        return '';")
J.append('      }')
J.append('')
J.append('      function parseDateForSort(dateStr) {')
J.append('        var ym = dateStr.match(/(\\d{4})\\u5e74(\\d{1,2})\\u6708/);')
J.append('        if (ym) return parseInt(ym[1], 10) * 100 + parseInt(ym[2], 10);')
J.append('        var mOnly = dateStr.match(/(\\d{1,2})\\u6708(\\d{1,2})\\u65e5?/);')
J.append('        if (mOnly) return 2026 * 100 + parseInt(mOnly[1], 10);')
J.append('        return 0;')
J.append('      }')
J.append('')
J.append('      var subjectNames = "\\u6570\\u5b66|\\u82f1\\u8bed|\\u7269\\u7406|\\u5316\\u5b66|\\u8bed\\u6587|\\u751f\\u7269|\\u5386\\u53f2|\\u653f\\u6cbb|\\u5730\\u7406";')
J.append('')
J.append('      for (var si = 0; si < normalized.length; si++) {')
J.append('        var sline = normalized[si];')
J.append('        var lineDate = getLineDate(sline);')
J.append('')
J.append('        // 1. Adjustment: "8月1日起数学和物理课酬调整为220元/小时"')
J.append("        var adjRegex = new RegExp('(\\\\d{1,2}\\\\u6708\\\\d{1,2}\\\\u65e5?)[\\\\u8d77\\\\u4ece]\\\\s*(?:(' + subjectNames + ')\\\\u548c(' + subjectNames + ')|(' + subjectNames + '))?(?:\\\\u8bfe\\\\u916c)?(?:\\\\u8c03\\\\u6574|\\\\u6539\\\\u4e3a|\\\\u53d8\\\\u4e3a)\\\\s*(?:\\\\u4e3a)?(\\\\d+)\\\\s*\\\\u5143\\\\/\\\\u5c0f\\\\u65f6');")
J.append('        adjRegex.lastIndex = 0;')
J.append('        var adjMatch = adjRegex.exec(sline);')
J.append('        if (adjMatch) {')
J.append('          var adjDateRaw = adjMatch[1];')
J.append('          var adjRate = adjMatch[adjMatch.length - 1];')
J.append('          var adjSubjects = [];')
J.append('          if (adjMatch[2] && adjMatch[3]) { adjSubjects = [adjMatch[2], adjMatch[3]]; }')
J.append('          else if (adjMatch[4]) { adjSubjects = [adjMatch[4]]; }')
J.append('          if (adjSubjects.length === 0) {')
J.append("            var ctxMatch = sline.match(new RegExp('(' + subjectNames + ')\\\\u548c(' + subjectNames + ')\\\\u8bfe\\\\u916c(?:\\\\u8c03\\\\u6574|\\\\u6539\\\\u4e3a|\\\\u53d8\\\\u4e3a)'));")
J.append('            if (ctxMatch) { adjSubjects = [ctxMatch[1], ctxMatch[2]]; }')
J.append('            else {')
J.append("              var singleCtxMatch = sline.match(new RegExp('(' + subjectNames + ')\\\\u8bfe\\\\u916c(?:\\\\u8c03\\\\u6574|\\\\u6539\\\\u4e3a|\\\\u53d8\\\\u4e3a)'));")
J.append('              if (singleCtxMatch) { adjSubjects = [singleCtxMatch[1]]; }')
J.append('            }')
J.append('          }')
J.append('          if (adjSubjects.length === 0) adjSubjects = ["\\u5176\\u4ed6"];')
J.append('          var adjYear = lineDate.match(/(\\d{4})/);')
J.append('          var adjDateFull = adjYear ? adjYear[1] + "\\u5e74" + adjDateRaw : adjDateRaw;')
J.append('          var effDate = parseDateForSort(adjDateFull);')
J.append('          var salStatus = effDate > 726 ? "pending" : "active";')
J.append('          for (var ai = 0; ai < adjSubjects.length; ai++) {')
J.append('            var aSubj = adjSubjects[ai];')
J.append('            var aKey = "adj-" + aSubj + "-" + adjRate;')
J.append('            if (!seenSalaryKeys[aKey]) {')
J.append('              seenSalaryKeys[aKey] = true;')
J.append('              salaryEntries.push({ subject: aSubj, rate: adjRate, effectiveDate: adjDateFull + "\\u8d77\\u751f\\u6548", effectiveDateSort: effDate, status: salStatus, isAdjustment: true, isCurrent: false, conversationDate: lineDate });')
J.append('            }')
J.append('          }')
J.append('          continue;')
J.append('        }')
J.append('')
J.append('        // 2. Keep pattern: "英语课酬保持180元/小时不变"')
J.append('        var keepRegex = new RegExp("(" + subjectNames + ")\\\\u548c(" + subjectNames + ")\\\\u8bfe\\\\u916c(?:\\\\u4fdd\\\\u6301|\\\\u7ef4\\\\u6301)\\\\s*(\\\\d+)\\\\s*\\\\u5143\\\\/\\\\u5c0f\\\\u65f6(?:\\\\u4e0d\\\\u53d8)?");')
J.append('        keepRegex.lastIndex = 0;')
J.append('        var keepMatch = keepRegex.exec(sline);')
J.append('        if (keepMatch) {')
J.append('          var keepSubjects = [keepMatch[1], keepMatch[2]];')
J.append('          var keepRate = keepMatch[3];')
J.append('          for (var ki = 0; ki < keepSubjects.length; ki++) {')
J.append('            var kSubj = keepSubjects[ki];')
J.append('            var kKey = "keep-" + kSubj + "-" + keepRate;')
J.append('            if (!seenSalaryKeys[kKey]) {')
J.append('              seenSalaryKeys[kKey] = true;')
J.append('              salaryEntries.push({ subject: kSubj, rate: keepRate, effectiveDate: "\\u5f53\\u524d\\u6807\\u51c6", effectiveDateSort: 0, status: "active", isAdjustment: false, isCurrent: true, conversationDate: lineDate });')
J.append('            }')
J.append('          }')
J.append('          continue;')
J.append('        }')
J.append('        var keepSingleRegex = new RegExp("(" + subjectNames + ")\\\\u8bfe\\\\u916c(?:\\\\u4fdd\\\\u6301|\\\\u7ef4\\\\u6301)\\\\s*(\\\\d+)\\\\s*\\\\u5143\\\\/\\\\u5c0f\\\\u65f6(?:\\\\u4e0d\\\\u53d8)?");')
J.append('        keepSingleRegex.lastIndex = 0;')
J.append('        var keepSingleMatch = keepSingleRegex.exec(sline);')
J.append('        if (keepSingleMatch) {')
J.append('          var ksSubj = keepSingleMatch[1]; var ksRate = keepSingleMatch[2];')
J.append('          var ksKey = "keep-" + ksSubj + "-" + ksRate;')
J.append('          if (!seenSalaryKeys[ksKey]) {')
J.append('            seenSalaryKeys[ksKey] = true;')
J.append('            salaryEntries.push({ subject: ksSubj, rate: ksRate, effectiveDate: "\\u5f53\\u524d\\u6807\\u51c6", effectiveDateSort: 0, status: "active", isAdjustment: false, isCurrent: true, conversationDate: lineDate });')
J.append('          }')
J.append('          continue;')
J.append('        }')
J.append('')
J.append('        // 3. Historical: "数学和物理课酬200元/小时，从2026年1月至今"')
J.append('        var histRegex = new RegExp("(" + subjectNames + ")\\\\u548c(" + subjectNames + ")\\\\u8bfe\\\\u916c\\\\s*(\\\\d+)\\\\s*\\\\u5143\\\\/\\\\u5c0f\\\\u65f6");')
J.append('        histRegex.lastIndex = 0;')
J.append('        var histMatch = histRegex.exec(sline);')
J.append('        if (histMatch) {')
J.append('          var histSubjects = [histMatch[1], histMatch[2]];')
J.append('          var histRate = histMatch[3];')
J.append('          var histDateContext = sline.match(/\\\\u4ece(\\\\d{4})\\\\u5e74(\\\\d{1,2})\\\\u6708(?:\\\\u5f00\\\\u59cb|\\\\u8d77|\\\\u81f3\\\\u4eca)/);')
J.append('          var histEffDate = ""; var histEffDateSort = 0;')
J.append('          if (histDateContext) {')
J.append('            histEffDate = histDateContext[1] + "\\u5e74" + histDateContext[2] + "\\u6708\\u8d77";')
J.append('            histEffDateSort = parseInt(histDateContext[1], 10) * 100 + parseInt(histDateContext[2], 10);')
J.append('          }')
J.append('          for (var hi = 0; hi < histSubjects.length; hi++) {')
J.append('            var hSubj = histSubjects[hi];')
J.append('            var hKey = "hist-" + hSubj + "-" + histRate;')
J.append('            if (!seenSalaryKeys[hKey]) {')
J.append('              seenSalaryKeys[hKey] = true;')
J.append('              salaryEntries.push({ subject: hSubj, rate: histRate, effectiveDate: histEffDate, effectiveDateSort: histEffDateSort, status: "historical", isAdjustment: false, isCurrent: false, conversationDate: lineDate });')
J.append('            }')
J.append('          }')
J.append('          continue;')
J.append('        }')
J.append('        var histSingleRegex = new RegExp("(" + subjectNames + ")\\\\u8bfe\\\\u916c\\\\s*(\\\\d+)\\\\s*\\\\u5143\\\\/\\\\u5c0f\\\\u65f6");')
J.append('        histSingleRegex.lastIndex = 0;')
J.append('        var histSingleMatch = histSingleRegex.exec(sline);')
J.append('        if (histSingleMatch) {')
J.append('          var hsSubj = histSingleMatch[1]; var hsRate = histSingleMatch[2];')
J.append('          var hsKey = "hist-" + hsSubj + "-" + hsRate;')
J.append('          if (!seenSalaryKeys[hsKey]) {')
J.append('            seenSalaryKeys[hsKey] = true;')
J.append('            salaryEntries.push({ subject: hsSubj, rate: hsRate, effectiveDate: "", effectiveDateSort: 0, status: "current", isAdjustment: false, isCurrent: true, conversationDate: lineDate });')
J.append('          }')
J.append('        }')
J.append('      }')
J.append('')
J.append('      salaryEntries.sort(function(a, b) {')
J.append('        if (a.isCurrent && !b.isCurrent) return -1;')
J.append('        if (!a.isCurrent && b.isCurrent) return 1;')
J.append('        return b.effectiveDateSort - a.effectiveDateSort;')
J.append('      });')
J.append('      results.salaries = salaryEntries;')
J.append('      return results;')
J.append('    }')

with open(dest, 'a', encoding='utf-8') as f:
    f.write('\n'.join(J) + '\n')
print('Part 3d done: parseChat salary extraction')
