# Generated by Django 4.2 on 2026-01-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('product_desc', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('product_images', models.JSONField(blank=True, null=True, verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品售价')),
                ('status', models.SmallIntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='状态')),
                ('total_stock', models.IntegerField(default=0, verbose_name='总库存数量')),
                ('remaining_stock', models.IntegerField(default=0, verbose_name='剩余库存数量')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏量')),
                ('is_recommend', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否推荐')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategory', verbose_name='关联分类')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchant.merchant', verbose_name='关联商户')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='product.product', verbose_name='关联商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '商品收藏表',
                'verbose_name_plural': '商品收藏表',
                'db_table': 'collection',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
