# Generated by Django 4.2 on 2026-01-09 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_product_original_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('rating', models.IntegerField(default=5, verbose_name='评分(1-5)')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='评价图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='关联商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '商品评价表',
                'verbose_name_plural': '商品评价表',
                'db_table': 'product_review',
                'ordering': ['-create_time'],
            },
        ),
    ]
