import type { Route, SharedRoute, Badge, User } from '@shared/types';

export const mockRoutes: Route[] = [
  {
    id: 'route-001',
    type: 'boomerang',
    typeLabel: '回旋镖航线',
    from: '北京',
    to: '上海',
    date: '2026-07-10',
    totalPrice: 680,
    totalDuration: 300,
    savings: 520,
    extraTime: 120,
    rating: 4.8,
    reviewCount: 128,
    directPrice: 1200,
    directDuration: 140,
    highlights: ['经停青岛可出机场', '青岛机场免费休息区', '省下520元吃海鲜'],
    segments: [
      {
        id: 'seg-001-1',
        type: 'flight',
        from: '北京大兴',
        to: '青岛流亭',
        departureTime: '08:00',
        arrivalTime: '09:30',
        duration: 90,
        price: 320,
        carrier: '中国国航',
        flightNo: 'CA1234',
      },
      {
        id: 'seg-001-2',
        type: 'flight',
        from: '青岛流亭',
        to: '上海虹桥',
        departureTime: '12:30',
        arrivalTime: '14:00',
        duration: 90,
        price: 360,
        carrier: '东方航空',
        flightNo: 'MU5678',
      },
    ],
    layovers: [
      {
        city: '青岛',
        duration: 180,
        type: 'airport',
        tips: ['机场有免费休息区', '可乘地铁去市区吃海鲜', '3号航站楼有行李寄存'],
      },
    ],
  },
  {
    id: 'route-002',
    type: 'open_jaw',
    typeLabel: '开口程方案',
    from: '北京',
    to: '杭州',
    date: '2026-07-10',
    totalPrice: 750,
    totalDuration: 360,
    savings: 450,
    extraTime: 180,
    rating: 4.6,
    reviewCount: 89,
    directPrice: 1200,
    directDuration: 150,
    highlights: ['南京停留6小时', '可逛夫子庙吃小吃', '高铁接驳便捷'],
    segments: [
      {
        id: 'seg-002-1',
        type: 'train',
        from: '北京南',
        to: '南京南',
        departureTime: '07:00',
        arrivalTime: '11:30',
        duration: 270,
        price: 440,
        carrier: '中国铁路',
        trainNo: 'G101',
      },
      {
        id: 'seg-002-2',
        type: 'train',
        from: '南京南',
        to: '杭州东',
        departureTime: '17:30',
        arrivalTime: '19:00',
        duration: 90,
        price: 310,
        carrier: '中国铁路',
        trainNo: 'G203',
      },
    ],
    layovers: [
      {
        city: '南京',
        duration: 360,
        type: 'city',
        tips: ['地铁直达夫子庙', '推荐鸭血粉丝汤', '行李可寄存在南京南站'],
      },
    ],
  },
  {
    id: 'route-003',
    type: 'same_train',
    typeLabel: '同车接续',
    from: '北京',
    to: '广州',
    date: '2026-07-10',
    totalPrice: 890,
    totalDuration: 480,
    savings: 380,
    extraTime: 60,
    rating: 4.9,
    reviewCount: 256,
    directPrice: 1270,
    directDuration: 420,
    highlights: ['同站换乘仅需20分钟', '武汉站吃热干面', '全程高铁不换站'],
    segments: [
      {
        id: 'seg-003-1',
        type: 'train',
        from: '北京西',
        to: '武汉',
        departureTime: '08:00',
        arrivalTime: '12:30',
        duration: 270,
        price: 520,
        carrier: '中国铁路',
        trainNo: 'G79',
      },
      {
        id: 'seg-003-2',
        type: 'train',
        from: '武汉',
        to: '广州南',
        departureTime: '13:00',
        arrivalTime: '16:40',
        duration: 220,
        price: 370,
        carrier: '中国铁路',
        trainNo: 'G1009',
      },
    ],
    layovers: [
      {
        city: '武汉',
        duration: 30,
        type: 'station',
        tips: ['站内换乘通道', '站台有便利店', '建议提前取好换乘票'],
      },
    ],
  },
  {
    id: 'route-004',
    type: 'boomerang',
    typeLabel: '回旋镖航线',
    from: '上海',
    to: '成都',
    date: '2026-07-10',
    totalPrice: 820,
    totalDuration: 420,
    savings: 680,
    extraTime: 150,
    rating: 4.7,
    reviewCount: 167,
    directPrice: 1500,
    directDuration: 210,
    highlights: ['经停西安3小时', '西安机场免费住宿', '肉夹馍必须吃'],
    segments: [
      {
        id: 'seg-004-1',
        type: 'flight',
        from: '上海浦东',
        to: '西安咸阳',
        departureTime: '07:00',
        arrivalTime: '09:30',
        duration: 150,
        price: 380,
        carrier: '海南航空',
        flightNo: 'HU7890',
      },
      {
        id: 'seg-004-2',
        type: 'flight',
        from: '西安咸阳',
        to: '成都天府',
        departureTime: '12:00',
        arrivalTime: '13:30',
        duration: 90,
        price: 440,
        carrier: '四川航空',
        flightNo: '3U8765',
      },
    ],
    layovers: [
      {
        city: '西安',
        duration: 150,
        type: 'airport',
        tips: ['T3航站楼有免费中转休息区', '机场有肉夹馍店', 'T2和T3之间有免费接驳车'],
      },
    ],
  },
  {
    id: 'route-005',
    type: 'normal',
    typeLabel: '经典中转',
    from: '广州',
    to: '北京',
    date: '2026-07-10',
    totalPrice: 720,
    totalDuration: 330,
    savings: 550,
    extraTime: 90,
    rating: 4.5,
    reviewCount: 203,
    directPrice: 1270,
    directDuration: 210,
    highlights: ['长沙停留1.5小时', '茶颜悦色必须打卡', '机票便宜一半'],
    segments: [
      {
        id: 'seg-005-1',
        type: 'flight',
        from: '广州白云',
        to: '长沙黄花',
        departureTime: '09:00',
        arrivalTime: '10:15',
        duration: 75,
        price: 280,
        carrier: '南方航空',
        flightNo: 'CZ3001',
      },
      {
        id: 'seg-005-2',
        type: 'flight',
        from: '长沙黄花',
        to: '北京大兴',
        departureTime: '12:45',
        arrivalTime: '14:30',
        duration: 105,
        price: 440,
        carrier: '厦门航空',
        flightNo: 'MF8001',
      },
    ],
    layovers: [
      {
        city: '长沙',
        duration: 150,
        type: 'airport',
        tips: ['T2有茶颜悦色', '机场免费WiFi', '行李可直挂'],
      },
    ],
  },
  {
    id: 'route-006',
    type: 'open_jaw',
    typeLabel: '开口程方案',
    from: '深圳',
    to: '西安',
    date: '2026-07-10',
    totalPrice: 680,
    totalDuration: 540,
    savings: 720,
    extraTime: 300,
    rating: 4.4,
    reviewCount: 76,
    directPrice: 1400,
    directDuration: 180,
    highlights: ['重庆停留5小时', '解放碑逛吃', '机票省一半多'],
    segments: [
      {
        id: 'seg-006-1',
        type: 'flight',
        from: '深圳宝安',
        to: '重庆江北',
        departureTime: '07:00',
        arrivalTime: '09:15',
        duration: 135,
        price: 320,
        carrier: '深圳航空',
        flightNo: 'ZH9901',
      },
      {
        id: 'seg-006-2',
        type: 'flight',
        from: '重庆江北',
        to: '西安咸阳',
        departureTime: '15:00',
        arrivalTime: '16:20',
        duration: 80,
        price: 360,
        carrier: '西部航空',
        flightNo: 'PN6201',
      },
    ],
    layovers: [
      {
        city: '重庆',
        duration: 345,
        type: 'city',
        tips: ['机场地铁直达解放碑', '推荐火锅和小面', '重庆北站也可以坐高铁'],
      },
    ],
  },
  {
    id: 'route-007',
    type: 'same_train',
    typeLabel: '同车接续',
    from: '上海',
    to: '北京',
    date: '2026-07-10',
    totalPrice: 550,
    totalDuration: 360,
    savings: 100,
    extraTime: 30,
    rating: 4.8,
    reviewCount: 312,
    directPrice: 650,
    directDuration: 330,
    highlights: ['济南西站换乘', '同站换乘仅15分钟', '比直达省100块'],
    segments: [
      {
        id: 'seg-007-1',
        type: 'train',
        from: '上海虹桥',
        to: '济南西',
        departureTime: '08:00',
        arrivalTime: '11:10',
        duration: 190,
        price: 310,
        carrier: '中国铁路',
        trainNo: 'G102',
      },
      {
        id: 'seg-007-2',
        type: 'train',
        from: '济南西',
        to: '北京南',
        departureTime: '11:25',
        arrivalTime: '13:00',
        duration: 95,
        price: 240,
        carrier: '中国铁路',
        trainNo: 'G104',
      },
    ],
    layovers: [
      {
        city: '济南',
        duration: 15,
        type: 'station',
        tips: ['站内换乘', '走便捷换乘通道', '提前买好联程票'],
      },
    ],
  },
  {
    id: 'route-008',
    type: 'normal',
    typeLabel: '经典中转',
    from: '成都',
    to: '广州',
    date: '2026-07-10',
    totalPrice: 590,
    totalDuration: 270,
    savings: 480,
    extraTime: 60,
    rating: 4.6,
    reviewCount: 145,
    directPrice: 1070,
    directDuration: 180,
    highlights: ['贵阳经停', '机场有酸汤鱼', '机票便宜近一半'],
    segments: [
      {
        id: 'seg-008-1',
        type: 'flight',
        from: '成都天府',
        to: '贵阳龙洞堡',
        departureTime: '08:00',
        arrivalTime: '09:20',
        duration: 80,
        price: 260,
        carrier: '成都航空',
        flightNo: 'EU2201',
      },
      {
        id: 'seg-008-2',
        type: 'flight',
        from: '贵阳龙洞堡',
        to: '广州白云',
        departureTime: '11:00',
        arrivalTime: '12:30',
        duration: 90,
        price: 330,
        carrier: '南方航空',
        flightNo: 'CZ3421',
      },
    ],
    layovers: [
      {
        city: '贵阳',
        duration: 100,
        type: 'airport',
        tips: ['T2有贵州特色小吃', '机场有免费休息区', '可体验苗寨风情拍照'],
      },
    ],
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-001',
    username: '中转达人小王',
    email: 'xiaowang@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaowang',
    points: 12580,
    level: 5,
    createdAt: '2025-03-15',
  },
  {
    id: 'user-002',
    username: '背包客阿明',
    email: 'aming@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aming',
    points: 8960,
    level: 4,
    createdAt: '2025-06-20',
  },
  {
    id: 'user-003',
    username: '省钱小能手',
    email: 'shenqian@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=shenqian',
    points: 23450,
    level: 7,
    createdAt: '2024-12-01',
  },
];

export const mockBadges: Badge[] = [
  {
    id: 'badge-001',
    name: '首发探路者',
    description: '发布第一条实测路线',
    icon: '🚀',
    unlocked: true,
    progress: 100,
    target: 1,
  },
  {
    id: 'badge-002',
    name: '中转达人',
    description: '发布3条以上实测路线',
    icon: '✈️',
    unlocked: true,
    progress: 100,
    target: 3,
  },
  {
    id: 'badge-003',
    name: '省钱能手',
    description: '分享的路线被收藏超过10次',
    icon: '💰',
    unlocked: true,
    progress: 100,
    target: 10,
  },
  {
    id: 'badge-004',
    name: '环球旅行家',
    description: '累计节省超过10000元',
    icon: '🌍',
    unlocked: false,
    progress: 65,
    target: 10000,
  },
  {
    id: 'badge-005',
    name: '社区之星',
    description: '获得100个赞',
    icon: '⭐',
    unlocked: false,
    progress: 45,
    target: 100,
  },
  {
    id: 'badge-006',
    name: '美食探索家',
    description: '分享5条带美食攻略的路线',
    icon: '🍜',
    unlocked: true,
    progress: 100,
    target: 5,
  },
  {
    id: 'badge-007',
    name: '夜行者',
    description: '体验过5次红眼航班中转',
    icon: '🌙',
    unlocked: false,
    progress: 40,
    target: 5,
  },
  {
    id: 'badge-008',
    name: '铁路通',
    description: '分享10条火车中转路线',
    icon: '🚄',
    unlocked: false,
    progress: 30,
    target: 10,
  },
];

export const mockSharedRoutes: SharedRoute[] = [
  {
    id: 'shared-001',
    userId: 'user-001',
    username: '中转达人小王',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaowang',
    routeId: 'route-001',
    routeFrom: '北京',
    routeTo: '上海',
    routePrice: 680,
    title: '青岛中转实测！机场休息区超赞',
    content: '亲测这条北京经青岛到上海的回旋镖航线，真的太香了！青岛机场T2的中转休息区有免费的按摩椅和茶水，中间3小时我还坐地铁去市区吃了一顿海鲜大排档，算下来比直飞还省了500多，强烈推荐！',
    tags: ['机场免费休息', '海鲜美食', '省钱神线'],
    likes: 128,
    saves: 56,
    comments: [
      {
        id: 'comment-001',
        userId: 'user-002',
        username: '背包客阿明',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aming',
        content: '请问行李需要重新托运吗？',
        createdAt: '2026-07-02 14:30',
      },
      {
        id: 'comment-002',
        userId: 'user-001',
        username: '中转达人小王',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaowang',
        content: '如果买的是联程票可以直挂，分开买的话需要取行李重新托运哦',
        createdAt: '2026-07-02 15:20',
      },
    ],
    createdAt: '2026-07-01 10:30',
    isLiked: false,
  },
  {
    id: 'shared-002',
    userId: 'user-002',
    username: '背包客阿明',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aming',
    routeId: 'route-002',
    routeFrom: '北京',
    routeTo: '杭州',
    routePrice: 750,
    title: '南京停留6小时！夫子庙逛吃攻略',
    content: '北京到杭州选了南京中转的开口程方案，中间6小时足够去夫子庙逛一圈了。南京南站寄存行李20块一天，地铁30分钟到夫子庙，鸭血粉丝汤和蟹黄包必须吃！回来的时候还带了盐水鸭，完美的一次中转体验。',
    tags: ['市区游玩', '美食攻略', '高铁中转'],
    likes: 89,
    saves: 42,
    comments: [
      {
        id: 'comment-003',
        userId: 'user-003',
        username: '省钱小能手',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=shenqian',
        content: '南京南站行李寄存在哪？',
        createdAt: '2026-06-28 09:15',
      },
    ],
    createdAt: '2026-06-25 16:45',
    isLiked: true,
  },
  {
    id: 'shared-003',
    userId: 'user-003',
    username: '省钱小能手',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=shenqian',
    routeId: 'route-004',
    routeFrom: '上海',
    routeTo: '成都',
    routePrice: 820,
    title: '西安中转必吃肉夹馍！机场就有',
    content: '上海飞成都在西安中转，本来以为很折腾，结果西安机场的中转服务太惊喜了！T3航站楼有免费的中转休息厅，还有好多陕西特色小吃，肉夹馍和凉皮味道超正宗，3个小时一下子就过去了，机票还省了600多，血赚！',
    tags: ['西安美食', '免费休息', '回旋镖'],
    likes: 156,
    saves: 78,
    comments: [],
    createdAt: '2026-06-20 08:20',
    isLiked: false,
  },
  {
    id: 'shared-004',
    userId: 'user-001',
    username: '中转达人小王',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=xiaowang',
    routeId: 'route-005',
    routeFrom: '广州',
    routeTo: '北京',
    routePrice: 720,
    title: '长沙中转必喝奶茶！茶颜悦色机场店实测',
    content: '广州飞北京选了长沙中转，就是为了喝茶颜悦色！长沙黄花机场T2就有两家店，不用出机场就能喝到。建议一下飞机先扫码点单，逛一圈回来刚好取。中转1.5小时刚刚好，奶茶+省钱双丰收~',
    tags: ['茶颜悦色', '奶茶攻略', '长沙中转'],
    likes: 234,
    saves: 112,
    comments: [
      {
        id: 'comment-004',
        userId: 'user-002',
        username: '背包客阿明',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aming',
        content: '感谢分享！已经种草了',
        createdAt: '2026-06-15 11:00',
      },
    ],
    createdAt: '2026-06-10 13:30',
    isLiked: true,
  },
  {
    id: 'shared-005',
    userId: 'user-002',
    username: '背包客阿明',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aming',
    routeId: 'route-003',
    routeFrom: '北京',
    routeTo: '广州',
    routePrice: 890,
    title: '武汉站换乘超方便！热干面必吃',
    content: '北京到广州的高铁同车接续，武汉站换乘只花了15分钟，站内换乘通道太方便了！重点是武汉站的热干面真的太好吃了，在站台便利店就能买到，赶时间也不耽误吃美食，比直飞省了300多呢。',
    tags: ['同站换乘', '武汉美食', '高铁出行'],
    likes: 98,
    saves: 34,
    comments: [],
    createdAt: '2026-06-05 09:00',
    isLiked: false,
  },
];

export const hotCities = [
  '北京', '上海', '广州', '深圳', '成都', '杭州',
  '武汉', '西安', '南京', '重庆', '长沙', '青岛',
];
