# Generated by Django 4.2 on 2026-01-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='学生真实姓名')),
                ('student_no', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('school_name', models.CharField(max_length=100, verbose_name='学校名称')),
                ('department', models.CharField(max_length=100, verbose_name='院系')),
                ('grade', models.CharField(max_length=20, verbose_name='年级')),
                ('class_field', models.CharField(db_column='class', max_length=20, verbose_name='班级')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('is_certified', models.SmallIntegerField(choices=[(0, '未认证'), (1, '已认证')], default=0, verbose_name='是否认证')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '学生详细信息表',
                'verbose_name_plural': '学生详细信息表',
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='收货人电话')),
                ('address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('is_default', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否默认地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '学生收货地址表',
                'verbose_name_plural': '学生收货地址表',
                'db_table': 'student_address',
            },
        ),
    ]
